### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_fill_missing'

### ISSUE THREAD

**Issue by jaberwoky83** [Electron-Cash/Electron-Cash#1002]
Trying to split BCH into BCH/BSV from off of my trezor on Ubuntu 16. (Following https://www.reddit.com/r/TREZOR/comments/9xp2bl/how_to_claim_the_forked_bchsv/)

I can successfully pull in info from my trezor, see my addresses. I attempt to use "spend from" on one of my smaller coins and send to another address. When I click 'send' I get the error in the subject. I've tried with both electron cash 3.3.2 and 2.9.4 and I get the same error.

**Comment by cculianu** [comment]
Try the latest coinsplitter version: https://github.com/markblundeberg/coinsplitter/releases
