### ISSUE TITLE
why synchronizing?

### ISSUE THREAD

**Issue by mykedjonz** [Electron-Cash/Electron-Cash#1005]

**Comment by mykedjonz** [comment]
hello, 
I have the electron wallet open, and since Monday it says "synchronizing".
what does it mean?

I initially transferred 1 BCH without splitting to an exchange and they asked me to split it, but it's already sent from both chains ABC and SV, however I only have the SV because I sent on the SV chain.
please help retrieve the ABC

**Comment by cculianu** [comment]
This was an issue with older EC versions that got confused on BSV / BCH chains.

We no longer support BSV so this issue is no longer relevant.  Closing.

(Sorry we didn't respond to you in a timely manner!)

**Comment by mykedjonz** [comment]
my BCH is missingplease retrieve it for me




On Thursday, January 17, 2019, 12:44 PM, Calin Culianu <notifications@github.com> wrote:


This was an issue with older EC versions that got confused on BSV / BCH chains.

We no longer support BSV so this issue is no longer relevant. Closing.

(Sorry we didn't respond to you in a timely manner!)
