### ISSUE TITLE
More on splitting BCH and BSV and Kraken

### ISSUE THREAD

**Issue by afduggirala** [Electron-Cash/Electron-Cash#1006]
Hello,
I am sorry to ask about this here, I have read a few posts and am still not completely sure on steps to take to split/send coins to my exchange (Kraken). I possess untouched (since before fork) BCH in my EC wallet. Kraken is crediting both BCH and BSV when deposited correctly: 
They told me:
'The client will need to broadcast to both (chains) if you wish to send bch and bsv (... for sending to Kraken for us to split it for you)
Keep in mind we can only credit the funds if a valid transaction is created on the bsv chain (That is a transaction that can be replayed).'
They also say:
'Deposit addresses for BCH and BSV are shared. This means that generating a BCH deposit address will result in generating the same deposit address for BSV, and vice versa.'

So, due to Locktime in Electron Cash, I should send the transaction while I am in the BSV chain, right? Does EC broadcast to both chains?
Is it safer to follow Mark Lundeberg's guide (https://www.reddit.com/r/btc/comments/9xmh2n/psa_how_to_split_your_coins_with_electron_cash/) to split my coins and then send split coins to Kraken? I dont know if that will create more or less problems with their depositing process.
thank you,

**Comment by fyookball** [comment]
https://www.reddit.com/r/btc/comments/9xmh2n/psa_how_to_split_your_coins_with_electron_cash/
