### ISSUE TITLE
UX Feature: Handle fully specified address within derivation path

### ISSUE THREAD

**Issue by emergent-reasons** [Electron-Cash/Electron-Cash#1014]
This is an additional way (like #992) to improve UX on single-address wallets that provide a seed phrase for backup.

If I understand bip32 correctly, this derivation path corresponds to exactly one key (i.e. there is no alternate interpretation).
`m/44'/0'/0'/0/0`
Sorry I couldn't investigate this enough so I am not sure.

Assuming that is correct, then users/services could provide the fully specified path like `m/44'/0'/0'/0/0`, and EC could convert it to a single private key.

**Comment by SomberNight** [comment]
> If I understand bip32 correctly, this derivation path corresponds to exactly one key (i.e. there is no alternate interpretation).
m/44'/0'/0'/0/0

Any path just leads to a node in the HD tree. The node can have a subtree, or can basically be considered a "root" in itself. So no, you cannot say that just because it has this structure it is a leaf, just by looking at BIP32.

**Comment by emergent-reasons** [comment]
> Any path just leads to a node in the HD tree. The node can have a subtree, or can basically be considered a "root" in itself. So no, you cannot say that just because it has this structure it is a leaf, just by looking at BIP32.

Ok right. Thank you. I think it should be true for BIP44?
