### ISSUE TITLE
Make bip32 derivation validation more robust

### ISSUE THREAD

**Issue by emergent-reasons** [Electron-Cash/Electron-Cash#1015]
update: Clearly my original premise is invalid as pointed out below. Closing this issue.

Sorry if this is my lack of knowledge. I asked in slack but didn't get an answer for a little while.

~~I think this path is invalid:~~
`m/44'/0'/0'/0/0/0/0/0/0/0/0/0/0/0/0/0`

However EC accepts it because it just checks that everything is a valid number, hardened number or empty [here](https://github.com/Electron-Cash/Electron-Cash/blob/baa2d69f47e4136600fb73e231107f7449dd8759/lib/bitcoin.py#L828).

If the fix is as easy as limiting the path slots to 0-3 values, I can submit a PR for it.

This came up as an issue [here](https://github.com/Electron-Cash/Electron-Cash/issues/992#issuecomment-444155737) where a service provided a long derivation path and EC interprets it differently than they intended.

**Comment by markblundeberg** [comment]
It may be helpful to have dropdown menu of pre-filled values for various wallet types.

And in general when the user enters `m/44'/0'/0'` it may be good to display something specific in a label underneath, like "Receiving addresses will be `m/44'/0'/0'/0/k` and change addresses will be `m/44'/0'/0'/1/k`."

**Comment by emergent-reasons** [comment]
Yes. Derivation paths really need to disappear entirely for the 99% use
case. Selecting original wallets as you suggested and also scanning common
paths are the best ways I can think of.

**Comment by markblundeberg** [comment]
Hmmm, one thing that could be made is to make an exceptional case when wallets start with `m/44'` (signalling BIP44) -- then you do know that addresses are supposed to be at 5 levels deep.

**Comment by emergent-reasons** [comment]
Wow. Just a few months ago I obviously had no idea what I was talking about with respect to the standards. Learning is good I guess.

@cculianu can I close this since it is so abstract? Many improvements are possible but probably should come one at a time with a use case attached.
