### ISSUE TITLE
3.3.1CS cannot split coins in Ledger hidden addresses

### ISSUE THREAD

**Issue by haiqu** [Electron-Cash/Electron-Cash#1017]
The Ledger Nano S contains a "plausible deniability" feature against $2.00 spanner attacks. Simply, there is a set of hidden addresses which can be accessed by using a different PIN.

Today I attempted to split pre-Nov15 BCH from those addresses and discovered that the Coin Splitter feature fails with an error: 'Ledger_KeyStore' object has no attribute 'get_private_key'.

I did see this error once while using 3.3.1CS on the standard PIN addresses but restarting the program fixed it. That was not the case with the hidden addresses however, and Coin Splitter could not be used there.

**Comment by markblundeberg** [comment]
Hey, just noticed this issue -- would be better on [the CS version's repo](https://github.com/markblundeberg/coinsplitter_checkdatasig/).
 
Anyway yeah, the splitter only works on a hot wallet as it derives a unique (and reproducible) splitting contract key using your private keys, thus it would not be able to work with a hardware wallet in either case (doesn't matter whether you use the secret PIN keystore or not). Just follow the same procedure as in your other reported Issue.

https://support.ledgerwallet.com/hc/en-us/articles/360012270054-Safely-claim-Bitcoin-Cash-SV-BSV-

**Comment by haiqu** [comment]
Perhaps I wasn't very clear. I was attempting to use the same procedure as linked. It behaved differently to the primary (non-hidden) addresses.
