### ISSUE TITLE
Cannot send SV coins from multi sig with trezor

### ISSUE THREAD

**Issue by someone235** [Electron-Cash/Electron-Cash#1020]
I get the error "unpack_from requires a buffer of at least 8 bytes" after signing a multisig transaction with Trezor, and the transaction is not broadcasted.

I use Electron 3.3.2 with Ubuntu 18.04

**Comment by markblundeberg** [comment]
Does it work on BCH? I guess this is not just an SV error since the multisig mechanics are identical...

**Comment by someone235** [comment]
Yes, it signs without errors for BCH

**Comment by cculianu** [comment]
Since we no longer support BSV on this version of EC I'm closing this to keep the issue count down.
