### ISSUE TITLE
Sv server not in list of servers 

### ISSUE THREAD

**Issue by Albyhanekroot** [Electron-Cash/Electron-Cash#1023]

**Comment by Albyhanekroot** [comment]
I used electron cash to claim my Bitcoin SV but @ the point of untick automatic server and choose SV server , there is no SV server in the list ?

**Comment by fyookball** [comment]
on the network tab, click on server tab you should see more complete list

some are:

sv1.hsmiths.com
satoshi.vision.cash

if you dont see them you can try entering manually

**Comment by Albyhanekroot** [comment]
Thankyou I will try that and let you know

Op za 8 dec. 2018 om 13:50 schreef fyookball <notifications@github.com>:
