### ISSUE TITLE
i sent by mistake my whole as fund

### ISSUE THREAD

**Issue by stefanovic32** [Electron-Cash/Electron-Cash#1034]
Dear Electron-Cash-Team,
I wanted to split my BCH with your tool. I am not familiar with cryptos, was in a hurry and used the Max.-button for the fund... Now the balance is 0 in both (hardware and splitting wallet). Please be so kind to send my BCH back to me.
The transaction-ID is 488128adb611d5e343df57b664facea0418eab48fcf91b75f1a899b403aac32c
For more informations please get in touch with me.
Thank you in advance!
Stefano

**Comment by cculianu** [comment]
Hey man,

I'm sorry you had trouble.  We don't control your funds! Cryptos are permissionless and decentralized. 
 Nobody on this planet can return your funds to you once sent and confirms on the blockchain.  That's the whole thing with cryptos.

I looked at the tx and it looks like you sent 15.00509388 BCH and BSV simultaneously to the address: bitcoincash:pr85208nyq8lpf4uezqlcyeg6uwge4n5tqxy596dfy (Legacy: 3LaxjzuJ3BQ4mccpsnZqsDbPt4NeKrmzBA).  This is a multi-sig address.

Do you control this address?  Do you have the keys to it?

If not, you need to ask the person that controls this address to return your funds to you.  There is nothing we can do about that.

I'm sorry you had trouble though, and if we can be of further help don't hesitate to write here.

I'm closing this issue as it's not really a bug on our end.

-Calin

**Comment by stefanovic32** [comment]
Hey, thanks for the fast response!
How can I find out whos address it is?
I used this instruction here: https://support.ledger.com/hc/en-us/articles/360012270054-Safely-claim-Bitcoin-Cash-SV-BSV
I sent the BCHs to the split contract adress (step 3).
What can I do now?

Stefano


 
 
 

Gesendet: Mittwoch, 12. Dezember 2018 um 11:08 Uhr
Von: "Calin Culianu" <notifications@github.com>
An: Electron-Cash/Electron-Cash <Electron-Cash@noreply.github.com>
Cc: stefanovic32 <pahl.stefan@web.de>, Author <author@noreply.github.com>
Betreff: Re: [Electron-Cash/Electron-Cash] i sent by mistake my whole as fund (#1034)


Hey man,

I'm sorry you had trouble. We don't control your funds! Cryptos are permissionless and decentralized.
Nobody on this planet can return your funds to you once sent and confirms on the blockchain. That's the whole thing with cryptos.

I looked at the tx and it looks like you sent 15.00509388 BCH and BSV simultaneously to the address: bitcoincash:pr85208nyq8lpf4uezqlcyeg6uwge4n5tqxy596dfy (Legacy: 3LaxjzuJ3BQ4mccpsnZqsDbPt4NeKrmzBA). This is a multi-sig address.

Do you control this address? Do you have the keys to it?

If not, you need to ask the person that controls this address to return your funds to you. There is nothing we can do about that.

I'm sorry you had trouble though, and if we can be of further help don't hesitate to write here.

I'm closing this issue as it's not really a bug on our end.

-Calin

**Comment by markblundeberg** [comment]
@stefanovic32 looks like you used my tool... All you need to do is load up the Tools | Coin Split in the same wallet that you used to generate that address, and it should find the funds.

**Comment by stefanovic32** [comment]
Dear markblundeberg, dear cculianu

thank you very much for your answers. With your information, markblundeberg, and the help of a friend of mine, we managed it to get the coins back and to split them.
I'm very grateful that (in the end) it turns out good for me.
Unfortunately is the world of cryptos indeed very crytic, if you are not familiar with it^^
Great learning for me.
Thank god, that you are so kind and helpful to answer my/and other request/s in no time.

THANK YOU again and have a great time markblundeberg and cculianu!!!

Big hug

Stefano
