### ISSUE TITLE
Wanted: Ability to "ban" a server so it never gets selected for connections

### ISSUE THREAD

**Issue by cculianu** [Electron-Cash/Electron-Cash#1036]
Particularly useful for users that don't want to see the other chain and considering our fork bugs, it can even cause a problem to see the other servers or the other chain.

**Comment by rt121212121** [comment]
That's already done.  The blacklist is persisted to the config, and can be edited.  It just needs additional UI to manage it I guess.

**Comment by cculianu** [comment]
Well that's convenient.  Thanks for the tip!  So the pipes are in place -- just needs a UI.  Awesome.

**Comment by cculianu** [comment]
Note to self: Need ability to unban as well.

**Comment by cculianu** [comment]
This is now implemented in #1098
