### ISSUE TITLE
"bitcoincash:" prefix in qr-code despite using legacy address

### ISSUE THREAD

**Issue by molecular** [Electron-Cash/Electron-Cash#1048]
The qr-code (at least on receive tab) displays "bitcoincash:" prefix even if legacy address format is used (checkbox "CashAddr address format" unchecked in preferences / appearance).

I'm not 100% sure, but I think legacy addresses should be encoded without "bitcoincash:" prefix?

**Comment by molecular** [comment]
discovered when checking out openswap. https://github.com/markblundeberg/openswap/issues/7

**Comment by cculianu** [comment]
Well, the receive tab generates a "bitcoin cash URL" which is confusingly very similar to the bitcoincash: address format.

You can type a description and an amount there to see that URL grow with parameters.  I think bitcoincash:OLD_FORMAT (as a URL) is legit.

Confusing, I know.

**Comment by molecular** [comment]
> bitcoincash:OLD_FORMAT

I don't think it's "legit", at least mycelium fails to parse it.

**Comment by molecular** [comment]
I see.

Ok, I guess that's fine. I only ran into usability issues because of a quirk in openswap.

**Comment by molecular** [comment]
sorry, I deleted that post about mycelium because it doesn't apply. I fed it a "bitcoincash:<legacy addr>" url, which clearly it needs to reject because mycelium is bitcoin only.

**Comment by cculianu** [comment]
Oh.. ha.
