### ISSUE TITLE
Attempted splitting BCH coins, lost BCH

### ISSUE THREAD

**Issue by morpheus1958** [Electron-Cash/Electron-Cash#1051]
I attempted splitting my BCH into BCHABC and BSV using the electron cash wallet coin splitting tool. I followed directions provided by electron cash linked to my Ledger Nano S. After attempting the split I tried sending what I thought would be the split BSV tokens to my Bittrex wallet to a BSV public address.

What actually happened was all my BCH was sent from my Ledger and disappeared. My guess is the token split didn't work and I sent my unsplit BCH to the BSV address.

Is there any way I might be able to recover my BCH?

**Comment by markblundeberg** [comment]
Strange -- if you followed the instructions from Ledger, this should not have occurred. Can you provide more information (transaction IDs, etc.) ?

**Comment by morpheus1958** [comment]
I have the history in my Electron Cash wallet. This is the final transaction I copied from block explorer.
![bsv-tx](https://user-images.githubusercontent.com/45954313/50127283-2abc8c00-0236-11e9-8756-b01963665159.png)

Here are some of the other transaction IDs in the wallet history.
0b7b7e3e548d7eeeb0c3fbb8590712079fec12f5b592cbbda8417224524e1f1a

018081bff15493112c5e3c9d6f4ff92a83afab57d9bbec4ff3ebd4bfd9461acb

52c7c13e72ce92d13d67d2252c04d422572c7162745e378429a7be72698efd3a

7bff193f527b13b7899dcb0dcbf00ac1d428a0e74c351ec286374d68683dc1cc

5410fb53b08a4c7dfb67e820b8d27265434da253f15d693a0cb7fdc52c5b5f91

16a3de7bf0389ab8596d1264d4d4bc405e19985116c1f7798fe9b191f722a566

759c6fe8bf7277759d331b5a0788135d850d907c8c3349c92aa05b414e207db9

c62d2e35b82ecb66b1a521bcb79a0c603c08a4fcdb23979c0bbcd44e9e0391a5

Thanks for taking a look.

**Comment by markblundeberg** [comment]
It looks like you successfully split your BCH from BSV. The BSV are still on this address: https://bchsvexplorer.com/address/qqycgcfenpwpzwxj4wvps08rtn764azj0yz3ftq6lw

So it sounds like what happened is: after splitting, you then accidentally sent the BCH instead of BSV.

**Comment by morpheus1958** [comment]
When I sent the split coins from the "splitting wallet" back to the "hardware wallet" I thought the balance showing in the EC "hardware wallet" were the BSV coins. The final instruction was to send them to a service that supported BSV so I could spend them. So, the balance that I saw was actually not the BSV coins but the BCH balance after splitting? So I thought I was sending BSV but instead sent the BCH?

I never saw any balance after splitting that said I had any BSV, I only ever saw BCH which, after splitting, I thought must now be the BSV showing as BCH.

**Comment by cculianu** [comment]
It's confusing as hell.  Both balances are labelled BCH.  You have to know which server you're connected to to know which network you're on.

Yes -- it looks like you sent BCH to Bittrex.  You should contact Bittrex support and ask them to refund you those funds. They are in control of them now.

**Comment by morpheus1958** [comment]
Thanks for your help. I will contact Bittrex and hopefully they can help.

How do I access the BSV I apparently still have? When I open the EC wallet connected to my Ledger with the BCH app open, I can't see any balance of any kind of BCH or BSV.

**Comment by morpheus1958** [comment]
Bittrex won’t help recover my BCH. They are not supporting recovery of lost BCH split coins due to no replay protection.

Can anyone give any suggestions on how to access my BSV that I might still have on my Ledger using the EC wallet? Would it involve switching to the BSV chain somehow?

**Comment by markblundeberg** [comment]
Yep, just follow [step 6 of the Ledger instructions](https://support.ledgerwallet.com/hc/en-us/articles/360012270054-Safely-claim-Bitcoin-Cash-SV-BSV-) if you want to spend BSV.
