### ISSUE TITLE
Spliting contract and sweep wallet to mix with BCH transection not disapearing 

### ISSUE THREAD

**Issue by Shahbaz8432** [Electron-Cash/Electron-Cash#1061]
As mentioned in the article "Safely claim Bitcoin Cash SV (BSV) " at leger support website.
all the process has gone through successfully, only at last one after selecting the server sv1.hsmiths.com nothing is happing as to change BCH into BCH (SV).
Kindly advise as soon as possible.

**Comment by markblundeberg** [comment]
Make sure it's sv1.hsmiths.com port 60004

The display name will not change from "BCH" to "BSV" -- rather, you should examine the transaction IDs to see that they are all different between BCH and BSV networks.
