### ISSUE TITLE
TREZOR: cannot partially sign multisig transaction

### ISSUE THREAD

**Issue by jhoenicke** [Electron-Cash/Electron-Cash#1090]
There is a bug in electroncash / Trezor multisig code that prevents accepting partial signatures.

To reproduce, create a 2-of-2 wallet with Trezor and an xpub as other signer.  Send multiple inputs to this wallet.  Create and sign a transaction with multiple inputs (three are enough); TREZOR should be the first signer.  

The problem is that electroncash expects that partially signed transactions have an amount after the input, which is a non-standard extension of electroncash.  Trezor doesn't know of this and produces a raw transaction without amount.

Possible mitigations:
1. rewrite the code to not parse the Trezor raw transaction but instead just parse the signature output (like electrum does).
2. Add a flag to transaction.py `deserialize` to mark that no amount field is expected.

**Comment by cculianu** [comment]
This has been fixed -- as of version 4.0.3 I believe but definitely latest has this fixed.
