### ISSUE TITLE
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Alex7\\Downloads\\electron_cash_data\\cache\\BitcoinAverage_USD'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1099]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.3.1cs-py3.5.egg\electroncash\util.py", line 609, in run_with_except_hook
  File "threading.py", line 862, in run
  File "site-packages\electron_cash-3.3.1cs-py3.5.egg\electroncash\exchange_rate.py", line 93, in get_historical_rates_safe

OSError: [Errno 22] Invalid argument: 'C:\\Users\\Alex7\\Downloads\\electron_cash_data\\cache\\BitcoinAverage_USD'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.1CS  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-7-6.1.7601-SP1 | standard | ru_RU | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
I think this is invalid.  Looks like he deleted his electron_cash_dir which is what caused this exception.
