### ISSUE TITLE
Can you please add the Raw Hex Script option to the Windows version of Electron Cash?

### ISSUE THREAD

**Issue by BCHTester** [Electron-Cash/Electron-Cash#1107]
Can you please add the Raw Hex Script option to the Windows version of Electron Cash?
We need this to be able to broadcast Cash Accounts registration TXs. The option is currently available to Linux users only. Not everyone is a Linux user.

**Comment by cculianu** [comment]
Oh hey.  Yeah they have it because they can run from source.  We can do a release -- or I can post a windows binary.  I'll ask Jonald what he wants to do...

@fyookball  --- thoughts?

**Comment by BCHTester** [comment]
>  We can do a release -- or I can post a windows binary. 

Yes please, I would really appreciate it.
Thanks in advance.

**Comment by cculianu** [comment]
Hmm well Jonald isn't around.  Want me to just post a Window binary to releases or something?

**Comment by cculianu** [comment]
Ok well I just put up a "development release" (complete with Windows & Mac binaries). It's in the releases tab here:

https://github.com/Electron-Cash/Electron-Cash/releases/tag/3.3.5-dev-1

**Comment by cculianu** [comment]
You're welcome!
