### ISSUE TITLE
BCHSV 3.3.2

### ISSUE THREAD

**Issue by SlaTkiS** [Electron-Cash/Electron-Cash#1112]
Hello all,

I apologize in advance if this has already been discussed but I was unable to find it.

I had sent my funds prior to the fork to Ledger Nano s.
After the fork since they didnt support both chains I used electron to claim my ABC and SV.
Here is where the problem starts.
I had installed 3.3.2 and received ABC instantly but SV I was unable to claim it as in 3.3.2 coin splitter wasnt available.

Since then I had moved my ABC out of electron and I am stuck with no options to claim SV.

Any help is kindly appreciated from anyone!

Thanks

**Comment by fyookball** [comment]
try https://electrumsv.io/
