### ISSUE TITLE
Cosigner plugin: Change default behavior of popup window

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#1113]
It's happened to me twice now: When waiting for my cosigner (for a multisig wallet) to make a transaction, I type things somewhere else. My cosigner signs the tx and sends through cosign server, tx pops up on my screen... then is immediately declined by me via a keystroke (probably enter or spacebar). 

This of course causes quite an annoyance on our part as it has to be done again the other way around, and notification isn't relayed well the second time for the same tx (for spam prevention?). Can we reduce such incidents by making the popup window not default to cancel - perhaps just not have a default at all, and you _have_ to click or tab-choose one of the actions?

**Comment by cculianu** [comment]
An admission of weakness: I have never once made a multisig wallet or have ever used this tool.

I do agree that critical popups such as this one as a rule should never have defaults that can be accidentally hit by the keyboard though. If it happened to you it probably happened to others.  The asynchronous nature of this window (I understand it can pop up at any time, right?) compounds the problem.

I'll go ahead and create a multisig wallet (on testnet) and figure out a way to play with this to a point where hopefully I can fix this bug.  It should be pretty easy once I go to the trouble of getting multisig working...

**Comment by cculianu** [comment]
Annoyingly, Qt won't let me make popup windows without a "default" button.  At least on Mac that's the case.

There are 2 options here:

1. Have the default button be the "Yes" button (this will at least open up the TX dialog).
2. User can close the wallet window and open it again and the cosigner plugin will pick up the partially signed tx again and ask the user again.

**Comment by cculianu** [comment]
Note that I made the poll time be 10s now for the cosigner check thread so it should at least be more responsive...

**Comment by cculianu** [comment]
I'm closing this issue as I don't anticipate us ever coming to a satisfying way to keep the dialog from doing what you said.  I set the default to "Yes" for the popup which should be good enough.

Also note you can close/reopen the wallet to poll the server again....

**Comment by cculianu** [comment]
Ok.. thanks @imaginaryusername for suggesting it.  I pushed a fix that does what you want:

<img width="513" alt="screen shot 2019-01-21 at 7 38 23 pm" src="https://user-images.githubusercontent.com/266627/51490718-cd77a580-1db4-11e9-9388-e9107a802025.png">
<img width="431" alt="screen shot 2019-01-21 at 7 35 00 pm" src="https://user-images.githubusercontent.com/266627/51490720-ce103c00-1db4-11e9-8cd8-f2718427e5f9.png">

**Comment by imaginaryusername** [comment]
The madman did the right thing!
