### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_tx_status'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1115]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/Users/calin/tmp/ec/electron-cash/gui/qt/main_window.py", line 335, in on_network_qt
    self.history_list.update_item(*args)
  File "/Users/calin/tmp/ec/electron-cash/gui/qt/history_list.py", line 147, in update_item
    if not self.wallet: return # can happen on startup if this is called before self.on_update()

AttributeError: 'NoneType' object has no attribute 'get_tx_status'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.4  | 3.5.6 (default, Sep 20 2018, 11:49:45)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-17.7.0-x86_64-i386-64bit | standard,2of2 | en_US | 

Additional Information
------------------------

> Just ran app. Got this.

---

**Comment by cculianu** [comment]
Hmm. I know why this is. Fixing now.
