### ISSUE TITLE
didnt recieve my bitchoin cahs

### ISSUE THREAD

**Issue by rowinhoff** [Electron-Cash/Electron-Cash#1116]
i did send bch to qqgleh9mjnsgam9fcmhek0630v9pwrwt6qz5wmyn2r that adress but never got it.... 100 % sure i had the right wallet id, i always double check

**Comment by markblundeberg** [comment]
@rowinhoff Yes, that address got it https://blockchair.com/bitcoin-cash/address/qqgleh9mjnsgam9fcmhek0630v9pwrwt6qz5wmyn2r

**Comment by rowinhoff** [comment]
> @rowinhoff Yes, that address got it https://blockchair.com/bitcoin-cash/address/qqgleh9mjnsgam9fcmhek0630v9pwrwt6qz5wmyn2r

no it didnt got it.... it was 0.109999 bitcoin cash its not on there

**Comment by rowinhoff** [comment]
> I see this address has a balance. Is this address in your wallet?
> 
> View -> Show Addresses
> 
> Go to the address tab -- see if this address is in there.
> 
> Also what EC version?

everytime i send it it goes to a diffrent wallet adress first but i normaly recieve it but this time not, if i look in show adresses all the adresses are difrent

**Comment by cculianu** [comment]
I'm closing this because it's not really an issue with Electron Cash. Feel free to continue asking questions here or look online for help. Try: www.reddit.com/r/btc -- perhaps people there can help you as well.
