### ISSUE TITLE
login issue on electron cash wallet with bitbox

### ISSUE THREAD

**Issue by Crowwe** [Electron-Cash/Electron-Cash#1119]
Good day

I have updated my bit box software and since the ugrade I cannot access my electron cash wallet - it wont accept my bitbox password?

Kindly advise how I can access my wallet.

**Comment by cculianu** [comment]
@imaginaryusername -- I have no concept about this hardware wallet (I'm hardware-wallet-challenged).  It looks like this is just a support request.  Is this an actual bug in the software? Let me know so I know whether to close this issue or not.

**Comment by imaginaryusername** [comment]
Probably not a software issue unless we learn of actual incompatibilities - I've been using my Bitbox fine. Feel free to close.

**Comment by Crowwe** [comment]
I will try the backup SD card but the wallet contents are still in place. The coins are still in the wallet and visible to me but I cannot transact due to the password being incorrect (according electron wallet). The password is not incorrect! So how do I correct this problem please?

Regards,
B Bishop

**Comment by cculianu** [comment]
@imaginaryusername -- any idea? Do you think this is user error or? Should I close this or leave it open?

**Comment by cculianu** [comment]
We're all volunteers here. Nobody pays us. This isn't a company.  I'm sorry you're upset .. but you should keep in mind this is open source. Nobody owes you anything.

**Comment by imaginaryusername** [comment]
I even upgraded my bitbox firmware in the meantime and it still worked. If you tried the backup it might have worked, but I guess it's more satisfying to bitch on github without providing anymore debug information instead.

This is a place to debug and work together to improve software, we're not customer representatives and have no obligation to be your emotional outlet.

>will definitely remember not to support your company in future

There's no company, dude. We work for free, every line of code is transparent, if you don't like it you can fork anytime.

**Comment by Crowwe** [comment]
F U!
