### ISSUE TITLE
AttributeError: 'ShuffleWidget' object has no attribute 'pThread'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1128]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/home/tristan/.electron-cash/external_plugins/shuffle_051v2.zip/shuffle/qt.py", line 154, in <lambda>
    self.coinshuffle_cancel_button = EnterButton(_("Cancel"),lambda :self.cancel_coinshuffle_protocol())
  File "/home/tristan/.electron-cash/external_plugins/shuffle_051v2.zip/shuffle/qt.py", line 519, in cancel_coinshuffle_protocol
    if self.pThread.is_alive():

AttributeError: 'ShuffleWidget' object has no attribute 'pThread'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.5  | 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0] | Linux-4.18.0-13-generic-x86_64-with-Ubuntu-18.10-cosmic | imported_privkey,standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
Ancient cash shuffle plugin.  We need to take this plugin out of circulation.
