### ISSUE TITLE
Strange "lowfee" warnings when using testnet

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#1130]
When combining many inputs together on testnet, and setting fee to 1sat/byte: I got a "low fee" warning, and in preview the wallet shows the tx as paying 0.99xxx sats/byte. If I send the transaction anyway, it turns out it actually pays 1.003sats/byte (yay), yet the wallet warns it as low fee anyway, culminating in this contradicting "details" dialog: 

![screenshot_20190125_144851](https://user-images.githubusercontent.com/34949601/51777145-abca3700-20b0-11e9-83a9-758a73607f84.png)

Not sure how reproducible this is in other wallets - it seems like the problem only occurs with transactions that has a lot of inputs (>>10kb). Might want to look into fee calculation logic for a bit.

**Comment by cculianu** [comment]
I am not sure what to think of this. I noticed it too in my testing.

Strangely the "low fee" warning seems correct for me most of the time -- if I pay 1 sat/B it's hard to get a confirm in 1 block.  But if I pay 10 sats/B I do get a confirm in 1 block.

So I just figured there are different fee rules for testnet.  

You know this to not be the case?

**Comment by imaginaryusername** [comment]
If I drag the bar to 2sat/byte, the warning goes away.

**Comment by cculianu** [comment]
OK, I'll investigate what's going on with that. I wonder if someone just set minimum in the code to 2 sats/B.

Honestly it's hard to get a confirm with 1 sat/B on testnet lately.  Not sure if that's by design or people just trolling testnet.. or what.

**Comment by cculianu** [comment]
Honestly it looks like it gets the fee estimates from the electrumx server and they seem to be accurate from my reading of the code.  Unless electrumx on testnet is lying.

In my testing it really looked like the "low fee" warning was accurate!

Did your tx confirm next block?

**Comment by imaginaryusername** [comment]
It did confirm next block: https://www.blocktrail.com/tBCC/tx/3d29392bc9c374d8694913423e5326b4b01271265cdbd16233d920cbb8366eea

**Comment by cculianu** [comment]
Hmm. well I'm looking here at the code and it pretty much gets its idea of what's a low fee or not from statistics compiled by the electrumx server it's talking to.

In my testing that "low fee" flag was pretty accurate -- I'll investigate more but so far this does not look like a bug.

I have done a LOT of testing on testnet lately (for cashshuffle) and that "low fee" flag seemed fairly accurate...

But I will have to read the electrumx sources to know for sure what the hell it's doing on testnet.

**Comment by imaginaryusername** [comment]
You might be right, the particular block I'm confirmed in happens to also clear a lot of other tx that previous blocks weren't interested in - I might have just got lucky.

**Comment by cculianu** [comment]
Yeah I'm like 60% sure that low fee flag is accurate -- I will look at how the code works in ElectrumX -- i suspect it looks at mempool and the kinds of tx's that did confirm in recent blocks to build some sort of a histogram, because Neil is not dumb.

In my recent experience there are lots of bastard miners on testnet. Stingy bastards!

But I will double check.

**Comment by cculianu** [comment]
PS: I'm looking at the blocks around that time and it seems there was a chain of stingy miners and blocks with only 1-2 tx's in them with 10 sat/B fees.

Then your block came and it had a bunch of "low fee" tx's in it.

I'm like 85% sure now. But I will check the code and let you know...
