### ISSUE TITLE
Electron Cash to use at BSV chain

### ISSUE THREAD

**Issue by bchtrue** [Electron-Cash/Electron-Cash#1137]
Hello, Sorry. Can I use Electron Cash last version (or 3.2 ?) to store and move my BSV coins. There Electrum SV is really peace of ****. It request too many libs to install at my linux and I do not trust them at all. If so how to choose right SV chain server to connect? Thanks

**Comment by cculianu** [comment]
:)  Well it's basically a fork of a recent Electrum version so -- it should be "safe".

We do have a variant of Electron Cash -- Electron Cash CoinSplitter -- which can still "talk" BSV. Get it here: https://github.com/markblundeberg/coinsplitter/releases

Good luck!
