### ISSUE TITLE
missing coins from the wallet.

### ISSUE THREAD

**Issue by taknado0** [Electron-Cash/Electron-Cash#1141]
What could be the reasons? After some time I entered the wallet and there is a balance of 0. I used version 3.1.6 on Mac

**Comment by cculianu** [comment]
Without more information I cannot say.  I suggest you try upgrading to the latest wallet version as well:
https://www.electroncash.org/

Do you see your coins in the block explorers online?

Provide more details please...

**Comment by taknado0** [comment]
updated to the latest version. if it was a theft, they would not lie without moving? https://bch.btc.com/86a97daa381dbf14d764da59960f67c53eee83128efaa2b29db94b799fcf5c97

**Comment by cculianu** [comment]
I do no understand your question.  Please ask again in a more wordy, clear way

**Comment by cculianu** [comment]
Is this the tx where they stole? Or? What are you showing me here?!

Please explain the situation CLEARLY using MANY WORDS (or at least MORE words than you have used up until now). I understand English is not your first language -- but you need to use more words. 
 Don't be shy. Thank you.

**Comment by taknado0** [comment]
Yes that's right. This is a transaction with stolen coins. I did not go into my wallet for a long time, and now there is nothing there (balance 0). I considered electrum a safe means of storage. Now I wanted to know how is this possible? I believe that to return them will not succeed?

**Comment by cculianu** [comment]
Well a number of things could have happened, but none of them are any solace to you (and none of them are really our fault or this software's fault):

1. You could have downloaded some malware or virus that found your wallet file and sent  it somewhere.

2. You could have downloaded some malware version of Electrum or Electron Cash which unfortunately stole your coins.

3. You could have generated your wallet on a site that belongs to scammers.

4. Any number of other things including people you know maybe have stolen your wallet data and used it to spend your coins.

You can't get your money back.  Transactions are irreversible on the blockchain.

I'm sorry this happened to you.  It's painful.  Did you click on any suspicious links recently?
