### ISSUE TITLE
DataOverflowError: 

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1144]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.3.4-py3.5.egg\electroncash_gui\qt\qrcodewidget.py", line 60, in paintEvent
  File "site-packages\qrcode\main.py", line 427, in get_matrix
  File "site-packages\qrcode\main.py", line 92, in make
  File "site-packages\qrcode\main.py", line 164, in best_fit

DataOverflowError: 
```

Reporter
------------

This issue was reported by 3 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.4  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-7-6.1.7601-SP1 | standard | en_GB | 
| 3.3.5_iOS (iOS Build: 03030501)  | 3.5.5+ (default, Jul  5 2018, 10:35:04)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-17.7.0-x86_64-64bit iOS 12.1 iPhone (2CBF507E-12E3-4241-B62A-0D02A0A81DDE) | standard | en_UK | 
| 3.3.5  | 3.5.6 (default, Sep 20 2018, 11:49:45)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-17.7.0-x86_64-i386-64bit | standard | en_US | 

Additional Information
------------------------

> @mhsmith here. Happens when you paste too much text into the Receive description box.

---

> Testing... Calin Here.

---

**Comment by cculianu** [comment]
oh hey good catch.  Probably should be catching that exception and presenting an error to the user I would guess.  Thanks @mhsmith

**Comment by cculianu** [comment]
Ok, fixed.
