### ISSUE TITLE
Transaction didn't appear in history

### ISSUE THREAD

**Issue by emajoy** [Electron-Cash/Electron-Cash#1153]
Hello,
I installed electron cash successfully using the installation instruction, then I tried to receive bitcoin, I had a new address from receive tab. I transferred to this address from bitpay wallet, the transaction has been confirmed successfully on block chain but I can not see it in the electron cash wallet history and the wallet balance still 0.
What are the possible reasons and how can I solve it?

**Comment by cculianu** [comment]
What is the transaction id (txid) of the transaction?

**Comment by emajoy** [comment]
051bc02c388df2ac168e0e2c472317cca3338e0f1d58ab8691e23820099480da

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cculianu** [comment]
This is a Bitcoin (Core/Legacy/Segwit/whatever you call it) transaction and not a Bitcoin Cash transaction. Hence, why it doesn't appear in your history.  Not sure what you did exactly, but you most certainly did not send these funds using Electron Cash.

**Comment by emajoy** [comment]
actually I transferred from bitcoin wallet on the address which I take from electron cash. I knew that was mistake but after the transaction  has been confirmed,, Can I do any thing to fix this?

**Comment by cculianu** [comment]
Yes. Download the Electrum Wallet from: https://www.electrum.org and re-generate a wallet in Electrum using the same seed you have in Electron Cash.  Click this icon to get the seed:  
<img width="38" alt="screen shot 2019-02-12 at 5 05 08 pm" src="https://user-images.githubusercontent.com/266627/52644894-613a1e80-2ee8-11e9-882a-e945bdaaf921.png">

And use that seed in **Electrum**.

**Comment by emajoy** [comment]
Thank you very much for help, I was lost.
Can I get them back to the original wallet?

**Comment by cculianu** [comment]
If you control the address you SENT the funds to, then yes.  If not, then you need to contact whomever you sent the funds to. It sounded to me like you sent the funds to yourself but to your Bitcoin Cash address.  

So you can get the funds if you use that address on Bitcoin Regular (using Electrum, with the seed from the Electron Cash wallet).

Otherwise I do not understand your question and you need to elaborate.

**Comment by emajoy** [comment]
Okay thank you for helping, It worked 
I just was confused between bitcoin and bitcoin cash wallet.
thank you again for helping

**Comment by cculianu** [comment]
You're very welcome.  Don't worry -- yours is a very common mistake people make.  Many have asked this. 👍
