### ISSUE TITLE
TypeError: 'QCborKnownTags' object is not callable

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1157]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/usr/lib/python3.7/site-packages/electroncash_gui/qt/main_window.py", line 742, in edit_changed
    amount * Decimal(rate) / COIN, False))

TypeError: 'QCborKnownTags' object is not callable
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.5  | 3.7.2 (default, Jan 10 2019, 23:51:51)  [GCC 8.2.1 20181127] | Linux-4.20.6-arch1-1-ARCH-x86_64-with-arch | standard | en_US | 

Additional Information
------------------------

> crash occured when I clicked "Max" button on send

---

**Comment by cculianu** [comment]
Woah. Crazy bug. Will investigate.

**Comment by cculianu** [comment]
This is a bug related to the new Qt 5.12 which also exports the name 'Decimal' which we import from python decimal.  The workaround was to keep the Qt name and import python decimal.Decimal as PyDecimal.

Fixed in 432edfd6a690db744667ed72e1333c709e6d84e6

**Comment by ProfessorVenkman** [comment]
Good evening @cculianu,

I just received another crash report related to this issue. The crash occured on Electron Cash 3.4.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 3.3.5 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
  File "/home/jza/Downloads/ElectronCash-SLP/gui/qt/main_window.py", line 797, in edit_changed
    amount * Decimal(rate) / COIN, False))

TypeError: 'QCborKnownTags' object is not callable
```


~ _With robotic wishes_

**Comment by marceloneil** [comment]
All Arch Linux users :sweat_smile:

**Comment by marceloneil** [comment]
@cculianu no huge rush as I patched the arch release, but its good to get a release out the door before other distributions start updating

**Comment by cculianu** [comment]
OK, just commenting there for the record -- Electron Cash 3.3.6 release now should no longer produce this error on installs with Qt 5.12.  I'm going to pin this issue in case others have this problem.

To whomever is reading this: Simply upgrade to Electron Cash 3.3.6 in order to fix this issue!

**Comment by ProfessorVenkman** [comment]
Good afternoon @cculianu,

I just received another crash report related to this issue. The crash occured on Electron Cash 3.4.2.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 3.4 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
  File "/home/thomas/appimage/Electron-Cash-SLP-3.4.2/gui/qt/main_window.py", line 802, in edit_changed
    amount * Decimal(rate) / COIN, False))

TypeError: 'QCborKnownTags' object is not callable
```


~ _With robotic wishes_

**Comment by cculianu** [comment]
Ancient version.  This has been fixed.
