### ISSUE TITLE
TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1159]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/home/trout/Electron-Cash/lib/util.py", line 650, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/home/trout/Electron-Cash/lib/network.py", line 1299, in run
    self.wait_on_sockets()
  File "/home/trout/Electron-Cash/lib/network.py", line 1273, in wait_on_sockets
    self.process_responses(interface)
  File "/home/trout/Electron-Cash/lib/network.py", line 694, in process_responses
    response['server'] = interface.server  # tell client code where it came from

TypeError: 'NoneType' object does not support item assignment
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.6  | 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0] | Linux-4.15.0-29-generic-x86_64-with-Ubuntu-18.04-bionic | standard | en_US | 

Additional Information
------------------------

> Was running CashShuffle. Had just restored an old snapshot of a VM. The EC client was trying to catch up with the tip of the chain.

---

**Comment by cculianu** [comment]
Thanks for this --   I must have just broken something in my last commit.  Will fix!
