### ISSUE TITLE
Warn users of old testnet wallets in UI that they need to regenerate wallet from seed: -- wallet files mysteriously fail (xpub vs tpub) "BaseException: ('Invalid xpub format', '0x488b21e')"

### ISSUE THREAD

**Issue by markblundeberg** [Electron-Cash/Electron-Cash#1164]
Related to #1121 fix...

Now that Electron Cash expects tpub, if I open an old wallet file (xpub) then it throws an exception in the terminal and the verifier gets stuck.

**The fix is to regenerate the wallet from seed** but it was not at all obvious that I should do this. Other testnet users will be confused too...

see also https://github.com/spesmilo/electrum/issues/4145 and #744

**Comment by cculianu** [comment]
Yeah I intended to add a warning in the UI for this but never got around to it.  I will do so. I'll rename this issue to indicate that.

**Comment by cculianu** [comment]
Ok, done!
