### ISSUE TITLE
Allow connection to .onion addresses

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#1174]
Right now it seems like Electron-cash does not allow connection to .onion address proxied through tor - perhaps due to a stringent SSL requirement. It will be desirable to relax this requirement at least for .onion addresses specified. 

To test, one can try 7nshufncf3nmp7pa42oqhnj6whsjgo2eok4jveex62tczuhvqur5ciad.onion 50001 while proxied through Tor.

**Comment by imaginaryusername** [comment]
Relevant commits that banned non-TLS servers, see if they help: 

https://github.com/Electron-Cash/Electron-Cash/commit/dc388d4c7c541fadb9869727e359edace4c9f6f0
https://github.com/Electron-Cash/Electron-Cash/commit/412ada557b9ef83f19ed44ef3455ac6fb8bffbba

**Comment by cculianu** [comment]
Ah. They do help.  Thanks for the due diligence.  I'll definitely fix this.

**Comment by cculianu** [comment]
Ok so basically they tore out non-SSL support 100% from the UI.  The core code still can do it -- but it's not easy to enable from any user action in the UI.

So if you input a .onion address -- it just bins it with the SSL servers and it will fail.

The fix would be to bring back from the dead some sort of UI support for non-SSL servers.

Internally the app can still talk to them if they are binned as non-SSL.

I tried a quick hack of "if string ends in .onion, force no-SSL" and it worked.  However that produced other UI weirdness where now the app is in "non-SSL" mode and if you pick a server from the list in the GUI it then tries to talk to it in non-SSL and that breaks.

I will need to spend more time figuring this out -- my quick UI hack works but it introduces other strangeness, basically.

**Comment by imaginaryusername** [comment]
One way to deal with this: Put in a checkbox but instead of "SSL", it says "Use Tor". If checked it pulls up all non-SSL peers... and filter out the non-onion options in GUI. If it's unchecked, behave as right now. 

If you enter an onion address in box it's automatically checked, vice versa for other addresses. 

Don't know how much work this is, but it's probably gonna be okay UX-wise.

**Comment by cculianu** [comment]
It's a good suggestion UX-wise.  This code is really hard to change thought and it will take me a bunch of time. Gah.

I want to work on CashShuffle stuff.. I may backburner this... if it looks too onerous.

Hmm.

**Comment by cculianu** [comment]
OK imma just gunna bring back the "Use SSL" checkbox... I think that's the easiest thing to do. :/

**Comment by imaginaryusername** [comment]
Do flip and rename it to "use Tor" though! Maybe grey out the non-onion stuff in the list. It's the least we can do :P

**Comment by cculianu** [comment]
Ok so try this branch @imaginaryusername and let me know!

https://github.com/Electron-Cash/Electron-Cash/tree/onion_resurrection
