### ISSUE TITLE
Make QR code image copyable to clipboard

### ISSUE THREAD

**Issue by Mengerian** [Electron-Cash/Electron-Cash#1175]
When you're on the "receive" tab, it would be nice to be able to copy the QR code image to the clipboard. Right now I can't figure out an easy way to grab the image (other than screenshot).

This would be useful for pasting it into documents such as invoices.

**Comment by marceloneil** [comment]
You can currently do this through the "addresses" tab, if you right click on a receive address and select details, and then click on the "QR" icon, you then have the option to copy the QR.

I agree it should be easier to do from the "receive" tab, and it should be fairly simple as the code is already implemented:
https://github.com/Electron-Cash/Electron-Cash/blob/3f0572d30f8425f5dc17c2c182f82550d0741d74/gui/qt/qrcodewidget.py#L124-L127

**Comment by cculianu** [comment]
QScreen.grabWindow?! Jesus.  They could have just called `QWidget.grab()`.

Nasty -- their core pulls the QR image in with other crap.

I'm going to fix this -- plus add the facility in the Receive tab.

**Comment by cculianu** [comment]
Ok, fixed.  This whole facility was ridden with bugs.  I'm glad you brought this to my attention @Mengerian as I fixed a bunch of things about this whole facility.

The QR Window that is spawned now is much more well behaved and the contents are laid out properly as well.

Thanks for the report!

**Comment by Mengerian** [comment]
Ha, ha, my pleasure @cculianu :)

Glad it resulted in fixing up some stuff.

Thanks for the quick action!
