### ISSUE TITLE
Decimal format of "Amount" in Coins tab is inconsistent

### ISSUE THREAD

**Issue by Mengerian** [Electron-Cash/Electron-Cash#1180]
In the "History" and "Addresses" tabs, the decimal is always aligned, so that large numbers (10 or greater), will protrude to the left. This is good, as it makes it easy to visually see larger amounts very quickly.

The "Coins" tab is different, the numbers are all left-justified. It would be better if the Coins tab followed the same format of keeping the decimal points aligned.

**Comment by cculianu** [comment]
You're 100% right. This is annoying. I couldn't quite put my finger on why the coins tab looked hard to read. It never occurred to me the numbers are misaligned.  That's it!

Will fix. This is important for CashShuffle where you find yourself staring at the coins tab a lot. :)

**Comment by Mengerian** [comment]
Another enhancement along this theme: It's nice if the leading "0"s can be made fainter.

Ie, for "0.1", the "0" would be fainter, for "0.003", all three "0"s would b faint. This have the same effect as the aligned decimal thing, let's you quickly detect orders of magnitude with a visual scan.

This might be more difficult to implement though, and is a very nit-picky thing, so I'd consider it a low-priority "nice to have" wishlist item.

**Comment by cculianu** [comment]
It's possible with HTML to do -- I wouldn't mind doing it.  I love UI niceties.  I'll keep it in mind as I look at this code and figure out how to fix it.

Thanks for the suggestion.

**Comment by markblundeberg** [comment]
@cculianu for the cases where it is lined up, I know this is done by:
1. right justifying, and
2. using monospace font, and
3. passing in a parameter to format_satoshis (I think that's the name of the function) that makes it pad the right of the number with the correct amount of spaces.

**Comment by markblundeberg** [comment]
If we don't use a monospace font, it's possible to achieve the same effect using the figure space instead of regular space. (`\u2007`)

https://en.wikipedia.org/wiki/Figure_space

Example:

* 123.18293798xxxx
* 123.        xxxx  (eight figure spaces)

**Comment by cculianu** [comment]
WOAH DUDE. I didn't know about the figure space.. go unicode!! That would have come in handy with my iOS work! And other apps I've written. 

The numbers in the coins tab don't look to be monospace.. but i'll play around.  You've given me a valuable tidbit with that figure space. Thanks!

**Comment by cculianu** [comment]
This was an easy fix.. I just decided to go with monospace (Indeed the \u2007 did look ok too with non-monospace -- but monospace looks better IMHO).  W00t. Looks good, I think.  Thanks a lot @Mengerian for bringing this up -- and thanks @markblundeberg for your helpful suggestions as always.

**Comment by cculianu** [comment]
Looks better on cashshuffle too:

<img width="389" alt="screen shot 2019-03-04 at 10 12 01 pm" src="https://user-images.githubusercontent.com/266627/53760109-970c6a80-3eca-11e9-972d-1bd916497060.png">

**Comment by marceloneil** [comment]
Monospace is a much better choice for tabular data, it was a great idea!

**Comment by cculianu** [comment]
Yeah -- whoever implemented it initially i guess forgot that refinement.  Funnily enough Electrum already has this fix so .. obviously someone complained there too. :)
