### ISSUE TITLE
Transaction status shows "Not verified" with Tor on clean install

### ISSUE THREAD

**Issue by jcramer** [Electron-Cash/Electron-Cash#1181]
If a user installs Electron Cash for the first time (i.e., there is no pre-existing `~/.electron-cash` folder with block headers downloaded) and he selects Tor proxy at Install Wizard, any pre-existing wallet file loaded with transaction history will show status of "Not verified".

**Comment by cculianu** [comment]
Thanks for finding this. I think this exposes some "race" type situation between the block header downloader and the verifier but I'm not sure yet.  Maybe.. maybe not.

I definitely was able to easily reproduce it.  Will look at it when I get time.

**Comment by cculianu** [comment]
Is it still doing this? I mucked around the wallet and verifier code and fixed a few things. Let me know.

**Comment by jcramer** [comment]
Wow, it's fixed! Thank you @cculianu

**Comment by cculianu** [comment]
Awesome!
