### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type PopupLabel has been deleted

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1183]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/home/sgoh/bin/dev/shuffletest/gui/qt/popup_widget.py", line 227, in autoHide
    self._startTimer(self.hide)
  File "/home/sgoh/bin/dev/shuffletest/gui/qt/popup_widget.py", line 201, in _startTimer
    self._timer = QTimer(self)

RuntimeError: wrapped C/C++ object of type PopupLabel has been deleted
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.9.6ShufBeta  | 3.7.2 (default, Jan 16 2019, 19:49:22)  [GCC 8.2.1 20181215 (Red Hat 8.2.1-6)] | Linux-4.20.7-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine | standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
Fixed in latest cashshuffle commit.
