### ISSUE TITLE
Package libsecp256k1.so in the .tar.gz and/or .zip "src" distributions.

### ISSUE THREAD

**Issue by cculianu** [Electron-Cash/Electron-Cash#1188]
Well -- concern has been raised that CashShuffle and Electron Cash in general needs libsecp for smoothe operation.  Python ecdsa is just too slow.

So -- in telegram @markblundeberg , @im_uname, and I came up with:

The "source distribution" we do already bundles some dependencies (so that people without a full python install can run Electron Cash). I think they may even already bundle binaries anyway as part of some of the python deps, correct? (Please comment on this if that's not the case).

Anyway -- the solution is: We can compile the lib with very-compatible CPU settings and no external dependencies and package it with the .tar.gz -- perhaps offer an x86 and amd64 .so and then Electron Cash can just use it.

- We'd need to add a script in contrib/ such as make_libsec or something and have that be part of the release process Jonald goes through.  `python setup.py sdist` will pick up the lib and throw it in the .tar.gz.

Questions:

1. Should we also bundle a macos .dylib in there? (perhaps the odd macos person runs from srcdist)
2. Should we also bundle a windos .dll in there? (perhaps the odd Windows person does same)

Answers:

3. In the case that the lib can't be loaded, we call back to python ecdsa for EC operations but we complain and/or inform the user that they should figure out how to install libsecp256k1 on their system.

---

Thoughts? Comments on the above?

**Comment by imaginaryusername** [comment]
If the mac and windows libs aren't too big, there's probably no harm in packing them in. Yes to (3).

**Comment by cculianu** [comment]
Hmm.. like 400kb for the mac and i think half that for windows...

 But the issue is do we figure out how to cross-compile them deterministically on Linux (I don't think that's that hard actually just a lot of work) -- or do we do the evil thing and just throw them in there and "hope people trust us" (muahaha)?

**Comment by cculianu** [comment]
Done in a recent commit. Closing. Yay!
