### ISSUE TITLE
When previous wallet was SLP, opening with standard EC throws a modal warning and does not allow selecting a new wallet.

### ISSUE THREAD

**Issue by emergent-reasons** [Electron-Cash/Electron-Cash#1189]
I am reporting for another user. I can ask more details if you need it.

OS: latest MacOS
EC Versions:
- SLP
- Standard (sorry I didn't get the exact version)

Expected behavior

- Open an SLP wallet in EC-SLP
- Close it
- Open EC-standard
- Previously opened wallet was SLP --> warning
- Select a non-slp wallet

Reported behavior:

- Open an SLP wallet in EC-SLP
- Close it
- Open EC-standard
- warning modal about unknown wallet type that shuts down the app when closed/oked.

![image](https://user-images.githubusercontent.com/34025062/54299533-7052e000-45fe-11e9-9fc9-9fb5f08d9c67.png)

**Comment by cculianu** [comment]
Yeah this is bad.  Will fix.

**Comment by emergent-reasons** [comment]
Nice! I will find the person that posted it on twitter and let them know.

**Comment by cculianu** [comment]
Yeah only thing is they need to run from git head .. release is Tuesday..
of CashShuffle verison.  It will contain this fix though so yay!
