### ISSUE TITLE
EC+Shuffle fails to start - workaround to clear config directory

### ISSUE THREAD

**Issue by emergent-reasons** [Electron-Cash/Electron-Cash#1201]
copied from https://github.com/clifordsymack/Electron-Cash/issues/115

MacOS: Mojave 10.14.3
Model: 2017 MacBook Pro

I walked a shuffle user through recovering their setup. Here is the history I heard:

- used mainline EC for a long time, at least months
- used shuffle EC successfully
- ?
- tried to run shuffle EC and gets no response / feedback from osx
- (not 100% about this one) same result on running mainline EC. Not sure if it is because shuffle EC was already running in the background or if it was having the same problem as shuffle EC.

When we investigated with the commandline, we found the following:

- EC was running in the background, two processes you can see in the terminal output below.
- simple kill on the earlier process closed out both of them
- run from the terminal with `-v`
- you can see in the output below that it only logs one config message and then gets stuck

We cleared out everything but wallets from `.electron-cash` and then it started normally and seems to be working with no problems.

```
asdfs-MacBook-Pro:~ asdf$ ps -ax | grep -i electron
[...some electron framework used by discord]
 1490 ??         0:01.46 /Applications/Electron-Cash.app/Contents/MacOS/Electron-Cash -psn_0_520319
 1492 ??         0:00.58 /Applications/Electron-Cash.app/Contents/MacOS/Electron-Cash
 1513 ttys000    0:00.00 grep -i electron

asdfs-MacBook-Pro:~ asdf$ kill 1490

asdfs-MacBook-Pro:~ asdf$ ps -ax | grep -i electron
[...some electron framework used by discord]
 1515 ttys000    0:00.00 grep -i electron

asdfs-MacBook-Pro:~ asdf$ /Applications/Electron-Cash.app/Contents/MacOS/Electron-Cash -v
|  0.425| |00| [SimpleConfig] electron-cash directory /Users/asdf/.electron-cash
^CTraceback (most recent call last):
  File "http/client.py", line 1331, in getresponse
  File "http/client.py", line 297, in begin
  File "http/client.py", line 258, in _read_status
  File "socket.py", line 586, in readinto
KeyboardInterrupt
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "electron-cash", line 373, in <module>
  File "Electron_Cash-3.9.15ShufBeta-py3.6.egg/electroncash/daemon.py", line 64, in get_fd_or_server
  File "Electron_Cash-3.9.15ShufBeta-py3.6.egg/electroncash/daemon.py", line 87, in get_server
  File "jsonrpclib/jsonrpc.py", line 652, in call
  File "jsonrpclib/jsonrpc.py", line 531, in _request
  File "jsonrpclib/jsonrpc.py", line 564, in _run_request
  File "xmlrpc/client.py", line 1154, in request
  File "jsonrpclib/jsonrpc.py", line 372, in single_request
  File "http/client.py", line 1331, in getresponse
KeyboardInterrupt
[1520] Failed to execute script electron-cash
|289.582| |00| [_ExpiringCacheMgr] Cache 'format_satoshis cache' has been gc'd, 0 still alive
|289.582| |00| [_ExpiringCacheMgr] No more caches, stopping manager thread and removing singleton
|289.582| |01| [_ExpiringCacheMgr] thread exit
asdfs-MacBook-Pro:~ asdf$
```

**Comment by emergent-reasons** [comment]
I will try to get the original config folder. I asked her to back it up. I do believe it had a daemon lock or similar file in there even after killing the process.

**Comment by emergent-reasons** [comment]
Attaching config directory from the user. I removed `blockchain_headers` but can get that to you if you need it. The `daemon` file is there.
[electron-cash-config.tar.gz](https://github.com/Electron-Cash/Electron-Cash/files/3000017/electron-cash-config.tar.gz)

**Comment by cculianu** [comment]
Nothing looks unkosher here.  It runs fine and the config is ok. :/

**Comment by emergent-reasons** [comment]
I guess the only clues are the 2 processes (it should usually be 1?) and the last log so we know it is dying after that config log and before whatever the next log usually is.

Since it's moving to mainline, this can probably be left behind. We can close it and reopen it if it appears. How does that sound?

**Comment by cculianu** [comment]
> I guess the only clues are the 2 processes (it should usually be 1?)

No. I said this earlier but maybe you lost it -- the .app uses
pyinstaller.  Pyinstaller creates a "master process" that then unzips the
actual program and runs that as a child process.  Hence the two processes
in the .app case.

> We can close it and reopen it if it appears. How does that sound?

That sounds good.  Honestly there's something bizarre about her setup.  I
actually think electron cash window is somewhere on another desktop/monitor
and she's too nub to find it.  She should use "Expose" on the mac to see
all the windows.  I bet it's there... is there no icon in her dock?
