### ISSUE TITLE
Encourage users to move to new version more directly than showing incompatible pools

### ISSUE THREAD

**Issue by emergent-reasons** [Electron-Cash/Electron-Cash#1221]
I really like the pools for dev use. Now that I think about it for users, they really shouldn't ever need to see it. Maybe it can be in a menu somewhere? On the main ux, I recommend: 

In place of the "omit..." button, it could display something like:

> Using old protocol. Get more shuffling partners by upgrading to the latest version. \<link\>

There is also the general upgrade notifier already so this is an additional layer.

What do you think @cculianu @fyookball ?

**Comment by cculianu** [comment]
Not a bad idea. 👍

**Comment by cculianu** [comment]
I'd still want ot see the incompatible pools somehow tho.. :/  but i do agree with the notification that you may need to upgrade.

I *really* like the incompatible pools thing... can you tell?

**Comment by emergent-reasons** [comment]
I do too! I think it's still useful for debug / dev. Not sure what menu to put it in but a menu would be ok right?

**Comment by emergent-reasons** [comment]
Closing as irrelevant since everything has moved on to fusion.
