### ISSUE TITLE
Specifying server in command line does not work in combination with "preferred servers" feature

### ISSUE THREAD

**Issue by dagurval** [Electron-Cash/Electron-Cash#1222]
In master branch, by default
```
./electron-cash --oneserver --server=127.0.0.1:60001:t --testnet
```
does not connect the client to the specified server, but some random other server. When I go into the network settings and uncheck "Connect only to preferred servers", this feature works again.

**Comment by cculianu** [comment]
OK, will fix.

**Comment by cculianu** [comment]
Fixed in latest commit.  I added 

```
calin@CalinMBP2016 ~/src/ec/electron-cash $ ./electron-cash daemon --help
# ... some stuff ...
  -x, --disable_preferred_servers_only
                        Disables 'preferred servers only' for this session.
                        This must be used in conjunction with --server or
                        --oneserver for them to work if they are outside the
                        whitelist in servers.json (or the user-specified
                        whitelist).
```

**Comment by cculianu** [comment]
(Sorry it took me so long.. was a trivial fix. I was a bit busy).

Let me know if it solves the problem you wanted solved... this was the easiest fix.  Other fixes include checking the config override and implicitly setting the flag but that requires more logic and makes the code more spaghettified...
