### ISSUE TITLE
BCH UX Suggestion: Mandatory CashAddr for P2SH

### ISSUE THREAD

**Issue by cculianu** [Electron-Cash/Electron-Cash#1225]
See this argument for it:

https://honest.cash/BigBlockIfTrue/bch-ux-suggestion-mandatory-cashaddr-for-p2sh-1214

**Comment by haplo** [comment]
I'd like to work on this issue, @cculianu. If I understand correctly this is what we want:

- Forbid sending to legacy-format P2SH addresses (i.e. those starting with a 3). Tell the user to obtain a CashAddr address. Maybe link to the honest.cash article?
- Advanced setting to disable this behavior (enabled by default)?
- Warning in the EC CashAddr converter when receiving a legacy P2SH address as input?

**Comment by cculianu** [comment]
Hey there -- feel free to try an implementation.  I may just tick this one off though pretty soon as it's been an outstanding issue for some time and people are making noise about it.

**Comment by haplo** [comment]
I started looking into the code yesterday (I'm new to the codebase), but didn't change anything yet, so just let me know and I'll find something else (#1450 is the only other issue labeled as "Good first issue", it'd be great if you could label other issues that are approachable for newcomers).

**Comment by cculianu** [comment]
Fixed in e6a195b77adbfb4419808cef607c18ae3557c710

**Comment by cculianu** [comment]
@haplo -- Yeah #1450 is difficult for me because I don't actually run Linux anymore.. it requires messing with the packaging system and stuff.  May the force be with you!

**Comment by cculianu** [comment]
This might be related: #1657
