### ISSUE TITLE
Ui pet peeve: make absolutely everything in tx dialog clickable 

### ISSUE THREAD

**Issue by cculianu** [Electron-Cash/Electron-Cash#1229]
Click an input -> opens the prevhash tx in another dialog (even if the tx isn’t yours)

Click an address -> offers a context menu to either open address in addresses tab if yours and/or see address details (history) EVEN IF NOT YOURS

Click an output -> do something clever. Like address and/or perhaps even spending tx if any...

**Comment by markblundeberg** [comment]
This would be pretty rad -- basically an in-wallet block explorer.

**Comment by markblundeberg** [comment]
We should improve the input classification system if this is to work properly with p2sh inputs that aren't multisig

**Comment by cculianu** [comment]
I'm down.  Definitely. Speaking of input classification system and/or limitations on how tx's are interpreted -- got a bug recently that I could use your help on (it may or may not be related to said input classification system - #1260

**Comment by cculianu** [comment]
This has been partially addressed in commit 46df4190c8a32fbada777d82e8663b01d062b739, but more is needed.

**Comment by cculianu** [comment]
More of this has been addressed in commit 52d845017c99d5c9a02df6b9af7825d2111b8def

I am considering this issue closed.  Note still cannot open addresses not belonging to wallet but perhaps that is a bit too ambitious for now.
