### ISSUE TITLE
AttributeError: module 'PyQt5.QtGui' has no attribute 'QInputDialog'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1235]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "D:\Electron Cash\electroncash_plugins\email_requests\qt.py", line 147, in <lambda>
    menu.addAction(_("Send via e-mail"), lambda: self.send(window, addr))
  File "D:\Electron Cash\electroncash_plugins\email_requests\qt.py", line 159, in send
    recipient, ok = QtGui.QInputDialog.getText(window, 'Send request', 'Email invoice to:')

AttributeError: module 'PyQt5.QtGui' has no attribute 'QInputDialog'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.6  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17763-SP0 | imported_addr | en_US | 

Additional Information
------------------------

> IMGONAMAKEIT80@GMAIL.COM

---

**Comment by cculianu** [comment]
I fixed this in latest commit.  Requests plugins was very b0rken.
