### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'verify'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1237]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.3.6-py3.5.egg\electroncash_gui\qt\invoice_list.py", line 90, in <lambda>
  File "site-packages\electron_cash-3.3.6-py3.5.egg\electroncash_gui\qt\main_window.py", line 2012, in show_invoice

AttributeError: 'NoneType' object has no attribute 'verify'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.6  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17763-SP0 | imported_addr | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
This was fixed in a recent commit.

Related electrum issue: https://github.com/spesmilo/electrum/issues/5222
