### ISSUE TITLE
Yellow background makes address illegible in dark mode

### ISSUE THREAD

**Issue by ty-everett** [Electron-Cash/Electron-Cash#1238]
When previewing a transaction in dark mode, highlighted addresses are white text on a yellow background. Using a yellow foreground color and a transparent background color in dark mode would greatly improve readability.

<img width="862" alt="Screen Shot 2019-03-31 at 4 43 42 PM" src="https://user-images.githubusercontent.com/23272461/55296923-f760d000-53d4-11e9-9cea-ac008c69c384.png">

**Comment by cculianu** [comment]
Yes, this looks terrible too.  I think the "ColorScheme" we use for dark mode definitely needs turning.  I'll fix this.

I didn't know it looked this bad on that screen. I  will fix this.

**Comment by TGollowitsch** [comment]
Just noticed this while using Dark Mode, same readability issue. EC v4.1.0 (Windows)
![image](https://user-images.githubusercontent.com/48141257/89527135-31917b80-d82c-11ea-9f4b-4137e7079143.png)

**Comment by ty-everett** [comment]
Also, if someone is already going to take the time to improve the UI for this page, the black QR code icon should probably be white while in dark mode.
