### ISSUE TITLE
QR code button should be white in dark mode

### ISSUE THREAD

**Issue by ty-everett** [Electron-Cash/Electron-Cash#1239]
When in dark mode, the QR code icon button (on the bottom-left of this screenshot) is black on a dark background. Making the icon white when in dark mode would improve usability. This occurs in the "Preview Transaction" screen.

<img width="862" alt="Screen Shot 2019-03-31 at 4 43 42 PM" src="https://user-images.githubusercontent.com/23272461/55296953-76560880-53d5-11e9-8545-b85791a38c2f.png">

**Comment by cculianu** [comment]
Oh wow that looks terrible. I will fix it.  Thank you for bringing this to my attention.
