### ISSUE TITLE
No balance showing up

### ISSUE THREAD

**Issue by 0psd** [Electron-Cash/Electron-Cash#1241]
Hello everyone. 

I got some issue with a wallet. I got Mac OS 10.11.6. Friend of mine has sent me few BSV coins from his Coinomi wallet (I've checked that he was sending coins exactly to BSV and Not BCHABC wallet link) and transaction went through and it is visible in any block explorer but it is not showing up in my Electron Cash wallet. I guess I have to set it up some specific way, but during installation I've chosen the standard offered options of setup like Create new standard wallet->Create a new seed->retype seed... Nothing special hasn't been done in my opinion. Please help me and I will reward you for your help with some fractal of coins. Thanks in advance.

PS. my trasaction:
https://bchsvexplorer.com/address/bitcoincash:qzzvk85s4c33pcp039yf0zsmecw3atux0ynveh4snf

**Comment by cculianu** [comment]
We don't support BSV.  Electron Cash is a Bitcoin Cash wallet.  You should try one of the BSV wallets.

**Comment by 0psd** [comment]
Excellent! That means my coins are lost? On reddit people where suggesting to use exactly this wallet for BSV

**Comment by cculianu** [comment]
You have to find version 3.3.3 which is the last version that supported BSV
or use Mark Lundeberg's CoinSplitter version:
https://github.com/markblundeberg/coinsplitter/releases

**Comment by 0psd** [comment]
Wow, thank you so much. I got it, you made my day. Can I make some donation to support your project?

**Comment by cculianu** [comment]
BCH or BSV? I won't refuse you!   bitcoincash:qplw0d304x9fshz420lkvys2jxup38m9symky6k028

**Comment by 0psd** [comment]
BSV i guess.

**Comment by cculianu** [comment]
thanks sir! :D
