### ISSUE TITLE
Ledger: Warn when btchip-python is not installed

### ISSUE THREAD

**Issue by EchterAgo** [Electron-Cash/Electron-Cash#1244]
As discussed in #925, there needs to be a warning message when `btchip-python` is not installed. Maybe there should be a general system for plugins to signal missing dependencies.

**Comment by cculianu** [comment]
Ok so I did some digging and there is such a mechanism in Electron Cash.  It's a bit contorted but you can look at what the Trezor plugin does.

Basically you write to `self.libraries_available_message` in the plugin instance and that string ends up hitting the UI when the user tries to open the hardware wallet in EC.

Here is a place to look:

https://github.com/Electron-Cash/Electron-Cash/blob/be671f1af888fc0eede7c11f7be698a1e25eceda/plugins/trezor/trezor.py#L120  and https://github.com/Electron-Cash/Electron-Cash/blob/be671f1af888fc0eede7c11f7be698a1e25eceda/plugins/trezor/trezor.py#L35 and https://github.com/Electron-Cash/Electron-Cash/blob/be671f1af888fc0eede7c11f7be698a1e25eceda/plugins/hw_wallet/qt.py#L196 for the actual code that acts on that message and on the `self.libraries_available` variable...

Trezor does it this way but I guess the Ledger plugin never implemented this mechanism.

It's contorted but it exists... hopefully this helps you in your fixups?

**Comment by EchterAgo** [comment]
So, the problem here is not when you already have a wallet file created for a hardware wallet. If you already have a file you get this error when opening it:

![image](https://user-images.githubusercontent.com/922233/55526203-4ef58900-56be-11e9-87aa-899aeb23e53e.png)

the problem is when you create a new wallet and the library is not installed you only get this:

![image](https://user-images.githubusercontent.com/922233/55526179-3b4a2280-56be-11e9-8e75-b391c00c1e04.png)

which does not show anything about the library problems.

**Comment by EchterAgo** [comment]
In `BaseWizard.choose_hw_device` there is this code:
```
        # check available plugins
        support = self.plugins.get_hardware_support()
        if not support:
            msg = '\n'.join([
                _('No hardware wallet support found on your system.'),
                _('Please install the relevant libraries (eg python-trezor for Trezor).'),
            ])
            self.confirm_dialog(title=title, message=msg, run_next= lambda x: self.choose_hw_device())
            return
```
The problem here is that the message only triggers when `get_hardware_support` returns an empty list. This can never happen as all it does is check if the plugin is enabled but the `HW_PluginBase.is_enabled` always returns `True`. To fix this I will add `and p.libraries_available` to the check in `get_hardware_support`. The function is only used from that one call site in `BaseWizard` so the change should not have any side-effects.

**Comment by EchterAgo** [comment]
Actually, I think it would be better to handle this in `choose_hw_device` with `any` and list comprehension. That way we can also show which plugins are missing libraries in case no unpaired HW wallet is found.

**Comment by EchterAgo** [comment]
The dialog when no HW devices have their libraries installed now looks like this:

![image](https://user-images.githubusercontent.com/922233/55527474-684d0400-56c3-11e9-968c-45f0d197cbac.png)

Also, I added `hidapi` to the `requirements-hw.txt`, the digitalbitbox plugin needs it.

**Comment by EchterAgo** [comment]
New message when some plugins are missing the libraries:

![image](https://user-images.githubusercontent.com/922233/55528713-1064cc00-56c8-11e9-8203-451210bb7ebd.png)

**Comment by EchterAgo** [comment]
When all libraries are available the dialog looks like this:

![image](https://user-images.githubusercontent.com/922233/55528799-689bce00-56c8-11e9-8ba4-b8c226b9dbca.png)

**Comment by cculianu** [comment]
Ah yes.  Wow.  You did great work here. I think this is very helpful for users.  I especially like that you detect when there is a problem loading the plugin versus when everything is good and it really can't see the hardware device. I think that's very very good.  And I love how you showed me screenshots to illustrate the new flow.
