### ISSUE TITLE
Ledger not detected (but Trezor is, and Electrum detects both Ledger and Trezor)

### ISSUE THREAD

**Issue by dreboli** [Electron-Cash/Electron-Cash#1249]
Ledger Nano S is not detected in Electron Cash 4.0.0. while it works with Electrum and Ledger Live on the same system (Ubuntu 18.04.2 LTS) without a problem.

Interestingly,  Trezor is detected with Electron Cash on the same system. 

Tried it on 2 other systems, Linux Mint Sonya and Tails with the same result, no hardware device detected.

None of these systems are on WMs.
I followed Ledger's trouble shooting guide and added udev rules to no avail, and as I mentioned Electrum and Ledger live detects my Ledger Nano S without a problem.
Rebooted, replugged the devices many times.

Not sure where to go from here, any help appreciated.

**Comment by dreboli** [comment]
Solved:
```
sudo apt install libudev-dev libusb-1.0-0-dev
pip3 install btchip-python
```

**Comment by cculianu** [comment]
Awesome! :)

**Comment by EchterAgo** [comment]
We really need that `btchip-python` warning (#1244)... I'll try to get something added today. Also, it might make sense to also distribute the Linux version as an AppImage.

**Comment by EchterAgo** [comment]
#1251 should improve the situation by warning users about missing libraries.

**Comment by cculianu** [comment]
> We really need that `btchip-python` warning (#1244)... I'll try to get something added today. Also, it might make sense to also distribute the Linux version as an AppImage.

YES! This! ^^  I want to port over Electrum's AppImage docker file and/or script.  I will do that very soon.  I am glad to see another AppImage supporter.  It really offers a solution to users that just want it to "just work".  And it also is deterministic!

**Comment by EchterAgo** [comment]
I might look into it. I also need to package one of my own apps as AppImage, so it would be good to learn more about it.

**Comment by cculianu** [comment]
Yeah I was going to do this after this release for EC.
