### ISSUE TITLE
Windows: Bundle ANGLE into the Windows installer

### ISSUE THREAD

**Issue by EchterAgo** [Electron-Cash/Electron-Cash#1255]
The Windows installer is currently lacking ANGLE libraries which will result in issues with some graphics drivers with sub-par OpenGL support.

ANGLE is libEGL.dll and libGLESV2.dll, which are included in my PyQt5 on Windows. By default Qt is built with -opengl dynamic, which will default to OpenGL 2.0 but fall back on ANGLE if it doesn't like the driver. There is also an optional fallback on opengl32sw.dll, which is essentially Mesa for Windows and does software rendering, but that is 20MB in size alone. I think we should just make sure to include libEGL.dll and libGLESV2.dll, which would be an extra 2.4MB. 

See #1253 for additional discussion.

**Comment by EchterAgo** [comment]
The file `d3dcompiler_47.dll` is also needed, so it is a total of 6.38MB.

**Comment by cculianu** [comment]
Ok so the docker wine dir that is created does include those DLLs (this is 32-bit windows we build for for maximal compat.). Here is the full DLL list -- should I include anything else?

```
total 60688
drwxr-xr-x  2 root root     4096 Nov 11  2000 DLLs
-rw-r--r--  1 root root    30342 Nov 11  2000 LICENSE.txt
drwxr-xr-x 30 root root     4096 Nov 11  2000 Lib
-rw-r--r--  1 root root   435627 Nov 11  2000 NEWS.txt
-rw-r--r--  1 root root   342016 Nov 11  2000 Qt5Bluetooth.dll
-rw-r--r--  1 root root  4874240 Nov 11  2000 Qt5Core.dll
-rw-r--r--  1 root root   349184 Nov 11  2000 Qt5DBus.dll
-rw-r--r--  1 root root  3993600 Nov 11  2000 Qt5Designer.dll
-rw-r--r--  1 root root  5197312 Nov 11  2000 Qt5Gui.dll
-rw-r--r--  1 root root   275968 Nov 11  2000 Qt5Help.dll
-rw-r--r--  1 root root  1122816 Nov 11  2000 Qt5Location.dll
-rw-r--r--  1 root root   581632 Nov 11  2000 Qt5Multimedia.dll
-rw-r--r--  1 root root    83456 Nov 11  2000 Qt5MultimediaWidgets.dll
-rw-r--r--  1 root root   984064 Nov 11  2000 Qt5Network.dll
-rw-r--r--  1 root root   115712 Nov 11  2000 Qt5NetworkAuth.dll
-rw-r--r--  1 root root   105472 Nov 11  2000 Qt5Nfc.dll
-rw-r--r--  1 root root   271872 Nov 11  2000 Qt5OpenGL.dll
-rw-r--r--  1 root root   250880 Nov 11  2000 Qt5Positioning.dll
-rw-r--r--  1 root root    49664 Nov 11  2000 Qt5PositioningQuick.dll
-rw-r--r--  1 root root   266240 Nov 11  2000 Qt5PrintSupport.dll
-rw-r--r--  1 root root  2641408 Nov 11  2000 Qt5Qml.dll
-rw-r--r--  1 root root  3009536 Nov 11  2000 Qt5Quick.dll
-rw-r--r--  1 root root   143360 Nov 11  2000 Qt5QuickControls2.dll
-rw-r--r--  1 root root   369152 Nov 11  2000 Qt5QuickParticles.dll
-rw-r--r--  1 root root   759296 Nov 11  2000 Qt5QuickTemplates2.dll
-rw-r--r--  1 root root   112128 Nov 11  2000 Qt5QuickTest.dll
-rw-r--r--  1 root root    60416 Nov 11  2000 Qt5QuickWidgets.dll
-rw-r--r--  1 root root   161280 Nov 11  2000 Qt5Sensors.dll
-rw-r--r--  1 root root    67072 Nov 11  2000 Qt5SerialPort.dll
-rw-r--r--  1 root root   158720 Nov 11  2000 Qt5Sql.dll
-rw-r--r--  1 root root   265216 Nov 11  2000 Qt5Svg.dll
-rw-r--r--  1 root root   205824 Nov 11  2000 Qt5Test.dll
-rw-r--r--  1 root root    87040 Nov 11  2000 Qt5WebChannel.dll
-rw-r--r--  1 root root   110592 Nov 11  2000 Qt5WebSockets.dll
-rw-r--r--  1 root root  4429312 Nov 11  2000 Qt5Widgets.dll
-rw-r--r--  1 root root   233984 Nov 11  2000 Qt5WinExtras.dll
-rw-r--r--  1 root root   150016 Nov 11  2000 Qt5Xml.dll
-rw-r--r--  1 root root  2245632 Nov 11  2000 Qt5XmlPatterns.dll
drwxr-xr-x  3 root root     4096 Nov 11  2000 Scripts
drwxr-xr-x  7 root root     4096 Nov 11  2000 Tools
-rw-r--r--  1 root root   250160 Nov 11  2000 concrt140.dll
-rw-r--r--  1 root root  3466856 Nov 11  2000 d3dcompiler_47.dll
drwxr-xr-x  2 root root     4096 Nov 11  2000 include
-rw-r--r--  1 root root    13312 Nov 11  2000 libEGL.dll
-rw-r--r--  1 root root  1950720 Nov 11  2000 libGLESv2.dll
-rw-r--r--  1 root root  1269248 Nov 11  2000 libeay32.dll
drwxr-xr-x  2 root root     4096 Nov 11  2000 libs
-rw-r--r--  1 root root   462120 Nov 11  2000 msvcp140.dll
-rw-r--r--  1 root root 15995904 Nov 11  2000 opengl32sw.dll
-rwxr-xr-x  1 root root    97296 Nov 11  2000 python.exe
-rw-r--r--  1 root root    58384 Nov 11  2000 python3.dll
-rw-r--r--  1 root root  3453968 Nov 11  2000 python36.dll
-rwxr-xr-x  1 root root    95760 Nov 11  2000 pythonw.exe
-rw-r--r--  1 root root   277504 Nov 11  2000 ssleay32.dll
-rw-r--r--  1 root root    87352 Nov 11  2000 vcruntime140.dll
```

**Comment by cculianu** [comment]
Also: Do you think this line from `deterministic.spec` will break things?

```
# Strip out parts of Qt that we never use. Reduces binary size by tens of MBs. see #4815
qt_bins2remove=('qt5web', 'qt53d', 'qt5game', 'qt5designer', 'qt5quick',
                'qt5location', 'qt5test', 'qt5xml', r'pyqt5\qt\qml\qtquick')
```
Can I send you a windows build that includes the DLLs to test? Would you be able to tell what it's doing and if it's using D3D or not?

**Comment by EchterAgo** [comment]
Yea, you can send me a build, but I'm not sure I can test it this evening. I don't see a problem with removing the other libraries. I'm also still trying to figure out how the OpenGL tester/blacklist of Qt on Windows works.

**Comment by EchterAgo** [comment]
Change `C:/python*/d3dcompiler_47.dll` to `C:/python*/d3dcompiler_*.dll`, this filename might change in the future.

**Comment by EchterAgo** [comment]
So, it looks like the driver version `10.18.10.5059` in #1253 is not on the Qt blacklist:
https://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/windows/openglblacklists/default.json
It only blacklists the Intel driver `<=10.18.10.3277`. 

This ticket suggests that even with the latest driver the Window Intel OpenGL ICD has issues and really should be blacklisted:
https://github.com/Yubico/yubikey-manager-qt/issues/60

If users have issues like that we should suggest running with QT_OPENGL=angle

**Comment by cculianu** [comment]
- Ok, I updated the `deterministic.spec` in the  `docker_windows_opengl_fix` branch to pick up a filename glob of `d3dcompiler_*.dll`

- I built some .exe's for windows and they seem to contain all 3 of the libs you recommended.  Is there a way for you to verify that the "right thing" is happening?  You can download them here: https://www.c3-soft.com/downloads/BitcoinCash/Electron-Cash/misc/

- As for QT_OPENGL=angle -- I could easily add this to the electron-cash env vars which would mean it would be in the env before PyQt is loaded into memory (and thus its DLLs and thus Qt) -- should we do this? Are there drawbacks to this?

By the way, I really appreciate the investigation and thorough platform knowledge here...

**Comment by cculianu** [comment]
PS: Get to testing it when you get to it -- this probably won't make today's release but if we figure it out and it's kosher (as in does no harm and only helps), we can definitely merge my `docker_windows_opengl_fix` branch to address this.

**Comment by EchterAgo** [comment]
I was wondering why EC even loads OpenGL libs in the first place because I thought only Quick (QML) and OpenGL components use OpenGL, but apparently now even GUI and Widgets load OpenGL. Widgets uses it for QOpenGLWidget, which we don't use, but GUI uses it for accelerated composition. Sadly the only way I see to disable that, and therefore prevent OpenGL being loaded/needed, is to recompile Qt with `-no-opengl` configure flag.

The build you made does load ANGLE when I set environment variable `QT_OPENGL` to `angle`, so dynamic loading of OpenGL implementations is working. I am not sure it is a good idea to set `QT_OPENGL` in `os.environ`, there are blacklist entries that blacklist ANGLE. I think the default setting should be fine, it will determine what implementation to use based on blacklist and testing OpenGL 2 support.

There are also cases where the blacklist forces software rendering, which would need `opengl32sw.dll` (~6MB compressed). I'm not sure if we should include it, but it would make the app work in case there is no 3D acceleration.

Also you include unneeded `qwebgl.dll`, `qoffscreen.dll` and `qminimal.dll` platform plugins. Those are ~700 KB compressed that you can save.

**Comment by EchterAgo** [comment]
It might be a good idea to have a command line option to set `QT_OPENGL` in case a user wants to force ANGLE / Mesa.

**Comment by cculianu** [comment]
I think qoffscreen.dll is used to render to things like QPaintDevices and off screen (we use that for composing the QR widgets).. no?  We still need that one.  

I'm ok with 6MB extra compressed -- I'll run  it by Jonald first though since he makes these decisions (he has a good feed for what the "market" wants) -- and it's his territory here.  

As for command-line options.. well Windows & command-line?  Well the option could be there and the installed version could offer a shortcut to "Electron-Cash (ANGLE Rendering)" or something, which then invokes Electron-Cash with -angle or something.

Honestly this might just be a corner case for like 0.0001% of users.  I wonder if we should even bother.. do you think we should?

**Comment by EchterAgo** [comment]
Probably right about `qoffscreen.dll`. I think just adding ANGLE without any command line switches should be enough, let Qt deal with blacklisting. If the extra size doesn't bother anyone I would also include the software renderer.

In case we have users having problems with OpenGL ICDs, we should just recommend trying to manually set `QT_OPENGL` to `angle` or `software`. It would also help to report the cases where this helps to the Qt bugtracker as it is something that should be on the blacklist.

**Comment by EchterAgo** [comment]
As for how many users this affects, my app sure doesn't have as many users as Electron Cash, I think a couple hundred users at most, but even in those we had 5 cases of problems with Desktop OpenGL (Intel GPUs are very common and have horrible Windows OpenGL drivers) and even one with no usable OpenGL. Since my app is expensive and does require OpenGL for displaying measurement data I definitely had to include both ANGLE and Mesa.

**Comment by cculianu** [comment]
Ok, so to summarize:

- basically ANGLE is much more likely to work right for most users since it's opengl -> directx translation.
- software rendering works for everybody but is slower and dumb
- OpenGL native drivers from some vendors (such as intel) are notoriously unreliable, right?
- Qt sometimes picks the right implementation based on what it knows about bad vendors, but the bad vendor list is not always accurate.  Qt prefers OpenGL but can pick ANGLE and/or software on its own if bad vendor?

Is the above accurate?

Hmm.  Let me ask Jonald what he thinks.  If it were up to me I'd package them all and be done with it and perhaps in the installed version offer a shortcut to run with software or angle or both.  But Jonald is sensitive about the windows version being a certain way so maybe he won't like the 6MB thing (or maybe he wouldn't mind).

**Comment by cculianu** [comment]
@EchterAgo also what app is your app? Just curious..

**Comment by EchterAgo** [comment]
Yea, that is accurate. My Qt app is [OptiTUIO](http://www.interactive-asia.com/laser-touch-controller-optituio/), which converts LIDAR scan data into multi touch.

**Comment by cculianu** [comment]
Wow.. this app you have is pretty cool! Lasers to make anything into a touch surface.  Very cool.  Ha.. I can see the Qt there in your screenshots, ha ha.  Are you doing some light OpenGL rendering in that calibration tool thing?  Looks like opengl drawing in there...

**Comment by EchterAgo** [comment]
Yea, it is quite nice and you can make huge touchscreens with it. Sadly the screenshots are quite low quality, I'll have to tell the guy doing the marketing/website. It is drawing the scan data using glDrawArrays with GL_POLYGON. This is just in the calibration tool, we also have a server that runs without any GUI or OpenGL.

**Comment by cculianu** [comment]
Pretty cool. 👍 If I see you on slack I'll ask you more about it to keep the topic here focused.

**Comment by cculianu** [comment]
Good news! Jonald is down for +6MB if it means it will run for everybody.

So just to recap, you recommend:

- add `libEGL.dll`
- add `libGLESv2.dll`
- add `d3dcompiler_*.dll`
- add `opengl32sw.dll`

And.. should we add a switch?  You're thinking `-angle`  to force `QT_OPENGL=angle`?

**Comment by EchterAgo** [comment]
Yea, that is pretty much it. I'll check that the new command line switch loads the correct libraries.

**Comment by EchterAgo** [comment]
I've confirmed that the correct libraries are getting loaded.

**Comment by cculianu** [comment]
Just curious -- how did you check?  I used "Process Explorer" to see what DLLs got loaded in each case and it seemed to me 'software' loaded openglsw23.dll and 'angle' ended up loading libGLES and its buddy (but not d3dcompiler).

I couldn't tell from within ElectronCash (console) what the opengl implementation it was using was -- would be curious if you knew of some Qt call that tells you.  (None of the calls that deal with OpenGLFunctions seem to work from within Python).

**Comment by EchterAgo** [comment]
I haved checked using a debugger and checking the module list for the same libraries as you did. I think d3dcompiler might not actually be needed in the case of EC as it is likely not using any shaders.

I also just found out how to enable debug logging for the Qt OpenGL selection:

set QT_LOGGING_RULES=qt.qpa.gl=true

I get this output without any command line switches:

```
qt.qpa.gl: QWindowsIntegration::createPlatformOpenGLContext QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
qt.qpa.gl: Basic wglCreateContext gives version 4.6
qt.qpa.gl: OpenGL 2.0 entry points available
qt.qpa.gl: GPU features: QSet()
qt.qpa.gl: QWindowsOpenGLTester::supportedRenderers GpuDescription(vendorId=0x1002, deviceId=0x67df, subSysId=0x4fb1043, revision=199, driver: "aticfx64.dll", version=25.20.15021.1007, "Radeon (TM) RX 480 Graphics") renderer:  QFlags(0x1|0x2|0x4|0x8|0x20)
qt.qpa.gl: Qt: Using WGL and OpenGL from "opengl32.dll"
qt.qpa.gl: QOpenGLStaticContext::create OpenGL: "ATI Technologies Inc.","Radeon (TM) RX 480 Graphics" default ContextFormat: v4.6 profile: QSurfaceFormat::OpenGLContextProfile(CompatibilityProfile) options: QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions),SampleBuffers, Extension-API present
Extensions: 298
qt.qpa.gl: QWindowsGLContext::QWindowsGLContext WGL extensions: WGL_ARB_extensions_string WGL_ARB_pixel_format WGL_ATI_pixel_format_float WGL_ARB_pixel_format_float WGL_ARB_multisample WGL_EXT_swap_control WGL_EXT_swap_control_tear WGL_ARB_pbuffer WGL_ARB_render_texture WGL_ARB_make_current_read WGL_EXT_extensions_string WGL_ARB_buffer_region WGL_EXT_framebuffer_sRGB WGL_ATI_render_texture_rectangle WGL_EXT_pixel_format_packed_float WGL_I3D_genlock WGL_NV_swap_group WGL_ARB_create_context WGL_AMD_gpu_association WGL_ARB_create_context_profile WGL_ARB_context_flush_control WGL_NV_DX_interop WGL_ARB_create_context_no_error WGL_NV_DX_interop2 WGL_NV_float_buffer
qt.qpa.gl: "ARB::choosePixelFormat  Attributes:  0x2003 , 0x2027 , 0x2010 , 0x1 , 0x2001 , 0x1 , 0x2014 , 0x18 , 0x2011 , 0x1 , 0x2013 , 0x202b , 0x201b , 0x8 , 0x2023 , 0x8 , 0x2041 , 0x0 , \n    obtained px # 5  of  60 \n     PIXELFORMATDESCRIPTOR dwFlags=0x8025 PFD_DRAW_TO_WINDOW PFD_SUPPORT_OPENGL PFD_SUPPORT_COMPOSITION PFD_DOUBLEBUFFER iPixelType=0 cColorBits=32 cRedBits=8 cRedShift=16 cGreenBits=8 cGreenShift=8 cBlueBits=8 cBlueShift=0 cDepthBits=0 cStencilBits=8 cAuxBuffers=4 iLayerType=0 cAlphaBits=8 cAlphaShift=24 "
qt.qpa.gl: ARB::createContext Creating context version 2 . 0 3 attributes
qt.qpa.gl: QWindowsGLContext::QWindowsGLContext 0x1d6bec93280 ARB  requested:  QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(DefaultColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
    obtained # 5 ARB QSurfaceFormat(version 4.6, options QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions), depthBufferSize 0, redBufferSize 8, greenBufferSize 8, blueBufferSize 8, alphaBufferSize 8, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, colorSpace QSurfaceFormat::ColorSpace(sRGBColorSpace), profile  QSurfaceFormat::OpenGLContextProfile(CompatibilityProfile))
     PIXELFORMATDESCRIPTOR dwFlags=0x8025 PFD_DRAW_TO_WINDOW PFD_SUPPORT_OPENGL PFD_SUPPORT_COMPOSITION PFD_DOUBLEBUFFER iPixelType=0 cColorBits=32 cRedBits=8 cRedShift=16 cGreenBits=8 cGreenShift=8 cBlueBits=8 cBlueShift=0 cDepthBits=0 cStencilBits=8 cAuxBuffers=4 iLayerType=0 cAlphaBits=8 cAlphaShift=24  swap interval:  0
    default:  ContextFormat: v4.6 profile: QSurfaceFormat::OpenGLContextProfile(CompatibilityProfile) options: QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions)
    HGLRC= 0x30000
```

`qt.qpa.gl: Qt: Using WGL and OpenGL from "opengl32.dll"` indicates it is using the desktop OpenGL implementation. With `-O software` I get

```
qt.qpa.gl: Qt: Using WGL and OpenGL from "opengl32sw.dll"
qt.qpa.gl: QOpenGLStaticContext::create OpenGL: "VMware, Inc.","Gallium 0.4 on llvmpipe (LLVM 3.6, 256 bits)" default ContextFormat: v3.0 profile: QSurfaceFormat::OpenGLContextProfile(NoProfile) options: QFlags<QSurfaceFormat::FormatOption>(DeprecatedFunctions),SampleBuffers, Extension-API present
Extensions: 207
```

with `-O angle` I see

```
qt.qpa.gl: QWindowsOpenGLTester::supportedGlesRenderers GpuDescription(vendorId=0x1002, deviceId=0x67df, subSysId=0x4fb1043, revision=199, driver: "aticfx64.dll", version=25.20.15021.1007, "Radeon (TM) RX 480 Graphics") renderer:  QFlags(0x2|0x4|0x8|0x20)
qt.qpa.gl: Qt: Using EGL from libEGL
qt.qpa.gl: Qt: Using OpenGL ES 2.0 from libGLESv2
qt.qpa.gl: QWindowsEGLStaticContext::create Created EGL display 0x2406fa2c760 v 1 . 4
```

**Comment by EchterAgo** [comment]
When the driver is blacklisted, the log should contain features like `disable_desktopgl` in the GPU features QSet in this line:

```
qt.qpa.gl: GPU features: QSet()
```

**Comment by cculianu** [comment]
Awesome.. this is good to know even for me beyond Electron Cash.  Thanks! :D
