### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type QTreeWidgetItem has been deleted

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1261]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash_slp-3.4.6-py3.6.egg\electroncash_gui\qt\slp_mgt.py", line 101, in <lambda>

RuntimeError: wrapped C/C++ object of type QTreeWidgetItem has been deleted
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.4.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.17134 | bip39-slp | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
This is SLP. I am pretty sure i know how to fix -- context menus shouldn't hold references to QTreeWidgetItems as they may go away by the time the user picks something from the context menu.

**Comment by cculianu** [comment]
Fixed in latest SLP commit
