### ISSUE TITLE
i cant seem to transfer from my ledger nano s. 

### ISSUE THREAD

**Issue by phedziko** [Electron-Cash/Electron-Cash#1264]
i see my balance on my ledger nano s (live) as well as electron cash but neither seem to work when i try sending them to an address. I get and error 'Invalid data received (0x6a80)'

**Comment by cculianu** [comment]
Hmm.. we have a resident Ledger expert here. I'll page him and hopefully he can come in and help you.  I lack such a device so am unable to troubleshoot, unfortunately. :/

**Comment by phedziko** [comment]
this sucks.. i tried everything but to no avail..

**Comment by cculianu** [comment]
Just hang tight maybe Axel Gembe can help you when he's around.  I already pinged him.

**Comment by EchterAgo** [comment]
Well, as I see it, if Ledger's own software won't work there is not much we can do. The documentation does only say that 6a80 means invalid data. Can you provide the verbose output (-v command line switch) so we can see at which message it fails?

**Comment by cculianu** [comment]
@EchterAgo @phedziko   -- this sounds like an invalid issue. Closing.  LMK if that's not the case.
