### ISSUE TITLE
We probably need to raise the gap limit for change to 20

### ISSUE THREAD

**Issue by cculianu** [Electron-Cash/Electron-Cash#1277]
__The problem:__ CashShuffle can potentially create situations where users have address gaps in their "change" account larger than the default gap limit for change of **6**.  There is no getting around this: Each tentative shuffle (of which there may be up to 6 pending on a default install .. 1 for each of the 6 tiers) reserves **2** change addresses ahead of time.  If only the *last* shuffle succeeds, there could be a gap as large as 10 in the change addresses (actually 11 since the Send tab also reserves a change address of its own).  

Subsequent shuffles or spends may use up these empty addresses in the gap -- but until they happen the wallet is in an in-between state where recovery becomes problematic and/or annoying for users.

__Problem impact:__ Users restoring a wallet that has such a gap may think they are missing funds.  They currently need to go into Wallet -> Scan beyond gap... to recover their funds.  This is something even a pro user (say like Amaury or Jonald or Mark) may forget to do and may panic at first and curse the software.  The software should never require the user to end up in such a situation.

__The solution:__ Make the gap limit for change 20.  The default of 6 is an "Electrumism" of just being very conservative.  It is arbitrary.  Raising it to 20 would solve this problem for users.

__Background:__ There is no "standard' gap limit for change -- historically 20 was used as a gap limit for receiving.  The 6 number appears to be arbitrary.  [BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) (which is an incomplete proposal) mentions a 20 address gap limit and leaves change unspecified.  

Bitcoin Core and Bitcoin ABC internally have an effective gap limit of 1000.

__Rationale:__ Right now effectively we are acting like the gap limit is >6 because of CashShuffle (we are acting like it's 12).  But in our code we have it set to 6.  This is a bug.  Setting it to 20 rights the wrongs.
 
__Summary:__ Let's set the gap limit for change to 20 (to match what our code does).  It will fix things.

---

Update: (For the casual reader) Increasing the gap limit won't mean we break things automatically.  (We already "broke" things by introducing CashShuffle with its strict requirements for how it does change address allocation).  One could set the gap limit to 1 billion and nothing much would change.  You'd eat up a lot of memory and wallet startup would take a day or two -- but you'd only end up with practically 0 address gaps in the wallet (if not using CashShuffle) and with CashShuffle you'd get gaps of 11 at most.  So increasing the gap limit is something we need to do to "read back" our own wallets properly off the blockchain -- and it has nothing to do with us "breaking" wallets going forward -- that has already been done by CashShuffle!

**Comment by markblundeberg** [comment]
![Screenshot from 2019-04-13 12-57-42](https://user-images.githubusercontent.com/36528214/56085571-73f2a600-5dfa-11e9-8d0a-58bed7f5407a.png)
example of a 9-long gap in my change history (from shuffle wallet)

**Comment by cculianu** [comment]
10 long. :'(

You had a bunch of shuffles up in parallel and probably only one of them went through.  Definitely not a "rare" situation.

So yeah. :/

**Comment by markblundeberg** [comment]
Long term we can look into having an even larger change gap limit, but only showing nonempty change addresses in that tab. (i.e., instead of 'Used' list for hiding, put a 'Empty' list)

**Comment by cculianu** [comment]
Hmm.  True.  "Change addresses" are supposed to be "machine-facing" only and not "real-world-facing" so.. that would be an argument for trying to not show them to the user and put them in the "Empty" list...

**Comment by cculianu** [comment]
The gap limit for change has now been changed from 6 to 20 in this commit: 550f3c910ecb870a62761a1fad6d4391fdadc3c2

There. It is done.
