### ISSUE TITLE
[Desktop] BitPay invoice QR code not recognized

### ISSUE THREAD

**Issue by dreboli** [Electron-Cash/Electron-Cash#1279]
4.0.1 Electron Cash
desktop
Tails 3.13.1

The BitPay Invoice is not recognised by the QR code reader in Electron Cash.
I had no problem with other QR generated and shown by Electrum or Electron Cash.

It's a problem with the QR code format or presentation of BitPay, generating my own QR code from the invoice was recognized by Electron Cash.

**Comment by cculianu** [comment]
How do I reproduce?  Use a merchant that sends me to bitpay and try and use their QR code?  What platform are you on?

**Comment by cculianu** [comment]
I just tried it on:

- iOS: **works**
- Mac: **works**
- Windows: (I lack a Windows machine with a camera)
- Linux: (I lack a Windows machine with a camera and my VM isn't using the camera properly)

If others also see this -- 

Linux & Windows both use the 'zbar' library.  Likely this is the culprit.  This is an ancient library and I noticed BitPay is producing some sort of "fancy" QR code.

I bet we aren't the first people to have trouble with they new QR code format.

Maybe we should also contact bitpay.  In the meantime a fix would be to see about possibly using a newer version of ZBar ..

**Comment by cculianu** [comment]
Update: We're working on/thinking about a different approach to reading QR codes on Windows (we currently rely on this zbar program which is old and no longer maintained).  It just may take a while for us to figure this one out -- but this issue isn't forgotten!  Thanks for reporting!

**Comment by cculianu** [comment]
@dreboli  -- Can you verify this is now working?  We updated zbar so detection should be much better now.  Latest release, 4.0.3 available [here](https://electroncash.org) or [here](https://github.com/Electron-Cash/Electron-Cash/relases)

**Comment by cculianu** [comment]
Ok -- well -- we fixed this, I'm pretty sure. Bitpay is working now for me.

**Comment by cculianu** [comment]
FYI -- try latest -dev1 release to test this, if you are still around @dreboli
