### ISSUE TITLE
Ledger: Windows build fails on 2FA for Ledger Nano

### ISSUE THREAD

**Issue by EchterAgo** [Electron-Cash/Electron-Cash#1280]
When trying to sign a transaction with the Windows build and a Ledger Nano / HW1 it will complain about missing `websocket` library. Not sure why this is not available in the Windows package. The error is produced in `plugins/ledger/auth2fa.py`. I think this might be solved by putting `auth2fa.py` into the `Analysis` call in `deterministic.spec`.

**Comment by EchterAgo** [comment]
To add to this, we should probably remove the websocket code from `auth2fa.py` as this service seems to have been discontinued by Ledger. The app for it also disappeared from the Google Play store.

**Comment by cculianu** [comment]
I'm all in favor of removing it. Interestingly we have it in our requirements-binaries.txt as `websocket-client` (is that the one?).

There is no reference in the codebase to it except for in the ledger plugin.  So getting rid of it would be safe.

Now -- of course, I lack a ledger.  Could you see about removing the code?  To me it looks like it's performing some critical functions related to pairing and whatnot for 2fa...  Is it trivial to remove?

**Comment by EchterAgo** [comment]
The whole pairing thing is broken as the service is not online anymore, so I'll try removing it tomorrow.

**Comment by cculianu** [comment]
Closed by #1298 . Thanks @EchterAgo
