### ISSUE TITLE
Windows: zbar crashes

### ISSUE THREAD

**Issue by EchterAgo** [Electron-Cash/Electron-Cash#1282]
Just wanted to test #1279 and zbar instantly crashes for me:

```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: F:\Electron-Cash-4.0.2-dev3-portable.exe
File: zbar/video/dshow.c
Line: 518

Expression: img->datalen == bufferlen

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
---------------------------
Abort   Retry   Ignore   
---------------------------
```

Might be related to the webcam driver I have installed, which is `OBS-VirtualCam`. I'll try to find out why this is happening later, this issue is just so I don't forget.

**Comment by cculianu** [comment]
Thanks for creating the issue.

Another issue with zbar not being that great: #1279  -- zbar has trouble recognizing some bar codes even when it does work.

If it turns out it's not your driver but zbar -- it may be worth exploring other solutions to this.  Ideally it would be a program or DLL you can "just call" and it does the camera reading and QR recognition like zbar does...

**Comment by EchterAgo** [comment]
Yea, I noticed this already. I am currently working on a replacement for zbar using QtMultimedia.

**Comment by cculianu** [comment]
Coo. How would you be doing the decoding?  Something like QZXing?  Or?  (AFAIK there is no QR decoding built into Qt...)

**Comment by EchterAgo** [comment]
I'm not sure yet, might still end up using zbar for detection but using Qt for all the capture / window / device selection stuff. ZXing seems to be Java. An alternative might be OpenCV, but it is big. I also found there is continued development of zbar by Mauro Chehab (maintainer of Linux Kernel Media subsystem) here:

https://github.com/mchehab/zbar/

It also looks like there are some efforts of making it usable in MinGW:

https://github.com/mchehab/zbar/issues/38

**Comment by EchterAgo** [comment]
I also intend to make a separate Qr code reader that takes a screenshot and allows you to select a rect in it to scan for Qr codes. Scanning for these types of Qr codes should be easier, for example the Yubico Authenticator has Python code to do it:

https://github.com/Yubico/yubioath-desktop/tree/master/py/qr

**Comment by EchterAgo** [comment]
BitPay's wallet uses ZXing. I just noticed that QZXing is C++ and not Java, even though it says this in its README:
> Qt wrapper library for the ZXing decoding library.
There are also these two C++ ports:
* https://github.com/nu-book/zxing-cpp
* https://github.com/glassechidna/zxing-cpp

**Comment by cculianu** [comment]
Yeah QZXing is using the C++ port... they copy-pasted the C++ port and put it in a folder buried deep in the project there.

The ideal thing is a library or stand-alone program that works like my QR reader I wrote for macOS -- it just pops up a window with a camera feed, and scans for QR in real time (QZXing does it via some filter scheme supported by Qt which I think is the best) -- this way it's little to no work for you.  Who wants to spend time making a QR reader program..? :)

On macOS the OS comes with this facility built-in -- you do a simple call to some Objective-C object and it does all the work... so I got lucky there -- as the "app" I wrote does little else than call into this subsystem.

This is why ZBar seemed like a good idea for the Electrum devs, I suppose... but it is showing its age... 

Does the Zbar continued impl. also have a standalone program for Linux and Windows like the other zbar we are using does?

**Comment by cculianu** [comment]
I looked at the Linux ZBar guy's repo -- Thus guy did a lot of work it seems but his thing is Linux only.  Still.. maybe we can use his Linux work here.. at least for the linux zbar. :)

**Comment by EchterAgo** [comment]
I read your source for the macOS QR reader, it looks great. It is probably good to just use that on macOS. It seems to handle the permissions well, which I don't know if Qt does.

I'd really like to have the video device access cross platform, which Qt does.

The image capture part and device selection is already working great in my WIP change, maybe I'll just try to use zbar as a first step, then see if we can replace it with ZXing.

Anyway, this will take a few days and the new GoT ep just finished downloading :)

**Comment by EchterAgo** [comment]
I'm trying to build a Python wrapper for `QZXing`, but so far `sip` is winning the fight :\ There are also 2 alternatives that already have Python wrappers:

* https://github.com/lubo/zxinglight
* https://github.com/Polyconseil/zbarlight

I was able to build `zxinglight` but haven't tried `zbarlight` yet. I'd really like to use `QZXing` though because the included filter is quite nice and does all necessary conversions from `QVideoFrame`

**Comment by cculianu** [comment]
Hmm.  Why need a python wrapper at all?  Have you seen the hax in `lib/qrscanner.py`.  

I recommend: 

- make a stand-alone (compiled) program that prints the scanned QR to stdout or nothing on cancel
- we/you can host the github repo of said program and we download it on build (I think adding a build step to fully compile this thing on windows might prove problematic)
- Profit!

So if the above is done: no need for a python wrapper! ;)

**Comment by mchehab** [comment]
> I looked at the Linux ZBar guy's repo -- Thus guy did a lot of work it seems but his thing is Linux only. Still.. maybe we can use his Linux work here.. at least for the linux zbar. :)

Just applied some patches that should make it build on Windows. Please let me know if it builds/works fine. Feel free to send patches if something is still broken on Windows.

**Comment by cculianu** [comment]
Oh wow @mchehab thanks for the response.  I'll make some time today or tomorrow to play with the code and see if it works ok on Windows.  Thanks so much for responding!

**Comment by EchterAgo** [comment]
Thanks for the information @mchehab . I have now successfully built your version of zbar on MinGW 32 & 64 bits. I'll submit a few fixes shortly. The Qt / GTK tools still do not build completely as `scan_video.c` is still Linux only. I'll make this work too later.

**Comment by EchterAgo** [comment]
See https://github.com/mchehab/zbar/pull/41

**Comment by cculianu** [comment]
@EchterAgo has this been fixed with latest release (note our latest release includes your new zbar build stuff).  Can I close this?

**Comment by EchterAgo** [comment]
Yes, it has been resolved. However we still don't support every camera, for that we need the new QR scanner.

**Comment by cculianu** [comment]
Soon!
