### ISSUE TITLE
UnboundLocalError: local variable 'amtw' referenced before assignment

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1286]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/home/smartsix/OpenSwap-0.1/gui/qt/openswap_public.py", line 130, in <lambda>
    b.clicked.connect(lambda: self.make_public_offer(self.c1, self.c2))
  File "/home/smartsix/OpenSwap-0.1/gui/qt/openswap_public.py", line 227, in make_public_offer
    msgbytes = b'\x00\x00' + amtw.to_bytes(8,'big') + amtg.to_bytes(8,'big')

UnboundLocalError: local variable 'amtw' referenced before assignment
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 0.1  | 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0] | Linux-4.15.0-20-generic-x86_64-with-LinuxMint-19-tara | standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
@markblundeberg .. this is one of yours i guess.

**Comment by markblundeberg** [comment]
huh... yep

**Comment by cculianu** [comment]
Don't beat yourself up too much about it.  Happens to the best of us.

**Comment by cculianu** [comment]
Should I close this? Is openswap actively supported/being worked on, etc? (Sorry .. I haven't kept up)...

**Comment by markblundeberg** [comment]
yeah I'll just link it over to here (if only I were admin, I could move the issue)

**Comment by markblundeberg** [comment]
Note to readers: OpenSwap is not really supported right now. I have bigger plans!

**Comment by cculianu** [comment]
Muahaha. Awesome. :)
