### ISSUE TITLE
all my BCH has gone!!!!!

### ISSUE THREAD

**Issue by sharlobin2** [Electron-Cash/Electron-Cash#1288]
Last week, when I wanted to transfer an amount of 0.13, I encountered a message that I had to update to the new version. After updating the new version for a few days, there was no problem, but today I saw that there is a transfer transaction in progress, and the entire zero purse inventory Have been
What happened to my money? How can i get it

**Comment by cculianu** [comment]
I'm sorry. 

You must have been using an old version of electron cash.  Older versions of Electron Cash inherited a vulnerability from Electrum (see:  https://github.com/spesmilo/electrum/issues/5216).

You were the victim of a phishing attack. The link/message you saw in Electron Cash was fake and was designed to trick you.  I am really sorry this bug existed.  It went unnoticed for years.  We patched the bug in Nov (I believe) but you may have been running a version that still had the vulnerability.  The bug allowed a malicious server to send you an arbitrary window when you try to send a tx.

I hope your loss was not that great.  There is not much you can do except for perhaps contact the FBI and report which IP address and server you were connected to.  A lot of people have been scammmed this way -- mostly on Electrum and on BTC.

**Comment by EchterAgo** [comment]
Well, you were hacked through a phishing campaign. If you can find out what site you have visited to download that "new version" I'll send you some BCH, check your browser history. Also, while what we've seen so far only steals keys, your system might not be clean now. Do not trust that system with any cryptocurrency. To be absolutely sure there is no malware on your system you will need to reinstall your operating system. Just using Windows Reset doesn't count, reinstall from clean installation media.
