### ISSUE TITLE
NameError: name 'traceback' is not defined

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1290]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash_slp-3.4.6-py3.6.egg\electroncash_gui\qt\slp_create_token_genesis_dialog.py", line 238, in create_token

NameError: name 'traceback' is not defined
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.4.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.17134 | bip39-slp | en_US | 

Additional Information
------------------------

> é char

---

**Comment by cculianu** [comment]
SLP.

**Comment by cculianu** [comment]
This has since been fixed
