### ISSUE TITLE
can"not start Electron cash

### ISSUE THREAD

**Issue by nikostudent** [Electron-Cash/Electron-Cash#1292]
Hello,
again I have a problem with starting an electron cash
Trying to open my app goes:
"base_library.zip could not be extracted
fopen : Permission denied"
The platform is:
Windows 7 ultimate 64 bit
The program range is 4.0.1 downloaded from the official site
The only change I've made is that I've uninstalled some updates in an attempt to remove telemetry.
I was headed by this site: https: //www.ghacks.net/2017/02/11/blocking-telemetry-in-windows-7-and-8-1/
and removed these updates:
    KB971033-- Description of the update for Windows Activation Technologies
    KB2952664 - Compatibility update for keeping Windows up-to-date in Windows 7
    KB2976978 - Compatibility update for keeping Windows up-to-date in Windows 8.1 and Windows 8
    KB2990214 - An update that lets you upgrade from Windows 7 to a later version of Windows
    KB3021917 - Update to Windows 7 SP1 for performance improvements
    KB3022345 - Update for customer experience and diagnostic telemetry
    KB3035583 - Update installs Get Windows 10 app in Windows 8.1 and Windows 7 SP1
    KB3044374 - An update that lets you upgrade from Windows 8.1 to Windows 10
    KB3068708 - Update for customer experience and diagnostic telemetry
    KB3075249 - Update that adds telemetry points to consent.exe in Windows 8.1 and Windows 7
    KB3080149 - Update for customer experience and diagnostic telemetry
    KB3123862 - Updated capabilities to upgrade Windows 8.1 and Windows 7
Obviously, one of them has messed up the job.
Interestingly, I removed the same updates from my other computer:
windows 7 ultimate 32 bit
There I have no problem with electron cash
The question is now how do I know exactly which update I need to re-install?
Thanks in advance for the help

**Comment by cculianu** [comment]
Jeez.. I  have no way of guessing what did it.  Is there a way you can reinstall them 1 by 1?  

The error you get is bizarre -- it may not have anything to do with the updates.  Did you install Electron Cash as a different user?  It looks like a permissions error and may not be related to your update thinning.

Maybe you can see about reassigning permissions to the files in the Electron Cash directory?

Also as a "test" -- try the Electron Cash "standalone EXE" available here: https://electroncash.org/downloads/4.0.1/win-linux/Electron-Cash-4.0.1.exe

If the above EXE runs fine -- then likely your install just has the wrong permissions, and you should just reinstall.

Let me know.

**Comment by nikostudent** [comment]
Hello,
I have only one user in windows
Before the update was uninstalled, the program worked, I really had to disable the zone alarm first, but then it left.
I just tried starting on my own .EXE file, using the file on my other computer - the same mistake.
This "Maybe you can see about reassigning permissions to the files in the Electron Cash directory" did not understand how I can do it

**Comment by nikostudent** [comment]
I understand where the problem is (without wanting of course)
It turns out that an Electron cash has malicious soft behaviors.
On the computer I have installed but no Zone ALarm, Emsisoft Anti-Malware Home too.
Obviously, the last program has a residual module loaded into memory, and even if it is not in compassion, it keeps track of ... and blocks the launch of the electron cash.
after running an Emsisoft Anti-Malware Home and then launching Electron cache  a message comes out that will block the program ... and a counter to refuse the blocking. after defining it as a trusted, it is no longer a problem to use a normal electron cache.

**Comment by cculianu** [comment]
Hmm.  Well, the fact that the .EXE didn't work as well means to me something else is funny about your windows install -- and it's not permissions or anything like that.

It could be something stupid like missing a tmp dir or maybe your home folder's temp directory was wiped or has wrong permissions too.

I don't really know what advice to give you.  This probably isn't an Electron-Cash specific issue (I don't think).  We don't really do anything terribly fancy with our software.

You can try Electrum wallet as an experiment (https://www.electrum.org).  That's a Bitcoin (BTC) wallet, but it uses the exact same techniques in python for packaging on windows.  If that runs, but Electron Cash doesn't then perhaps it's related to us.

I do think your windows is mysteriously hosed, though.  Perhaps there is a way to do a repair install?

**Comment by cculianu** [comment]
Oh hey we posted at the same time.

I'm glad you fixed it.  Yes, there is anti-virus software that is overzealous.  Electron Cash is not malware, but lots of anti-virus software sees our "Pyinstaller" packaging and Python and just assumes it's malware without realizing many legitimate apps use Pyinstaller.

Glad you fixed it!

**Comment by nikostudent** [comment]
Once again, I want to thank the github society. There are always responsive people, though sometimes you have to deal with quite ignorant questions.
Indeed, I had to check the anti-virus software first
