### ISSUE TITLE
UI Feedback: In dark mode disabled menu entries are too dark

### ISSUE THREAD

**Issue by EchterAgo** [Electron-Cash/Electron-Cash#1306]
![image](https://user-images.githubusercontent.com/922233/56468956-76d64200-645d-11e9-9698-34492521b9fb.png)

**Comment by cculianu** [comment]
Jesus that's bad.. heh I noticed that too for other things.

Will have to look into how to fix -- I think that comes from QDarkStyle.. but perhaps that's tunable with stylesheets somehow...

**Comment by cculianu** [comment]
How would we override the color for that? Is there some app-global style we can apply after QDarkStyle loads?  My Qt stylesheet knowledge is about as much as you've seen me exhibit in here with you -- I get the sense you may know a little more about that.

If not I can research it too -- will be an opportunity to learn more about stylesheets in Qt..

**Comment by EchterAgo** [comment]
Yes, remember how I combined the stylesheets for the console? We can do that with qdarkstyle. qdarkstyle loads its stylesheet into QApplication, so we can patch it. I found out about this when making my keyboard focus help work with dark style

https://pastebin.com/ZQP3Aba6

**Comment by EchterAgo** [comment]
Oh, forgot, I'll check what the actual style is we need to modify.

**Comment by cculianu** [comment]
> so we can patch it.

Right.. I just have no idea what key(s) it would be..  But I can just open up qdarkstyle and see.. ha ha.

Awesome man.  This is great.  Maybe with a little polish QDarkStyle will be kickass (right now it has a little rough inconsistencies..).

Also it sets various QPalette things to bizarre values on some platforms... maybe if I, or you, or we spend the time to dissect QDarkStyle we can override some of its style stuff with saner values for corner cases where it is deficient.  Great!

**Comment by EchterAgo** [comment]
It is probably one of these:

https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qmenu

Here is what qdarkstyle has at the moment:

https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/master/qdarkstyle/style.qss#L322

**Comment by EchterAgo** [comment]
I think `QMenu::item:disabled` is the selector you're looking for.

**Comment by EchterAgo** [comment]
And indeed, `qdarkstyle` does not set it.

**Comment by cculianu** [comment]
Ah so -- they forgot to set it and the default is the normal one -- which is why it looks terrible. Ha! Makes sense.

There is also other weirdness I want to fix -- namely for Mojave "dark" mode (my commits last night attempted to put a bandaid around it).

This is great..

**Comment by cculianu** [comment]
FWIW I think QDarkStyle has a weirdness on Mojave running in "DARK" mode (OS-level dark mode) --  `QPalette.Disabled, QPalette.Text` always returned a 100% black color which looked terrible.  Not sure if it's because they neglected to set a key in the QDarkStyle or if some other weirdness causes that.

Interestingly it looks ok on non-os-level-dark-mode (Mojave light style) or on non-Mojave (Windows, Linux, High Sierra)... maybe they just never set the key and the default from light style happened to fit... IDK.

**Comment by EchterAgo** [comment]
I have a WIP fix for the disabled item issue here:

https://github.com/EchterAgo/Electron-Cash/tree/dark_theme_disabled_fix

So far I only tested it on Windows though.

**Comment by cculianu** [comment]
I think this should pretty much fix it.  It already looks better on macOS.  Trying Mojave too now... and I'll try Linux as well and write back here.

**Comment by cculianu** [comment]
Linux (macOS looks similar) -- notice the disabled 'Save' button is barely visible or too faded:

<img width="933" alt="Screen Shot 2019-04-24 at 1 25 39 PM" src="https://user-images.githubusercontent.com/266627/56652686-9f944c80-6694-11e9-9c8d-28197facfa09.png">


Your branch:

<img width="913" alt="Screen Shot 2019-04-24 at 1 25 01 PM" src="https://user-images.githubusercontent.com/266627/56652661-8f7c6d00-6694-11e9-8717-a0c114768481.png">

**Comment by cculianu** [comment]
You should just submit a PR.  Looks good to me.

**Comment by EchterAgo** [comment]
Yea, i noticed the button too, wanted to look into that before I make a PR.

**Comment by EchterAgo** [comment]
Ah, QPushButton:disabled uses the same low color, #454545, I think this is an easy fix.

**Comment by EchterAgo** [comment]
Those are the only 2 styles using that color.

**Comment by EchterAgo** [comment]
![image](https://user-images.githubusercontent.com/922233/56653177-5275a200-66b7-11e9-9b9b-c660dde4dab8.png)
