### ISSUE TITLE
UI Feedback: Tab bar overflow makes navigation buttons unusable

### ISSUE THREAD

**Issue by EchterAgo** [Electron-Cash/Electron-Cash#1313]
![image](https://user-images.githubusercontent.com/922233/56489071-b0b15200-650a-11e9-84a2-c98f1c3fa630.png)

![image](https://user-images.githubusercontent.com/922233/56489082-bd35aa80-650a-11e9-8d4d-5a19011490bb.png)

when the window layout is too small to fit all the tabs the tab bars navigation buttons can't be operated.

**Comment by EchterAgo** [comment]
This seems to only be an issue with the dark style.

**Comment by EchterAgo** [comment]
`requirements.txt` says `qdarkstyle<2.6` but I've upgraded to 2.6.5 anyway and the problem persists, so I'll raise an issue in their repo.

**Comment by EchterAgo** [comment]
See https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/136

**Comment by cculianu** [comment]
Yeah -- thanks for opening it up with them.  Who knows maybe they will publish a fix.

I'm not sure why we are on <2.6  Electrum seemed to have an issue with >= 2.6 on some platforms (I honestly forgot what the issue was) -- so I just adopted their wisdom.

**Comment by EchterAgo** [comment]
Looks like they fixed it:

https://github.com/ColinDuquesnoy/QDarkStyleSheet/commit/29bb0619e3b6970df704e7bb46016d6c1a013da4

I'll test their changes.

**Comment by EchterAgo** [comment]
NVM, that was for a different bug.

**Comment by cculianu** [comment]
LOL :)

**Comment by dpizetta** [comment]
May your requirement for 2.6< is not needed anymore. Also, I required some more info about this actual bug :) Tks
