### ISSUE TITLE
UI Feedback: Console does not handle DPI switching

### ISSUE THREAD

**Issue by EchterAgo** [Electron-Cash/Electron-Cash#1314]
Tested on Windows with 2 monitors, one 4K High DPI with 125% display scaling, the other 1080p with 100% display scaling. Console starts out on the 4K monitor, font is a normal size. Then I proceed to drag the window to the 1080p screen, nothing in the window changes until the mouse pointer crosses the boundary between the screens, then suddenly the font switches to a much smaller font that is hard to read. When dragging the window back to the 4K screen, the font does not change back. Qt is DPI aware, but this seems to be a bug in Qt. I also tested this on the latest PyQt5 version and the way the app scales is a bit different, but the console issue is the same.

I tested a few more parts of the UI for DPI awareness issues, but haven't found any. Can someone test this on Linux or macOS?

**Comment by EchterAgo** [comment]
This also might be caused by my display configuration. My 4k display is on an nVidia card and my 1080p is on Intel.

**Comment by cculianu** [comment]
Hmm.. I have 2 monitors here on macOS (well, a TV that takes HDMI and a regular laptop screen). I'll try it later and see.

So the regular console tab looks messed up (after dismissing the warning), you say?  Ok. Will see what it does here.

**Comment by EchterAgo** [comment]
Here is a video capture. The first change in the window is when switching from high DPI to normal screen. You can see everything just gets smaller. The second change is switching from normal to high DPI screen. Everything gets large again but the console font stays small. I also noticed the window actually gets larger than before.

![dpi_switch](https://user-images.githubusercontent.com/922233/56629779-d9575a00-6678-11e9-9837-2fa534673a9d.gif)

**Comment by EchterAgo** [comment]
I searched the Qt bug tracker but haven't found any bug that seems related. I tried some combinations of `Qt.AA_EnableHighDpiScaling` / `QT_AUTO_SCREEN_SCALE_FACTOR` but the behaviour didn't change. What I did notice is that when I leave the font at default, when i move the window from high DPI and back, the result is pixel perfect. This makes me believe we lose the default font for the document. If you look closely at the capture above, the font is not even mono space anymore (look at the `t`). I'm now trying to figure out how I can detect DPI changes, but so far I've found no good method.

BTW, I think we should change the default mono space font on Windows from Lucida Console to Consolas. Consolas has much better ClearType hinting.

**Comment by EchterAgo** [comment]
It definitely loses the font. When I read the `defaultFont` after DPI switch, it is a different object than what was passed to `setDefaultFont`. Setting the font object again restores the proper font.

**Comment by EchterAgo** [comment]
I figured it out after reading the relevant Qt source files. The documents `setDefaultFont` is called during initialization and when there is `QEvent::ApplicationFontChange` or `QEvent::FontChange`. When those events occur, it just sets `setDefaultFont(font())`. There is a `font` property of the editor that we have not been setting. After setting this per monitor DPI awareness works great!

**Comment by cculianu** [comment]
Hardcore.  Much respect for going to the Qt sources. 💯
