### ISSUE TITLE
Ensure Tor doesn't compromise IP upon disconnection.

### ISSUE THREAD

**Issue by markblundeberg** [Electron-Cash/Electron-Cash#1324]
A hint from Francis here:

https://twitter.com/francispouliot_/status/1122550675286654976

![Screenshot from 2019-04-28 11-07-41](https://user-images.githubusercontent.com/36528214/56868335-df657780-69a5-11e9-9de9-fd326391f2d1.png)

Not sure what's the best way to test this but it seems important to test.

**Comment by cculianu** [comment]
Huh?  Do you have any reading material about this?  How does the IP get compromised?

**Comment by imaginaryusername** [comment]
If you specified port 9050 and there's nothing else on that port, wouldn't the wallet already fail when Tor no longer works? I don't think it falls back...

**Comment by markblundeberg** [comment]
I don't have anything specific... it could be fixed by now, for all I know. :)

**Comment by markblundeberg** [comment]
closing for now
