### ISSUE TITLE
'Preferred' Servers having unnecessarily high fee limits

### ISSUE THREAD

**Issue by OverlordQ** [Electron-Cash/Electron-Cash#1325]
I notice half the time when letting Electron pick a server for me I get connected to one that gives me this error:

`The transaction was rejected due to paying insufficient fees and/or for being of extremely low priority.`

I then have to go back into the network settings and manually pick a new server and resend the transaction.

**Comment by cculianu** [comment]
Which server was this?  Let us know and we'll remove it from the defaults.

**Comment by OverlordQ** [comment]
I last noticed it on the coinucopia.io server, I'm not sure if that one was it the other times, I'll have to keep track

**Comment by cculianu** [comment]
I can try them 1 by 1, sending money to myself.

Coinucopia said they fixed it but if not, they’re going away from servers.json.

I’ll try them all today and take out any offenders I find.

Thanks for the info.

Will write back later if I find anything.

**Comment by cculianu** [comment]
hmm well I tried sending 1 1.0 sats/B tx on coinucopia.io, and it failed.

Then I redid the tx a little differently later, to double-check my sanity, also exactly 1.0 sats/B, and it succeeded.

Considering we've had various complaints from coinucopia.io -- and that it failed for me just now (I think I was using "new" coins that didn't have sufficient coinage but were confirmed) -- I am doing to remove them from servers.json.

**Comment by cculianu** [comment]
Yep. Seems they have amount & age filters.  See screenshot.

Ok, they are gone from `servers.json`.

<img width="757" alt="Screen Shot 2019-05-02 at 4 16 05 PM" src="https://user-images.githubusercontent.com/266627/57077829-a7d43380-6cf5-11e9-9679-1878639fc8f9.png">

**Comment by cculianu** [comment]
So Coinucopia wrote back to me and apparently they addressed the issue. I guess the quick banhammer is an effective motivator.

Here is their email to me:

<img width="974" alt="Screen Shot 2019-05-02 at 5 30 06 PM" src="https://user-images.githubusercontent.com/266627/57082749-0acac800-6d00-11e9-8f5a-d880b32f4bb6.png">


I added them back to servers.json.

Do let me know if you see this issue again!!
