### ISSUE TITLE
Client refuse to connect to servers with self-signed certificates

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#1327]
Message: `SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1056)`, but problem is "fixed" after clearing ~/.electron-cash/certs.

**Comment by cculianu** [comment]
Thanks for reporting.  The value in caching the certs is.. minimal. And if it's buggy, it's actually a liability.

I may turn off the caching altogether after first investigating its performance/network cost.  Or I may make the cached files expire after a day.  

I doubt it's very expensive to download a cert -- so the cache is dumb.  :P

**Comment by SomberNight** [comment]
It's not a cache, it's certificate pinning.

**Comment by quangld** [comment]
Yup, I wasted 5 hours trying to figure it out why I couldn't connect my own server under SSL :) I think this could be the reason why when I turn on SSL-only on my server. I received less connections and getting a lot of dis-connections to my ElectrumX server (I just switched to ElectrsCash).
I use LetsEncrypt, so I have to renew my cert every 80 days.
I hope this get fixed soon!

**Comment by cculianu** [comment]
Yeah this certificate pinning thing ignores a large part of the design of SSL certs. Why was it done this way @SomberNight ? How does a server operator go about invalidating a cert if they got a new one now without having clients reject them for eternity?

What is the rationale behind this design???

**Comment by cculianu** [comment]
@quangld Any chance you can re-use your old self-signed cert from your old ElectrumX days until I find out why this design exists and/or if I can nuke it?

**Comment by SomberNight** [comment]
This is how it works in Electrum atm:
https://github.com/spesmilo/electrum-docs/blob/master/faq.rst#i-might-run-my-own-server-are-client-server-connections-authenticated

> What is the rationale behind this design???

Self-signed certs, combined with cert pinning,  provide authentication. Connections cannot be man-in-the-middled, and the client can be certain that they connect to the server they expected (e.g. their own server!).
If you don't want authentication guarantees, feel free to remove the pinning.

**Comment by cculianu** [comment]
Right, I get that -- it's obvious --  but what happens if an admin wants to switch certs?

**Comment by cculianu** [comment]
Oh I see. If you're using self-signed you better stick to self-signed until they expire.  Meh. :/

**Comment by quangld** [comment]
@cculianu If I switched back to the old cert, users who currently connected won't be able to connect.
If you use putty, filezilla, or even ssh command line, when the certificates aren't matched (compared with the one has been saved locally), the software will ask you if you want to replace. I wonder if we can do the same here.

**Comment by cculianu** [comment]
Yeah I think the fix would be that all EC clients should, if they see a CA signed cert, assume it's valid (CA signed certs are impossible to forge), and then clear the pinned self-signed cert in that case.

>  I wonder if we can do the same here.

That might be a viable option.  This problem has happened time and again and it bites admins each time.  You aren't the first.. and you won't be the last.  I'll think about a solution but I definitely will also see about having the signed-certs "trump" any pinned self-signed certs.

**Comment by cculianu** [comment]
This has now been fixed in #1918
