### ISSUE TITLE
change new wallet creation to not require immediately backing up seed

### ISSUE THREAD

**Issue by markblundeberg** [Electron-Cash/Electron-Cash#1329]
Feedback from Roger Ver:

>Electron cash should also stop forcing people to back up their seed before they have any funds in the wallet at all.

How bitcoin.com wallet does it: user can make a new wallet and hit the ground running, only it has a nag box that encourages user to perform backup process.

**Comment by markblundeberg** [comment]
How it could be done (sketch):

* On new wallet creation show seed but allow a 'skip backup' option.
* If users skips then set 'backupnag=1' in the wallet file.
* As long as backupnag=1, show a nag box.
* Once user decides to backup, the process works as usual (show seed, ask user to re-enter). Upon success, remove backupnag from wallet file.

**Comment by cculianu** [comment]
Ok, sounds good.  So if backupnag=1, prompt on wallet window open each time?

**Comment by markblundeberg** [comment]
for reference, the bitcoin.com wallet nag is quite unobtrusive
![image](https://user-images.githubusercontent.com/36528214/57341723-6c1fdc00-70f0-11e9-834d-8f42a64079d3.png)

This is the initial wallet creation ask about backing up
![image](https://user-images.githubusercontent.com/36528214/57341787-95d90300-70f0-11e9-8fe0-18a0857d43cc.png)

**Comment by cculianu** [comment]
Wow.. really nice resource. Thanks for providing these screenshots.  

I can get started on this right now or today.  This is good.  We can do similar.

**Comment by cculianu** [comment]
We did this for SLP.  Jonald hates it -- so I'm closing this.
