### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1330]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at com.chaquo.python.utils.ConsoleActivity.restoreScroll(ConsoleActivity.java:198)
	at com.chaquo.python.utils.ConsoleActivity.onGlobalLayout(ConsoleActivity.java:152)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:945)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2254)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1396)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6773)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
	at android.view.Choreographer.doCallbacks(Choreographer.java:778)
	at android.view.Choreographer.doFrame(Choreographer.java:713)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
```

Reporter
------------

This issue was reported by 31 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.1.0 on Q-Innovations QS5509A (QS5509QL) | unknown | en_US | 

Additional Information
------------------------

> receiving and paying

---

**Comment by mhsmith** [comment]
Chaquopy internal issue 5443.

**Comment by cculianu** [comment]
Ah, ok. Closing.

**Comment by mhsmith** [comment]
That was just a note to myself: it does still need fixing. Reopen please.
