### ISSUE TITLE
BIP38 Sweep: wrapped C/C++ object of type QComboBox has been deleted

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#1338]
As title said, when sweeping BIP38 with a key that has balance on it, final step yields `wrapped C/C++ object of type QComboBox has been deleted` without actually sweeping. The decoding is correct so private key can be copied and re-pasted to sweep, but the error persists if you attempt to sweep straight from BIP38.

**Comment by cculianu** [comment]
Eeek! Will fix.

**Comment by cculianu** [comment]
Ok, tested and fixed in latest commit.  It was a total oops on my part.  Should be 100% fixed now.
