### ISSUE TITLE
Electron-Cash (4.0.2) Error on stopping daemon

### ISSUE THREAD

**Issue by malik9353** [Electron-Cash/Electron-Cash#1349]
After Stopping daemon it gives error and then it keep on giving error on every command
Please Help !!!
`root@ip-172-31-19-44:/media/electron/electron-cash# electron-cash --testnet daemon stop

Daemon stopped
root@ip-172-31-19-44:/media/electron/electron-cash# Traceback (most recent call last):
  File "/usr/lib/python3.6/weakref.py", line 624, in _exitfunc
    f()
  File "/usr/lib/python3.6/weakref.py", line 548, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/usr/local/lib/python3.6/dist-packages/Electron_Cash-4.0.2-py3.6.egg/electroncash/caches.py", line 120, in on_cache_gc
    assert slf.thread.is_alive()
AssertionError`

**Comment by cculianu** [comment]
You are right.  I fixed this in a commit just now. Thanks so much for reporting this!

**Comment by malik9353** [comment]
Do i need to install it again ? (4.0.2 v)

**Comment by cculianu** [comment]
No. :) Either can run "from source" off of github here (if you don't know how to do that, don't worry).  Tomorrow we released 4.0.3 - so you can also wait until tomorrow.
