### ISSUE TITLE
Signing the transaction is asking for password again ans again wallet is loaded (4.0.2)

### ISSUE THREAD

**Issue by malik9353** [Electron-Cash/Electron-Cash#1359]
I am developing a code in nodeJS using electron-cash cli to work transactions here is what i did :-
1:- After payto an address like this :- 
electron-cash --testnet payto ${address} ${value} --unsigned > unsigned.txn
2:- I signed the transaction like this 👎 
cat unsigned.txn | electron-cash --testnet signtransaction - > signed.txn

**After this command it ask for the password can help me that how should i place the password in my command so it does not ask for it ?**

Thanks Regards.

![Password](https://user-images.githubusercontent.com/34607108/57829075-3ef5bc80-77c7-11e9-8611-b9022d15b66c.JPG)

**Comment by cculianu** [comment]
Try the command-line option `-wp` or `--walletpassword` as so:

```
electron-cash --testnet payto ${address} ${value} --unsigned --walletpassword ${walletpass} > unsigned.txn
```

Let me know if the above does not fix it for you, and I will re-open this issue.
