### ISSUE TITLE
Install error: does not seem to find python3-pyqt5 installed via apt

### ISSUE THREAD

**Issue by DavidTangye** [Electron-Cash/Electron-Cash#1361]
On my ODroid xu4, running ubuntu 18.04.2 LTS, as a normal user with sudo privilege, I downloaded the 4.0.2 tarball, and ran 'python3 setup.py install |tee ../install_Electron-Cash-4.0.2.log' (twice actually, since I had to chgrp sudo /usr/local/bin to get the script file installed). 

It seems that setup.py cannot find qt5, even though synaptic shows it is installed (package python3-pyqt5 version 5.10.1+dsfg-1ubuntu2)

The install log ends as follows (The issue is shown in the last 2 lines.) ...

```
Electron-Cash 4.0.2 is already the active version in easy-install.pth
Installing electron-cash script to /usr/local/bin

Installed /usr/local/lib/python3.6/dist-packages/Electron_Cash-4.0.2-py3.6.egg
Processing dependencies for Electron-Cash==4.0.2
Searching for pyqt5
Reading https://pypi.org/simple/pyqt5/
No local packages or working download links found for pyqt5
error: Could not find suitable distribution for Requirement.parse('pyqt5')
```

**Comment by DavidTangye** [comment]
Additional info: setup.py has installed files into /usr/local/lib/python3.6/dist-packages/Electron_Cash-4.0.2-py3.6.egg, and has installed a .desktop file somewhere so I do have a menu item for it. However running the menu item results in no window, presumably since it cannot find the link to qt5.

**Comment by cculianu** [comment]
We do require PyQt5 5.11.

Why not try the .AppImage release available here: https://github.com/Electron-Cash/Electron-Cash/releases .

It should work much better.

Also, if you MUST run from source, try doing the following:

```
python3 -m pip install -r contrib/requirements/reqirements.txt --user
python3 -m pip install -r contrib/requirements/reqirements-hw.txt --user
python3 -m pip install -r contrib/requirements/reqirements-binaries.txt --user
```

**Comment by cculianu** [comment]
Haven't heard from user in a while. Closing.
