### ISSUE TITLE
Reproducible UI lag on a normal wallet (~800 tx)

### ISSUE THREAD

**Issue by emergent-reasons** [Electron-Cash/Electron-Cash#1369]
Every once in a while when I use EC (I use several versions so it's hard to say which one), I get hit with heavy lag - most things I do result in a big lag spike where the UI becomes unresponsive. E.g. click to open a wallet. Click on a tab. Click to close the wallet. I have also heard similar stories occasionally from other users.

At least for now I can reproduce it reliably:

- [4.0.3 dev release 6](https://github.com/Electron-Cash/Electron-Cash/releases)
  - 1cde1e9 - run from source and I get fat lag bombs. e.g. 10 seconds to open wallet window after entering password
  - [AppImage](https://github.com/Electron-Cash/Electron-Cash/releases/download/4.0.3-dev6/Electron-Cash-4.0.3-dev6-x86_64.AppImage) with confirmed checksum does not have any of the lag

That suggests some dependency or interaction with a dependency is causing the problem but I don't have the knowledge to investigate more deeply at this time. If anyone has specific things for me to check, I can definitely do it.

@EchterAgo had some recommendations for investigation with strace, pdb, etc. but I wasn't able to isolate the activity around the lagging behavior yet. Again, any specific recommendations and I can try it. The only thing I did see clearly was a huge stack of these `futex` calls when opening a wallet. The same action on the AppImage had only a handful of the same calls.

```
futex(0x559f1eba59c8, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x559f1eba59c0, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x559f1eba59c8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x559f1eba59c4, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1558320186, tv_nsec=382680000}, 0xffffffff) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x559f1eba59c8, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x559f1eba59c0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x559f1eba59c8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x559f1eba59c4, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1558320186, tv_nsec=409192000}, 0xffffffff) = 0
futex(0x559f1eba59c8, FUTEX_WAKE_PRIVATE, 1) = 0
```

**Comment by emergent-reasons** [comment]
Here is a log where I tried to isolate the lag when unlocking a wallet. Unfortunately, there are no log entries during the lag. However it does isolate the lag at least between the two entries.

```
| 11.482| |00| [UpdateChecker] Downloading progress 100% from https://raw.githubusercontent.com/Electron-Cash/Electron-Cash/master/contrib/update_checker/releases.json
| 11.484| |00| [UpdateChecker] Active _Req@12752 finished
| 11.883| |05| [electroncash.dk] request_initial_proof_and_headers pending
| 12.718| |05| [electroncash.dk] server was verified correctly
| 12.718| |05| [electroncash.dk] set_mode(default)
| 12.734| |05| [electroncash.dk] connected chunk, height=560498 count=147 proof_was_provided=True
| 54.249| |00| [WalletStorage] wallet path (( switched to some other wallet in the GUI to get this log ))
| 64.334| |00| [WalletStorage] wallet path (( switched back and immediately click open ))

<< lag is here

| 75.177| |00| [profiler] Abstract_Wallet.load_transactions 0.0485
| 75.178| |00| [profiler] Abstract_Wallet.build_reverse_history 0.0008
| 75.207| |00| [profiler] Abstract_Wallet.check_history 0.0291
| 75.256| |00| [Network] Job added <electroncash.verifier.SPV object at 0x7f2149a95048>
| 75.256| |00| [Network] Job added <electroncash.synchronizer.Synchronizer object at 0x7f2149a93fd0>
| 75.392| |00| [shuffle] Window 'electron-shuffle' registered, performing window-specific startup code
| 75.393| |00| [shuffle] Patched wallet
| 75.394| |00| [shuffle] Patched utxo_list
| 75.398| |00| [shuffle] Patched window
```

**Comment by cculianu** [comment]
Hmm.  How much memory do you have and are you on an HDD?  Could it be just plain old Linux swapping out the pages from RAM and them taking a long time to make it back to RAM?  Python programs and Electron Cash do use up a good bit of RAM so sometimes they do make heavy use of swap on older systems.  Electron Cash alone with 1 wallet is 100+ MB or RAM.

If you have SSD and/or a newish system with plenty of RAM that isn't running out of memory that shouldn't be happening though.  Just double-checking here.

Nothing in the logs is particularly worrying or unusual or.. even indicative of where to begin looking.

The "futex" calls are just normal calls that happen -- the Python interpreter itself has all sorts of locking it is doing -- and also program level threading.Lock locks probably make it down as futex to the kernel.

So none of that stuff indicates anything unusual or a deadlock situation as far as I can tell.

This also never happens to me on macOS -- so it's not indicative of a high-level programming error but rather some lower-level interaction.

So -- yes.  What are the system specs of the system you observed this behavior on?

**Comment by cculianu** [comment]
Also -- follow-up: does this happen even *as* you use the app?  Like you are just minding your business using EC and then it randomly lags?  Or is it more or only if you had left the app "inactive" for a period of time and then switched back to it?

**Comment by cculianu** [comment]
> 1cde1e9 - run from source and I get fat lag bombs. e.g. 10 seconds to open wallet window after entering password

This could be unrelated and/or something else: "pycryptodomex" is really needed for native crypto otherwise lag-after-enter-password is to be expected.  Make sure you installed this requirement.  Install all the requirements:

```
python3 -m pip install -r contrib/requirements/requirements.txt --user
python3 -m pip install -r contrib/requirements/requirements-binaries.txt --user
python3 -m pip install -r contrib/requirements/requirements-hw.txt --user
```

**Comment by emergent-reasons** [comment]
> How much memory do you have and are you on an HDD?

16GB with an NVMe SSD. Shouldn't be an issue.

> The "futex" calls are just normal calls that happen

Yes. I confirmed that they happen in both cases. However there are pages and pages of them during the 10s lag when I run from source. I'm sure there is more interesting information in there too but I didn't immediately find a way to start the log just before clicking to unlock the wallet.

Since I have it reproducible (lag on running from source; no lag running from appimage), I mentioned I think it is possibly due to dependencies. Any leads to investigate there? E.g. any way you can give me a pip freeze on the full app image packages? I can compare to my own.

**Comment by emergent-reasons** [comment]
> This could be unrelated and/or something else

I agree but at least the base should all be the same since I am running from the same commit the appimage is built from, right?

**Comment by cculianu** [comment]
> 16GB with an NVMe SSD. Shouldn't be an issue.

Indeed.  Your hardware is kickass.  It's definitely not.

> Yes. I confirmed that they happen in both cases. However there are pages and pages of them during the 10s lag when I run from source. 
...
> I agree but at least the base should all be the same since I am running from the same commit the appimage is built from, right?

Running from source has the "gotchas" in that you are depending on system python libs (either in your ~/ user dir or in your system-wide /usr/ dir).

AppImage has exactly all the dependencies installed -- with the correct versions.

Running from source may not.  In particular `pycryptodomex` is the one that is needed to open wallet files quickly and decrypt them using native calls.  If that is lacking or the wrong version, the fallback is python-only ecdsa for decrypting wallet files which is ridiculously slow.

Also the PyQt libs earlier than 5.11 had lots of memory leak bugs.  5.11+ is recommended.

I suggest installing the requirements by issuing the commands above, using  --user to get them into your user dir (so they override and/or otherwise don't interfere with system).  

Let me know if that helps in the "run from source" case.

**Comment by emergent-reasons** [comment]
I just tried installing with what I have already.

`requirements.txt`:

```
Requirement already satisfied: .....
Installing collected packages: qdarkstyle
  Found existing installation: QDarkStyle 2.6.5
    Uninstalling QDarkStyle-2.6.5:
      Successfully uninstalled QDarkStyle-2.6.5
Successfully installed qdarkstyle-2.6.8
```
`requirements-binaries.txt`:

More interesting. Apparently I had a lot of stuff out of date.

```
Requirement already satisfied: ...
Installing collected packages: PyQt5-sip, PyQt5, pycryptodomex, sip, psutil
  Found existing installation: PyQt5-sip 4.19.15
    Uninstalling PyQt5-sip-4.19.15:
      Successfully uninstalled PyQt5-sip-4.19.15
  Found existing installation: PyQt5 5.12.1
    Uninstalling PyQt5-5.12.1:
      Successfully uninstalled PyQt5-5.12.1
  Found existing installation: pycryptodomex 3.8.1
    Uninstalling pycryptodomex-3.8.1:
      Successfully uninstalled pycryptodomex-3.8.1
Successfully installed PyQt5-5.11.3 PyQt5-sip-4.19.13 psutil-5.6.1 pycryptodomex-3.6.6 sip-4.19.8
```

`requirements-hw.txt`:
```
Requirement already satisfied: ...
Installing collected packages: keepkey
  Found existing installation: keepkey 4.0.2
    Uninstalling keepkey-4.0.2:
      Successfully uninstalled keepkey-4.0.2
Successfully installed keepkey-6.1.0
```

**Comment by cculianu** [comment]
Hmm.  Nothing is particularly bad about what you had -- you did have kind-of-new/untested versions of some things, out-of-date of others.

Nothing especially bad.  It's possible pycryptodomex's api has changed in 3.8.. not sure.  Now you're back on 3.6 which hopefully will be saner.

Curious if that solved at least the "easily reproducible" one in running from source.

**Comment by emergent-reasons** [comment]
Yep. After upgrading everything, the lag is gone.

So we agree it is probably dependencies. When users appear with major lag, we can point them here at least.

**Comment by emergent-reasons** [comment]
I was hoping it might be a bigger issue that would help with Windows or Mac users complain about lag. Maybe it's only us source people having problems.

**Comment by cculianu** [comment]
Yes. Also you said you did experience it in AppImage -- just under different circumstances and harder to reproduce.  I do believe you there may be lag issue unrelated to dependencies but instead something else.

How hard is it to reproduce AppImage?  Is it like once in a blue moon?  Totally random? Any information is useful here.

**Comment by emergent-reasons** [comment]
No the opposite. It was interesting because I could reproduce lag on source and no-lag on the appimage even at the same commit.

**Comment by cculianu** [comment]
Yes well same commit isn't the whole story.  Commit depends on packages and stuff like that. :)

Ok so as far as you can tell AppImage is at least much rarer or never at all?

**Comment by cculianu** [comment]
OK, well.. I'm closing it for now but this issue being here will help others too as they google search, etc, hopefully -- and is a good place to send them.

I do appreciate your thorought investigation @emergent-reasons  -- believe it or not those logs were helpful in that they ruled out some possibilities!

**Comment by emergent-reasons** [comment]
I can't remember the AppImage ever lagging. I consider this issue resolved and mostly wanted it to be documented for future laggers like me.
