### ISSUE TITLE
Can't follow steps on trezor.io to split BCH/BSV

### ISSUE THREAD

**Issue by achillez** [Electron-Cash/Electron-Cash#1372]
trezor.io outlines the steps quite clearly here: 
https://wiki.trezor.io/How_to_split_and_send_your_Bitcoin_Cash_forks

However, when trying to use electroncash it rejects the BSV servers. Seems they are part of the banlist or some other problem. Is there a way to override this for this purpose?

**Comment by cculianu** [comment]
Their instructions are a bit old.  At the time of the fork we supported both BCH and BSV.  Right now, Electron Cash only supports BCH.

You are better off obtaining [ElectrumSV](https://electrumsv.io) to do the split -- but be careful as their split tool only allows you to do 1 split tx per day so make sure it grabs your whole balance to do it.

**Comment by cculianu** [comment]
Alternatively -- try finding a "historical copy" of Electron Cash. 3.3.2 was the last version that could use BSV.  The instructions on trezor.io are from that era.
