### ISSUE TITLE
Op_Return option for mobile wallet

### ISSUE THREAD

**Issue by Leandrodimarco** [Electron-Cash/Electron-Cash#1378]
Add Op_Return option for mobile wallet.

**Comment by cculianu** [comment]
Ok, I'll add it to the list of to-do's for iOS.  I don't have the capability to update the android wallet. So just iOS it will be.

**Comment by LightningLoya** [comment]
I can try to tackle this problem. I already made some progress. Is it ok @cculianu ?

<img width="366" alt="Captura de Pantalla 2021-06-22 a la(s) 23 01 38" src="https://user-images.githubusercontent.com/45250003/123033945-3ad8f780-d3ae-11eb-9a74-57541de29ce2.png">

**Comment by cculianu** [comment]
I’m very impressed that you managed to add that. The iOS app is Byzantine, to say the least.

**Comment by LightningLoya** [comment]
Editing the XIB manually felt like doing reverse engineering 😂

Alright I'll try to do a PR for this feature if you don't mind.

My motivation is to have a mobile client (not just the desktop app) that works for http://bchpages.com/

**Comment by libreloya** [comment]
Alright. 

I managed to successfully send a op_return output using the mobile app. I'll open a Pull Request tomorrow to continue working on this feature.

https://bchblockexplorer.com/tx/c1ea9d4ad160dbb7bf6ef3b9a45ee0d1e94d68ecddb04ecd282ac65277923c7c

<img width="308" alt="Captura de Pantalla 2021-07-03 a la(s) 3 16 14" src="https://user-images.githubusercontent.com/45250003/124348022-42b64a00-dbad-11eb-9eaa-fa0152370e92.png">
<img width="312" alt="Captura de Pantalla 2021-07-03 a la(s) 3 16 27" src="https://user-images.githubusercontent.com/45250003/124348026-48139480-dbad-11eb-9349-b5ca35c0a5c7.png">

**Comment by libreloya** [comment]
@cculianu I already opened the PR [#2307] as promised 
I'm excited to contribute. I'll wait for further instructions.

**Comment by cculianu** [comment]
@libreloya Good work. I will review it very soon. Looks good on first read-through though. I am very impressed that you managed to get it to build, etc (it sometimes takes some fennagling).  The approach looks sound.

**Comment by cculianu** [comment]
Ok, this has been done for iOS in #2307.  Anybody that uses Android know if Android still lacks this .. or if it has it (in which case I may close this).  @mhsmith @fyookball ?

**Comment by mhsmith** [comment]
It hasn't been done for Android, so I've created a separate issue #2309 to avoid confusion.
