### ISSUE TITLE
feature request: transaction details view: inputs list could show amount?

### ISSUE THREAD

**Issue by molecular** [Electron-Cash/Electron-Cash#1384]
in transaction detail view (open by right-clicking a transaction and selecting "details" from popup menu), there's a list of inputs and outputs. The output list has an amount column.

Is there a reason why the inputs list lacks an amount column?

![image](https://user-images.githubusercontent.com/589745/58373418-5b63c880-7f2e-11e9-8268-0e61e07df54a.png)

If there's no reason, I would love to see an amount column in the inputs list.

**Comment by imaginaryusername** [comment]
This is probably related to the fact that bitcoin transactions do not contain input amounts - so anything that wants input amounts must fetch them from previous tx, which makes it non-trivial.

**Comment by molecular** [comment]
Well, I don't know the intricacies of the implementation, but all the inputs are from within the wallet (already in local utxo list).

I acknowledge it's not trivial. How can I best add a bounty to this?

**Comment by markblundeberg** [comment]
Hey @molecular we are already planning to refactor a lot of the input-handling stuff.

What is going to eventually happen is there will be a button "Get input details" that downloads all parent transactions and obtains the juicy info: addresses (the actual addresses, not inferred), and input amounts. From this you will of course finally be able to see the fee on transactions that were sent to you.

**Comment by molecular** [comment]
great!

**Comment by cculianu** [comment]
Let's leave this open so we have an issue-to-close as a reward for when we get this done.

**Comment by cculianu** [comment]
This has been implemented in latest git also in latest pre-release here: https://github.com/Electron-Cash/Electron-Cash/releases/tag/4.0.6-dev1

**Comment by molecular** [comment]
@cculianu and the others, you guys are amazing!

I looked at the feature and it does exactly what I would expect.

At first I was a bit taken aback becaues I would've expected a button instead of a checkbox for "download input data". I checked to see wether the checkbox state is persisted and it is. Cool solution. I like it.

:confetti_ball:

**Comment by cculianu** [comment]
Yeah the checkbox is a little unconventional but it grows on you.  This way it is an action + a setting.

Mark thought it was bizarre at first too but then he also liked it.

I just wanted the feature to be both very very visible and obvious (since it's useful) and take up as little space as possible, and also be a persistent setting.  Checkbox it was.

I leave it on all the time.  It spreads the load out to a bunch of servers actually (which is why it's so fast even for big tx's).

Glad you like it!
