### ISSUE TITLE
ux confusion using "spend" from coin/address in conjuction with cashuffle

### ISSUE THREAD

**Issue by molecular** [Electron-Cash/Electron-Cash#1385]
with cashuffle enabled, I tried to spend a utxo that was "too small", so I right-clicked the utxo and selected "spend". The spend dialog opens, but hitting the "max" button doesn't fill out the amount. Amount input box remains empty. 

So I was confused.

Why was the amount not filled by using "max" button? because CashShuffle was set to "Spend Shuffled".

What can be done? Maybe when entereing the spend dialog by selecting "spend" on an unshuffled utxo, the setting could automatically switch to "spend unshuffled"?

Maybe a popup (or tooltip on "max" button) could tell me why it's not working or something along those lines?

**Comment by markblundeberg** [comment]
> Maybe when entereing the spend dialog by selecting "spend" on an unshuffled utxo, the setting could automatically switch to "spend unshuffled"?

Yes, I support this -- even allowing users to spend shuffled & unshuffled coins together if they truly want it. A warning is deserved of course, if unshuffled coins are present. :-)

**Comment by molecular** [comment]
Thanks for supporting this idea. There's one caveat though: I'm assuming this setting is persistent across re-entry of the spend dialog and also across restarts? So that's a pitfall where users could later unintentionally send unshuffled coins.

**Comment by cculianu** [comment]
I'm going to implement this now. It always bugged me too that it did that .. and no.. that you mention it.. the solution is so obvious.  Just switch the damned mode to match the coin!

Stay tuned...

**Comment by cculianu** [comment]
Just pushed a commit that implements this in master.

**Comment by cculianu** [comment]
@molecular it's not persistent across re-starts but is persistent across clears/sends during the same session.  It is what it is.  By default the app does warn you whenever you enter "spend unshuffled" mode even with this new change.  I don't see it as a huge problem.  Funds are segregated either way...

**Comment by molecular** [comment]
@cculianu taking that warning into account (didn't know it existed, only recently started using cashuffle), I also think this is a non-issue.

thanks for implementing! wanted to quickly test it, but I don't have unshuffled coins in any of the wallets I have cashuffle enabled on, so I guess I'll test it later.

**Comment by molecular** [comment]
@cculianu got around to testing it. It works as advertised.

I very much like that the popup informing about spending unshuffled coins appears right away and that after choosing "no, don't spend unshuffled" the setting flips right back. Perfect!
