### ISSUE TITLE
BCH Balance Shows Zero

### ISSUE THREAD

**Issue by snobani** [Electron-Cash/Electron-Cash#1402]
Followed the advice from this link https://bitcoinsv.io/coin-splitting-guides-for-bitcoin-sv/, created both wallets ElectronCash and ElectrumSV, tried the split for 1 BCH and it worked fine, then I moved all of My BCH from my Ledger Nano to Electron Cash ( 5 BCH and then 14.99 BCH), the split in ElectrumSV worked fine, but then my Electron Cash is showing my balance Zero and that two sent transactions are shown in the history, I have No clue were My BCH was sent. Can you help retrieve my BCH? where were they sent and how can I reclaim them?. Thanks.

![ElectronCash Screenshot](https://user-images.githubusercontent.com/51159746/58553160-da9e1880-821c-11e9-84db-57b5f14b5d07.JPG)
![My BCH is Gone](https://user-images.githubusercontent.com/51159746/58553161-da9e1880-821c-11e9-8e3b-6ec9d0466137.JPG)
![Screenshot From Blockchain Explorer](https://user-images.githubusercontent.com/51159746/58553162-db36af00-821c-11e9-814b-a3b60db81ed0.JPG)

**Comment by acidsploit** [comment]
Your BCH got sent to the same address you sent your SV.

**Comment by snobani** [comment]
They are not, I sent my SV to my account at Bitfinex and they are there, but my BCH is not there. What can I do to get them?.

**Comment by acidsploit** [comment]
Contact Bitfinex and and tell them your BCH got replayed and is now also on the BSV address you sent your BSV too. They are the only ones that can recover it for you. And never use that BSV split tool again, it is utter shit.

**Comment by imaginaryusername** [comment]
For future reference: When moving coins from a fork, *always* move the more valuable coin first to protect yourself against possible shenanigans from splitting tools.

**Comment by snobani** [comment]
. Thank You. I will contact Bitfinex, can they refuse to recover BCH for me? what options do I have in that case? what are my chances of recovering the coins?

**Comment by imaginaryusername** [comment]
They have a moral duty to recover your coins for you, but unless you take legal action (good luck), they don't _have_ to. Never dealt with them before, they do have a history of shady practices - you're gonna need that luck for sure.

**Comment by EchterAgo** [comment]
Check here for BitFinex policy on cross chain deposits:

https://support.bitfinex.com/hc/en-us/articles/360006262533-Deposit-of-wrong-tokens-or-wrong-addresses

As this exceeds $2500 in value they will likely help you for a fee.

**Comment by cculianu** [comment]
I'm going to go ahead and close this to keep the issue count down.  I feel we've already done a bang up job in helping this user.  Thanks @EchterAgo for your great find that they do indeed have a procedure in place for recuperating large-ish funds.

**Comment by snobani** [comment]
Thank You EchterAgo, you've been a great help, will handle this with Bitfinex. Thank You
