### ISSUE TITLE
BCH - BSV split but moved BCH first!

### ISSUE THREAD

**Issue by Lostalot** [Electron-Cash/Electron-Cash#1403]
Hi, I think I have done this the wrong way, I had some pre fork BCH in my EC wallet, a few weeks ago, I sent the contents of the wallet (thankfully not much) to my Kraken account thinking they would be split into BCH and BSV on arrival. But they only credited my account with BCH.
Is it possible for me to claim the BSV coins that I had not received?
I still have the EC wallet which has the transaction history etc..

Thanks.

**Comment by imaginaryusername** [comment]
Please ask Kraken.

**Comment by Lostalot** [comment]
I did, they didn't want to know!

**Comment by imaginaryusername** [comment]
That is none of Electron-cash maintainers' concern, especially when the coin in limbo isn't even BCH. @fyookball please close.

**Comment by Lostalot** [comment]
WOW

**Comment by cculianu** [comment]
Yeah we have had a lot of support burden lately due to BSV users losing funds — this could have all been avoided had the BSV devs implemented reply protection. Don’t take it personally, @lostalot

I wish you luck in recovering your funds.

**Comment by drnick30** [comment]
Did you get your bsv back?
