### ISSUE TITLE
AttributeError: 'SlpCreateTokenGenesisDialog' object has no attribute 'on_error'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1404]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/tmp/Electron Cash SLP-3.4.13/gui/qt/util.py", line 709, in on_done
    cb(result)
  File "/tmp/Electron Cash SLP-3.4.13/gui/qt/slp_create_token_genesis_dialog.py", line 323, in on_failed
    self.on_error(exc_info)

AttributeError: 'SlpCreateTokenGenesisDialog' object has no attribute 'on_error'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.4.13  | 3.7.3rc1 (default, Mar 13 2019, 11:01:15)  [GCC 8.3.0] | Linux-4.19.0-5-amd64-x86_64-with-debian-10.0 | slp_standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
Seems fixed, closing
