### ISSUE TITLE
'Clear' option fails to properly clear "Pay to' field

### ISSUE THREAD

**Issue by Leandrodimarco** [Electron-Cash/Electron-Cash#1411]
MacOS Mojave 10.14.4
Electron Cash 4.0.5

'Clear' option fails to properly clear text from "Pay to' field.
LMB out of Electron Cash user interface clears "Pay to" field after using 'Clear' option.
Despite 'Pay to' field still showing text it seems not to be considered as valid information.
The issue does not represent a major problem and it is easily solved by the user but does not work in the direction of appealing user experience. 

To reproduce:
1. Enter receiving address.
2. Click on 'Clear' button.
3. Check field 'Pay to'.
4. LMB out of Electron Cash user interface.

![EC Clear 1](https://user-images.githubusercontent.com/40478033/58751919-2f8b9a00-847c-11e9-9b81-e1e178253dc2.png)

**Comment by cculianu** [comment]
I can't reproduce this. "Clear" does what you expect. I am on macOS High Sierra. I tried it on Mojave too and same behavior.  No matter what's in the Pay-to field, it always clears.

Please elaborate on how to reproduce it?

**Comment by Leandrodimarco** [comment]
Sure. First, let me add:
Tested in Windows 10 Pro:
Electron Cash 3.3.2: No issue detected.
Electron Cash 4.0.5: No issue detected.
Electron Cash 4.0.6 Dev1: No issue detected.

Tested in MacOS Mojave 10.14.4:
Electron Cash 3.3.2: No issue detected.
Electron Cash 4.0.5: **Issue detected.**
Electron Cash 4.0.6 Dev1: **Issue detected**

To reproduce:
Enter the receiving address.
![Screenshot 2019-06-02 at 11 06 45](https://user-images.githubusercontent.com/40478033/58762772-8dc28680-8529-11e9-92a9-93e97fa05f75.png)

Click on 'Clear' button and check 'Pay to' field. Cursor goes back to the left margin covering the first character (in this case "1') but the rest of the string is still on display.
![Screenshot 2019-06-02 at 11 11 21](https://user-images.githubusercontent.com/40478033/58762775-9b780c00-8529-11e9-878f-317dd8e0f659.png)

I guess that if you can't reproduce it in Mojave the issue is dependant on my environment/installation.

**Comment by cculianu** [comment]
Hmm.  I believe you that it's happening.  What worries me is it may happen to others too.

Here is a small GIF movie I made illustrating that it works on my system.

![clear_problem_works - Edited](https://user-images.githubusercontent.com/266627/58766234-d196a980-8584-11e9-85ad-33f9ab252594.gif)

I would *REALLY* love to know why it's not working.  Maybe you are getting an exception raised silently somewhere... hmm.

Can you try the following:

1. Open up Terminal.app (⌘ + Space, "Terminal", ENTER)
2. At the terminal, enter the following (assuming Electron-Cash is installed in /Applications):

```
    /Applications/Electron-Cash.app/Contents/MacOS/Electron-Cash -v
```

  This will run Electron-Cash is verbose mode. You should see a bunch of stuff printed on the console (debug info, etc).

3. Try and reproduce the problem and check the terminal for things that look like an Exception stacktrace.  This is a sample stacktrace:

<img width="619" alt="Screen Shot 2019-06-02 at 10 25 51 PM" src="https://user-images.githubusercontent.com/266627/58766289-68fbfc80-8585-11e9-80fb-58e86f6aca81.png">

If you see something like the above, please paste in the text of the log around that area, including that area.

**Comment by Leandrodimarco** [comment]
I tried the requested workflow.
No errors or exceptions detected at Terminal.
:(

**Comment by EchterAgo** [comment]
Could you please test if you have this issue with 4.0.2? If you don't have it with 4.0.2, please also test 4.0.3 and 4.0.4 so we know which version the issue was introduced in.

**Comment by Leandrodimarco** [comment]
Test results using MacOS Mojave 10.14.4:
4.0.4: Issue detected
4.0.3: Issue detected
4.0.2: Issue detected
4.0.1: Issue detected
4.0.0: Issue detected
3.3.6: Issue detected
3.3.5: Issue detected
3.3.4.1: Issue detected
3.3.4: Electron-Cash quit unexpectedly
3.3.3: Electron-Cash quit unexpectedly
3.3.2: Issue _NOT_ detected

The issue I see affects just 'Pay to' field.
'Clears' works perfectly with other fields.

**Comment by cculianu** [comment]
Ok, thanks for the thorough data points.  I will try and see what changed since then.  Of course we are missing some data points since 3.3.2... :)

I'll do a diff and see if anything pops out at me...

**Comment by cculianu** [comment]
I looked at the diffs between working vs not working versions and nothing is obvious -- although the diffs are quite large.

Can you do me a favor: disable all plugins (external and internal)?  It's possible some plugin is interfering (not likely, but possible).

Let me know if that helps... :/

**Comment by cculianu** [comment]
GOOD NEWS!

I was able to reproduce this with Electron Cash 4.0.0 release (but not 4.0.5) on my girlfriend's mac.  It behaves exactly as you describe and it looks like a repaint glitch.

I even found a workaround to get it to work -- (force a repaint).  I'm committing something to the repo now and will put together an extra special dev build just for you so you can download and test and let me know if the problem went away for you.

Will post the URL here when the dev build is ready.

**Comment by cculianu** [comment]
Update: Leandro got back to me and he confirmed it works now.. Success!

**Comment by Leandrodimarco** [comment]
Tested in 'extra special dev build'.
No issue detected.
'Clear' properly clears 'Pay to' field.
Thanks!
