### ISSUE TITLE
AttributeError: 'ElectrumWindow' object has no attribute 'slp_amount_e'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1424]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/Users/calin/src/ec/ec-slp/gui/qt/main_window.py", line 1721, in spend_max
    self.do_update_fee()
  File "/Users/calin/src/ec/ec-slp/gui/qt/main_window.py", line 1866, in do_update_fee
    if not self.slp_amount_e.get_amount():

AttributeError: 'ElectrumWindow' object has no attribute 'slp_amount_e'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.4.13  | 3.6.8 (default, Dec 30 2018, 13:01:55)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-17.7.0-x86_64-i386-64bit | slp_standard,imported_privkey | en_US | 

Additional Information
------------------------

> Calin here:
> 
> 1. Loaded imported wallet (non-SLP)
> 2. Tried to send some funds in send tab by right-clicking coin in coins tab -> spend
> 3. entered an address
> 4. hit "max", got this crash

---

**Comment by cculianu** [comment]
I suspect this happens on imported private key wallets (non-SLP) only..?

**Comment by jcramer** [comment]
probably, I have tested the other wallet types more extensively and never saw this.  I'll check it out.

**Comment by cculianu** [comment]
Nope, happens on any non-SLP wallet..

**Comment by cculianu** [comment]
#1426 Is another one, @jcramer

**Comment by jcramer** [comment]
@cculianu you can close this, its handled ^
