### ISSUE TITLE
AttributeError: 'ElectrumWindow' object has no attribute 'token_type_combo'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1426]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/Users/calin/src/ec/ec-slp/gui/qt/main_window.py", line 2899, in update_buttons_on_seed
    is_cointext = bool(self.payto_e.cointext) and self.token_type_combo.currentIndex() == 0

AttributeError: 'ElectrumWindow' object has no attribute 'token_type_combo'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.4.13  | 3.6.8 (default, Dec 30 2018, 13:01:55)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-17.7.0-x86_64-i386-64bit | standard,slp_standard | en_US | 

Additional Information
------------------------

> Calin here. More bugs :)

---

**Comment by cculianu** [comment]
Likely related: #1424

**Comment by jcramer** [comment]
@cculianu you can close this, its handled ^

**Comment by cculianu** [comment]
Awesome @jcramer  thanks for the reminder. I like to see issue count decrease. :)
