### ISSUE TITLE
Indicate per-wallet and global setting groups in Preferences

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#1427]
There are some items in Tools -> Preferences that are global (e.g. Transaction -> Enable OP_RETURN), and others that are per wallet only (e.g. "Use Schnorr Signatures"). While there are usually good reasons for each, a user cannot tell which settings are global and which are per wallet right now, resulting in a confusing UX. 

Recommend grouping them into "All wallets" and "This wallet only" in each tab.

**Comment by cculianu** [comment]
Thanks. I definitely want to do this soon. Much appreciated for bringing it up. Was a pet peeve of mine too.
