### ISSUE TITLE
satoshi.vision.cash

### ISSUE THREAD

**Issue by chambam** [Electron-Cash/Electron-Cash#1428]
satoshi.vision.cash
Is shown as a banned server on my network.
Can anyone tell me which server I should be using?
I was using satoshi.vision.cash which also showed my account balance now this server shows as banned and my account balance is zero.
Any help plz.

**Comment by imaginaryusername** [comment]
It's a bsv server and hence unsupported by Electron-cash. There's a long list of other servers you can use from the default list.

**Comment by chambam** [comment]
Thank you. I don't see electron-cash on the BSV site as a recommended wallet. Is it OK to send BSV to electron-cash? Or would you use eletrumsv for example?

**Comment by imaginaryusername** [comment]
Electron-cash has nothing to do with BSV anymore other than some outdated tools to split coins - ask the BSV community if you want to manage that coin. Electron-cash maintainers will not be responsible for any problems if you use this software to manage non-BCH coins.

**Comment by chambam** [comment]
thank you
