### ISSUE TITLE
NameError: name 'ModuleNotFoundError' is not defined

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1430]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/home/shako/Desktop/Electron Cash-4.0.6/gui/qt/main_window.py", line 3524, in settings_dialog
    except (ModuleNotFoundError, ImportError) as e:

NameError: name 'ModuleNotFoundError' is not defined
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.6  | 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609] | Linux-4.15.0-51-lowlatency-x86_64-with-Ubuntu-16.04-xenial | standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by EchterAgo** [comment]
Python 3.5 doesn't have ModuleNotFoundError

**Comment by EchterAgo** [comment]
Why do we catch both `ModuleNotFoundError` and `ImportError` there when `ModuleNotFoundError` is a subclass of `ImportError`? Just catching `ImportError` should be sufficient.

**Comment by cculianu** [comment]
Ouch. my bad.

**Comment by EchterAgo** [comment]
Seems that nobody triggered it in 4.0.5, so it seems like there are only very few Python 3.5 users left.

**Comment by cculianu** [comment]
See #1432 -- That's me trying it out in Python 3.5.  Python3.5 really doesn't work anymore.
