### ISSUE TITLE
SyntaxError: invalid syntax (camera_dialog.py, line 55)

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1432]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/Users/calin/src/ec/electron-cash/gui/qt/paytoedit.py", line 305, in qr_input
    super(PayToEdit,self).qr_input(_on_qr_success)
  File "/Users/calin/src/ec/electron-cash/gui/qt/qrtextedit.py", line 102, in qr_input
    if ElectrumGui.instance.warn_if_cant_import_qrreader(self):
  File "/Users/calin/src/ec/electron-cash/gui/qt/__init__.py", line 474, in warn_if_cant_import_qrreader
    from .qrreader import QrReaderCameraDialog
  File "/Users/calin/src/ec/electron-cash/gui/qt/qrreader/__init__.py", line 26, in <module>
    from .camera_dialog import QrReaderCameraDialog

SyntaxError: invalid syntax (camera_dialog.py, line 55)
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.6  | 3.5.7 (default, Mar 19 2019, 00:47:37)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-17.7.0-x86_64-i386-64bit | imported_privkey | en_US | 

Additional Information
------------------------

> Calin here:
> 
> I just tried EC with Python 3.5.  It pretty much fails everywhere.  We can safely say EC does not support Python 3.5.

---

**Comment by cculianu** [comment]
EchterAgo .. **at least I'm not the only one** :)

**Comment by EchterAgo** [comment]
Damnit. Is relative import not in Python 3.5?

**Comment by cculianu** [comment]
Commit d9ab02e7087deb12c15a2a8eb1720475abb6a06e disallows Python3.5 now.  We want to look forward, and not back!

**Comment by cculianu** [comment]
> Damnit. Is relative import not in Python 3.5?

@EchterAgo No actually the real crash was on your use of:

```

SOME_VAR : int = 5

```

Which I forgot actually isn't supported in Python3.5.

**Comment by cculianu** [comment]
@EchterAgo  Here:

https://github.com/Electron-Cash/Electron-Cash/blob/d9ab02e7087deb12c15a2a8eb1720475abb6a06e/gui/qt/qrreader/camera_dialog.py#L55

**Comment by EchterAgo** [comment]
Oh, right, line 55. I think its best to drop Python 3.5. We might want to add some automated checking with pylint to check for language features that are too new. I'll look into what it would take to get that.
