### ISSUE TITLE
BSV stolen from Electron Cash 3.3.2???

### ISSUE THREAD

**Issue by harrystigman** [Electron-Cash/Electron-Cash#1433]
I use my BCH privkeys to fire up the wallet, connected to the BSV chain and once it synced, all coins 6.8 went to this address - qzlmhayy5h0lyuh87jjm3dj5477fde2nkymks46wv7??

Why is this fraud software on your downloads list???

**Comment by EchterAgo** [comment]
Did you recently try to split your coins? Or did you follow some advice to upgrade your wallet?

**Comment by harrystigman** [comment]
I tried to use my BCH keys to claim the coins from the split. Once syncing completed on the BSV chain, my balance was transferred.

qzlmhayy5h0lyuh87jjm3dj5477fde2nkymks46wv7 already transferred to another address,

I downloaded the exe from here - https://electroncash.org/downloads/3.3.2/.

How could that possibly happen unless your website hosts a malicious file?

**Comment by harrystigman** [comment]
@EchterAgo Can you please help me figure what happened?

**Comment by cculianu** [comment]
Which file did you download exactly? Do you still have the file?  Can you run a sha256sum on it?

If you don't know what that is perhaps you can email it or somehow transfer it to us.

**Comment by cculianu** [comment]
Is this the tx? 0ea57c687663bbd68dccfe8c2d5807a97cfd55f0b99b2bc5c5992e82a5cbde39

It appears to only exist on BSV chain... so it's not a splitting issue. Would really help if you could provide us with the EXE you downloaded.

**Comment by harrystigman** [comment]
@cculianu Yes, that is the correct transaction.

I downloaded ElectronCash-3.3.2.exe from https://electroncash.org/downloads/3.3.2/win-linux/

The file is attached here as ".txt", please rename to .exe.
[ElectronCash-3.3.2.txt](https://github.com/Electron-Cash/Electron-Cash/files/3263900/ElectronCash-3.3.2.txt)

**Comment by harrystigman** [comment]
Here is the checksum - 
![image](https://user-images.githubusercontent.com/33494909/59073518-7969eb00-8895-11e9-8889-d91c16582828.png)

**Comment by cculianu** [comment]
Ok, the file checks out. It's the same as on the site, and it's the exact same file which was originally offered for download (same shasum). 

I can assure you we have no malware on any of these previous versions. Electron Cash 3.3.2 was downloaded by thousands upon thousands of people and nobody lost any coins in the way you describe.

It's possible you have some other malware installed on your system from some other place. It may be listening for events such as when you copy-paste private keys to the clipboard or it may even be listening for windows events to read the contents of text boxes, etc.

That is the one possible explanation for this that I can think of... there are other things that could have happened as well.

Is there any way you can figure out if your system is compromised?

**Comment by harrystigman** [comment]
Thanks for checking @cculianu , I'm running other wallets on the same machine and is well protected, regularly scanned and uses a VPN.

That being said, it must've been something I did, just need to figure out what.

There's no way to recover the funds now :(( but thank you for your help.

**Comment by cculianu** [comment]
Oh man good luck.  Yeah I really don't think it's that EXE.  I wish you luck -- if you find out how it happened let us know.

**Comment by cculianu** [comment]
Hey @harrystigman I know you said you are pretty sure your computer is clean, and it may be -- but the fact that your current wallets are ok, while this one wasn't does not prove there isn't some private key scanner installed; if it only knows to scan for private keys in windows messages as well as clipboard then it probably can't touch your already-installed wallets.

It might not even be that though, just throwing that out there.  Of course a way to test it would be to send some small amount to an address, and then try and copy paste the private key behind that address..

Just a thought.  Good luck!
