### ISSUE TITLE
TypeError: 'ElectrumWindow' object is not callable

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1435]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash_slp-3.4.14-py3.6.egg\electroncash_gui\qt\__init__.py", line 288, in on_focus_change

TypeError: 'ElectrumWindow' object is not callable
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.4.14  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.17134-SP0 | slp_standard | en_US | 

Additional Information
------------------------

> James on a pre-release build of EC SLP 3.4.14

---

**Comment by cculianu** [comment]
Nice catch. Was a bug in EC too. Fixed in latest EC & EC SLP
