### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type WindowModalDialog has been deleted

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1437]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "C:\Program Files (x86)\Electron Cash\electroncash_plugins\hw_wallet\qt.py", line 172, in clear_dialog
    self.dialog.accept()

RuntimeError: wrapped C/C++ object of type WindowModalDialog has been deleted
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.0  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17763-SP0 | standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
Weird: They are on a 'standard' wallet yet the user triggered an exception in HW wallet code.  It's the dreaded "Wrapped C++ object".  I looked at that code yet can't easily see how that can reasonably happen.  Nothing explicitly deletes that object.
