### ISSUE TITLE
Consider displaying entire outpoint in tx detail window

### ISSUE THREAD

**Issue by fyookball** [Electron-Cash/Electron-Cash#1439]
One thing I noticed in Electrum BTC is that they give the entire outpoint in the tx details window rather than truncated with dot dot dot in the middle

**Comment by fyookball** [comment]
![image](https://user-images.githubusercontent.com/7663756/59233948-a3365100-8bb8-11e9-92f6-aebc7ca859cd.png)

**Comment by cculianu** [comment]
Yeah it bugged me too: We can do that but it would eat up valuable space -- but can be done.  I'll look at how I can reformat the text to not look bad. 

Worst-case:  how would you feel about being able to right-click on it and get a context menu to copy the text to clipboard?

I'll try and format it like Electrum though if it doesn't make it super nasty.. considering we display more info there (including correct address and reliable amounds) ...

**Comment by fyookball** [comment]
i'm absolutely fine with click to open because most users wont use that very often.

**Comment by imaginaryusername** [comment]
On this topic: Can there be a "copy" button in the txid box (as seen in the "receive address" box)? Copying txid is probably why I open the window 99% of the time and it's kind of strange that button isn't there.

**Comment by cculianu** [comment]
You both got it! :)

**Comment by cculianu** [comment]
This has been addressed in latest commit via a right-click menu.  Exploding out the full output hash seemed a bit too much for the eyes .. IMHO.  I feel with the right click menu it's more useful anyway.

Bonus: You can now right click on an input -> View Tx to see the prevout tx!

Also bonus: If the address in inputs/outputs is one of yours, you can view its history!
