### ISSUE TITLE
OpenAlias Error.

### ISSUE THREAD

**Issue by janowitz** [Electron-Cash/Electron-Cash#1441]
I entered my OpenAlias which is already set up properly on the DNS side in Electron Cash preferences but it quits with an error. Also sending to an OpenAlias address is not working, since it states it's not a valid address (however it's set up as DNS TXT record). Probably it doesn't even get parsed and there is no DNS request performed.

It would be nice to see OpenAlias fully integrated in BCH wallets, since it's an open, extendable standard for yers and far superior to AliasSV / PayMail recently brought up by BSV.

**Comment by cculianu** [comment]
This facility has been given 0 love. I'm not surprised it's broken.  I'll look into fixing it. Thanks for reporting.

PS: If you have an openalias record I can point to to test, would be great.  Just give me a domain name if you don't mind.  If you want to remain private, I understand.. I can set one up on my domain, I guess. :)

**Comment by janowitz** [comment]
Feel free to try this one, there is an OpenAlias for BCH, BTC and XMR: pebx.pl

However, without DNSSEC, but shouldn't be necessary according to the protocol.

**Comment by cculianu** [comment]
Ok, I'll look at it later today or tomorrow. Thanks. Likely it used to work but is code-rotten now. Hopefully with some minor nudging it works again.

**Comment by EchterAgo** [comment]
I have it working. It seems we never switched to another prefix than `btc`. I see you are using `bch`, so I switched to that (need some feedback on this @cculianu ). Also there was an issue where the TXT record was not properly decoded into a string and the pay to editor didn't handle returned address objects.

**Comment by cculianu** [comment]
You are a superstar @EchterAgo .. So you'll submit a PR?

**Comment by EchterAgo** [comment]
Yes, I want to test DNSSEC working properly before doing that though.

**Comment by EchterAgo** [comment]
https://github.com/Electron-Cash/Electron-Cash/blob/master/lib/contacts.py#L115

What do you think about changing the prefix to `bch`? It seems like the logical choice to me. The OpenAlias website says:

> OpenAlias does not maintain a repository of prefixes at this stage, but may do so in future.

And some people like @janowitz seem to be using `bch` already.

**Comment by janowitz** [comment]
> Yes, I want to test DNSSEC working properly before doing that though.

I've just added an OpenAlias to janowitz.me (only bch, no btc) - with DNSSEC activated, however you know how slow DNS servers usually update, so I have to wait until Namecheap propagates the change.

> And some people like @janowitz seem to be using bch already.

It should be definitely bch, like any other coin (btc, xmr, nav) should be separated. And I think it's great to have a common standard instead of like the bsvalias everyone implementing it somehow different, since then exchanges and other places will never implement it separately for every single asset.

**Comment by EchterAgo** [comment]
I tested with DNSSEC using `axel@gembe.net` already and it works :)

**Comment by cculianu** [comment]
W00t. EchterAgo is a superstar.  He fixed it quickly.  @janowitz -- if you can run from source -- pull latest and check it out. Yayyyyy!
