### ISSUE TITLE
"No Data" for Amount + Balance of shuffled coin in history tab using CoinGecko

### ISSUE THREAD

**Issue by jkister** [Electron-Cash/Electron-Cash#1448]
The history tab currently shows no data available for the amount and balance columns of coins that are shuffled.  would be nice to show the values there like normal.

**Comment by cculianu** [comment]
I'm not sure what you mean? Like a separate column for shuffled balance, etc?

**Comment by jkister** [comment]
no separate fields--  since i enabled the shuffle plugin, all the amount/balance columns say "No data".  They say no data for shuffle tx, sending, and receiving.

prior to enabling shuffle plugin, the amount and balance fields always had correct values.

I suppose this might not be a feature request, maybe a bug report?

**Comment by jkister** [comment]
ends up this is not a feature request and does seem to be a bug.

I just changed  Preferences -> Fiat -> Source to Coincap -- makes the fields work for both pre-and-post enabling shuffle plugin.
i changed it back to CoinGecko and only pre-enabling shuffle plug transactions work.

**Comment by cculianu** [comment]
Yep. It's a bug alright.  Thanks for reporting I'll fix it.

**Comment by cculianu** [comment]
This definitely happens.  I deleted the files in ~/.electron-cash/caches and the historical data came back -- but before then it was all "No data".

I'll work on this today. Thanks for reporting.
