### ISSUE TITLE
[feature request] make update checker less obtrusive

### ISSUE THREAD

**Issue by jkister** [Electron-Cash/Electron-Cash#1449]
Current update checker displays separate window every few minutes to alert about an update.  History during vulnerability showed this useful.  Perhaps it's time to change the window to only show when versions have some tag that indicates it's critical.  And maybe put an icon somewhere to indicate non-critical updates are available.

**Comment by cculianu** [comment]
I agree. It kinda sucks and tempts you to turn it off -- defeating its purpose.

I will make this a higher-than-average priority.

**Comment by imaginaryusername** [comment]
People have suggested using the notification bubbles (already used for incoming transactions), which should be much less annoying than popup windows while still remaining visible.
