### ISSUE TITLE
Preferences option to turn off desktop notifications

### ISSUE THREAD

**Issue by fyookball** [Electron-Cash/Electron-Cash#1451]
Some users (me) don't really like the desktop notifications.  Might be nice to have the ability to switch them off.

**Comment by cculianu** [comment]
Ok, sounds reasonable.

**Comment by cculianu** [comment]
Just for tx's? Or even in-app things like "Yyour cashshuffle server broke" or "a new version is coming"?

Note: I plan on making the update notifier less intrusive and just have it do a systray notification once per app run, with maybe an icon somewhere in a corner too.

**Comment by cculianu** [comment]
Ok well I will put this in as per-wallet.
