### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u279d' in position 88: character maps to <undefined>

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1453]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-4.0.6-py3.6.egg\electroncash_gui\qt\main_window.py", line 2999, in export_history_dialog
  File "site-packages\electron_cash-4.0.6-py3.6.egg\electroncash_gui\qt\main_window.py", line 3029, in do_export_history
  File "c:\python3.6.8\lib\encodings\cp1252.py", line 19, in encode

UnicodeEncodeError: 'charmap' codec can't encode character '\u279d' in position 88: character maps to <undefined>
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-8.1-6.3.9600-SP0 | standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
This was due to bugs in code. On Windows Python `open` can default to using `cp1262` or other `cp` style encodings and **not** `utf-8`. The solution is to ALWAYS force utf-8 in Python to prevent this craziness.
