### ISSUE TITLE
Mistakenly Sent BCH using Electron Cash to SV address on Poloniex

### ISSUE THREAD

**Issue by aaroninsb** [Electron-Cash/Electron-Cash#1458]
I mistakenly Sent BCH using Electron Cash to SV address on Poloniex.

What can I do to recover the BCH?

**Comment by cculianu** [comment]
You need to contact Poloniex and ask them to send you your money back or credit your account. There is nothing else you can do.  They control the private key of the address that has those funds now -- so if they are nice they will return the funds or credit you.

It happens .. :/
