### ISSUE TITLE
Extend export with historical price data

### ISSUE THREAD

**Issue by emergent-reasons** [Electron-Cash/Electron-Cash#1459]
I heard that Calin got historical price working well now. Would it be possible to include that in the export data now? It will help with anyone that needs accurate historical records on their transactions.

**Comment by cculianu** [comment]
Yes. 100% agreed. Will do this now.

**Comment by cculianu** [comment]
Ok, done. Take it for a spin when you get a chance and let me know if it works ok. Note: very old tx's have no history quotes (most servers don't return much of a history rate before 2015 or so).

**Comment by cculianu** [comment]
Note that I also am sorting the history now in reverse order (like the history tab).  I hope that doesn't break anything for you!

**Comment by emergent-reasons** [comment]
Looks great! Thank you very much.

I compared with my records on one wallet and found just one issue.

The export uses local time so the price will vary depending on the locale that the data is exported in. If you use UTC instead, at least all exports would be consistent. The best would be to know what TZ the data service is using, but I've never been able to find that.

**Comment by cculianu** [comment]
I agree with you it would be more accurate then but this calls into wallet code that just always exports local time.  If you want you can open an issue to add this as an enhancement but I won't do it right now because other bugs/features take priority...

**Comment by emergent-reasons** [comment]
I won't file that because it doesn't really impact me and it's still arguable what the actual TZ is. Thanks again.
