### ISSUE TITLE
Feature Request: Add button to "Payment Sent" modal for copying explorer link to tx

### ISSUE THREAD

**Issue by memalley** [Electron-Cash/Electron-Cash#1464]
On payment sent modal:
1. Add button, "Copy Link"
2. Clicking button copies link to transaction URL on user's explorer of choice
3. After copying, the modal is closed

>Improves UX of sharing newly created transactions

![image](https://user-images.githubusercontent.com/12281083/59737904-5595a480-929a-11e9-950c-e9df9b9731b8.png)

**Comment by cculianu** [comment]
Done in latest commit.
