### ISSUE TITLE
AttributeError: 'ElectrumWindow' object has no attribute 'token_type_combo'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1468]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "Electron_Cash_SLP-3.4.14-py3.6.egg/electroncash_gui/qt/bfp_upload_file_dialog.py", line 427, in select_file
  File "Electron_Cash_SLP-3.4.14-py3.6.egg/electroncash_gui/qt/bfp_upload_file_dialog.py", line 310, in sign_txns

AttributeError: 'ElectrumWindow' object has no attribute 'token_type_combo'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.4.14  | 3.6.8 (default, Jun  8 2019, 19:47:49)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] | Darwin-17.7.0-x86_64-i386-64bit | standard,slp_standard | en_US | 

Additional Information
------------------------

> jcramer using EC SLP 3.4.14 with non-SLP wallet type.
> 
> 1. Open non-SLP wallet type.
> 2. Try to upload file with Bitcoin File Upload dialog

---

**Comment by cculianu** [comment]
This one's for Cramer.

**Comment by jcramer** [comment]
@cculianu this one can be closed.
