### ISSUE TITLE
feature request: copy multiple addresses

### ISSUE THREAD

**Issue by molecular** [Electron-Cash/Electron-Cash#1475]
In coins tab and addresses tab, one can select multiple entries.

It would be cool to have a entry "copy addresses" (similar to the entry when clicking on single address/coin) that puts a list of the selected addresses into clipboard.

I would personally prefer unix line separator ("\n") because my use case wants one address per line, but maybe other separators can make sense?

**Comment by cculianu** [comment]
Hmm.. the separator is the question.  Standard would be " " this way you can paste them onto a command-line, etc.... Hmmmmm.

Good suggestion. Can do this.

**Comment by molecular** [comment]
" " is fine. If needed people can use awk, sed or some text editor search and replace function.

**Comment by molecular** [comment]
just checked it out, works as expected.

I see you used some <newline> as separator after all. Great for me.

Thanks for all your great work :heart:

**Comment by cculianu** [comment]
Yeah you were right. The "\n" made the most sense.  " " looked stupid.

Glad it works!

I actually used this feature too recently. It's handy.
