### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'to_string'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1478]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "F:\dev\Electron-Cash\plugins\ledger\qt.py", line 62, in auth_dialog
    dialog = LedgerAuthDialog(self, data)
  File "F:\dev\Electron-Cash\plugins\ledger\auth2fa.py", line 114, in __init__
    pin_changed('')
  File "F:\dev\Electron-Cash\plugins\ledger\auth2fa.py", line 103, in pin_changed
    addressstr = address.to_string(Address.FMT_LEGACY, net=networks.MainNet)

AttributeError: 'tuple' object has no attribute 'to_string'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.8  | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by EchterAgo** [comment]
This was me trying to do a Ledger legacy TX on master. Investigating it now.

**Comment by cculianu** [comment]
Ok.. I can also help if it's obvious. I don't have a ledger tho.. ha!
