### ISSUE TITLE
~bug: preview allows multiple broadcast of same tx due to delay in disabling broadcast button

### ISSUE THREAD

**Issue by emergent-reasons** [Electron-Cash/Electron-Cash#1483]
EC version: 4.0.7 AppImage

I noticed when I sign and broadcast a tx manually, that the broadcast button stays enabled for a short period after broadcasting. Enough to click "ok" on the confirmation dialog and then re-broadcast the tx.

I especially noticed it when signing a multisig - for some reason it stayed enabled long enough for me to doubt myself - "Did I actually broadcast or did I do something wrong just now?"

**Comment by cculianu** [comment]
Yeah the button really should disable itself immediately and only re-enable itself on broadcast failure (error).

Will fix.

**Comment by cculianu** [comment]
This has finally been fixed in master! Yay!
