### ISSUE TITLE
App shows no GUI after running a few times with no output on CLI

### ISSUE THREAD

**Issue by hieutvan** [Electron-Cash/Electron-Cash#1484]
I'm using Electron Cash 4.0.7 on Debian 9. After starting & quitting the app a few times, it stops showing GUI (nothing shows up at all). Running it via CLI yields no output nor debugging info.

**Comment by cculianu** [comment]
Try removing the lockfile from `~/.electron-cash`... See #1240 

Also try running `electron-cash` with verbose output `electron-cash -v` and let me know what the log says.

**Comment by hieutvan** [comment]
Duplicate #892

**Comment by cculianu** [comment]
Ah I see. Ok glad you figured it out. (I am assuming you figured it out)
