### ISSUE TITLE
search text entry box in status bar can be invisible

### ISSUE THREAD

**Issue by molecular** [Electron-Cash/Electron-Cash#1493]
Sometimes I use the search feature (Ctrl-F) in address tab to check wether my wallet contains some address. This opens a text entry field in the status bar on the bottom, right next to the status text.

Now when the status text is very long (for example when cashshuffle is in progress with unconfirmed tx and fiat display is enabled) as seen in the screenshot and the window isn't wide enough, that text entry box can become very small or even invisible (in the screenshot it's barely visible for clarity, the bad case is when it's invisible) due to the very long status text.

![image](https://user-images.githubusercontent.com/589745/60505712-90e59980-9cc4-11e9-899b-d05fe9e96225.png)

The search text entry box always be visible and at least a certain size.

Maybe the status text can be hidden while the text entry box is shown?

**Comment by cculianu** [comment]
Lol yeah that's pretty hilarious. Either hide the status text or maybe not print the full status ... Ha ha. OK, thanks for reporting. Will see about fixing when I'm done with my current Cash Accounts implementation. 👍

**Comment by molecular** [comment]
> Either hide the status text or maybe not print the full status

yeah. or simply reorder so the search entry box comes first?

**Comment by cculianu** [comment]
> yeah. or simply reorder so the search entry box comes first?

Very good suggestion. I'm on vacation not but when I get back I'll investigate if this is possible out of the box with Qt.

**Comment by cculianu** [comment]
Ok, done. This made me also fix a bunch of other quirks in the search box. I'll be posting a new build later tonight or tomorrow with this and the other fix.. hope you can try it out and let me know if you like what I did with the search box.

**Comment by molecular** [comment]
works! :white_flower:

**Comment by cculianu** [comment]
W00h00!
