### ISSUE TITLE
feature request: become semi-aware of slp

### ISSUE THREAD

**Issue by jkister** [Electron-Cash/Electron-Cash#1494]
Way before SLP is implemented/ported, we could become semi aware of it.

Send a warning to the user with 'send anyway' button when spending tx which has op_return set.

**Comment by cculianu** [comment]
Not a bad idea. We can scan the prevout tx and if it "looks SLPish" based on the protocol bytes after the OP_RETURN,  we can then warn the user that it may or may not contain a token.

Good suggestion.

**Comment by jcramer** [comment]
@cculianu would this method satisfy this issue/request?  Maybe we can close this?

https://github.com/simpleledger/Electron-Cash-SLP/blob/186cdf21965d459d9e72141e7937fe2e9ed5bb7b/lib/slp_checker.py#L9

**Comment by cculianu** [comment]
I don't think this issue should be closed until we actually have this capability in Electron Cash.

As for the linked function -- it may or may not be sufficient.  I need to set up some time to review these things but I am not going to merge anything just yet.
