### ISSUE TITLE
SCAM SITE DO NOT VISIT -- www.electrum-bsv.org --

### ISSUE THREAD

**Issue by sodomak** [Electron-Cash/Electron-Cash#1495]
Is website http://www.electrum-bsv.org/ somehow related to this project? Or is it some scam? There are links to this repo but no links to the web here.

**Comment by EchterAgo** [comment]
It is neither related to this project, nor to the [ElectrumSV](https://electrumsv.io/) project. The download there is a fake Delphi program that will steal your funds.

**Comment by sodomak** [comment]
Thanks.
