### ISSUE TITLE
com.chaquo.python.PyException: FileExistsError: /data/user/0/org.electroncash.wallet/files/data/wallets/Big.winner

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1497]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
	at <python>.create(/android_asset/chaquopy/app.zip/electroncash_gui/android/console.py:147)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:282)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrows(chaquopy_java.pyx:254)
	at com.chaquo.python.PyObject.callAttrThrows(Native Method)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:207)
	at org.electroncash.electroncash3.DaemonModel.createWallet(Daemon.kt:121)
	at org.electroncash.electroncash3.NewWalletSeedDialog.onCreateWallet(Wallets.kt:280)
	at org.electroncash.electroncash3.NewWalletDialog2$onShowDialog$1$1.run(Wallets.kt:248)
	at java.lang.Thread.run(Thread.java:764)
com.chaquo.python.PyException: FileExistsError: /data/user/0/org.electroncash.wallet/files/data/wallets/Big.winner
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.5-1  | 3.6.5 (default, Dec  7 2018, 13:59:54)  [GCC 4.9] | Android 8.0.0 on samsung SM-A520F (a5y17lte) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
We confirm the wallet name doesn't already exist in the first dialog, and then the user can take as long as they want to complete the second dialog. But I can't see how a file with that name could appear during the intervening time:
* If it's the name of the currently-open wallet, then the file should exist constantly: it might be saved during this time by a background thread, but renames should be atomic on Android just as they are on Linux, so the change in #1364 should make no difference.
* Or if it's a different wallet, all the commands which create or delete wallet files will block the user interface with a progress dialog until they complete, so there's no way for the user to be in the new wallet process at the same time.

**Comment by cculianu** [comment]
Yeah wow.. it's a mystery, I guess... Should we leave this open? or?

**Comment by mhsmith** [comment]
Probably caused by the same thing as #1575: the progress dialog wasn't actually coming up quickly enough to block multiple clicks. Please close.

**Comment by cculianu** [comment]
Oooh yeah that totally makes sense, I think.
