### ISSUE TITLE
allow notes on CashAccount contacts

### ISSUE THREAD

**Issue by emergent-reasons** [Electron-Cash/Electron-Cash#1508]
Although the names are human readable, just like with email it is not always easy to remember who is associated with each one.

Would be nice to allow a note on each contact.

Love CashAccount integration!

**Comment by cculianu** [comment]
Oh.. like labels? Hmm. Yeah that’s probably a good idea.  Previously the contacts were user created free form name/address pairs but now with the cadhaccounts type, they are blockchain generates so notes make sense.  Will do this. Good suggestion!

**Comment by cculianu** [comment]
This has now been addressed in the latest commit.
