### ISSUE TITLE
Cashaccount/contacts tab does not respect address format toggle

### ISSUE THREAD

**Issue by acidsploit** [Electron-Cash/Electron-Cash#1510]
When you add a cashaccount it adds the account with the current address format state. If you toggle legacy vs. cashaddr the contacts tab does not react to that.

**Comment by fyookball** [comment]
seems to work for me.  I am pressing the toggle button and the address on the contacts tab associated w my cashaccounts are toggling correctly.

**Comment by fyookball** [comment]
to create the bug, user imported account rather than created it.

**Comment by cculianu** [comment]
Users are free to paste Legacy Addresses and always see them as such.  The address book functionality does not pay attention to address format.

This isn't really a bug per se but rather how the system was designed. Addresses are stored in the form the user entered them as strings. This is by intention.  

Note that Cash Accounts do not behave by this.  I do not think this is a bug nor will I fix it, sorry.

**Comment by cculianu** [comment]
@acidsploit Actually it appears this bug can easily be reproduced with Cash Accounts. I misunderstood the error.  Will fix.

**Comment by acidsploit** [comment]
You to fast, I was just about to link this: https://giant.gfycat.com/AbandonedHiddenGerbil.webm

**Comment by cculianu** [comment]
@acidsploit Fixed.  Good catch.  All apologies for not "getting it".  Very good catch as now the UI is consistent.  Note I went ahead and made the legacy "Address" entries also respect the GUI preference setting because it bugged me that they don't.
