### ISSUE TITLE
Cashaccounts gone from contacts tab

### ISSUE THREAD

**Issue by fyookball** [Electron-Cash/Electron-Cash#1511]
After closing wallet and opening the next day, nothing shows on contacts tab.

![image](https://user-images.githubusercontent.com/7663756/61053914-71cdc280-a3bc-11e9-8e3a-3075a29789bf.png)

![image](https://user-images.githubusercontent.com/7663756/61053933-7e521b00-a3bc-11e9-8388-47e32aff66de.png)

**Comment by fyookball** [comment]
false alarm.

**Comment by cculianu** [comment]
FYI -- 4.0.7 and 4.0.8 dev have completely different contacts DB format (by design).  You won't see your new 4.0.8 contacts in 4.0.7.  But you will when opening in 4.0.8.
