### ISSUE TITLE
[Android] Display a receiving address at Requests page without an additional tap

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#1514]
Right now the "requests" tab on Android is empty, and requires an additional tap to receive anything. Please consider automatically putting up the last unused address there as a QR, similar to desktop Electron-Cash.

**Comment by mhsmith** [comment]
There's plenty of room on a desktop screen for both the list of requests and the details of one request, but on a phone screen you can only show either the list or the detail, and obviously you have to start with the list. The other three screens in the app all work in the same way.

If you have any other ideas for how this could work then let me know.

I agree that the user might be confused when we present them with a completely blank screen, so I'll add a caption when the list is empty so they know what to do.

**Comment by imaginaryusername** [comment]
In that case, the list should probably be abandoned or otherwise tucked into its own "advanced" tab. An always-on receiving screen that refreshes itself upon receipt is by far a more frequent usecase for mobile than multiple concurrent requests.

**Comment by imaginaryusername** [comment]
Copay and bitcoin.com, for example, relegates the "requests" lists very deep into the "address lists" for a given wallet - and nobody seems to miss them, the receiving screen simply shows a big QR that has a "specific amount?" button. 

For mobile most people simply need to flash a receiving address and QR quickly to senders - simultaneous payment requests each with their own amounts to many people, as well as historical requests, are not a concern.

**Comment by mhsmith** [comment]
I see what you mean. OK then, how about adding a second button to the Transactions tab, so we have Send and Receive side by side there, like in the iOS app? Clicking the Receive button would bring up the same dialog as the + button in the Requests tab (and they can close it without saving if they want). That way, many users would never have to leave the Transactions tab at all.

**Comment by imaginaryusername** [comment]
Send and Receive side by side will indeed be a massive improvement, as  long as it's obvious where Receive is.

**Comment by mhsmith** [comment]
Here's what it looks like:

<img src="https://user-images.githubusercontent.com/166954/61577064-0e3d4680-aada-11e9-83a6-392cec90e038.png" width="400"/>

**Comment by imaginaryusername** [comment]
Can the receive icon not be a little more obviously "receive", like 
![inbox_receive-512](https://user-images.githubusercontent.com/34949601/61578151-39f30900-aaa7-11e9-9581-781b47e09082.png) ?

**Comment by mhsmith** [comment]
Yeah, I was kind of attached to the icon meaning "request" rather than "receive", but I think you're right.

**Comment by imaginaryusername** [comment]
Seems addressed by https://github.com/mhsmith/electrum/commit/e92ab428eef8225558832c58fd28c7f7e1ee572d .
