### ISSUE TITLE
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

### ISSUE THREAD

**Issue by markblundeberg** [Electron-Cash/Electron-Cash#1517]
As of Python 3.7 or thereabouts, we get this warning on startup:
```
./electron-cash:96: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```

https://github.com/Electron-Cash/Electron-Cash/blob/9582741418aca557e02c2fd49e51c21ad4d83a7b/electron-cash#L94-L99

It's a bit annoying to refactor these lines using `importlib` because we rename the modules.

**Comment by markblundeberg** [comment]
refs:
https://docs.python.org/3/library/importlib.html
https://docs.python.org/3/library/imp.html

**Comment by cculianu** [comment]
Hmm... so this isn't immediately refactorable? Let me read the `importlib` docs and see if we can do something... :/

Yet more reasons to switch away from this rewriting of the import paths thing...

**Comment by markblundeberg** [comment]
I'm sure there's a way, just not immediately obvious.

**Comment by cculianu** [comment]
Yeah I just tried hacking away at it -- not immediately obvious either. The python docs to importlib and importlib.util come with a bunch of recipes and examples but none of them really works to do what we want.  Will look into this more...

The real solution is to just do away with this hacky rewriting of dirs... but it requires going into all the build scripts and other assorted odds and ends and making sure they don't break... so it's an annoying task.. :/

**Comment by markblundeberg** [comment]
Worth noting: recent discussion on deprecation schedules suggests python 3.10 will have `imp` removed, so we have quite some time to deal with this.

https://www.python.org/dev/peps/pep-0594/#imp

Given 3.8 and 3.9 release schedules, we could guess that 3.10 will come out in March 2021. Hard to say for sure, could be much later than that.
https://www.python.org/dev/peps/pep-0569/#schedule
https://www.python.org/dev/peps/pep-0596/#schedule

**Comment by cculianu** [comment]
Ok, well I'll backlog this.  This is more a nit than anything -- it would be nice to remove the imp module stuff altogether but it's annoying little work that takes like 4 hours to get right and test.

**Comment by mhsmith** [comment]
See also #807.
