### ISSUE TITLE
Update the current logo to a square

### ISSUE THREAD

**Issue by BeltranLeo** [Electron-Cash/Electron-Cash#1526]
The current logo is good, as it is based upon the official Bitcoin Cash logo. I made a square version to use across different platforms.

![Electron Cash Logo Square](https://user-images.githubusercontent.com/32263015/61378196-39762a80-a87b-11e9-827f-f6897fc0ccf9.png)

It retains the essence of the traditional logo of Electron Cash, and it is more easily displayable in low resolution screens, as a favicon, and places where only a square of a fixed amount of pixels per side is available to use.

**Comment by cculianu** [comment]
Any chance you can also supply this as `.svg`? We've been on an SVG kick lately because we like scalable vector graphics.  Scalable vector graphics are forever! When we get 10k virtual reality 3d smell-o-vision monitors you'll thank me!

**Comment by EchterAgo** [comment]
We do need to go to a square icon but we need to choose which one. I am attaching my previous proposals here. I personally would prefer one of the variants with the bigger B, especially for small icon sizes <=24px.

[logos.zip](https://github.com/Electron-Cash/Electron-Cash/files/3402347/logos.zip)

**Comment by cculianu** [comment]
My vote is for the first one, Logo-test. But I like all of them. Also the BigB one.

**Comment by EchterAgo** [comment]
Yea, I'd also prefer logo test. Note that I screwed up the file and it is actually not square but 512x521. I'll fix that if we go with that one.

**Comment by BeltranLeo** [comment]
Hey, @cculianu, here is the SVG version! I tried to upload it as such, but GitHub will not let me. So now it is zipped.

[Electron Cash Logo Square.zip](https://github.com/Electron-Cash/Electron-Cash/files/3403073/Electron.Cash.Logo.Square.zip)

Thank you!

**Comment by cculianu** [comment]
Looks great! thank you!

Ok so now how do we decide?  Who wins?  I propose trial by combat. Fight to the death and may the man standing choose. :)  It's the viking way.

![helmet](https://user-images.githubusercontent.com/266627/61397266-2fcbe180-a8d2-11e9-8128-7cecb68e610f.png)


(No, but seriously.. how do we decide? I Jonald even down for an icon change? I really want to change it to something square too but Jonald gets the final say).

**Comment by BeltranLeo** [comment]
> The magic of software is that it can be changed.

I also like the first one proposed by @EchterAgo. It is just a matter of taste. Mine is the _BCH Logo For Wallets / Exchanges_ present at [Logos / Graphics](https://www.bitcoincash.org/graphics.html) (in blue,  of course).

**Comment by marceloneil** [comment]
My two cents,

The square logo is not as unique or interesting, however it's a bit more standard and would likely be easier to use in different scenarios.

**Comment by fyookball** [comment]
@EchterAgo in your zip file, is the logo_test.svg also for iOS even though it doesnt say iOS in the file name?

**Comment by fyookball** [comment]
are these proposed logos only for iOS?

**Comment by EchterAgo** [comment]
The file names are not intended to say anything about which platform they are for. Logo ios is called that way because it looks exactly like our current ios logo, just as svg. The svg icons can be used on any platform (some might need rasterizing). I think ideally we should use the same icons on all platforms.

**Comment by fyookball** [comment]
I see. I like the perfect square one @BeltranLeo posted the best.

**Comment by EchterAgo** [comment]
That format is also fine with me, most important is making it square. If we go with that design I would still increase the size of the B though, it really helps with small icon sizes.

**Comment by fyookball** [comment]
im fine with increasing the size of the B

**Comment by cculianu** [comment]
Ok, I tried all the icons.  On second thought I do not like the one proposed in this issue. The corners hanging off the end look a bit strange in practice.  Here are some screenshots:

---

### 1. The one proposed at top (first one):

<img width="313" alt="Screen Shot 2019-07-18 at 6 09 37 PM" src="https://user-images.githubusercontent.com/266627/61469234-8515fa80-a987-11e9-93c1-05d910d4ae62.png">

I dislike the way the corners look.  They need to not be flush with the circle. It looks like someone cropped them in MSPaint. Also the B could be bigger. Sorry!

---

### 2. One of ichundes's ones (logo_test I believe):

<img width="237" alt="Screen Shot 2019-07-18 at 6 11 05 PM" src="https://user-images.githubusercontent.com/266627/61469230-847d6400-a987-11e9-8ef2-8058e99616c5.png">

It's better fine, I like it more than (1) above; but the bigger B ones 3 & 4 below are better IMHO.

---

### 3. "Logo ios" (ignore the name)

<img width="207" alt="Screen Shot 2019-07-18 at 6 10 44 PM" src="https://user-images.githubusercontent.com/266627/61469231-8515fa80-a987-11e9-96dc-17c3632e9ce1.png">

I love it!

---

### 4. Logo_ios_big_b

<img width="210" alt="Screen Shot 2019-07-18 at 6 10 20 PM" src="https://user-images.githubusercontent.com/266627/61469233-8515fa80-a987-11e9-83f6-72db60d2bb07.png">

This is my favorite one by far! This or (3) above!! Please!!

**Comment by cculianu** [comment]
Here is (4) above (my favorite) in the "About Electron Cash" window on macOS:

<img width="424" alt="Screen Shot 2019-07-18 at 6 19 37 PM" src="https://user-images.githubusercontent.com/266627/61469864-a6c3b180-a988-11e9-86e5-6ce5553edc31.png">


It's so handsome!

**Comment by fyookball** [comment]
I can see what you mean about the square one not looking great in the tray.  @cculianu .  But in other contexts I don't agree with your opinion.  So maybe we should get other opinions.  Also we should challenge the assumption that we should only have 1 version of the logo.  (Maybe its ok to have a different one in the tray).

**Comment by cculianu** [comment]
@fyookball Just to clarify terminology: in this context "tray" means usually the system tray (the tiny little icon which on windows is in .. the system tray!).  I think you mean "task bar" or "dock" as they are called on Linux & Windows and Mac respectively.

That being said -- yeah nobody I think wants it to be just *one* icon for everything ...

**Comment by cculianu** [comment]
And yeah maybe we can ask the community how they feel.. 👍

**Comment by BeltranLeo** [comment]
It would be nice to let the community decide. You are right that the logo I proposed looks a bit odd, maybe it could be changed, but I still would suggest to make it square. Maybe something like this.

![Electron Cash Logo Square 2 svg](https://user-images.githubusercontent.com/32263015/61482340-bd5e0e80-a970-11e9-94a2-e84be95ece61.png)

And, of course, here is the source file.

[Electron Cash Logo Square 2.zip](https://github.com/Electron-Cash/Electron-Cash/files/3407925/Electron.Cash.Logo.Square.2.zip)

**Comment by fyookball** [comment]
i dont mind the square w rounded corners... i think we should enummerate all the palces the logo is used so we can judge better.  i like the original square first but when Calin showed in context I agreed with him.  so yeah.

**Comment by EchterAgo** [comment]
![image](https://user-images.githubusercontent.com/922233/61539709-47d46a00-aa66-11e9-9899-d5574238b531.png)
Windows - Window title bar

**Comment by EchterAgo** [comment]
![image](https://user-images.githubusercontent.com/922233/61539753-6175b180-aa66-11e9-9d16-0260da47cbe5.png)
Windows - Systray light

**Comment by EchterAgo** [comment]
Windows screenshots are at 125% scaling.

**Comment by EchterAgo** [comment]
![image](https://user-images.githubusercontent.com/922233/61539975-d648eb80-aa66-11e9-9c27-cdeda28b367d.png)
Arch Linux KDE Plasma - Window title bar

![image](https://user-images.githubusercontent.com/922233/61540012-ebbe1580-aa66-11e9-92a4-6e58dda46c92.png)
Arch Linux KDE Plasma - Systray

![image](https://user-images.githubusercontent.com/922233/61540046-009aa900-aa67-11e9-999b-950e19192263.png)
Arch Linux KDE Plasma - Task bar

**Comment by EchterAgo** [comment]
![image](https://user-images.githubusercontent.com/922233/61540596-1bb9e880-aa68-11e9-8201-78f0829fc4e5.png)
Ubuntu 18.04 GNOME - Task bar (not sure if that's what its called). This is a really bad example

**Comment by EchterAgo** [comment]
![image](https://user-images.githubusercontent.com/922233/61540714-5885df80-aa68-11e9-8999-a67a56ef3ddc.png)
Ubuntu 18.04 GNOME - Install wizard

![image](https://user-images.githubusercontent.com/922233/61540737-6a678280-aa68-11e9-87a8-a5d61892e535.png)
Ubuntu 18.04 GNOME - Side bar

**Comment by EchterAgo** [comment]
![image](https://user-images.githubusercontent.com/922233/61540780-810dd980-aa68-11e9-8ffa-70374acd60b8.png)
Ubuntu 18.04 GNOME - Systray

**Comment by EchterAgo** [comment]
Note the light systray icon needs to be improved too. It has way too low contrast between the light gray and the white B. I had a version with black fill for the B, but haven't submitted a PR for that yet.

**Comment by EchterAgo** [comment]
One between the IOS logo and IOS logo with big B, as requested in Telegram:

[logo_ios_medium_b.zip](https://github.com/Electron-Cash/Electron-Cash/files/3411430/logo_ios_medium_b.zip)

**Comment by cculianu** [comment]
Ok, icon updated as per conversation in Telegram, etc.  We are using the latest one posted by @EchterAgo .

Thanks a lot for opening the issue and bringing it to our attention, @BeltranLeo
