### ISSUE TITLE
Support Tor from Brave browser

### ISSUE THREAD

**Issue by damascene** [Electron-Cash/Electron-Cash#1555]
Brave browser is becoming more popular nowadays, it has[ Tor built in](https://brave.com/tor-tabs-beta/) so you can open private tab that uses Tor. It would be nice if the wallet could detect Tor from brave and use it for traffic. Users wouldn't need to download separate Tor browser or to setup Tor manually.

Currently it's using port:9350 for tor tabs. You can already setup it manually in the wallet but could be useful for some people to have the option to use it directly.

**Comment by imaginaryusername** [comment]
I just checked, with Tor Private Tab open port 9350 does not work. Port 9050 works, but that's just my system's own Tor proxy.

**Comment by damascene** [comment]
> I just checked, with Tor Private Tab open port 9350 does not work. Port 9050 works, but that's just my system's own Tor proxy.

Did you check if your is listening to  a different port?
`#lsof -i -P -n | grep LISTEN`

**Comment by imaginaryusername** [comment]
>#lsof -i -P -n | grep LISTEN

After some fiddling I was able to make it work over 9350, seems like there are two private modes, and you gotta pick the right one. 

That said, I'll recommend putting this off for now, for the following reasons:

1. There is no proxy and bridge settings, unlike most other Tor implementations: https://github.com/brave/brave-browser/issues/1138

2. Settings page seems to be entirely empty: https://community.brave.com/t/make-a-tor-configuration-page/27114

3. There's no documentation in general on using Brave private window as a Tor proxy. Undocumented features that do not show up anywhere in the UI tends to break.

I think this should be revisited in the future when Brave offcially start supporting its Tor client as a proxy.

**Comment by cculianu** [comment]
Apparently Brave browser requires kyc or something. Closing

https://www.reddit.com/r/btc/comments/ck56zw/privacy_focused_brave_browser_now_requires_kyc/
