### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'send'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1560]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/Users/calin/src/ec/ec-slp/gui/qt/slp_add_token_dialog.py", line 184, in download_info
    self.network.send(requests, callback)

AttributeError: 'NoneType' object has no attribute 'send'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.4.15  | 3.6.8 (default, Dec 30 2018, 13:01:55)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-17.7.0-x86_64-i386-64bit | slp_standard | en_US | 

Additional Information
------------------------

> Calin here. In EC SLP.  Ran wallet in offline mode, tried adding a token, hit Download. Explodey time.
> 
> Note that self.network is None  when in offline mode.  All code needs to check this when doing stuff with self.network.
> 
> Add token dialog should actually detect offline mode and complain to user and not even allow them to hit the "Download" button.

---

**Comment by cculianu** [comment]
@jscramer Note this was run in `--offline` mode.  User should probably be presented with the "Electron cash is in offline mode bla bla" dialog when they try to add a token in offline mode.

**Comment by jcramer** [comment]
@cculianu I think we can close this with the above to commits.  Just want to check that you are ok with the code, it Is just checking `if not self.network` condition before displaying the offline message:

`You are using Electron Cash in offline mode; restart Electron Cash if you want to get connected`

**Comment by cculianu** [comment]
@jcramer I commented on one of the commits -- what was done is fine but perhaps we'd rather not hard-code that text in 16,000 places all over the app. It's better to have it in 1 place, maybe, this way updating it later is easier.

So I suggested the utility function in gui_object be called that encapsulates this logic.. Up to you to update it.

Either way this can be closed.

**Comment by jcramer** [comment]
@cculianu comment incorporated, thanks
