### ISSUE TITLE
Why does Electron Cash still generate Electrum seeds and not BIP39 seeds?

### ISSUE THREAD

**Issue by lugaxker** [Electron-Cash/Electron-Cash#1570]
Hello, 

Electrum and Electron Cash have a different kind of seed than the one used by most wallets (BIP39). Why does Electron Cash still use this different standard by default and not the BIP39 standard? Is there a good reason?

When I create a wallet on Electron Cash, I would like to be able to import it elsewhere (e.g. on my phone wallet).

**Comment by fyookball** [comment]
Eventually we will move to BIP39.  We inherited the Electrum seed format from BTC and although it has its advantages, we see the value of moving to a unified format for the ecosystem.  As it is now, you cannot import your Electrum/Electron Cash seed to another wallet.  However, you can do the reverse.

You can read more about the history of the seed format here:

http://docs.electrum.org/en/latest/seedphrase.html

**Comment by lugaxker** [comment]
Ok! I wanted to generate a BIP39 phrase earlier, and I was surprised to see I couldn't do this with Electron Cash.

**Comment by cculianu** [comment]
Yeah just to add to this: it's very much a high priority for us to make BIP39 seeds "first class citizens" for Electron Cash. They already are for the SLP version.  We will do this very soon. It's one of the high priority items.
