### ISSUE TITLE
CashShuffle: Failed to resolve SSL certificate?

### ISSUE THREAD

**Issue by ShadowOfHarbringer** [Electron-Cash/Electron-Cash#1581]
CashShuffle does not seem to be working at all today.

When I try to connect to multiple server, none of them is operational.

shuffle.servo.cash: Failed to verify SSL certificate error
shuffle.electroncash.dk: Failed to verify SSL certificate error
cashshuffle.net: Connection failure

Is this normal or is some kind an attack happening on cashshuffle servers?

Did not try the .onion servers, because on my VM i don't have TOR configured currently.

**Comment by ShadowOfHarbringer** [comment]
System: Linux Mint 18.3
Electron cash version: 4.0.6, 4.0.9 (AppImage)

(Almost Clean VM with Mint installed, not any kind of weird setup)

**Comment by fyookball** [comment]
Tried, cross checked with multiple people, cert on servo.cash is fine. Are you sure your OS and connection is fine? Is the expired cert cached somewhere?  To double check where the problem might be, navigate manually in your browser to https://shuffle.servo.cash:8080/stats. Does the certificate look good?

**Comment by ShadowOfHarbringer** [comment]
Yeah, the OS was not fine apparently.

The VM must have been broken in some way, maybe python version or something in python that processes SSL certificates? (I did not change or install anything, so that's weird AF anyway).

I just checked on the base/host system and it works.

Closing issue.

**Comment by EchterAgo** [comment]
I just checked in a clean Mint 18.3 VM and it works fine with AppImage. How did you install EC?

**Comment by EchterAgo** [comment]
Just noticed you also used AppImage, making our environments almost identical. Any chance the clock could have been off by a year or so?

Ideally we should be giving the user some more information when SSL verification fails as it can be caused by multiple things, for example time constraints, untrusted CA, revokation, hostname mismatch, etc...

**Comment by ShadowOfHarbringer** [comment]
> Any chance the clock could have been off by a year or so?

Not a chance, I checked this first.

However, I use different DNS settings on the VM and on the host. Maybe that was the case.

But I used dig and ping and everything seemed to be the same. This is weird AF.

> Just noticed you also used AppImage, making our environments almost identical. 

My Mint was not updated with latest patches. Maybe Python fixed some SSL security issues lately?
