### ISSUE TITLE
imaginary.cash Testnet server seems to be on another fork.

### ISSUE THREAD

**Issue by theblains** [Electron-Cash/Electron-Cash#1590]
Hi,

It seems the testnet sever may be on another fork? Does anyone know how to contact the operator?

https://1209k.com/bitcoin-eye/ele.php?chain=tbch

Thanks

**Comment by EchterAgo** [comment]
imaginaryusername

**Comment by EchterAgo** [comment]
@imaginaryusername

**Comment by imaginaryusername** [comment]
Indeed it's on another fork. You're welcome to join the November 2019 fork testnet if you feel like it! 

Perhaps I should put it in banner text.

**Comment by theblains** [comment]
> Indeed it's on another fork. You're welcome to join the November 2019 fork testnet if you feel like it!
> 
> Perhaps I should put it in banner text.

@imaginaryusername that clears that up! How do I switch over? Thanks

**Comment by imaginaryusername** [comment]
https://github.com/bitcoincashorg/bitcoincash.org/blob/master/workgroups/wg-testing/2019-11-15_upgrade_testnet.md

**Comment by cculianu** [comment]
Closing this issue...
