### ISSUE TITLE
Add option to eliminate coin by donating to miner

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#1597]
For spams that are very small ( < 731 bytes), not even the [Donate Spare Change](https://github.com/cculianu/DonateSpareChange) plugin can deal with them; they will likely either remain there forever, or have to be combined with another coin when spent together, creating a privacy problem. 

One way to deal with them may be to create a one-in-one-out transaction where the output is a minimal op_return (for example, pushing 1 byte), therefore "donating" any excess output to the miner and net eliminating one UTXO. To ensure safety, this can be limited to, for example, only outputs below 1000 bytes. Operations can be further automated by way of additional options in the Donate Spare Change plugin.

**Comment by cculianu** [comment]
Yeah I mean can be easily added. So would this be a right-click option that appears only for coins <= 1000 satoshi's or what?  This is like an uber power feature only 0.0001% of people will even notice I bet but can be done.  I sort of dislike menu options that "appear magically" in only certain contexts.. but showing "donate to miner" for eg 12.56 valued coins has the potential to cause damage... so idk what to do there.

**Comment by cculianu** [comment]
It could then just be a part of DonateSpareChange and not touch the main codebase. That's easily done.
