### ISSUE TITLE
Querying a bad address with ismine causes daemon to crash

### ISSUE THREAD

**Issue by markmeson** [Electron-Cash/Electron-Cash#1600]

**Comment by cculianu** [comment]
It doesn't cause it to crash. It just raises an exception and returns an error to the client. The daemon continues to run normally and you can keep sending it commands afterwards.

It's how the daemon works on bad inputs -- shows a stack trace, returns an error.. keeps on keeping on.

Please provide more information if you believe it actually crashed.
