### ISSUE TITLE
ValueError: could not convert string to float: 

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1627]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/home/mary/files/electron_SLP/gui/qt/main_window.py", line 1381, in save_payment_request
    amount = float(self.receive_slp_amount_e.text())

ValueError: could not convert string to float: 
```

Reporter
------------

This issue was reported by 5 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.5.1  | 3.6.8 (default, Jan  3 2019, 03:42:36)  [GCC 8.2.0] | Linux-4.19.0-5-amd64-x86_64-with-debian-buster-sid | slp_standard | en_US | 
| 3.5.1  | 3.6.8 (default, Jan  3 2019, 03:42:36)  [GCC 8.2.0] | Linux-4.19.0-5-amd64-x86_64-with-debian-buster-sid | slp_standard | en_US | 
| 3.6.1  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | slp_imported_addr | de_DE | 
| 3.6.3  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | slp_standard | en_US | 
| 3.6.3  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | slp_standard | en_US | 

Additional Information
------------------------

> In Receive Tab, select token type SPICE, Type Address Description, then click SAVE

---

> BABY636@OUTLOOK.DE

---

> set Required expires to 1 day from default and got Sorry message

---

> tried to save slp description and got Sorry message

---

**Comment by cculianu** [comment]
@jscramer ...

**Comment by ProfessorVenkman** [comment]
Good morning @jcramer,

I just received another crash report related to this issue. The crash occured on Electron Cash 3.6.5.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 3.6.3 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
  File "site-packages\electron_cash_slp-3.6.5-py3.6.egg\electroncash_gui\qt\main_window.py", line 1495, in save_payment_request

ValueError: could not convert string to float: 
```


~ _With robotic wishes_
