### ISSUE TITLE
Disable sending to 3xx legacy addresses

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#1658]
It seems like sending BCH to segwit addresses continue to be a problem, and people are still losing money depositing to legacy-only exchanges, resulting in loss of funds when amount is small and much trouble recovering when amount is large. Disabling sending to 3xx legacy addresses in the send tab would be a sensible approach (i.e. all p2sh should be pxxx). Address translator exists for people who really, really need to send to multisig but somehow cannot fetch them in cashaddr.

One possible UI would be to blanket ban any string that starts with "3" at preview/send, but instead of "invalid lines found" as in other invalid cases, display "possible Segwit legacy address - you may lose funds" instead.

**Comment by cculianu** [comment]
3xxx is also multisig now? Don't some people that use multisig still use Legacy?

**Comment by imaginaryusername** [comment]
normal P2PKH is recoverable, but segwit is only recoverable by nonstandard mining... am assisting one such guy right now. Freaken Bitstamp I tell ya...

**Comment by cculianu** [comment]
Bitstamp gave him a SegWit address to send to on BCH chain?  Or user after 3 years still doesn't know BCH != BTC??

**Comment by imaginaryusername** [comment]
It was a mistake, which happens when we get enough numbers of user. Minimizing the potential for such mistakes is a good thing.

Not saying this is something that absolutely needs to be fixed today, but we did discuss this before, and sending to legacy 3xxx is just a thing people don't do for legit reasons anymore, and I think the potential for fund loss/freeze now vastly outweighs it.

**Comment by cculianu** [comment]
So what should the logic be? If user inputted legacy format p2sh, warn them?  I can have it "remember" their choice for that particular address. This way they get nagged each time.  Can make it so they have to check a checkbox saying "definitely not a BTC segwit I am sure" before they can hit ok...

**Comment by imaginaryusername** [comment]
That sounds like a great way to do it if you don't mind that it's more work :)

**Comment by BigBlockIfTrue** [comment]
Note: this is a duplicate of #1225 .

**Comment by cculianu** [comment]
Yep, it is.  Ok maybe I'll take care of this today.

**Comment by cculianu** [comment]
Ok, this is the error dialog. It's a simple all-stop refusing to allow the user to proceed if it detects any '3' p2sh. It just advises the user to use cashaddr for p2sh if it sees '3'-style p2sh.

I'm about to commit this.  Works in all possible cases I can think of.

<img width="957" alt="Screen Shot 2019-11-04 at 12 33 59 PM" src="https://user-images.githubusercontent.com/266627/68114755-7ab04a00-feff-11e9-8a43-9b496fd2a782.png">


---

Settings:

<img width="536" alt="Screen Shot 2019-11-04 at 12 34 22 PM" src="https://user-images.githubusercontent.com/266627/68114765-80a62b00-feff-11e9-8360-f15b9f1fc70b.png">

**Comment by imaginaryusername** [comment]
@Gitcash send 0.05 BCH to @cculianu

**Comment by imaginaryusername** [comment]
trying again: @Gitcash send 0.05 BCH to @cculianu

**Comment by GitCash** [comment]
Hey **cculianu**, user **imaginaryusername** tipped you **50000 bits** in Bitcoin Cash ( ~ **$14.35** ).

*[Click here to claim it!](https://gitcash.io/claim/cculianu)*

You can also add the "thumbs down" reaction to **imaginaryusername**'s comment above to prevent future tips.
