### ISSUE TITLE
CLI: no data for fiat balances

### ISSUE THREAD

**Issue by Ferrous256** [Electron-Cash/Electron-Cash#1671]
I'm trying to get the wallet history via the CLI and it's not displaying fiat balances. I'm running up-to-date Ubuntu 18.04.3 LTS

First, I'm not sure exactly what this error is telling me, but when I open the gui from terminal I get:
```
./Electron-Cash-4.0.10-x86_64.AppImage
OpenType support missing for "Ubuntu", script 16
```
In the GUI, after selecting "USD" for the fiat currency, selecting "show history rates", and selecting  "show fiat balance for addresses", I still cannot get fiat balances to appear when issuing the command:

`./Electron-Cash-4.0.10-x86_64.AppImage history -w [path-to-wallet] --show_fiat`

In the "Fiat Balance:" and "Fiat Value" fields it says "no data". It works if I export via the GUI, but in my application I need it to output pure JSON data with the fiat values from the CLI.

It's a multi-sig 3 of 6 watch-only wallet, if that makes a difference. I've tried 4.0.10, 4.0.9, 4.0.8 and 4.0.7 with no luck. Any help is greatly appreciated!

**Comment by cculianu** [comment]
Yep. You're right. I just pushed a commit to fix this.  The code wasn't initializing the "fx" object correctly and thus no data.  Fixed in latest git master.

Note we are doing a release soon (hopefully later this week) so the fixed version should be out soon.  If you can't wait -- you can try running fro sources off github (requires Python env to be set up correctly and have PyQt5, etc).

**Comment by Ferrous256** [comment]
Can you make it display the fiat rate as well? That would help. Also, every once in a while, it still displays "No data" on some of the more recent transactions even though I can see the fiat rate in the GUI. 

In my wallet I can see correct fiat values for all transactions before 2019-11-08, but anything more recent than that it displays "No data".

I'm running the history command every couple minutes to display a "live" view of the wallet balance. I can't seem to replicate when it does this. I just know it happens every so often.

**Comment by cculianu** [comment]
Hey man -- hmm yeah the thing is the FX subsystem relies on going out to network each time and it's.. not designed to be re-used in this context.  If I actually did it right I would have it wait for 1-5s tops while it does its own thing going out to the network.  Right now the FIAT values are cached values when you run it.  The design of the FX subsystem assumed it could go out to the network and grab data.

If you want I can make it hit the network with a 5s timeout (if it doesn't grab data in 5s, it proceeds anyway with cached values as you have now).  Would such a timeout be acceptable?

It bugs me too that it doesn't always get the data TBH and I'd like to do it this way but I wasn't sure if introducing the timeout was worth it.

As for adding fiat_fee -- that can be easily done as well.  I'll add that as a separate field (if the fee is known).

**Comment by cculianu** [comment]
Ok, this has been addressed in #1682 .  Pull latest git and try it out. There are a couple of new CLI options for `history` .. do `electron-cash history -h` to see them.

- Fee (if known) will also include a fiat amount for the fee
- CLI waits for fx thread for `--timeout` seconds (default 30.0) to grab FX data. Note it may still fail. FX is strange.
- Added `--use_net` option which can try and fetch more fee information from the network (it will be slower though) to get fee data on tx's with inputs not even belonging to wallet
- GUI has been updated to allow export history to take advantage of the above features.

**Comment by Ferrous256** [comment]
Thank you. I will test it out on Monday and report back.

**Comment by Ferrous256** [comment]
I wanted to wait for a transaction to go through to make sure it stays up-to-date. Everything seems to be running perfectly, so thank you very much! I do have one additional question though - how is the BCH price determined? I know it gets one value from either coinCap or coinGecko, but is it an average price for the day, or a specific time of day?

**Comment by fyookball** [comment]
it gets the real time spot price from whatever source is chosen.

**Comment by cculianu** [comment]
@Ferrous256 I have no idea how CoinGecko or CoinCap determine price -- I assume they take an weighted average of the major exchanges or even of all the exchanges (weighted based on volume for each exchange).  That's typically the way it's done in traditional finance.  I think to really find out you'd have to hit CoinGecko or CoinCap's sites and read their "About" or whatever pages and see how they determine the price.

We simply download the price from them and repeat it verbatim to you. So it's up to their policy.
