### ISSUE TITLE
Once user opts out of crash reporter -- no way to bring it back

### ISSUE THREAD

**Issue by cculianu** [Electron-Cash/Electron-Cash#1672]
@markblundeberg encountered this.  He may have mistakenly clicked the "don't show me crash reporters" button on the crash reporter.. and didn't realize it months later he was wondering where the crash reporter went.

We definitely want as many crash reports as possible from users.  I would go so far as to say the "don't show me again EVER" button is a bad idea.  Either:

1. We make the decision on per-exception encountered or something nuts (like save a list of exceptions  seen to config and key them based on bottom of the stack trace/line number).  And so the decision is PER exception. (This one is complicated).

OR

2. Make the decision be temporary. Like 1 day and then the crash reporter returns.

OR

3. Make the opt-out only happen explicitly if user goes to preferences to disable it.  This ensures they know how to bring it back later.

I think the behavior that we get when the reporter is gone -- which is in many cases either a hard app exit or a stack trace printed on console -- is not helpful to us or users.

We want to encourage these reports.  And users are often better off seeing the crash reporter than getting a hard crash-to-desktop.

**Comment by fyookball** [comment]
number 3 seems fine to me
