### ISSUE TITLE
Is it possible to include transaction fees in the history output?

### ISSUE THREAD

**Issue by Ferrous256** [Electron-Cash/Electron-Cash#1679]
The electrum wallet has a flag for the history function "--show_fees" that breaks out the fees associated with each transaction. Having this added to the electron-cash wallet would be incredibly beneficial.

**Comment by cculianu** [comment]
Can be added. Note that it may not always know the fees unless it is the one that generated the transaction. The reason for that is it can't figure it out without examining all the "prevout" tx's for each input.. which it can't easily do unless the tx's belong to the wallet itself.

So it may be missing for tx's originating outside the wallet -- but it will be accurate for tx's where all inputs come from the wallet.

Does that make sense?  I believe Electrum has this limitation as well.

Can be added tho.

**Comment by Ferrous256** [comment]
Yes, it appears electrum only reports fees if it's a transaction outgoing from the wallet, which is the only thing I am concerned about displaying for accounting purposes (need to know how much I paid the other party vs. how much I paid in fees).

If I understand correctly, all outgoing tx's would have to originate from the wallet itself, right?

Just displaying those would be hugely beneficial.

**Comment by Ferrous256** [comment]
I think I was misunderstanding you. You mean if I were to use bitcoin.com's wallet to send BCH, then say if the electron-cash wallet were set-up as a watch wallet only, it would not easily be able to determine the fees?

The electrum wallet does not have this limitation.

**Comment by cculianu** [comment]
No, no that would work, if you were watching-only.  It doesn't matter which wallet physically sent it -- it has to be a set of addresses your wallet is "closely monitoring" (the wallet in EC & Electrum can't download ALL the tx's -- just the ones it is interested in, is the reason -- it needs to see the previous tx's to know the fee).. 

Short answer: It would be just like Electrum, basically..

**Comment by Ferrous256** [comment]
If that feature could be included like Electrum, I would be eternally grateful.

**Comment by cculianu** [comment]
You got it man. Just pushed a commit that does exactly what you want.  This was a good suggestion as I am sure others would find this functionality useful.

If you want to see it in action pull latest git and run from source.

**Comment by Ferrous256** [comment]
This seems to go a step further and display the fee associated with transactions coming into the wallet. Either way, the more info the better. This works great! Thank you very much!

**Comment by cculianu** [comment]
Yeah I tried to make it look at it’s caches too. It may actually do more than electrum now.
