### ISSUE TITLE
negative balance shown in tx history due to wrong sort order

### ISSUE THREAD

**Issue by molecular** [Electron-Cash/Electron-Cash#1703]
![2019-11-26-215851_1544x980_scrot](https://user-images.githubusercontent.com/589745/69672332-2e889d80-1098-11ea-94af-b610ab24359a.png)

The two transactions shown in the screenshot are ordered backwards, hence a negative balance is shown in the history.

I openend the 2 tx details dialogs to show that the second tx (first in the list) actually spends and output of the first one (second in the list). Maybe this could be used as an additional sorting criteria (after block height or whatever is used primarily)?

**Comment by cculianu** [comment]
Yep. This is as intended. CTOR.  Transactions on the blockchain are sorted lexically by their txid. `33b4...` sorts before `4803...`.  So in Electron Cash you get a temporary negative balance if 2 tx's appear on the same block that reference each other and that are out of order.

We don't bother figuring out the natural order of tx's in your history.  Doing so in Python would slow down the history refresh tremendously.  Most people aren't too bothered.  At the end of all the tx's you end up with the right balance (topmost balance is correct, always).

Think of it a little bit like quantum physics -- the universe may "borrow" energy to create virtual particles temporarily but at the end of it all energy is conserved locally.

👍

**Comment by molecular** [comment]
ok, fine with me.
