### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1713]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "Electron_Cash-4.0.11-py3.6.egg/electroncash_gui/qt/util.py", line 896, in on_done
  File "/var/folders/vn/dm0jswh13lbd53p7p1ycbkbm0000gn/T/_MEI66avfF/electroncash_plugins/satochip/qt.py", line 188, in change_pin
    oldpin= list(oldpin)

TypeError: 'NoneType' object is not iterable
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.11  | 3.6.9 (default, Aug 17 2019, 12:35:02)  [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] | Darwin-18.5.0-x86_64-i386-64bit | standard |  | 

Additional Information
------------------------

> Another bug using Satoship wallet, to repro: click the Satochip logo in the lower right corner, then click "Change PIN", then click "Cancel".

---

**Comment by cculianu** [comment]
Oh wow thanks for this -- will investigate.
