### ISSUE TITLE
ValueError: Single '}' encountered in format string

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1718]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/tmp/.mount_ElectrI2yNs6/usr/lib/python3.6/site-packages/electroncash_gui/qt/main_window.py", line 3477, in toggle_ww_txt
    set_ww_txt(link=="show")
  File "/tmp/.mount_ElectrI2yNs6/usr/lib/python3.6/site-packages/electroncash_gui/qt/main_window.py", line 3468, in set_ww_txt
    + '</b></font> <a href="hide">{link}</a>').format(link=_("Hide"), monoface=MONOSPACE_FONT)

ValueError: Single '}' encountered in format string
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.11  | 3.6.9 (default, Jun 28 2018, 19:01:02)  [GCC 5.4.0 20160609] | Linux-5.3.8-3-MANJARO-x86_64-with-arch-Manjaro-Linux | standard | en_DK | 

Additional Information
------------------------

> I was trying to export my private keys, and when the window displayed the BIP38 encrypted keys, I clicked on "Click to show"(passphrase) above them.

---

**Comment by cculianu** [comment]
Looks like a translator messed up...?

**Comment by cculianu** [comment]
Yeah bug in how we used format strings.  User has a '}' in his password.  Fixing now.
