### ISSUE TITLE
[Satochip] EC crashes when using Satochip to sign tx with 2FA enabled

### ISSUE THREAD

**Issue by Toporin** [Electron-Cash/Electron-Cash#1734]
Currently getting an error with Satochip 2FA. Regular non-2FA works fine, I can send and receive fine. But when I enable 2FA and attempt to send and it triggers the 2FA I get this error:
```
Traceback (most recent call last):
  File "/var/folders/ls/yjq_rz6s7f1dq4nqm5tsrnx00000gn/T/_MEIsQOdS2/electroncash_plugins/hw_wallet/qt.py", line 164, in error_dialog
    self.win.show_error(msg, parent=self.top_level_window())
  File "Electron_Cash-4.0.12-py3.6.egg/electroncash_gui/qt/util.py", line 228, in show_error
  File "Electron_Cash-4.0.12-py3.6.egg/electroncash_gui/qt/util.py", line 299, in msg_box
RuntimeError: wrapped C/C++ object of type QMessageBoxMixin has been deleted
 
```
Additional information:
```
Electron Cash version: 4.0.12 
Python version: 3.6.9 (default, Aug 17 2019, 12:35:02) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] 
Operating system: Darwin-18.7.0-x86_64-i386-64bit 
Wallet type: standard 
Locale: None
```

**Comment by Toporin** [comment]
To reproduce the error:
- Use a Satochip hardware wallet with 2FA enabled.
- To trigger the issue, the 'satochip 2FA' plugin **must be deactivated**: this will produce a pop-up error message signaling that the plugin should be enabled in 'tools > optional features'.
- When closing the popup, EC crashes.

**Comment by cculianu** [comment]
OK well I managed to "fix" the bug by making the lib code it calls into in util.py more resilient to the situation.

However I think the core problem remains -- somehow error messages are spammed and the previous windows get killed before they return.

Anyway this latest commit "fixes" it in that users will at least not observe any problems....
