### ISSUE TITLE
Claiming BSV

### ISSUE THREAD

**Issue by srkisrki** [Electron-Cash/Electron-Cash#1766]
Dear Colleagues,

I have been following these instructions from Trezor to claim my BCH SV - https://wiki.trezor.io/How_to_split_and_send_your_Bitcoin_Cash_forks

It says that I should "connect to a server serving the longer chain. Currently, this is ABC. 
9. Send all your funds to the fresh address you labeled ABC. - (_I did that_.)

11. Connect to a server serving the shorter chain, currently SV.

However, I am  not able to find servers serving the SV chain. 

Is there a way to solve this problem and successfully claim BCH SV coins?

Thank you!

**Comment by EchterAgo** [comment]
Trezors instructions are outdated. Current Electron Cash can not connect to the BSV chain anymore. You've already moved your BCH, so I'd recommend using [Electrum SV](https://electrumsv.io/) to send your BSV.

**Comment by srkisrki** [comment]
Thank you EchterAgo! Are there any instructions how to do it?
