### ISSUE TITLE
TypeError: restart_cashshuffle() missing 1 required positional argument: 'window'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1783]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/Users/calin/src/ec/electron-cash/plugins/shuffle/qt.py", line 1082, in try_to_apply_network_dialog_settings
    parent = Plugin.network_dialog)

TypeError: restart_cashshuffle() missing 1 required positional argument: 'window'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.13  | 3.6.10 (default, Dec 21 2019, 11:40:12)  [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] | Darwin-18.7.0-x86_64-i386-64bit | standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
This was me refactoring cashshuffle, I accidentally hit "send report".  Closing.
