### ISSUE TITLE
CashFusion UI Network dialog

### ISSUE THREAD

**Issue by acidsploit** [Electron-Cash/Electron-Cash#1784]
1. Move cashfusion network dialog to a Network window tab, just like CashShuffle.
2. When enabling integrated to through notification wizzard, on success it instructs you on how to monitor status. Add a button to, or automatically open the network window.

**Comment by cculianu** [comment]
Ok, item (2) above has been addressed in commit  e29e2cc

Item (1) above will need a little more work so I may do it later today or this weekend.

**Comment by cculianu** [comment]
This has now been fully addressed in f586e71
