### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'to_ui_string'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1788]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-4.0.12-py3.6.egg\electroncash_gui\qt\main_window.py", line 1446, in update_receive_qr

AttributeError: 'NoneType' object has no attribute 'to_ui_string'
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.12  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-7-6.1.7601-SP1 | standard,imported_privkey,imported_addr | th_TH | 
| 4.0.12  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-7-6.1.7601-SP1 | standard,imported_privkey,imported_addr | th_TH | 

Additional Information
------------------------

> 0xfb1b6e9b882de4a15fc3e4daa4d57a2afe77b494

---

> 1JoeSHthR3M49Wd4CpWcDt6aopnGJfDLjt

---

**Comment by cculianu** [comment]
This is related to #1789  -- the user had a wallet with 0 addresses in it.

However the fact that this function doesn't check if `self.receive_address` is valid is a programming error -- since the class does initialize this variable to `None` on construction and it clearly can end up as `None`.

**Comment by ProfessorVenkman** [comment]
Good morning @cculianu,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.4.3.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.0.12 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
  File "/tmp/.mount_Electr7kOAcu/usr/lib/python3.11/site-packages/electroncash_gui/qt/main_window.py", line 1691, in update_receive_qr
    uri = web.create_URI(self.receive_address, amount, message, token=self.qr_use_token_address, **kwargs)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'ElectrumWindow' object has no attribute 'qr_use_token_address'
```


~ _With robotic wishes_

**Comment by ProfessorVenkman** [comment]
Good evening @cculianu,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.4.4.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.4.3 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
  File "electroncash_gui/qt/main_window.py", line 1691, in update_receive_qr

AttributeError: 'ElectrumWindow' object has no attribute 'qr_use_token_address'
```


~ _With robotic wishes_

**Comment by ProfessorVenkman** [comment]
Good morning @cculianu,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.4.5.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.4.4 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
  File "/Users/calin/src/ec/electron-cash/electroncash_gui/qt/main_window.py", line 1691, in update_receive_qr
    uri = web.create_URI(self.receive_address, amount, message, token=self.qr_use_token_address, **kwargs)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'ElectrumWindow' object has no attribute 'qr_use_token_address'
```


~ _With robotic wishes_
