### ISSUE TITLE
AttributeError: 'LoadRWallet' object has no attribute 'network'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1790]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/home/karol/.electron-cash/external_plugins/inter-wallet-transfer.zip/inter-wallet-transfer/ui.py", line 95, in showEvent
    if not self.network and self.isEnabled():

AttributeError: 'LoadRWallet' object has no attribute 'network'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.12  | 3.8.1 (default, Dec 21 2019, 20:57:38)  [GCC 9.2.0] | Linux-4.19.95-1-lts-x86_64-with-glibc2.2.5 | 2of2 | pl_PL | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by KarolTrzeszczkowski** [comment]
sorry, it was me

**Comment by cculianu** [comment]
:)
