### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:/Users/mbalolong/Documents/May Balolong/electron-cash-history.csv'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1799]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-4.0.12-py3.6.egg\electroncash_gui\qt\util.py", line 921, in on_done
  File "site-packages\electron_cash-4.0.12-py3.6.egg\electroncash_gui\qt\main_window.py", line 3753, in on_success

PermissionError: [Errno 13] Permission denied: 'C:/Users/mbalolong/Documents/May Balolong/electron-cash-history.csv'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.12  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.14393-SP0 | imported_addr | en_PH | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
User just has weird permissions issues.  It happens.

**Comment by ProfessorVenkman** [comment]
Good afternoon @cculianu,

I just received another crash report related to this issue. The crash occured on Electron Cash 4.2.4.
I'm not sure which versions of Electron Cash include the fix but this is the first report from anything
newer than 4.0.12 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
  File "electroncash_gui\qt\util.py", line 980, in on_done
  File "electroncash_gui\qt\main_window.py", line 3801, in on_success

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\huber/electron-cash-history.csv'
```


~ _With robotic wishes_
