### ISSUE TITLE
How to claim BSV (from the BCH fork in 2018)?

### ISSUE THREAD

**Issue by HeRo002** [Electron-Cash/Electron-Cash#1803]
Hi! 4 months ago I tried to claim my BSV from the fork of BCH in 2018. 
My BCH is in a Trezor wallet, so I tried to follow guides from their website and others. But it all led to dead ends. 
In the end, the Trezor.io support asked me "to get in touch with the Electron support team." 
Is this github forum 'the Electron support' or is it https://t.me/electroncashwallet (on Telegram)?
My concrete problem was that the Trezor document - https://wiki.trezor.io/How_to_split_and_send_your_Bitcoin_Cash_forks - asked me to install Electron Cash and find an SV server, but I couldn't see which servers were BSV servers.
So I feel quite lost.

**Comment by cculianu** [comment]
How nice of a for-profit business to offload some of their work onto us, a volunteer project.  Very cool.

If you want, come into the Telegram channel and somebody will help you do a split.  I'm closing this issue now because this issue tracker is more geared towards issues with the software rather than support with other cryptocurrencies.

Do come into the channel: https://t.me/electroncashwallet

**Comment by HeRo002** [comment]
Hi cculianu! Thank you!

**Comment by levis2t** [comment]
Hola, por favor me puedes pasar los pasos para poder reclamar los bsv, también tenía los BTC Cash en Trezor... Agradezco si puedes ayudarme.

**Comment by HeRo002** [comment]
In the Telegram channel I was pointed to this guide:

https://read.cash/@sploit/quick-guide-to-splitting-your-bch-and-bsv-with-electron-cash-53894a80

But I have not yet finished the procedure, so I can't tell if it will work for me. :-)

**Comment by drnick30** [comment]
Are you still having issues with this?

**Comment by HeRo002** [comment]
After asking several questions in the Telegram Channel and receiving a small amount of already split BCH from someone, I finally managed to split my BCH and thus claim the BSV. But I think it was the most complex crypto-procedure I have been through.
