### ISSUE TITLE
AttributeError: 'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1806]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\transaction_dialog.py", line 835, in on_context_menu_for_outputs

AttributeError: 'list' object has no attribute 'split'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.6.1  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | slp_imported_addr | de_DE | 

Additional Information
------------------------

> BABY636@OUTLOOK.DE

---

**Comment by jcramer** [comment]
I fixed SLP edition, but it seems like it should be fixed in mainline also.

**Comment by cculianu** [comment]
Ah ok. Thanks. Fixed in master & cashfusion branches.
