### ISSUE TITLE
ImportError: cannot import name 'seed_type'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1808]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/Users/calin/src/ec/electron-cash/gui/qt/seed_dialog.py", line 187, in on_edit
    from electroncash.bitcoin import seed_type

ImportError: cannot import name 'seed_type'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.1.0  | 3.6.10 (default, Dec 21 2019, 11:40:12)  [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] | Darwin-18.7.0-x86_64-i386-64bit | standard | en_US | 

Additional Information
------------------------

> ad

---

**Comment by cculianu** [comment]
This was me messing around with new code. Invalid.
