### ISSUE TITLE
java.lang.RuntimeException: Unable to create application org.electroncash.electroncash3.App: com.chaquo.python.PyException: Traceback (most recent call last):

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1812]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback

java.lang.RuntimeException: Unable to create application org.electroncash.electroncash3.App: com.chaquo.python.PyException: Traceback (most recent call last):
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.11-0  | java.lang.IllegalStateException: Python startup previously failed, and cannot be retried | Android 7.1.2 on google G011A (G011A) | unknown | en_US | 
| 4.0.14-0  | java.lang.IllegalStateException: Python startup previously failed, and cannot be retried | Android 5.1.1 on vivo vivo X7 (PD1602) | unknown | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
No reports in the last 6 months since moving to Chaquopy version 9.
