### ISSUE TITLE
KeyError: 'کپی'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1820]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash_slp-3.6.1-py3.6.egg\electroncash_gui\qt\address_list.py", line 231, in create_menu

KeyError: 'کپی'
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.6.1  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.17134-SP0 | slp_standard | fa_IR | 
| 3.6.1  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.17134-SP0 | slp_standard | fa_IR | 

Additional Information
------------------------

> please it crash when click on the number wallet

---

**Comment by EchterAgo** [comment]
Fixed: https://crowdin.com/translate/electron-cash/532/en-fa#25886
