### ISSUE TITLE
"cannot pair trezor" with Electron-Cash-4.1.0-fusion

### ISSUE THREAD

**Issue by molecular** [Electron-Cash/Electron-Cash#1825]
using Electron-Cash-4.1.0-fusion-1-74-g12dd3338e-x86_64.AppImage I cannot pair my trezor.

```
Traceback (most recent call last):
  File "/tmp/.mount_Electr481Czl/usr/lib/python3.6/site-packages/electroncash_gui/qt/util.py", line 949, in run
    result = task.task()
  File "/tmp/.mount_Electr481Czl/usr/lib/python3.6/site-packages/electroncash/wallet.py", line 2469, in sign_message
    return self.keystore.sign_message(index, message, password)
  File "/tmp/.mount_Electr481Czl/usr/lib/python3.6/site-packages/electroncash_plugins/trezor/trezor.py", line 62, in sign_message
    client = self.get_client()
  File "/tmp/.mount_Electr481Czl/usr/lib/python3.6/site-packages/electroncash_plugins/trezor/trezor.py", line 56, in get_client
    return self.plugin.get_client(self, force_pair)
  File "/tmp/.mount_Electr481Czl/usr/lib/python3.6/site-packages/electroncash_plugins/trezor/trezor.py", line 185, in get_client
    client = devmgr.client_for_keystore(self, handler, keystore, force_pair)
  File "/tmp/.mount_Electr481Czl/usr/lib/python3.6/site-packages/electroncash/plugins.py", line 878, in client_for_keystore
    client = self.force_pair_xpub(plugin, handler, info, xpub, derivation, devices)
  File "/tmp/.mount_Electr481Czl/usr/lib/python3.6/site-packages/electroncash/plugins.py", line 923, in force_pair_xpub
    'receive will be unspendable.').format(plugin.device))
electroncash.plugins.DeviceUnpairableError: Electron Cash cannot pair with your Trezor.

Before you request bitcoins to be sent to addresses in this wallet, ensure you can pair with your device, or that you have its seed (and passphrase, if any).  Otherwise all bitcoins you receive will be unspendable.
```

I verified passphrase is correct by using older, non-cashfusion version (tried many times)

**Comment by molecular** [comment]
This also happens in master branch.

I tracked it down a little: tag 4.0.13dev1 ist still ok, in 4.0.13 the issue occurs.

**Comment by cculianu** [comment]
Wow that's helpful.  I'll try to reproduce here later and let you know.  If you don't hear back from me in a few days...  ping me again here!

**Comment by cculianu** [comment]
Just curious what Linux version/distro are you on?

**Comment by darkbluelight** [comment]
I think my issue is related to this. I cannot pair anymore my password protected Trezor wallets in 4.0.13. Those same wallets get paired fine with 4.0.11.

What I found out till now is that if I create a new Trezor wallet with 4.0.13 with the same Trezor password it creates DIFFERENT addresses than if I create it with 4.0.11. It doesn't matter if I choose m/44'/145'/0' or m/44'/0'/0' I'm never able to create the same BCH addresses with 4.0.13 that I got with 4.0.11.

I am still able to pair my 4.0.11 Trezor wallet that has NO password with 4.0.13. So the bug must have to do something with the implementation of the password in 4.0.13.

I'm using Linux Mint Debian (LMDE).

**Comment by molecular** [comment]
@darkbluelight thanks for chiming in. Sounds like the same issue. I also use a passphrase.

@cculianu I'm on arch linux. In case you need me to narrow the breaking change down to a single commit, I can do that with a little bit of time (logarithmic in the number of commits ;-)). Also PING ;-)

**Comment by cculianu** [comment]
If you could that would be helpful -- i'm a little backlogged so that would help @molecular !!

**Comment by cculianu** [comment]
@molecular You would have to use git bisect -- you know how to use it right?

**Comment by EchterAgo** [comment]
Start a git bisect like this:

```
git bisect start
git bisect bad v4.0.13
git bisect good v4.0.11
```
It should then tell you something like this:

```
Bisecting: 675 revisions left to test after this (roughly 10 steps)
```

This tells you how many revisions (changes) are between those two versions and an estimate of how many you will have to test to find the bad revision.

Now for every revision bisect stops at you have to test if the version works or not. So you need to set up a fresh python environment, start EC using it and check for the issue. When the current revision is good you exectute `git bisect good` and if it is bad you execute `git bisect bad`

Using this you should end up at the commit which introduced the issue in the minimum number of steps possible. When you do it should tell you something like `<revision> is the first bad commit"

See here for more information: https://git-scm.com/docs/git-bisect

**Comment by molecular** [comment]
Thanks @EchterAgo for the bisect refresher, it's been a long time...

this commit that made things go sour #d6a4d28279bf522a89b3d923b017d6076000c1b9

```
d6a4d28279bf522a89b3d923b017d6076000c1b9 is the first bad commit
commit d6a4d28279bf522a89b3d923b017d6076000c1b9
Author: Calin Culianu <calin.culianu@gmail.com>
Date:   Mon Feb 10 17:27:40 2020 +0200

    Refactor mnemonic.py; resurrect BIP39 seed generation
```

**Comment by darkbluelight** [comment]
@molecular thank you very much for taking the time to find the bug!
@EchterAgo thank you for your help with bisect!

**Comment by molecular** [comment]
@darkbluelight, well, I didn't "find the bug", just identified the commit that broke things.

From the looks of it I think it will probably quickly become apparent to @cculianu what the problem is when he sees the commit, though.

**Comment by cculianu** [comment]
Yeah -- it's probably a crash in the plugin due to API changes.  I could have sworn it was working and that I tested it but apparently I did not.  I'll let you know what I come up with.

**Comment by EchterAgo** [comment]
I'll also do some testing with Keepkey and Ledger.

**Comment by cculianu** [comment]
Thanks @EchterAgo

**Comment by molecular** [comment]
this persists in 4.1.0-fusion-2 (which I assume is most recent fusion tag?) and also master.

@cculianu  you said above I should ping you in case you forget this issue. Well: ping!

**Comment by EchterAgo** [comment]
Sorry for forgetting to test this. So Keepkey and Ledger still work fine and I did test this using the Trezor emulator, but I fail to reproduce this. Using the official AppImage of both 4.0.12 and 4.0.13 I made new wallets for a password protected Trezor and received the same addresses. I tried with 2 different passwords. Maybe it is password specific? Anyone mind sharing the password they are using? Also, what firmware version are you using?

**Comment by molecular** [comment]
@EchterAgo sorry, cannot share the passphrase. It has letters, numbers and some symbols, but nothing non-ascii or otherwise wild.

firmware is 1.8.3 (not the most recent, I admit)

**Comment by molecular** [comment]
upgraded firmware to 1.9.2, problem still occurs

**Comment by molecular** [comment]
partly Good news...

**I can open wallet and successfully enter passphrase in 4.1.0 but not in master.**

I'm starting to get confused. Overview (firmware 1.9.2, trezor lib 0.11.2):

  * 4.0.13: DeviceUnpairableError when entering passphrase
  * 4.0.13-dev1: can open wallet, can sign message, cannot send tx (see other issue I will link later)
  * 4.1.0: can open wallet, can sign message, cannot send tx (see other issue I will link later)
  * master e1fe712b2: DeviceUnpairableError when entering passphrase

with another trezor with really old firmware (1.6.3) I get this picture:

  * 4.0.13: DeviceUnpairableError when entering passphrase
  * 4.0.13-dev1: can open wallet, can sign message, can send tx
  * 4.1.0: can open wallet, can sign message, can send tx
  * master e1fe712b2: DeviceUnpairableError when entering passphrase

so 4.0.13 and master behave identically (DeviceUnpairableError) for both firmware versions I have available on hardware.
4.0.13-dev1 and 4.1.0 also behave identically (everything I test works) except that new other issue with the new firmware 1.9.2

**Comment by cculianu** [comment]
Hmm. See if you can upgrade to firmware 2.0?  (Not 2.3 -- that limits you to using only /145/ paths!)

**Comment by molecular** [comment]
I don't think I can upgrade to firmware 2.0. It's a "trezor classic", not Model T. I used wallet.trezor.io to upgrade firmware and it says 1.9.2 is the newest.

**Comment by molecular** [comment]
Wonderfull!!!

on master branch 292e860fc (I was on older commit earlier) everything works now with firmware 1.9.2 (didn't re-test the older 1.6.3).

Still confused what the issue actually was.
