### ISSUE TITLE
ModuleNotFoundError: No module named 'statistics'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1827]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/Users/huckfinne/.electron-cash/external_plugins/bitcoin-bileto-v0.0.12.zip/bitcoin-bileto/ui.py", line 96, in <lambda>
    f = lambda: tab.plugin.open_fund_dialog(tab.wallet_name, tab)
  File "/Users/huckfinne/.electron-cash/external_plugins/bitcoin-bileto-v0.0.12.zip/bitcoin-bileto/qt.py", line 186, in open_fund_dialog
    from .fund_dialog import FundDialog
  File "/Users/huckfinne/.electron-cash/external_plugins/bitcoin-bileto-v0.0.12.zip/bitcoin-bileto/fund_dialog.py", line 13, in <module>
    import statistics

ModuleNotFoundError: No module named 'statistics'
```

Reporter
------------

This issue was reported by 3 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.1.0  | 3.6.9 (default, Aug 17 2019, 12:35:02)  [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] | Darwin-19.2.0-x86_64-i386-64bit | standard |  | 
| 4.1.0  | 3.6.9 (default, Aug 17 2019, 12:35:02)  [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] | Darwin-19.2.0-x86_64-i386-64bit | standard |  | 
| 4.0.14  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | standard | es_VE | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
External plugin.
