### ISSUE TITLE
4.0.13 Windows "Installable" exe doesn't work

### ISSUE THREAD

**Issue by mhsmith** [Electron-Cash/Electron-Cash#1836]
When I run Electron-Cash-4.0.13-setup.exe on Windows 10, I get this error:

> Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item.

The 4.0.12 installer works fine, and so does the 4.0.13 standalone EXE.

**Comment by cculianu** [comment]
Hmm. It works for me. I just re-downloaded it off the electroncash.org website and installed it and ran it.  Windows 10.

I noticed the .exe has the "sysadmin" little shield on the icon for the installer.  (I am not even sure how Windows determines that.. file properties in the file??).

Maybe right-click -> Run as Administrator?

If not make sure the hash is good?

**Comment by mhsmith** [comment]
The 4.0.12 installer automatically asks for administrator access, but the 4.0.13 installer doesn't get that far. Run as Administrator made it prompt for admin access, but then it immediately fails with the same error.

The hash is good.

**Comment by cculianu** [comment]
Well we haven't changed anything with the installer. It literally just worked for me. Since I can't reproduce it -- if you can figure it out, would be great.  I wonder if others have had this issue..

**Comment by mhsmith** [comment]
Unfortunately I don't know much about Windows programming, and I've never even built EC for Windows. If you've got any ideas for how to diagnose it, let me know and I'll try them.

**Comment by EchterAgo** [comment]
@mhsmith I just checked on latest Windows 10 and it asks for UAC elevation. When you look at the icon of the file, does it display the UAC shield? It should look like this:

![image](https://user-images.githubusercontent.com/922233/77218947-78275780-6b63-11ea-8346-58f97d7ba591.png)

You did check the SHA256, right? Should be 42CD7477F5BC70C342E13C8F4EACA2E4A044A84E1BC6012012793BDEE9859DC8

**Comment by EchterAgo** [comment]
The NSIS manifest, which is what specifies if elevation is needed, seems to be correctly embedded in the file:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <assemblyIdentity version="1.0.0.0" processorArchitecture="*" name="Nullsoft.NSIS.exehead" type="win32"/>
  <description>Nullsoft Install System v3.02.1</description>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*"/>
    </dependentAssembly>
  </dependency>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="requireAdministrator" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
    </application>
  </compatibility>
</assembly>
```

The `requestedExecutionLevel` is correctly set to `requireAdministrator`. It looks like either something is wrong with your system or the file you downloaded doesn't match. If the file doesn't match, please upload it somewhere for us to check.

**Comment by EchterAgo** [comment]
I don't think it can be something like a truncated download as the manifest is embedded quite early in the binary.

**Comment by cculianu** [comment]
@EchterAgo Thanks for responding -- ok so EXE's have a manifest.  That answers why I see the shield! :)

Curious. I wonder if he's on one of the "buggy" windows service packs (remember those?). What exact version of Windows 10 is it? 

Here's what I'm on:

From settings... 
<img width="292" alt="Screen Shot 2020-03-21 at 8 33 36 AM" src="https://user-images.githubusercontent.com/266627/77221045-b5351f00-6b4e-11ea-984c-338885de08e8.png">

Click on "About" and you can see this...

<img width="504" alt="Screen Shot 2020-03-21 at 8 33 29 AM" src="https://user-images.githubusercontent.com/266627/77221053-c54cfe80-6b4e-11ea-9570-50d623c9913c.png">

**Comment by mhsmith** [comment]
The SHA256 is correct, and I think the UAC shield was always visible. The first time I ran the installer after downloading it, I got the message "Windows Defender SmartScreen prevented an unrecognized app from starting". I clicked "Run anyway", and then I think I immediately got the error without any UAC dialog.

Subsequent runs didn't show the Windows Defender message but went straight to the error. When I chose "Run as administrator", I got the UAC dialog followed by the error.

But when I try again today, I can't reproduce the problem anymore. When I run the installer I get the UAC dialog and then it completes normally. When I download a fresh copy, it's exactly the same except I get the Windows Defender message on the first run.

I can't imagine what's changed: I haven't done anything except put my computer to sleep overnight. Here are the Windows version details:

<img src="https://user-images.githubusercontent.com/166954/77224576-077e3c00-6b5f-11ea-85ec-b3f5e9bb856c.png" width="400"/>

I guess there's not much more we can do to explain this, but thanks everyone for your help.

**Comment by cculianu** [comment]
So weird!  If it makes you feel better we have experienced all sorts of weirdnesses between various windows versions.  You're on 1909 which differs from mine (1803).  Microsoft is using the public as their beta testers, sadly.  I suspect Windows itself somehow having subtle bugs that are hard to reproduce.  I know there's always a temptation as an application programmer to just blame the OS or somebody else -- but in this case I really feel that's the most likely explanation given the facts at hand -- and the fact that it later worked.

Weird! :D

**Comment by mhsmith** [comment]
> You're on 1909 which differs from mine (1803). Microsoft is using the public as their beta testers, sadly.

I think 1909 is the current stable version, so I'm not too worried about that. The machine was upgraded from Windows 7 a couple of months ago. 

When I intially ran the installer there was an existing installation of Electron Cash 4.0.8. After the first failure I tried uninstalling that before running the installer again, but it didn't fix the problem.

**Comment by cculianu** [comment]
> I think 1909 is the current stable version

Right.. but "stable" is relative. MS releases new versions constantly and sometimes they plug 1 bu and open up 2 more.  It's whack-a-mole with them... :P
