### ISSUE TITLE
Multisig wallet broadcast error with "An error occurred broadcasting the transaction" 

### ISSUE THREAD

**Issue by devilrayzl** [Electron-Cash/Electron-Cash#1839]
OS: Mac 10.15.3
Version: 4.0.12

1.Signed the transaction by wallet1 and wallet2,
2. Broadcast the signed transaction

result:
Broadcast fail with error message "An error occurred broadcasting the transaction".
And there is no other details.

![image](https://user-images.githubusercontent.com/8674861/77515501-94a0f800-6eb3-11ea-9898-6750a052a557.png)

**Comment by cculianu** [comment]
Ok, can you do the following:

1. Open a terminal (-Space, Terminal.app)
2. Tell it to run electron-cash with `-v` option: `/Applications/Electron-Cash.app/Contents/MacOS/Electron-Cash -v`
3. Note: You *may* have to replace `/Applications/Electron-Cash.app/Contents/MacOS/Electron-Cash` above with the path to your `Electron-Cash.app` bundle -- but only if you didn't put it in `/Applications`.  If you did put it in `Applications`, just do step (2) above.
4. You should see a bunch of **debug** output.  In the terminal window.
5. Try broadcasting the tx again and look to see what the error message about broadcast is and send it there.

**Comment by cculianu** [comment]
If the above instructions are too complicated -- I just thought of something **easier**.   **After** you sign the transaction -- click on this in the Transaction dialog:

![tx](https://user-images.githubusercontent.com/266627/77516372-f5fca300-6e82-11ea-9571-71fc91a377e4.png)

And paste the text here.  I can try broadcasting it to see what the error message is.

**Comment by cculianu** [comment]
Oh wait.  I just realized what the problem is!!!  For some reason Electron Cash is signing this transaction with schnorr -- but we never implemented multisig schorr!!

Can you go to preferences and **disable Schnorr** for this wallet?

This must be a bug -- that shouldn't be allowed to happen in the UI.

<img width="382" alt="Screen Shot 2020-03-25 at 10 29 08 AM" src="https://user-images.githubusercontent.com/266627/77516845-c13d1b80-6e83-11ea-8cd5-2d4480f570a3.png">

**Comment by devilrayzl** [comment]
![image](https://user-images.githubusercontent.com/8674861/77518490-d97b5d80-6eb8-11ea-9928-661b9d94bd31.png)
It seemed the multisig wallet does not got this option.
But I disable it in the cosigner wallet. I will try it again.

**Comment by devilrayzl** [comment]
Yes, broadcast successfully.You are right.Thanks a lot.

**Comment by cculianu** [comment]
Yay! Glad it worked out.
