### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '1CS'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1851]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.3.1cs-py3.5.egg\electroncash_gui\qt\external_plugins_window.py", line 243, in on_install
  File "site-packages\electron_cash-3.3.1cs-py3.5.egg\electroncash_gui\qt\external_plugins_window.py", line 341, in install_plugin_confirmed
  File "site-packages\electron_cash-3.3.1cs-py3.5.egg\electroncash\plugins.py", line 386, in install_external_plugin
  File "site-packages\electron_cash-3.3.1cs-py3.5.egg\electroncash\util.py", line 619, in versiontuple

ValueError: invalid literal for int() with base 10: '1CS'
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.1CS  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.18362 | standard | en_US | 
| 3.3.1CS  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.18362 | standard | en_US | 

Additional Information
------------------------

> flipstarter install error

---

> flipstarter install error

---

**Comment by emergent-reasons** [comment]
This was reported while installing the Flipstarter plugin.

**Comment by emergent-reasons** [comment]
Looks like the plugin code is trying to convert to int but some versions of EC have non-numbers in the version.

**Comment by cculianu** [comment]
Yeah IDK.  This is a very ancient version of Electron Cash.  Likely Flipstarter should put in its manifest that it requires 4.0.0 or above or something like that.  This ancient version lacks the proper lib support that Flipstarter is expecting.

**Comment by emergent-reasons** [comment]
FWIW, this is not related to Flipstarter. It is a bug in Electron Cash plugin system that happens with versions of Electron Cash that have non-numerical content in their version strings.

**Comment by cculianu** [comment]
Yeah.  The external plugin system no longer calls that function.  Indeed it's a bug with older EC versions.  I'm keeping this closed though since it's since been fixed. Will re-label it.
