### ISSUE TITLE
timeout: Server did not answer

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1853]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/home/john/.electron-cash/external_plugins/mecenas-v1.2.4.zip/mecenas/ui.py", line 58, in handle_finding
    self.contract_tuple_list = find_contract_in_wallet(self.wallet, MecenasContract)
  File "/home/john/.electron-cash/external_plugins/mecenas-v1.2.4.zip/mecenas/contract_finder.py", line 12, in find_contract_in_wallet
    ("blockchain.scripthash.listunspent", [contract.address.to_scripthash_hex()]))
  File "/tmp/.mount_ElectrpSFx5o/usr/lib/python3.6/site-packages/electroncash/network.py", line 1707, in synchronous_get
    raise util.TimeoutException('Server did not answer')

timeout: Server did not answer
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.1.0  | 3.6.9 (default, Jun 28 2018, 19:01:02)  [GCC 5.4.0 20160609] | Linux-4.15.0-91-lowlatency-x86_64-with-debian-buster-sid | standard | en_US | 

Additional Information
------------------------

> Tried to "find existing Mecenas contract" but the program overall seemed hung up. I couldn't resize the window, and it was still "Synchronizing", so that may have had to do with it.

---

**Comment by cculianu** [comment]
This isn't really a bug in Electron Cash since it's plugin-related.  Maybe contact the Mecenas devs.
