### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1855]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-4.0.14-py3.6.egg\electroncash_gui\qt\main_window.py", line 1352, in save_payment_request
  File "site-packages\electron_cash-4.0.14-py3.6.egg\electroncash\wallet.py", line 2257, in add_payment_request
  File "site-packages\electron_cash-4.0.14-py3.6.egg\electroncash\wallet.py", line 2239, in save_payment_requests
  File "site-packages\electron_cash-4.0.14-py3.6.egg\electroncash\util.py", line 345, in <lambda>
  File "site-packages\electron_cash-4.0.14-py3.6.egg\electroncash\util.py", line 341, in do_profile
  File "site-packages\electron_cash-4.0.14-py3.6.egg\electroncash\storage.py", line 181, in write
  File "site-packages\electron_cash-4.0.14-py3.6.egg\electroncash\storage.py", line 189, in _write
  File "json\__init__.py", line 238, in dumps
  File "json\encoder.py", line 201, in encode
  File "json\encoder.py", line 430, in _iterencode
  File "json\encoder.py", line 404, in _iterencode_dict
  File "json\encoder.py", line 353, in _iterencode_dict

TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

Reporter
------------

This issue was reported by 10 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale | Stack |
|---|---|---|---|---|---|
| 4.0.14  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-7-6.1.7601-SP1 | 2of2 | pl_PL | [ℹ](https://crashhub.electroncash.org//crash/977) | 
| 4.0.14  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | imported_addr,standard | en_US | [ℹ](https://crashhub.electroncash.org//crash/1049) | 
| 4.0.14  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | standard,imported_addr | en_US | [ℹ](https://crashhub.electroncash.org//crash/1051) | 
| 4.1.0  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | standard,imported_addr | en_US | [ℹ](https://crashhub.electroncash.org//crash/1110) | 
| 4.2.4  | 3.9.2 (default, Feb 20 2021, 18:40:11)  [GCC 10.2.0] | Linux-5.11.2-arch1-1-x86_64-with-glibc2.33 | standard | en_US | [ℹ](https://crashhub.electroncash.org//crash/1584) | 
| 3.6.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | slp_imported_privkey,slp_standard | de_DE | [ℹ](https://crashhub.electroncash.org//crash/1605) | 
| 4.1.1  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | standard,imported_privkey | de_DE | [ℹ](https://crashhub.electroncash.org//crash/1624) | 
| 3.6.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | slp_imported_privkey | de_DE | [ℹ](https://crashhub.electroncash.org//crash/1636) | 
| 3.6.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | slp_standard,slp_imported_privkey | de_DE | [ℹ](https://crashhub.electroncash.org//crash/1650) | 
| 3.6.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.22000-SP0 | slp_standard | de_DE | [ℹ](https://crashhub.electroncash.org//crash/2108) | 

Additional Information
------------------------

> baby636@outlook.de
> krise636@gmail.com

---

> baby636@outlook.de

---

**Comment by cculianu** [comment]
Needs investigation.  PR code is old and likely has bugs.

**Comment by molecular** [comment]
this was me while developing a plugin.

Possibly I wrote value "None" to wallet storage.

I think this can be safely ignored by EC devs for now.

**Comment by molecular** [comment]
why did you reopen?
