### ISSUE TITLE
Electron Cash Appimage GUI without captions

### ISSUE THREAD

**Issue by user0919** [Electron-Cash/Electron-Cash#1856]
Hey,

i downloaded the recent ElectronCash 4.0.14 Appimage to a Whonix Debian KVM System.
Using as desktop xfce 4.12

The GUI starts, but the captions of all controls are missing:
I also installed electron trough pip, with the same result.
The debug log doesnt contain any useful information just the following Warning is thrown at startup:

dbind-WARNING **: 19:04:46.675: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

Here’s a screenshot of the GUI after start:
![electron](https://user-images.githubusercontent.com/63824139/79516771-b6108200-8022-11ea-82ed-2bb312afa106.png)

Looks for me like an Graphical libraries issue, unfortunately i dont know how to debug this kind of misbehavior.

Looking for any idea…

**Comment by EchterAgo** [comment]
This can happen when the AppImage detects that your system has an older fontconfig library version and uses its own fontconfig, but it conflicts with your systems fontconfig settings.

You could try running like this to use only your systems settings:

```
FONTCONFIG_FILE=/etc/fonts/fonts.conf ./Electron-Cash-4.0.14-x86_64.AppImage
```

This assumes your `fonts.conf` file is in `/etc/fonts`. If it is not, that would explain why our overrides are not working.

If this works, you can disable fontconfig overrides in the settings menu, though you'll likely lose the ability to display the CashAccount color emojis correctly.

**Comment by user0919** [comment]
Yes, with the manual FONTCONFIG_FILE declaration and later disabling the emoji fonts everything is working now.

Thanks.

**Comment by cculianu** [comment]
Update: Another user in the telegram chat had this issue and said said:

```
apt install xfonts-scalable
```

Should fix it.

I am going to pin this issue.

**Comment by EchterAgo** [comment]
Specifically `ttf-bitstream-vera` should be installed. We use it as the default font to replace Verdana. The Verdana font is almost the same as Bitstream Vera, but it overrides some Emojis. I'll check if recent Qt versions have some better way of handling this stuff.

**Comment by Eemanali** [comment]
My bit cash wallet
