### ISSUE TITLE
Exception: Password required

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1863]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/home/alien/.electron-cash/external_plugins/flipstarter-1.2.1.zip/flipstarter/qt.py", line 377, in on_cancel_pledges
    password = self.get_wallet_password()
  File "/home/alien/.electron-cash/external_plugins/flipstarter-1.2.1.zip/flipstarter/qt.py", line 170, in get_wallet_password
    raise Exception(_("Password required"))

Exception: Password required
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.1.0  | 3.6.9 (default, Jun 28 2018, 19:01:02)  [GCC 5.4.0 20160609] | Linux-4.15.0-91-generic-x86_64-with-debian-buster-sid | standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by emergent-reasons** [comment]
Ok I can't close it. Any maintainer please feel free.
