### ISSUE TITLE
TypeError: isinstance() arg 2 must be a type or tuple of types

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#1886]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/Users/calin/src/ec/electron-cash/lib/util.py", line 830, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/calin/src/ec/electron-cash/lib/fanout.py", line 50, in fanin
    assert isinstance(list, txs_out) and not txs_out

TypeError: isinstance() arg 2 must be a type or tuple of types
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.0.15  | 3.6.10 (default, Dec 21 2019, 11:40:12)  [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] | Darwin-18.7.0-x86_64-i386-64bit | standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
False alarm. This was me messing around with some code. Sorry.
