### ISSUE TITLE
feature: make it harder to attempt doublespend for a sequence of multisig transactions

### ISSUE THREAD

**Issue by emergent-reasons** [Electron-Cash/Electron-Cash#1889]
When I make multiple multisig transactions in a short period of time, it is easy to end up attempting to spend the same coin multiple times. Currently I need to spend from specific coins to make sure that I don't do that.

I could send multiple outputs in a single transaction but it links the recipients and I prefer to preserve even a little bit of privacy if possible.

**Comment by emergent-reasons** [comment]
I had two ideas. I don't know if either is good:

1. freeze coins when signing a multisig. I can imagine this causing problems for tx that don't end up being completed.
2. use a facility like I proposed in #1888 to exclude multisig coins from transactions without necessarily freezing them :shrug:

**Comment by emergent-reasons** [comment]
FWIW this is not high priority for me. Just want to capture the issue.

**Comment by cculianu** [comment]
I think #1888 would be the real power solution -- perhaps should be done as a plugin.  This recent commit does solve this partially though: ca78b14e94837f4aa597ce73a3cae0a0c18a3ee0

I'm leaving #1888 open as that's a really useful feature, but closing this one to keep issue-count down.
