### ISSUE TITLE
BTC Transfered to BCH account by mistake

### ISSUE THREAD

**Issue by problemsssssssssss** [Electron-Cash/Electron-Cash#1894]
Hi is there a way to retrieve BTC currency from BCH Wallet? I have just transfereed the funds by mistake.

**Comment by cculianu** [comment]
It depends on where you sent it to.  Did you send it to yourself or to an exchange?  Let's take this conversation to the Electron Cash telegram channel -- in there other users can help you solve this.

https://t.me/electroncashwallet
