### ISSUE TITLE
CRITICAL: Cannot send money with new Trezor Firmware

### ISSUE THREAD

**Issue by Technologov** [Electron-Cash/Electron-Cash#1898]
pic-1 : BCH send fails.
https://www.dropbox.com/s/js06iya7szrtz3q/electron%20cash%20unable-to-send-anymore.png?dl=0

pic-2: signining message OKAY. (proving my private key and ownership)
https://www.dropbox.com/s/votd8t8gwv2lvpt/electron%20cash%20message%20signing%20OK.png?dl=0

I have an old Trezor One and a new Trezor One -- with new one I'm unable to send any money anymore. But those are different wallets, with a different key.

Probably due to new firmware. (New Trezor One v1.9.1 , old is Firmware v1.8.0 )

Electron Cash 4.0.15. How to fix this ?

NOTE, that I can sign a message with the new Trezor. So private key and PIN is correct.

NOTE2: i set my address in Electron cash to legacy in Trezor setting somehow

BCH address = bitcoincash:qrmuvzelp0ehv7d6qk832p6hsvxpywrv0shmtml9ng

**Comment by cculianu** [comment]
Yeah Trezor updated their firmware to fix a potential bug with BTC.  Can you do me a favor and complain to Trezor to submit patches to Electron Cash?  It's very onerous for us to maintain their plugin and we do it on a volunteer basis for free.  Can you tell them, as a customer -- that you expect them to contribute not just to Electrum but also to Electron Cash ?

The squeaky wheel gets the grease and if they realize many of their customers use BCH, not just BTC, they may be more likely to contribute in the future.

Bonus if you can convince them to donate to us.

Otherwise yes, thanks for reporting and I'll leave this issue open and will address it, free time permitting.

**Comment by Technologov** [comment]
Trezor Bug  Ticket ID: 21436

**Comment by cculianu** [comment]
Maybe -- but it would really like to see them own up to and support their own frikkin' product.  They benefit from free work here.. it's not even about money.  It's their overall attitude.

**Comment by cculianu** [comment]
@Technologov can you link to the issue itself on the issue tracker if it's public?  I want to comment on it to remind them that they submitted a patch to the BTC-based Electrum -- they can do similar to Electron Cash if they want to speed things up.  Or maybe you can remind them of this fact.

**Comment by rt121212121** [comment]
Strip down your mobile app and make a version targeted at use on offline devices as a "hardware wallet" equivalent solution. You could even sell it in the stores and fund your project, even if it is also available as open source to meet the purity test. Declare last supported firmware versions for each hardware device, and start encouraging users to move to the app. When a hardware wallet vendor comes to the party and offers first class proactive support for their device, take it off the unsupported list for as long as it lasts. Hardware wallet vendors wouldn't be able to compete on the app as you'd rightly be able to point out that their products should be avoided as they have a history of not supporting them.

**Comment by cculianu** [comment]
@Technologov We just pushed a commit to master that fixes this.  Note you may need to update your trezorlib to 0.12. `python3 -m pip install --user--upgrade trezorlib`

Can you try latest master?  Do you now how to run from source off of master?

**Comment by EchterAgo** [comment]
https://ec.loping.net/4.0.15-8-g7e545bedb/

@Technologov this is a binary test build of the fix that you can try.
