### ISSUE TITLE
Signing a transaction with Trezor fails with cryptic error message

### ISSUE THREAD

**Issue by davalb** [Electron-Cash/Electron-Cash#1903]
I tried to empty an old address (pre BTC / BCH fork). When I sign the transaction with the Trezor device the following message appears in a window:

`b"$'s\x9f\x14\x05\xca\xe5\xf2\xe6\xbaz\xa1K\x82\xf6\x1f\xac\x0bf\x08#\x8f\xfb\x96\xbdR+\n\xf0\x9cr"`

The trezor device is stuck on "signing transaction" and the gears on the screen are not moving.

Any idea, what could be the problem. Thank you!

**Comment by EchterAgo** [comment]
This is an incompatibility with the new Trezor firmware 1.9.1/2.3.1 and is already solved in 7e545bedbdf09c9312ab9a3de5ee3aeb931e7f56. You will need to run from source or use the test build from https://ec.loping.net/4.0.15-8-g7e545bedb/

Alternatively you can downgrade your Trezor firmware to 1.9.0/2.3.0, see https://wiki.trezor.io/Firmware_downgrade

**Comment by davalb** [comment]
Thank you very much! I will try that and close this ticket.
