### ISSUE TITLE
Ledger library not recognized with python-hidapi 0.9.0.3

### ISSUE THREAD

**Issue by dkaparis** [Electron-Cash/Electron-Cash#1907]
Under archlinux, when opening ledger-enabled wallet, I get the message:

```
Cannot find python library for 'ledger'.
Make sure you install it with python3
```

Python-btchip library is installed on the machine and the wallet used to work with ledger before upgrading the python-hidapi package to version 0.9.0.3-4. Downgrading python-hidapi to 0.9.0.2-4 solves the problem.

**Comment by EchterAgo** [comment]
Did you install EC / the dependencies from Arch using `pacman` or from PyPI using `pip`?

**Comment by EchterAgo** [comment]
This is not an issue with EC, the `python-hidapi` package is broken on Arch.

See https://bugs.archlinux.org/task/67103?project=5

**Comment by EchterAgo** [comment]
The issue is being fixed

https://github.com/Foxboron/archlinux-pkgbuilds/pull/1

**Comment by EchterAgo** [comment]
python-hidapi-0.9.0.3-5 was released which fixes the issue

https://www.archlinux.org/packages/community/x86_64/python-hidapi/

it might take some time to propagate to your mirror

**Comment by cculianu** [comment]
Thanks @EchterAgo for handling this
