### ISSUE TITLE
Tor dialog is confusing

### ISSUE THREAD

**Issue by zander** [Electron-Cash/Electron-Cash#1932]
a user that does not have 'tor' on their system will get a notification on starting it that is confusingly implying that EC is internally buggy.

When you are asked to start tor, while there is no tor executable available, you get a notification that the "internal" tor failed.

> The integrated Tor client experienced an error or could not be started.

The word "integrated" here is going to mean to most people that this is not a separate component on the system, and as such they can't fix it by installing the dependency. I would suggest adjusting this message to clear up this confusion.

It would be even nicer if the proxy dialog checks the executable to be present and avoids enabling this feature if it is not, explaining to the user that they need to install the external app to make it work.

**Comment by cculianu** [comment]
This is a very good suggestion, thanks. I see @EchterAgo already has resolved it.
