### ISSUE TITLE
 Electron Cash SVG LOGO

### ISSUE THREAD

**Issue by Real-FEELS** [Electron-Cash/Electron-Cash#1935]
Can the Electron Cash SVG logo be released please. 

![image](https://user-images.githubusercontent.com/68990054/89172574-c9683e80-d57a-11ea-8e5c-22beb39c146f.png)

**Comment by cculianu** [comment]
I don't think we have an svg of this -- @fyookball ? Do you know?

**Comment by EchterAgo** [comment]
I also wasn't able to find a Vector version of this. However I got a very good result running the image through Vector Magic and optimizing the settings a bit.

[ec-logo-7.zip](https://github.com/Electron-Cash/Electron-Cash/files/5015840/ec-logo-7.zip)

**Comment by cculianu** [comment]
Wow thanks Axel.  That's amazing.  I'll close this issue now.

**Comment by Real-FEELS** [comment]
@EchterAgo thanks for the conversation but I am looking for the original. 

@cculianu please reopen this issue.

**Comment by cculianu** [comment]
I am like 97% sure the original is lost because I know for a while Jonald was only producing images in PNG format.  I will re-open it and ping him.

**Comment by cculianu** [comment]
I spoke to Jonald.  He doesn't have any SVGs.  He made that by hand and all he saved was a bitmap image.  Sorry. Closing.

**Comment by EchterAgo** [comment]
My .svg generates an indistinguishable raster image without the alpha issues of the image on the website.
