### ISSUE TITLE
Trezor One error with Electron Cash 4.1.0 on Linux

### ISSUE THREAD

**Issue by darkbluelight** [Electron-Cash/Electron-Cash#1946]
The latest 4.1.0 with Cash Fusion doesn't work anymore on Linux with Trezor One hardware wallet with firmware 1.9.0.

When trying to sign a transaction Electron Cash shows the error:

_get_passphrase() got an unexpected keyword argument 'available_on_device'_

**Comment by EchterAgo** [comment]
will be fixed by #1947
