### ISSUE TITLE
Cashfusion: Suppress Tor prompt or offer plugin disable when Fusion is disabled

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#1970]
Currently Cashfusion triggers a "Tor is missing" prompt every time the program starts, as long as it cannot find a Tor port anywhere (whether integrated or systemwide), as long as the Fusion plugin is on (default). This is non-ideal for users  who do not wish to run a Tor client nor Fusion, but nevertheless is uninformed about the option to turn Cashfusion plugin off in menus.

One way to address it is to move the check for Tor availability to only trigger when Fusion is either manually enabled, or at start only when Fusion was enabled in the previous session.

Another (easier?) way is that in the same prompt, in addition to starting Tor or Cancel, add an additional option to disable the Cashfusion plugin altogether. Perhaps add a line "If you disable Cashfusion plugin now and wish to enable it later, find it at Tools -> Optional Features -> Cashfusion".  

A third way may be to remove the prompt altogether, and always enable integrated Tor as long as no system Tor is detected to be running. However that might be undesirable for people who do not want a Tor client of any kind to run on their machine.

**Comment by cculianu** [comment]
I just want to remove this prompt altogether. It creates a mess in the code to manage it and nobody cares about it either way. Really.

**Comment by georgedonnelly** [comment]
IMHO CF should only be enabled or triggered manually at this time, as most people do not use it or seek the functionality nor are people running Tor. I am speaking from the context of a more mainstream audience of merchants and beginner users, not power users. I expect this audience is where we want to grow right now. Hope this helps.

**Comment by cculianu** [comment]
@georgedonnelly Yeah I thunk Jonald and Mark wanted to have it enabled by default to maximize the chances it would be used. If it's not loaded at all the button won't appear in the status bar on the bottom right and then we lose chances that people try it.

I'll make the dialog box that does prompt suck less and/or maybe offer some way to not have it ask each time.

**Comment by georgedonnelly** [comment]
To maximize the chances of it being used, maybe a tips dialog that sends the user to a video or something that promotes the use of CF in a marketing fashion.

**Comment by cculianu** [comment]
@georgedonnelly That's a good idea.
