### ISSUE TITLE
Cashfusion coin chooser: more than 3 utxos per address lead to address being ineligible

### ISSUE THREAD

**Issue by molecular** [Electron-Cash/Electron-Cash#2002]
I've been trying to figure out why my coins weren't getting fused.

this line was the culprit:

https://github.com/Electron-Cash/Electron-Cash/blob/380f820ce0fb67f11d3898593b295e196e4d76e2/plugins/fusion/plugin.py#L126

not sure what the implications of removing this condition would be. But if it has to stay I think we need some way to inform the user why some coins were not selected for fusing.

**Comment by molecular** [comment]
further below in plugin.py:

```
             # * = We skip addresses with too many coins, since they take up lots
            #     of 'space' for consolidation. TODO: there is possibility of
            #     disruption here, if we get dust spammed. Need to deal with
            #     'dusty' addresses by ignoring / consolidating dusty coins.
```

**Comment by fyookball** [comment]
Yeah it's probably bad for privacy to allow that, because if multiple people do that it can make the number of addresses in a fusion round too small.  Ideally the wallet could possibly auto generated consolidation tx if it finds x number of coins on same address , or provide ux for user to do it etc

**Comment by fyookball** [comment]
tagging @markblundeberg if he wants to chime in

**Comment by markblundeberg** [comment]
Yeah some kind of indicator is needed to explain why some coins aren't getting fused. And auto-consolidations too!

The main reason for the restriction here is if too many coins from same address are selected, they 'use up' slots in the fusion without actually being distinct for privacy reasons.

**Comment by molecular** [comment]
> The main reason for the restriction here is if too many coins from same address are selected, they 'use up' slots in the fusion without actually being distinct for privacy reasons.

Shouldn't this logic be applied in the selection process for each single candidate transaction instead of as a "global" filter on the pool of available coins? That would accomplish the same goal while still being able to use those coins, right?

**Comment by molecular** [comment]
>  Ideally the wallet could possibly auto generated consolidation tx if it finds x number of coins on same address

I intentionally broke up those coins from large utxos (currently in the process of shuffling most of my coins pre-fork). Largish utxos (>100 BCH) don't seem to get picked up currently. I changed my process to break the large utxos up into multiple adresses, not just multiple utxos (it's not much more work thanks to the "copy adresses with balance" and "send to many" features), so this is not a pressing issue for me any more.

The main problem here is discoverability of the issue even existing (as Marc recognized). As is people are speculating wildly on why their coins arent getting picked up.

**Comment by readcash** [comment]
Oh, @molecular is completely right. I've been stumbling for *days* trying to figure out why my coins aren't getting fused. 

@fyookball I really don't think it should be closed. From an outsider perspective, it seems like CashFusion is broken. Can't Electron Cash just select a few UTXOs to spend instead of just ignoring the whole address?

**Comment by molecular** [comment]
@readcash

> Can't Electron Cash just select a few UTXOs to spend instead of just ignoring the whole address?

yeah, or not filter at all when globally collecting eligible utxos and then when selecting utxos for a fusion round make sure to not select more than n from each address?
