### ISSUE TITLE
Fusion Server issue on 4.2.0

### ISSUE THREAD

**Issue by fyookball** [Electron-Cash/Electron-Cash#2024]
Users keep getting "timed out during receive".

LOG from server op:

Oct 22 21:22:11 bch2 CashFusion[2340162]: |408.009| |32| [FusionController] Starting fusion with 12 players at tier=6800000
Oct 22 21:22:11 bch2 CashFusion[2340162]: |408.017| |32| [FusionController] Covert server started @ 10.19.96.105:40783 (announcing as: b'51.15.70.215':40783)
Oct 22 21:22:41 bch2 CashFusion[2340162]: |438.415| |32| [FusionController] startround sent at 1603401761.4246197; accepting covert components
Oct 22 21:22:42 bch2 CashFusion[2340162]: |439.975| |32| [FusionController] got commitments from 12 clients (dropped 0)
Oct 22 21:22:56 bch2 CashFusion[2340162]: |453.660| |32| [FusionController] ending covert component acceptance. 53 received.
Oct 22 21:22:56 bch2 CashFusion[2340162]: |453.665| |32| [FusionController] problem detected: too few components submitted
Oct 22 21:22:56 bch2 CashFusion[2340162]: |453.665| |32| [FusionController] problem detected: excess fee mismatch
Oct 22 21:22:56 bch2 CashFusion[2340162]: |453.666| |32| [FusionController] skipping covert signature acceptance
Oct 22 21:22:56 bch2 CashFusion[2340162]: |453.667| |32| [FusionController] entering blame phase. bad components: set()
Oct 22 21:23:12 bch2 CashFusion[2340162]: |469.931| |32| [FusionController] Ended with error: too few remaining live players

**Comment by cculianu** [comment]
@markblundeberg Any ideas?

**Comment by markblundeberg** [comment]
One important thing here is this: `ending covert component acceptance. 53 received.`

If all clients were successful in submitting their covert components then that would be 12 * 23 = 276 instead.

**Comment by markblundeberg** [comment]
I've dug around a bit, and spent a bunch of time fighting with protobuf breaking across versions (unrelated) ... but finally I can't find any clues as to what is happening.

**Comment by cculianu** [comment]
But does it break more on 4.2.0 vs 4.1.1 or is that unrelated?

**Comment by markblundeberg** [comment]
I'm not able to reproduce it. When server admin is awake perhaps we can coordinate an upgrade again and look at logs more carefully.

**Comment by markblundeberg** [comment]
Problem found: see #2025 for reason.

**Comment by markblundeberg** [comment]
(the recent reorganization of directory structures meant that the server installation wasn't looking for libsecp in the same place, so the lib was effectively missing)
