### ISSUE TITLE
Retire old change addresses

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#2026]
Since Cashfusion went to production, people have increasingly created wallets with tens of thousands of addresses in relatively short time and had trouble getting service from Fulcrum/Electrs servers. Simply lifting limits at server implementations is unsustainable, since leaving fusion wallets on can easily 10x or even 100x these addresses in a few months. One workaround is to advise users to only turn on fusion when necessary and transfer to new wallets regularly, but that makes for much degraded user experience.

A longer term solution is to retire old addresses from the change list: Do not subscribe to them, and do not revise their transaction lists at wallet start, only update if user makes a manual request to do so, and perhaps users can manually turn "watch this address" on by themselves. Addresses are conveniently separated into receive and change (internal), so we never have to retire any receiving address that we hand to other people. Possible modes of operation (pick one):

1. By time: If last transaction is n days away and the change address has no UTXO on it, flag address as retired.

2. By number: If the change address has no UTXO on it and it's more than n addresses before the latest change address, flag address as retired. 

3. By fusion: If the change address has no UTXO on it and it contains at least one Fusion transaction in its history, flag address as retired. 

We can pick one of the above, do some due diligence on how they might or might not impact usecases and privacy, implement and make wallets much more scalable in the future. My suspicion is this will also make wallets leak a lot less information to servers over time, but curious to hear what others think.

**Comment by markblundeberg** [comment]
Yes, something like this is needed.

Another aspect we can consider is to intermittently monitor the retired addresses, so that possible incoming payments are never lost, just delayed.

**Comment by cculianu** [comment]
Yeah I like the intermittent monitoring idea.  Either in the background or maybe offer a tool to scan them explicitly (perhaps under the `Scan for more addresses ...` menu), or both (that is, you can turn off the monitoring but still use the tool?).

I think some good heuristics for what to retire and what not to retire are easily devised.  The vast majority of these addresses will have been obvious cashfusion (or cashshuffle) temp change addresses.  They can easily be retired after they are used.

I don't believe this is a difficult problem to solve -- requires a bit of thinking and some elbow grease. I'm all for this.

**Comment by imaginaryusername** [comment]
One possible, unambiguous permutation of (3) that has no knobs to turn: 

If a change address has exactly two fusion transactions and 0 balance (it was only ever involved in fusions as an intermediate), it's retired.

In order for people to subsequently want to refund or deposit back to the address, generally a non-fusion transaction would be involved, so if both entry and exit are fusions it should be safe; while this can be broken by dust attacks, doing so en masse can be quite expensive for the griefer, and we don't need to let perfect be enemy of good. 

Hopefully this can be revived soon :D

**Comment by zander** [comment]
in the wallet [Flowee pay](https://github.com/floweethehub/pay) the 'change' chain is used as such;

the wallet is *KNOWN* to be the only one that has access to these addresses, as we never hand them out to users on the 'receive' screen. As such we have a simple algo that looks at 30 change addresses we have not used yet and monitor those as well as the ones in use. (the 30 is re-evaluated each time a tx depositing in it is seen, though, as we linearly traverse the chain).

More important to this question is that Flowee pay knows if a certain address is either 'unsed', 'has utxo' or 'empty' (aka spent).  And spent change addresses are effectively retired which means that while the user can go though the wallet advanced screen to get them, the wallet use them, deposite anything on them and as a result won't be monitoring them.

They are empty, money was deposited in it by us, then spent by us and we never shared those addresses with anyone in any form that creates the expectaction that they are monitored.

**Comment by cculianu** [comment]
Implementation to address this is here: https://github.com/Electron-Cash/Electron-Cash/pull/2408
