### ISSUE TITLE
4.2.0 not working with nano firmware

### ISSUE THREAD

**Issue by fyookball** [Electron-Cash/Electron-Cash#2054]
from the user

"it looks like 4.2.0 is has a bug with the nano s firmware 1.6.1 but 4.1.1 worked. When I clicked "Send" EC said it was signing, but that I needed to "Confirm Transaction on the ledger". There was no ability to confirm on the ledger and the tranasctiom just hung in confirm mode and cancelled.  When I tried the same with 4.1.1 I was able to scroll through the nano s and comfirm"

**Comment by EchterAgo** [comment]
I just tested firmware 1.6.1 with Bitcoin app version 1.5.0 and it works fine.

**Comment by greenertux** [comment]
Same here. After updating Bitcoin app to 1.5.1 on Ledger it is not working anymore.
Doesn't work with 4.1.1. either, so not sure it is an actual problem of Electron Cash 4.2.0.

**Comment by greenertux** [comment]
Electron seems to have a patch ready, any chance this can be ported to Electron Cash?

https://github.com/spesmilo/electrum/commit/b78cbcffd11364ed4651af1886d507b36bc1b013

**Comment by spokpark** [comment]
Same here. After updating Bitcoin app to 1.5.1 on Ledger it is not working anymore.
Doesn't work with Electron Cash 4.2.0.

Any fix available?

**Comment by EchterAgo** [comment]
Fix: https://github.com/Electron-Cash/Electron-Cash/pull/2061
