### ISSUE TITLE
Getting BCH (DAA)

### ISSUE THREAD

**Issue by acrodragon** [Electron-Cash/Electron-Cash#2057]
I had an outdated version of electron-cash prior to 11/15 (2.9.x).  I just installed the newest version (4.2.0).  Is there any way I can still secure my BCH DAA?  

Thanks!

**Comment by cculianu** [comment]
What is BCH DAA?

You should get latest 4.2.1 from the releases page: 

https://github.com/Electron-Cash/Electron-Cash/releases/tag/4.2.1

- Run it normally for BCH
- Run it with the CLI arg `--taxcoin` to see the ABC coin

Follow splitting instructions here:

---

im_uname#100🍋, [Nov 18, 2020 at 5:29:48 PM]:
...From Electron-Cash 4.2.1 and later:

1. Open your Electron-Cash wallet. Any default way will do, from icon, installed version, command line...

2. Copy your receive address and DM to someone trustworthy to get your "split dust", make sure you tell them you want BCH dust, not ABC. That person can be a @bitcoincashnode or @electroncashwallet admin, a trustworthy exchange, or someone you know who has already split their coins. After they send, you should see several hundred sats incoming. 

3. Wait for the transaction to confirm. After 1 confirmation, go to receive tab, get a new address, paste it into send, click "Max", then send. This is the "splitting" transaction.  

4. After the second "splitting" transaction is confirmed, congratulations, your coins are split and safe! If you send your BCH from that wallet, the send will not replay your ABC coins, and vice versa. 

Note: If used on a Cashfusion/Cashshuffle wallet, this can severely degrade the wallet's privacy. For Cashfusion in particular, simply leaving the split dust in and letting the coins fuse for a while may work better.

Now to access your ABC coins once your BCH is safely split:

5. From command-line, run Electron-Cash with argument --taxcoin. Electron-Cash will start as Electron-Tax, duplicating your existing wallets to minimize errors and server load. Follow instructions, pick your existing wallets when asked to create or restore. 

6. As recommended, "manually select server", pick one. All the starred servers should already be on the ABC chain.

7. You should see any BCH-only transactions, such as your splitting dust, disappear. If there were any ABC-only transactions before they should be present.

8. Send ABC coins to exchange, or anywhere you like.

Note that Electron-Cash (start anywhere, default) can be run simultaneously with Electron-Tax (start from command line only with --taxcoin argument). While that can be convenient, if you have doubts, run only one at a time to avoid sending the wrong coin.

Release Electron Cash 4.2.0 with Cas...

From Electron-Cash 4.1.1 and 4.2.0 (dow...

**Comment by acrodragon** [comment]
Sorry, ABC coin.   Thanks so much for your help.  Also, it appears i never split my BCH into BSV either (I have had this BCH since 2017.  Can i still do that too without losing the ability to split to ABC?

**Comment by cculianu** [comment]
Yes just be sure the tx's are set to "sign with schnorr" in the settings dialog.  If you sign with schnorr they cannot be replayed on the BSV network.  

See screenshot:

<img width="489" alt="Screen Shot 2020-11-18 at 6 45 49 PM" src="https://user-images.githubusercontent.com/266627/99560203-4c988d80-29ce-11eb-974d-89417ad6979a.png">
