### ISSUE TITLE
"No hardware device detected." Ledger Nano S

### ISSUE THREAD

**Issue by snafusam** [Electron-Cash/Electron-Cash#2068]
I am trying to set up electron-cash with my ledger nano s and it does not seem to detect the ledger device. I have followed these instructions:
Connect and unlock your Ledger device.
Open the Bitcoin Cash app.
Launch Electron Cash from your applications folder. The install wizard opens.
Leave the default wallet name and click Next.
Select Standard wallet and click Next.
At the keystore screen, select Use a hardware device and click Next. 
*This is where I get the error

I have tried it on both my macOS and windows 10 systems and get the same problem.

My iMac operating system is: macOS Big Sur 11.0.1
Ledger Nano S firmware: 1.6.1

If you need more information please let me know.

**Comment by EchterAgo** [comment]
What is the version of the Bitcoin App you have installed? I think it likely is 1.5.1. If so, this issue was already fixed in #2061.

**Comment by diploux** [comment]
@EchterAgo I have the same issue as OP and as you guess, am using BCH 1.5.1 on my Nano S. Sorry for the dumb question, but with the issue being fixed does that mean the next release it will work again or that current build of EC should work? FWIW, I dloaded the latest client from EC.org earlier today. Thanks for your help.

**Comment by EchterAgo** [comment]
It will work again in the next release. If you want to test the change, there is a test build in https://github.com/Electron-Cash/Electron-Cash/pull/2061 (no macOS build yet though)

**Comment by snafusam** [comment]
Thank you!
