### ISSUE TITLE
Ledger Nano S will not connect to Electron Cash 4.2.2

### ISSUE THREAD

**Issue by Quikfix73** [Electron-Cash/Electron-Cash#2079]
I do tech support for a living and I have tried this on 3 separate computers

2 of them on Windows 10 Home 2004 and 1 of them on Windows 10 Pro 2004 and I cannot connect to latest version of Electron Cash 4.2.2 that I downloaded from https://electroncash.org and I have tried both the regular EXE that only runs and also the Setup EXE.
![1](https://user-images.githubusercontent.com/75220145/100550811-5a051180-3231-11eb-9d0e-8af3bd137cce.jpg)

My Ledger Nano S is on latest firmware 1.61 and also on latest Bitcoin Cash Wallet 1.5.1

Please fix this

**Comment by EchterAgo** [comment]
Fixed in #2061, wait for a new release, which will come soon, or use the test build from the PR.

**Comment by Quikfix73** [comment]
Thank you so much!  It now works.
