### ISSUE TITLE
electrum.bitcoinabc.org (need a valid Bitcoin Cash ABC server)

### ISSUE THREAD

**Issue by Quikfix73** [Electron-Cash/Electron-Cash#2082]
I am trying to split my Bitcoin Cash ABC and Bitcoin Cash Node coins and in both these articles below It tells us to go to this server "electrum.bitcoinabc.org" to view your Bitcoin Cash ABC coins.

https://news.bitcoin.com/a-step-by-step-guide-to-splitting-abc-fork-tokens-from-bitcoin-cash/

https://www.reddit.com/r/btc/comments/juphpu/here_is_an_easy_way_to_split_abc_and_bch_coins/

Yet on my version of Electron Cash version 4.2.2-4-gc513afc04 (I am using this version since this is latest version that works with Ledger Nano as regular version 4.2.2 did not) the moment I try to put this server above, it gets banned.

My question is how can I see my Bitcoin Cash ABC coins if I don't have an ABC server?  Can you provide me with a valid Bitcoin Cash ABC server?

![1](https://user-images.githubusercontent.com/75220145/100643234-a19da300-32ee-11eb-902f-5c9016924f8b.jpg)

**Comment by EchterAgo** [comment]
4.2.2 does not allow connections to ABC servers. You can start the software with the `--taxcoin` command line argument or try using the Bitcoin ABC fork here: https://bitcoinabc.org/electrum

**Comment by Quikfix73** [comment]
I am assuming this will be correct for Windows 10?

Copy an existing shortcut to Electron Cash 4.2.2 to your desktop. Right Click and select properties. Edit the target field so it reads as follows:

"C:\Program Files (x86)\Electron Cash\Electron-Cash.exe" --taxcoin

Click "OK" Go back to your desktop and right click the edited shortcut. Select Rename. Edit the desktop title of the shortcut to your choice such as "Electron Cash TAX"

**Comment by EchterAgo** [comment]
Yea, that should do it.
