### ISSUE TITLE
Build using system dependencies

### ISSUE THREAD

**Issue by nopeinomicon** [Electron-Cash/Electron-Cash#2090]
Hey, I'm packaging Electron Cash for openSUSE, and I'm running into a problem regarding the build scripts. For packaging I need to, unless somehow impossible, avoid packaging prebuilt libraries that are available in the system repos. The build scripts when building using `setup.py sdist` automatically build independent versions of tor, libzbar, and libsecp256k1, making the package non-compliant. I see there are some kind of build arguments for the setup.py file, but I have no clue how to pass them to it. So if that alone will work to ensure the app uses system dependencies, then that will be great. Otherwise that is a feature that definitely needs to be in the build scripts for packaging purposes.

**Comment by EchterAgo** [comment]
You might want to look at the Arch Linux PKGBUILD, which also does not package prebuilt binaries:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=electron-cash

another one is the Fedora package:

https://src.fedoraproject.org/rpms/electron-cash/blob/master/f/electron-cash.spec

**Comment by cculianu** [comment]
@nopeinomicon Yes, it's possible -- do look at the other scripts.

Note that we use the bitcoin cash version of `libsecp256k1` which differs from the bitcoin core version. 

Our `libsecp256k1` has Schnorr signatures.  This Schnorr-enabled verison is required in order to use CashFusion.  So you should figure out a way to use the bitcoin cash version.  That version is currently hosted here: https://github.com/Electron-Cash/secp256k1

**Comment by nopeinomicon** [comment]
Ah okay. I'm going to close this and use what you two put here for reference, and I think that will do. Thank you both! It'll probably take a bit to make get everything together, especially the other secp package, but it'll happen. Also @cculianu what is the difference between the BitcoinABC and the Electron-Cash versions?? Because it seems like the BitcoinABC is just more up to date. If you can answer that it'll help, but this issue is done aside from that. Thanks again!

**Comment by cculianu** [comment]
@nopeinomicon Is your question with regards to ABC's secp256k1? Yes., it's functionally identical but more up-to-date. You can use their version with this software no problem.  Just don't use the bitcoin core version, is what I was trying to emphasize. (The bitcoin core version is the one most likely to already exist on e.g. opensuse as a package... so you may have to roll your own bch and/or abc package of secp).

Note that ElectrumABC also requires the bitcoin cash and/or abc version of secp and won't work right with the bitcoin core version....

**Comment by nopeinomicon** [comment]
@cculianu Ah, yeah. The bitcoin-core version is already on the OBS repos for SUSE. I'll see if I can get the Schnorr version up too.

**Comment by cculianu** [comment]
Yeah, I figured it would be.  Note Core also added schnorr recently but their API is completely different and Electron Cash and/or ElectrumABC can't talk to it.. so yeah we will need the ABC/BCH version...
