### ISSUE TITLE
Will offline transactions signed with releases prior to 4.1.1 continue to work post the Nov 15 2020 fork?

### ISSUE THREAD

**Issue by vogelito** [Electron-Cash/Electron-Cash#2094]
Hi,

It seems to me that the only change pertaining to the last Nov 15 hard fork was the introduction of ASERTi3-2d DAA, which is a change in BCH blocks, bur not in BCH transactions.

Does that mean that an offline transaction signed on 4.0.x software will continue to be valid today?

**Comment by cculianu** [comment]
Yes, that is correct. It would be valid today.

**Comment by vogelito** [comment]
Thank you!!
