### ISSUE TITLE
"Server did not answer" on v.4.2.3

### ISSUE THREAD

**Issue by silicontraption** [Electron-Cash/Electron-Cash#2109]
Trying to transfer some BCH to a new address. I keep getting "Server did not answer" error regardless of which server I'm connected to...tried the default one and 3 others.

I have the "Green light" in my EC, all looks good, but nothing happens. 

Any suggestions?

**Comment by cculianu** [comment]
Hmm. Is your wallet very big?  Also what server(s) did you try?

**Comment by silicontraption** [comment]
I rebooted the machine and it finally worked. Thanks!

**Comment by cculianu** [comment]
I'm glad it eventually worked out.
