### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2163]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "C:\Users\dusti\AppData\Local\ElectronCash\external_plugins\bitcoin-bileto-v0.1.zip\bitcoin-bileto\create_dialog.py", line 186, in generate_biletoj
    cwd=self.working_directory, shell=False)
  File "subprocess.py", line 287, in call
  File "subprocess.py", line 729, in __init__
  File "subprocess.py", line 1017, in _execute_child

FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.3  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | standard | en_US | 

Additional Information
------------------------

> I tried to make tickets with https://github.com/KarolTrzeszczkowski/Bitcoin-Bileto/releases/download/0.1/bitcoin-bileto-v0.1.zip
> 
> and it crashed.

---

**Comment by EchterAgo** [comment]
That plugin seems to be designed for Linux/macOS rather than Windows, that line tries to execute a command not available on Windows. @KarolTrzeszczkowski

**Comment by cculianu** [comment]
LOL yeah either Karol should make the plugin abort and refuse to run on Windows or.. maybe he can find an alternate way to do this on Windows...

**Comment by mhsmith** [comment]
Created https://github.com/KarolTrzeszczkowski/Bitcoin-Bileto/issues/1.
