### ISSUE TITLE
BCH solen from official 4.2.3 electron cash wallet!

### ISSUE THREAD

**Issue by garytman** [Electron-Cash/Electron-Cash#2167]
I downloaded electron cashwallet from www.electroncash.org and password protected my wallet with a password.  I decided to finally claim my bitcoin fork from 2014 and it was a mistake  I swept my old bitcoin private keys and voilla!  i transferred over to a new electron cash wallet on 01/24/26  checked today and 0 balance and was sent to a different wallet address.
![20210213_181342 (1)](https://user-images.githubusercontent.com/8344943/107864250-4e84b800-6e28-11eb-9c99-ae50b722eef3.jpg)
![20210213_181322](https://user-images.githubusercontent.com/8344943/107864251-55abc600-6e28-11eb-9dcd-c093f11731e7.jpg)
![20210213_181402 (1)](https://user-images.githubusercontent.com/8344943/107864259-69572c80-6e28-11eb-8e8e-ef15e507617f.jpg)
![20210213_173701](https://user-images.githubusercontent.com/8344943/107864264-796f0c00-6e28-11eb-89e5-30fbb2e39644.jpg)
![20210213_172859](https://user-images.githubusercontent.com/8344943/107864270-90156300-6e28-11eb-82d2-da6035a7356b.jpg)
![20210213_171722](https://user-images.githubusercontent.com/8344943/107864275-a1f70600-6e28-11eb-9b23-9a9ac8dff9b6.jpg)

**Comment by EchterAgo** [comment]
I just checked the downloads on electroncash.org and they are still the same files as I independently reproduced at https://ec.loping.net/4.2.3/

Do you mind sharing the `Electron-Cash-4.2.3.exe` you used? If it has SHA256 `00c69bed27a8683683020a5699a522bd66c81a9dee773b56fa83e6a670c57e8f`, no need to share it, that is the original hash.

**Comment by garytman** [comment]
Thanks for replying back!  I downloaded the wallet directly from my site.  I still have the my browsing history from the 24th and I have the wallets I created from the software.  As for the exe file I will look.  As soon as I noticed my coins were stolen I immediately saved my wallets as proof.  The weird thing about all of this is when i turned my laptop on today i was no longer connected to the internet I had to type the password in again.  I just recently swept my old btc address into coinomi and received BTC SVC and BTC gold so at least I could salvage that.  As for this electron cash wallet I no longer trust it.  How can someone steal a password protected wallet? That makes no sense and my screenshots prove that.  I will look for the exe file but I know I deleted my recycle bin.

**Comment by garytman** [comment]
![20210213_225907](https://user-images.githubusercontent.com/8344943/107868100-2a889d00-6e4f-11eb-9e18-49f7cf148b97.jpg)

**Comment by garytman** [comment]
![20210213_230219](https://user-images.githubusercontent.com/8344943/107868132-8eab6100-6e4f-11eb-9520-45b7b19bafa8.jpg)

**Comment by garytman** [comment]
I went to official website in help command and it takes me here.
![20210213_230325](https://user-images.githubusercontent.com/8344943/107868154-cb775800-6e4f-11eb-8943-5028d2c24d78.jpg)

**Comment by garytman** [comment]
I hope this helps someone else.  I would not trust any of these wallets, none of them are safe in my opinion.  As a matter of fact, the only reason I kept my all of my crypto safe over the years was because I had these on a hard drive which was disconnected from my pc for 7 years.  I keep all my wallets on a memory stick.  These hackers will find a way or it's someone that keeps a close eye on the BCH blockchain.  When I swept my secret keys that was the end of my BCH.

**Comment by garytman** [comment]
The wallets were safer back in 2014.  I will NEVER download a software wallet again lesson learned.

**Comment by garytman** [comment]
I just want to say that since the IRS deemed cryptocurrency as "property" I am going to claim this theft through my Home insurance policy.  I also have investigators from a crypto team investigating this as i type this.  I know that this isn't alot of money to be complaining about.  It's the fact that it bothers me and i can't let it go.  I earned that BCH and it's a shame that this has happened to me and so many others.

**Comment by cculianu** [comment]
I'm sorry for your loss. However, there is no backdoor unless you didn't download the official version. Are you sure it was downloaded from https://www.electroncash.org ?

Also it's possible your system has viruses or something that knew how to snoop to get to the wallet data.  Our software is used by thousands of users and nobody has had their funds stolen.  I myself keep lots of BCH in this wallet. The most likely things are:

1. You didn't download the official version but some bugged/virused version
2. Your system has viruses on it that stole the funds.

**Comment by cculianu** [comment]
It's also possible that your keys were stolen through some other vector...  Did you sweep to coinomi before or after this happened?

**Comment by garytman** [comment]
> I'm sorry for your loss. However, there is no backdoor unless you didn't download the official version. Are you sure it was downloaded from https://www.electroncash.org ?
> 
> Also it's possible your system has viruses or something that knew how to snoop to get to the wallet data. Our software is used by thousands of users and nobody has had their funds stolen. I myself keep lots of BCH in this wallet. The most likely things are:
> 
> 1. You didn't download the official version but some bugged/virused version
> 2. Your system has viruses on it that stole the funds.

Thanks man I appreciate it.  Absolutely positive I did.  I triple checked and it is in my browser history that way too.  If my system had viruses etc on it my other wallet.dat files would be stolen and also I did check today on the bcha block site and there still is BCHA full amount. .993 something.  So my secret keys were not stolen, unless the thief only got my BCH.  Everything else has been safe.  I did delete the wallet software and I myself would never trust it again.  I'm glad yours is safe.  I even had mine password protected.

**Comment by garytman** [comment]
> It's also possible that your keys were stolen through some other vector... Did you sweep to coinomi before or after this happened?

I swept to coinomi after this happened to get my other forks.

**Comment by garytman** [comment]
You can clearly see that it's the official wallet.

**Comment by garytman** [comment]
> > I'm sorry for your loss. However, there is no backdoor unless you didn't download the official version. Are you sure it was downloaded from https://www.electroncash.org ?
> > Also it's possible your system has viruses or something that knew how to snoop to get to the wallet data. Our software is used by thousands of users and nobody has had their funds stolen. I myself keep lots of BCH in this wallet. The most likely things are:
> > 
> > 1. You didn't download the official version but some bugged/virused version
> > 2. Your system has viruses on it that stole the funds.
> 
> Thanks man I appreciate it. Absolutely positive I did. I triple checked and it is in my browser history that way too. If my system had viruses etc on it my other wallet.dat files would be stolen and also I did check today on the bcha block site and there still is BCHA full amount. .993 something. So my secret keys were not stolen, unless the thief only got my BCH. Everything else has been safe. I did delete the wallet software and I myself would never trust it again. I'm glad yours is safe. I even had mine password protected.

And also I disagree that no one else has had their money stolen with the correct software.  I have read about this happening over the years and even with exodus.  I still believe there is some "backdoor" meaning when I swept the keys that was "seen" across the bitcoin cash network or something.  Crypto theft is by no way nothing new with these software wallets.  I personally don't trust them anymore.  Good luck and keep your coins safe!

**Comment by garytman** [comment]
I just checked and I still have the original exe file that I downloaded from www.electroncash.org.  how do I check it for the correct sha 256 hash?

**Comment by garytman** [comment]
![20210214_185921](https://user-images.githubusercontent.com/8344943/107893032-c6b9af00-6ef6-11eb-94f6-4ac66b2bb126.jpg)

**Comment by cculianu** [comment]
Do you know about replay tx's? You have clients for BSV and BCHA -- it's possible your tx got replayed.

Anyway I'm closing this.

**Comment by garytman** [comment]
> Do you know about replay tx's? You have clients for BSV and BCHA -- it's possible your tx got replayed.
> 
> Anyway I'm closing this.

Ok I have never heard of replay texts? I will have to look that up.  Thanks again
