### ISSUE TITLE
AttributeError: 'Thread' object has no attribute 'isAlive'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2174]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/usr/lib/python3.9/site-packages/electroncash_gui/qt/scan_beyond_gap.py", line 159, in done_slot
    self.accept()
  File "/usr/lib/python3.9/site-packages/electroncash_gui/qt/scan_beyond_gap.py", line 119, in accept
    self.cancel()
  File "/usr/lib/python3.9/site-packages/electroncash_gui/qt/scan_beyond_gap.py", line 100, in cancel
    if self.thread.isAlive():

AttributeError: 'Thread' object has no attribute 'isAlive'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.3  | 3.9.1 (default, Feb  6 2021, 06:49:13)  [GCC 10.2.0] | Linux-5.10.16-arch1-1-x86_64-with-glibc2.33 | standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
This has been fixed in ac47c40a6f12ea9b365dc0c193659d7c897aeb3f
