### ISSUE TITLE
AttributeError: 'ElectrumWindow' object has no attribute 'main_window'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2183]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "C:\dev\Electron-Cash-SLP\gui\qt\main_window.py", line 1558, in showEvent
    if self.main_window.is_slp_wallet:

AttributeError: 'ElectrumWindow' object has no attribute 'main_window'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.6.6  | 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 07:55:33) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.21327-SP0 | slp_standard | en_SG | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by EchterAgo** [comment]
Sorry, accidentally clicked send. This can be closed.
