### ISSUE TITLE
Electrum ABC doesnt Show Balance of Electron Cash

### ISSUE THREAD

**Issue by BkRenegade** [Electron-Cash/Electron-Cash#2194]
In following the instruction to split BCH to BSV according to the instruction below. I download Electrum ABC my existing wallet in Electron Cash was not copied in Electrum ABC which I though would be automatic. How do I get electron ABC retrieve info from Electrum Cash?
Thanks

Step two: Electrum ABC
Send coins to yourself in Electrum ABC. If you do not already have Electrum ABC installed, you can get it here. Upon installation, Electrum ABC will copy existing Electron Cash wallets for you.

**Comment by EchterAgo** [comment]
Sounds like an issue with Electrum ABC, you can report it here: https://github.com/Bitcoin-ABC/ElectrumABC/issues

As for your wallet, I'd recommend restoring from seed over having another software copy your wallet files.
