### ISSUE TITLE
DNSSEC error: No module named '_cffi_backend'

### ISSUE THREAD

**Issue by georgengelmann** [Electron-Cash/Electron-Cash#2201]
I am getting this error message if I try to use OpenAlias:

|337.868| |35| DNSSEC error: No module named '_cffi_backend'

EC cannot verify DNSSEC.

Reproduce:

Start Electron Cash via cmd.exe
Enter an OpenAlias in the Send Tab (try testnet@21.cash or mainnet@21.cash)
OR
Enter an OpenAlias in Tools->Preferences->Fees&Misc

**Comment by Art0272536137** [comment]
8pLQssgY
