### ISSUE TITLE
Fiat thousand separator on Android is gone

### ISSUE THREAD

**Issue by hieu-van** [Electron-Cash/Electron-Cash#2246]
I'm using EC for Android, version 4.2.3-3. The thousand separator for fiat amount seems to have gone since a recent version.

**Comment by mhsmith** [comment]
I removed the commas when adding the fiat input boxes on the Send and Request screens, because commas aren't accepted in numeric text boxes. However, I agree that the commas should have been retained for fiat amounts which are read-only.

**Comment by mhsmith** [comment]
Thanks for the report, we'll fix this in the next version.
