### ISSUE TITLE
I cannot connect to any servers with my Electron cash desktop

### ISSUE THREAD

**Issue by jichiros** [Electron-Cash/Electron-Cash#2269]
I have tried everything. I have tried to connect to all the different servers, tried disconnecting the wifi, and rebooted the system. No go. I uploaded the latest version. It is still not detecting any servers. I was thinking about the possibility of downloading the phone app and giving it the same seed/keys as my desktop version. Would this recover my BCH there?

**Comment by cculianu** [comment]
What version are you on and what os?

**Comment by jichiros** [comment]
I use the windows 10 on, and the electron cash wallet is version 4 2.0. Whenever I upgrade the version it goes back to the previous version after I logout.

Sent from Yahoo Mail on Android 
 
  On Mon, May 10, 2021 at 10:35 AM, Calin ***@***.***> wrote:   


What version are you on and what os?

**Comment by jichiros** [comment]
.Windows 10 and version 4.2.0

**Comment by jichiros** [comment]
Thanks

Sent from Yahoo Mail on Android 
 
  On Mon, May 10, 2021 at 12:41 PM, Calin ***@***.***> wrote:   


4.2.0 does not work with the current upgraded network rules. Please install 4.2.4.

**Comment by jichiros** [comment]
I loaded up the new version and it did not work. I loaded up a new electron wallet on my phone, typed in the recovery seed and got all of my coins backThank you so much for your time.
Jon Sakugawa
 

    On Monday, May 10, 2021, 01:55:33 PM CDT, Jon Sakugawa ***@***.***> wrote:  
 
 Thanks

Sent from Yahoo Mail on Android 
 
  On Mon, May 10, 2021 at 12:41 PM, Calin ***@***.***> wrote:   


4.2.0 does not work with the current upgraded network rules. Please install 4.2.4.

**Comment by cculianu** [comment]
If it didn't work on your pc then there may be some firewall issues for you on your system, perhaps, interfering with the network connections, etc.  It works here for me on Win10.  

Anyway good luck and glad you got to your coins eventually.

**Comment by jichiros** [comment]
It is one of the things that I tried. I stopped the windows firewall and that did not work???

Sent from Yahoo Mail on Android 
 
  On Mon, May 10, 2021 at 4:07 PM, Jon ***@***.***> wrote:   I loaded up the new version and it did not work. I loaded up a new electron wallet on my phone, typed in the recovery seed and got all of my coins backThank you so much for your time.
Jon Sakugawa
 

    On Monday, May 10, 2021, 01:55:33 PM CDT, Jon Sakugawa ***@***.***> wrote:  
 
 Thanks

Sent from Yahoo Mail on Android 
 
  On Mon, May 10, 2021 at 12:41 PM, Calin ***@***.***> wrote:   


4.2.0 does not work with the current upgraded network rules. Please install 4.2.4.
