### ISSUE TITLE
KeyError: 'sigadr'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2270]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/home/nick/bitcoin/electron-cash/electroncash_plugins/chaintipper/qt.py", line 118, in on_new_version
    "<li><b>", _("Signature Address"), "</b>: ", metainfo["sigadr"], "</li>",

KeyError: 'sigadr'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.4  | 3.9.4 (default, Apr 20 2021, 15:51:38)  [GCC 10.2.0] | Linux-5.12.1-arch1-1-x86_64-with-glibc2.33 | standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by molecular** [comment]
sorry, my bad. Another accidental plugin error report Can be closed.
