### ISSUE TITLE
Android: appearing offline 

### ISSUE THREAD

**Issue by Butcoin4U** [Electron-Cash/Electron-Cash#2273]
I don't know what is wrong with my account.  
![Screenshot_2021-05-14-08-41-04-2039562416](https://user-images.githubusercontent.com/84193658/118291868-f5342f80-b4cf-11eb-9670-8b76de0923c5.png)

**Comment by Butcoin4U** [comment]
WARNING!
Do not enter code here that you don't understand. Executing the wrong code could lead to your coins being irreversibly lost.
Type 'help' for available commands and variables.
>>> [fulcrum.fountainhead.cash] failed to connect timed out
[electrum.imaginary.cash] failed to connect timed out
[fulcrum.devops.cash] failed to connect timed out
[bitcoincash.quangld.com] failed to connect timed out
[bch.soul-dev.com] failed to connect timed out
[bch2.electroncash.dk] failed to connect [Errno 101] Network is unreachable
[electron.jochen-hoenicke.de] failed to connect [Errno 101] Network is unreachable
[greedyhog.mooo.com] failed to connect timed out
[Network] connecting to bitcoincash.quangld.com:50002:s as new interface
[bch.loping.net] failed to connect [Errno 101] Network is unreachable
[bch.cyberbits.eu] failed to connect timed out
[jktsologn7uprtwn7gsgmwuddj6rxsqmwc2vaug7jwcwzm2bxqnfpwad.onion] cannot resolve hostname
[j2tjfxntnsqpojaamnndgmfrc6lh3thattnlpc2xx53h2ojoi7agccid.onion] cannot resolve hostname
[electrumx-cash.1209k.com] failed to connect [Errno 101] Network is unreachable
[bitcoincash.quangld.com] failed to connect timed out
[electroncash.de] failed to connect [Errno 101] Network is unreachable
[Network] connecting to bitcoincash.quangld.com:50002:s as new interface
[electrs.bitcoinunlimited.info] failed to connect timed out
[blackie.c3-soft.com] failed to connect timed out
[electrumx.hillsideinternet.com] failed to connect timed out
[crypto.mldlabs.com] failed to connect timed out
[bch0.kister.net] failed to connect timed out
[electroncash.dk] failed to connect [Errno 101] Network is unreachable
[electrumx-bch.cryptonermal.net] failed to connect timed out
[ec-bcn.criptolayer.net] failed to connect timed out
[bitcoincash.quangld.com] failed to connect timed out
[Network] connecting to bitcoincash.quangld.com:50002:s as new interface
[bitcoincash.network] failed to connect timed out
[bch.imaginary.cash] failed to connect timed out
[bch.crypto.mldlabs.com] failed to connect timed out
[bitcoincash.quangld.com] failed to connect timed out
[Network] connecting to bitcoincash.quangld.com:50002:s as new interface
[bitcoincash.quangld.com] failed to connect timed out
[Network] connecting to bitcoincash.quangld.com:50002:s as new interface
[Network] network: retrying connections
[jh3jgcrwweh6yvmprtjnp72u2hqn34nlftlg3msrr4vmlapft4yvt2id.onion] cannot resolve hostname
[bitcoincash.quangld.com] failed to connect timed out
[Network] connecting to bitcoincash.quangld.com:50002:s as new interface
[bch.imaginary.cash] failed to connect timed out
[fulcrum.devops.cash] failed to connect timed out
[bch.cyberbits.eu] failed to connect timed out
[bitcoincash.network] failed to connect timed out
[electrs.bitcoinunlimited.info] failed to connect timed out
[bch2.electroncash.dk] failed to connect [Errno 101] Network is unreachable
[electrumx.hillsideinternet.com] failed to connect timed out
[bch.loping.net] failed to connect [Errno 101] Network is unreachable
[electroncash.de] failed to connect [Errno 101] Network is unreachable
[j2tjfxntnsqpojaamnndgmfrc6lh3thattnlpc2xx53h2ojoi7agccid.onion] cannot resolve hostname
[bch.crypto.mldlabs.com] failed to connect timed out
[jktsologn7uprtwn7gsgmwuddj6rxsqmwc2vaug7jwcwzm2bxqnfpwad.onion] cannot resolve hostname
[bitcoincash.quangld.com] failed to connect timed out
[Network] connecting to bitcoincash.quangld.com:50002:s as new interface
[electrumx-bch.cryptonermal.net] failed to connect timed out
[greedyhog.mooo.com] failed to connect timed out
[electrumx-cash.1209k.com] failed to connect [Errno 101] Network is unreachable
[ec-bcn.criptolayer.net] failed to connect timed out
[electron.jochen-hoenicke.de] failed to connect [Errno 101] Network is unreachable
[electroncash.dk] failed to connect [Errno 101] Network is unreachable
[electrum.imaginary.cash] failed to connect timed out
[blackie.c3-soft.com] failed to connect timed out
[fulcrum.fountainhead.cash] failed to connect timed out
[bitcoincash.quangld.com] failed to connect timed out
[bch0.kister.net] failed to connect timed out
[Network] connecting to bitcoincash.quangld.com:50002:s as new interface
[crypto.mldlabs.com] failed to connect timed out
[bch.soul-dev.com] failed to connect timed out
[bitcoincash.quangld.com] failed to connect timed out
[Network] connecting to bitcoincash.quangld.com:50002:s as new interface
[bitcoincash.quangld.com] failed to connect timed out
[Network] connecting to bitcoincash.quangld.com:50002:s as new interface
[bitcoincash.quangld.com] failed to connect timed out
[Network] connecting to bitcoincash.quangld.com:50002:s as new interface
[Network] network: retrying connections
[electrumx-cash.1209k.com] failed to connect [Errno 101] Network is unreachable
[bitcoincash.quangld.com] failed to connect timed out
[Network] connecting to bitcoincash.quangld.com:50002:s as new interface
[bitcoincash.quangld.com] failed to connect timed out
[Network] connecting to bitcoincash.quangld.com:50002:s as new interface

**Comment by mhsmith** [comment]
Sorry, I didn't notice this issue before because it didn't use the word "Android". 

It looks like your device was unable to reach the network. Did this affect other apps, or only Electron Cash? And did you manage to fix the problem?

**Comment by mhsmith** [comment]
If this is still a problem, please answer the questions above and I'll reopen the issue.
