### ISSUE TITLE
Add a custom exchange rate for Argentine peso (ARS)

### ISSUE THREAD

**Issue by BeltranLeo** [Electron-Cash/Electron-Cash#2283]
Hello! 

I have been working in the [Bitcoin Cash Argentina](https://bitcoincashargentina.com/) community to promote the adoption of Bitcoin Cash as a medium of exchange. We are focusing mainly in brick and mortar shops, but we have plans to reach more users. We promote the usage of various tools, including Electron Cash.

Due to problems in the exchange rates caused by local restrictions, we had to develop a custom system to enable users (both customers and merchants) to use the Argentine peso as a reference. The price displayed by most websites is incorrect and not the price a normal user would have to pay to acquire Bitcoin Cash.

I would like to ask you to implement this system in order to facilitate conversion for those merchants who do not have business smartphones and tablets (and thus are unable to use Register App) and would like to use computers. Our system is already usable in the Bitcoin.com wallet and in the Register App.

The rule is the following: We take the US dollar value in ARS from https://yadio.io/simple.html and then multiply it by the Bitcoin Cash value in dollars. Essentially:

	BCH price (in USD) × USD price (in ARS) = BCH price (in ARS)

I know that adding a custom exchange just for Argentina might be not standard. We try to deal with the restrictions the best that we can, and I hope this change might help in the work we are doing.

Thanks in advance!

**Comment by imaginaryusername** [comment]
Electron-Cash fetch simple exchange rate from user-defined external endpoints as seen in https://github.com/Electron-Cash/Electron-Cash/blob/master/electroncash/exchange_rate.py , we don't actually maintain any of these rates ourselves. It does sound like you guys have a pretty good idea what you want in terms of usable ARS rates! If you can provide an API EC can fetch from, I think it'll be pretty straightforward to add that as an option. 

For starters, maybe ask https://yadio.io/api.html to add BCH as a base currency? :)

**Comment by BeltranLeo** [comment]
Thanks for the answer.

Unfortunately for us, they seem to focus mainly in BTC. Would it be possible to  directly query Bitcoin.com as they already have the correct exchange rate? I assume there has to be an API as they feed that information straight to their wallet and register app.
