### ISSUE TITLE
Exception: testing crashhub

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2284]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/home/nick/bitcoin/electron-cash/electroncash_plugins/chaintipper/tiplist.py", line 258, in digestTipUpdates
    raise Exception("testing crashhub")

Exception: testing crashhub
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.4  | 3.9.5 (default, May 12 2021, 17:14:51)  [GCC 10.2.0] | Linux-5.12.5-arch1-1-x86_64-with-glibc2.33 | standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by molecular** [comment]
ooops, that didn't work.

sorry, please close
