### ISSUE TITLE
Path of external_plugins doesn't respect `-D` option

### ISSUE THREAD

**Issue by oxalica** [Electron-Cash/Electron-Cash#2300]
I'm using electron-cash on Linux with `-D <directory>` option in command line to change app directory to another path instead of the default `~/.electron-cash`. But it still create a single directory `~/.electron-cash/external_plugins`, while all other data (chain, wallets, etc.) are under the path specified by `-D`.

**Comment by cculianu** [comment]
Thanks for the bug report. Fixed in latest. Thanks @jonas-lundqvist for the fix.
