### ISSUE TITLE
RPA version does not work with old GLIBC. Intended or unintended?

### ISSUE THREAD

**Issue by ShadowOfHarbringer** [Electron-Cash/Electron-Cash#2308]
I tried testing RPA release on my old Linux Mint 18.3.

It's not working, newer version of GLIBC is required (the system has Ubuntu GLIBC 2.23-0ubuntu9).

` 
./Electron-Cash-4.2.4.2-RPA-1-g21854b8da-x86_64.AppImage 
/tmp/.mount_ElectrR8zE8Y/usr/bin/python3.8: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.25 not found (required by /tmp/.mount_ElectrR8zE8Y/usr/lib/libpython3.8.so.1.0)
/tmp/.mount_ElectrR8zE8Y/usr/bin/python3.8: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.26 not found (required by /tmp/.mount_ElectrR8zE8Y/usr/lib/libpython3.8.so.1.0)
/tmp/.mount_ElectrR8zE8Y/usr/bin/python3.8: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.27 not found (required by /tmp/.mount_ElectrR8zE8Y/usr/lib/libpython3.8.so.1.0)
`

Is this the intended behavior?

**Comment by cculianu** [comment]
Idk the RPA version is experimental — you could just run from source

**Comment by ShadowOfHarbringer** [comment]
Hmmm I guess I should just install new Linux Mint and try on a fresh distro.

I do not really want to play with running from source on that old Mint, it will be a headache.

**Comment by cculianu** [comment]
Yeah I can imagine getting all the prereqs installed would be.

yeah sorry you are having trouble. This was released as an experimental build and I guess jonald, who prepared the release, didn’t look into the details of supporting older Linux, maybe.

good luck shoot me a msg on slack tho if you want with questions

**Comment by ShadowOfHarbringer** [comment]
I am downloading Linux Mate 20.1 right now, I will try to test it next week.

This week (starting monday) I will be unavailable.
