### ISSUE TITLE
extracting a private key from a seed 

### ISSUE THREAD

**Issue by nikostudent** [Electron-Cash/Electron-Cash#2324]
Hello,
I have been tormented by a question for some time ..
I have a jaxx wallet installed.
If someone guesses 12 words, he immediately gets access to all my keys on all the blockchains that are in the wallet. Is that true? As far as I understand these 12/24 words are randomly selected from about 2000 words. But here we are talking anyway for a centralized service .. and to what extent is this "random" choice really random?
Do you think I have reason to worry if I have funds in such a wallet..not only jaxx but everyone else with mnemonic phrases

**Comment by cculianu** [comment]
Guessing 12 words from a set of 2000 is 2000^12. That number is a chance of 1 in  4*10^39.  That's a 4 with 39 zeroes after it.  Most lotteries give far better odds, by about 31 orders of magnitude.   Just to have a computer run through that many possibilities -- it would take hundreds of thousands of years before the computer even hit 1 valid wallet.  And that wallet won't even be yours.

That being said -- I cannot vouch for jaxx as to whether they steal your seed or whether their random number generator is secure.  I can say that with a bad RNG the odds improve significantly for a brute force guess.

I can say that if implemented **correctly** (with a secure RNG), seed phrases are very secure.  I can only vouch for Electron Cash and tell you the seed phrase generator in electron cash is secure.

**Comment by nikostudent** [comment]
> 
> 
> Guessing 12 words from a set of 2000 is a probability of 1/2000^12. That number is a chance of 1 in 4*10^39. That's a 4 with 39 zeroes after it. Most lotteries give far better odds, by about 31 orders of magnitude. Just to have a all the computing power on the planet run through that many possibilities -- it would take hundreds of thousands of years before the computers even hit 1 valid wallet. And that wallet won't even be yours.
> 
> That being said -- I cannot vouch for jaxx as to whether they steal your seed or whether their random number generator is secure. I can say that with a bad RNG the odds improve significantly for a brute force guess.
> 
> I can say that if implemented **correctly** (with a secure RNG), seed phrases are very secure. I can only vouch for Electron Cash and tell you the seed phrase generator in electron cash is secure.

My concern comes precisely from the fact that we are really talking about random selection for this product.
If I understood correctly - BIP 38 allows you to encrypt the private key itself - so if someone guesses it still will not be able to use it if he does not know the phrase even if he uses old software. But ... BIP38 is for bitcoin. is there an equivalent for etherium
Greetings

**Comment by cculianu** [comment]
I don't know, Electron Cash is a Bitcoin Cash wallet, not an Ethereum wallet.  I haven't delved into the finer details of Ethereum. 

I'm going to close this Q & A now -- I suggest you ask these questions in a forum, or on reddit.  This github is more focused on issues specifically with the Electron Cash software, bug reports, etc.  General discussion, even of interesting topics, can be taken up elsewhere. Best.

**Comment by nikostudent** [comment]
> I don't know, Electron Cash is a Bitcoin Cash wallet, not an Ethereum wallet. I haven't delved into the finer details of Ethereum.
> 
> I'm going to close this Q & A now -- I suggest you ask these questions in a forum, or on reddit. This github is more focused on issues specifically with the Electron Cash software, bug reports, etc. General discussion, even of interesting topics, can be taken up elsewhere. Best.

Greetings
