### ISSUE TITLE
Stuck on loading screen iOS15 beta

### ISSUE THREAD

**Issue by alabbe9545** [Electron-Cash/Electron-Cash#2330]
I updated to iOS15 beta recently and my electron cash wallet is stuck on the loading screen, it doesnt even ask me for my finger

**Comment by The00Dustin** [comment]
I was previously on Android and moved to a new iPhone.  I'm running iOS 15.0.2 and installed Electron Cash from the app store.  On first launch, it took a significant amount of time to load, but eventually did.  I chose the import seed option, and after putting in the seed and setting a wallet password, it has hung on "Opening <walletname>..." "Please wait" with some stuff spinning around a circle above that for far longer than it took to launch to begin with.

**Comment by mhsmith** [comment]
@cculianu: several people are complaining about this on Telegram as well.

**Comment by cculianu** [comment]
I will fix this soon!  Sorry! Apple broke everything unexpectedly.  Stay tuned! I am aware and will make time very very very soon to update it!!

**Comment by cculianu** [comment]
This has now been fixed and the latest version is in the store which runs ok on iOS 15: https://apps.apple.com/us/app/electron-cash/id1359700089
