### ISSUE TITLE
Idiot sending BTC to electron cash

### ISSUE THREAD

**Issue by gabmass90** [Electron-Cash/Electron-Cash#2336]
I'm an idiot who sent bitcoin from bitcoin.com wallet to my electron BCH account. I can see on my bitcoin wallet that the order was confirmed but obviously it didn't end up in my electron account. Wondering if/how I can get it back? Not sure if it makes a difference but i just set up an electrum BTC wallet as well

**Comment by cculianu** [comment]
If you can get your seed into electrum -- it should work.  Note that if you created your Electron Cash wallet relatively recently it will use a BIP39 style seed with derivation path: `m/44'/145'/0'`.  If you created your wallet long enough ago, then we used  the same seed format as Electrum in the past.


You could also just export the single private key for the address in question on the BCH side and import it to Electrum on the BTC side. You need the Address tab visible and you can right-click on an address to get the private key. See screenshot:

<img width="469" alt="Screen Shot 2021-09-07 at 8 46 12 PM" src="https://user-images.githubusercontent.com/266627/132388418-778bccae-6903-4c78-b95d-c8834bfb342f.png">

**Comment by gabmass90** [comment]
Thanks so much, it worked 👍

**Comment by cculianu** [comment]
Yay!
