### ISSUE TITLE
Biometric support

### ISSUE THREAD

**Issue by bdkappel** [Electron-Cash/Electron-Cash#2353]
Any chance for biometric support on the android app? I've been using BCH for meal delivery lately and my current flow of events is to order food, click pay, open Electron Cash, type in my long password, paste the transaction, type in my long password again, and finally send the transaction. I think biometric support could help adoption, the easier something is to use, the more likely people are to use it. Most current banking and transaction apps have this built-in, so I think the want/need is present.

**Comment by mhsmith** [comment]
Thanks for the request. We don't have any plans to add this in the near future, but please subscribe to #1655 for updates.
