### ISSUE TITLE
Electron Cash is stuck on opening animation

### ISSUE THREAD

**Issue by lilfruini** [Electron-Cash/Electron-Cash#2356]
I'm using an iPad 12.9" 4th Gen, the Electron Cash wallet currently has crypto in it that I want to retrieve but the app fails to open into the wallet menu, only spinning the green circles continuously.

Let me know what I need to do to access diagnostics. I lost my recovery key so I would ideally like to not delete the app, though there is a backup on my iTunes app.

**Comment by lilfruini** [comment]
Offloading did not work, the app still "loads" and rotates the green circles across the letter "O".

**Comment by quangld** [comment]
Same problem on iphone with iOS 15.1
