### ISSUE TITLE
Wrong hash / signature files on 4.2.6 release on Github

### ISSUE THREAD

**Issue by EchterAgo** [Electron-Cash/Electron-Cash#2374]
The hashes / signatures of the 4.2.6 release on Github are HTML files, they should be replaced with plain text files.

**Comment by EchterAgo** [comment]
The hashes / signatures on https://github.com/Electron-Cash/keys-n-hashes/tree/master/sigs-and-sums/4.2.6/win-linux seem to be correct and match my reproduction at https://ec.loping.net/4.2.6/sha256sum.txt

**Comment by cculianu** [comment]
Oh, thanks for the notice.  LOL. I used a script to slurp them up from the annoyingly-set-up github repo they exist in.  This is because I couldn't easily clone that repo since it's hundreds of megabytes for some reason.  I'll fix it. Thank you for the alert.

**Comment by cculianu** [comment]
Ok, updated. Sorry for the mistake and thanks so much for alerting me quickly.
