### ISSUE TITLE
Wallet Problem

### ISSUE THREAD

**Issue by Thrive777** [Electron-Cash/Electron-Cash#2379]
delete

**Comment by cculianu** [comment]
Bitcoin Cash and Bitcoin are two different blockchains.  You need to import the wallet seed for this wallet back into electrum to see your balance.  You cannot transfer BTC -> BCH in this way.

**Comment by cculianu** [comment]
If you really want to trade BTC for BCH you must use an exchange to sell the BTC for BCH.  What you just did was you sent BTC to another BTC address that is the same as your BCH address.  You mush re-create that same wallet in Electrum (using the same seed as used on the BCH side), to recover your locked BTC now.

**Comment by Thrive777** [comment]
ty

**Comment by Thrive777** [comment]
I imported again and now the wallet has the correct BTC, but its watch only still. What did I do wrong?
