### ISSUE TITLE
How do you Withdraw from a Watch Only BTC Wallet?

### ISSUE THREAD

**Issue by Thrive777** [Electron-Cash/Electron-Cash#2380]
So I have read quite a few things about Watch Only wallets and my ultimate goal is to get my BTC to where I can sell/withdraw it. I have read that any BTC in a watch only wallet is basically stuck in it unless you have the master key. I am pretty sure I have it because it was the wallet where the BTC originally came from and where it was transferred out, the only thing is how do I put that master key to use? I have already tried making new wallets with the "Use a master key" option but  its just uploading again as watch only.

**Comment by Thrive777** [comment]
resolved

**Comment by mhsmith** [comment]
For anyone else with the same problem: there are two kinds of master key. If it starts `xpub`, then it'll create a watching-only wallet. If it starts `xprv`, it'll create a normal spendable wallet.

**Comment by Hodlnwin** [comment]
I have this same problem with BlueWallet and a Keystone hardware wallet.

**Comment by Thrive777** [comment]
I'm not familiar with those 2, but my problem has been resolved.

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 26, 2022 at 12:05 PM, ***@***.***> wrote:   


I have this same problem with BlueWallet and a Keystone hardware wallet.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hodlnwin** [comment]
Thanks for the reply!  When you say you got it resolved does that mean you were able to move your balance out of the watch only wallet and into another wallet?  

I accidentally moved all of my bitcoin into my watch only wallet.  Not sure if your issue was identical, but I've been reading that it's all lost.

**Comment by Thrive777** [comment]
I'm not sure the entire situation here, but If you are able to see the funds in the watch only wallet then your funds are still yours and safe. You would have to have the wallet where the funds were sent to first, which we'll call it the Original wallet (the wallet the funds were transferred FROM into the watch only wallet). If you have the original wallet then theres still hope.

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 26, 2022 at 12:34 PM, ***@***.***> wrote:   


Thanks for the reply! When you say you got it resolved does that mean you were able to move your balance out of the watch only wallet and into another wallet?

I accidentally moved all of my bitcoin into my watch only wallet. Not sure if your issue was identical, but I've been reading that it's all lost.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Thrive777** [comment]
I was able to get my funds out of the watch only wallet, but I had to have my original wallet where the funds were transferred from and into my watch only.

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 26, 2022 at 2:55 PM, Brett ***@***.***> wrote:   I'm not sure the entire situation here, but If you are able to see the funds in the watch only wallet then your funds are still yours and safe. You would have to have the wallet where the funds were sent to first, which we'll call it the Original wallet (the wallet the funds were transferred FROM into the watch only wallet). If you have the original wallet then theres still hope.

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 26, 2022 at 12:34 PM, ***@***.***> wrote:   


Thanks for the reply! When you say you got it resolved does that mean you were able to move your balance out of the watch only wallet and into another wallet?

I accidentally moved all of my bitcoin into my watch only wallet. Not sure if your issue was identical, but I've been reading that it's all lost.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by anubhav47** [comment]
hi can you please tell me the process

**Comment by Thrive777** [comment]
> hi can you please tell me the process
It's been a long time since this occurred, but I will try to help with what I remember. I remember It had something to do with the Derivation Paths that was on the wallet I had. Here is a link on more about those https://learnmeabitcoin.com/technical/derivation-paths. 

I had a wallet on Electrum 4.3.2 and then transferred BTC from that wallet into a wallet on Electron Cash which is two completely different wallet types. If you send the BTC to another wallet, I would try changing Derivation Path to one of the following below.

BIP 32: m/0'/0/0 
BIP 44: m/44'/0'/0'/0/0
BIP 49: m/49'/0'/0'/0/0
BIP 84: m/84'/0'/0'/0/0

Hope that helps, I would have to have the problem again to retrace all my steps unfortunately.

**Comment by jaycutler1** [comment]
i have 2 wallet watch one in ETH e one TWT...i lost phrases that i write in paper, how can i do?

**Comment by Thrive777** [comment]
I would try support for whatever wallet you have

Sent from Yahoo Mail on Android 
 
  On Sun, Aug 13, 2023 at 11:39 AM, ***@***.***> wrote:   


i have 2 wallet watch one in ETH e one TWT...i lost phrases that i write in paper, how can i do?

**Comment by Hub-glitcher** [comment]
Hi do you have solutions for Blue wallet and Trust wallet?

**Comment by TWinner24** [comment]
I have an Electrum watch only wallet. I have all these seed phrases, cause I had no clue what I what I was doing. I dont know what to do now, with bitcoin going up the way it has, it has more than tripled, now I cant get it out???

**Comment by Thrive777** [comment]
So whatever was put in the wallet will still be in the same price and amount that was put in the wallet. If you have it in the stock market you can withdraw it to your wallet and then transfer from wallet to something like coinbase and withdraw as USD or whatever currency you have. Also keep those phrases and dont share with anyone or your wallet could get taken.

Yahoo Mail: Search, Organize, Conquer 
 
  On Sun, Dec 22, 2024 at 11:20 AM, ***@***.***> wrote:   


I have an Electrum watch only wallet. I have all these seed phrases, cause I had no clue what I what I was doing. I dont know what to do now, with bitcoin going up the way it has, it has more than tripled, now I cant get it out???
