### ISSUE TITLE
The transaction was rejected due to an error in script execution

### ISSUE THREAD

**Issue by Paayam** [Electron-Cash/Electron-Cash#2385]
Wallet file corruption detected. Please restore your wallet from seed, and compare the addresses in both files

**Comment by Paayam** [comment]
this is the actually error show me in electrum bitcoin Wallet file corruption detected. Please restore your wallet from seed, and compare the addresses in both files

**Comment by mhsmith** [comment]
See discussion in Telegram. This looks like a scam attempt with a modified copy of Electron Cash, but whether this person is the attacker or the victim is unclear. 

Do not install Electron Cash from anywhere except the following trusted sources:
* https://electroncash.org/
* Android Google Play
* Apple App Store
* This GitHub repository

**Comment by mhsmith** [comment]
Previous Electrum issue: https://github.com/spesmilo/electrum/issues/7565.
