### ISSUE TITLE
AttributeError: 'QCursor' object has no attribute 'position'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2401]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "C:\Users\Tinos\AppData\Roaming\ElectronCash\external_plugins\AutoCove-Plugin.zip\AutoCove\qt.py", line 942, in redoAvailable
    self.CurrentScript, self.CurrentPosition = Script, self.ScriptBox.cursor().position()

AttributeError: 'QCursor' object has no attribute 'position'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.6  | 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | imported_addr | en_NZ | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by TinosNitso** [comment]
Sorry, this was an accident. Please close (or delete). Where it's got cursor() should be textCursor().
