### ISSUE TITLE
electron cash wallet automatic transfer my bch to other scam address , now my balance "0"

### ISSUE THREAD

**Issue by lelongfu** [Electron-Cash/Electron-Cash#2406]
electron cash wallet automatic transfer my bch to other scam address , now my balance "0" .

just one days after  install the electron cash wallet using imported privkey.

why like this ??  
![1](https://user-images.githubusercontent.com/100269722/155275481-68929d44-4081-45e6-9c29-732e63a7af0e.JPG)

![2](https://user-images.githubusercontent.com/100269722/155275666-31f22855-2b4f-44e4-a18d-2354721775af.JPG)

**Comment by lelongfu** [comment]
![1](https://user-images.githubusercontent.com/100269722/155275437-c42de0a0-dbac-4818-82e1-a566bbda8a48.JPG)

**Comment by lelongfu** [comment]
that received address qph3s8p27pfg2lxgpzqmdel25tsmlryatyhxwzx3x5 is malware family that we named KryptoCibule .
it is posible to recorvery back the coin back to my account ?  how?

**Comment by cculianu** [comment]
You downloaded malware.  You did not download it from electroncash.org, correct?  Sorry you were scammed.  It wasn't us.  You downloaded a fake one.

**Comment by lelongfu** [comment]
I think malware "KryptoCibule "early store at my pc, once install electron cash wallet, it was automatic transfer to the scam address.
![KryptoCibule Cryptocurrency wallets](https://user-images.githubusercontent.com/100269722/155579994-f5e33dca-5c73-483f-ab79-fd60bce142f3.JPG)

![KryptoCibule address 2](https://user-images.githubusercontent.com/100269722/155580420-fb8077bf-2a21-4b74-a97d-bc4755b2507e.jpg)


 now my money at the scam address.
![qph3s8p27pfg2lxgpzqmdel25tsmlryatyhxwzx3x5](https://user-images.githubusercontent.com/100269722/155580467-7d518689-53bf-467f-88d8-91564a0e24ad.JPG)

anyway to recorvery back to my BCH address ??
