### ISSUE TITLE
freeze_utxo RPC

### ISSUE THREAD

**Issue by chappjc** [Electron-Cash/Electron-Cash#2446]
It would be good to merge the `freeze_utxo` and `unfreeze_utxo` RPCs from upstream.  See https://github.com/spesmilo/electrum/commit/bc6f2926f4b11c7d4293c7c286f7aec1a9889e03

**Comment by cculianu** [comment]
Merge unlikely since codebase has diverged significantly.  But adopt/port maybe. :) Good suggestion. Also easy to do since we have all the machinery in place for that.  Good idea.

**Comment by chappjc** [comment]
Nice. Thanks, @cculianu.  The `getinfo` RPC is also pretty clutch for my application, but I've not tested [the PR](https://github.com/Electron-Cash/Electron-Cash/pull/2399) for that one.

**Comment by chappjc** [comment]
Was resolved in https://github.com/Electron-Cash/Electron-Cash/pull/2490, and included in the [v4.2.12](https://github.com/Electron-Cash/Electron-Cash/releases/tag/4.2.12 release)
