### ISSUE TITLE
AttributeError: 'ElectrumWindow' object has no attribute 'cash_account_e'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2474]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "electroncash_gui\qt\request_list.py", line 74, in item_changed

AttributeError: 'ElectrumWindow' object has no attribute 'cash_account_e'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale | Stack |
|---|---|---|---|---|---|
| 0.1.0  | 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | standard | en_IN | [ℹ](https://crashhub.electroncash.org//crash/1942) | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
This is some unknown EC version. Closing.
