### ISSUE TITLE
testnet support for RPA

### ISSUE THREAD

**Issue by fyookball** [Electron-Cash/Electron-Cash#2478]
You might want to change this line:
https://github.com/Electron-Cash/Electron-Cash/blob/a22f189c4dfed9d13f352d81d7faf5bd64ec36e5/electroncash/rpa/paycode.py#L440
To:
extendedkey = hex(networks.net.WIF_PREFIX)[2:] + privkey or similar... RPA obviously don't work on testnet without it

**Comment by cculianu** [comment]
Working on it.

**Comment by cculianu** [comment]
Ok fixed in latest master.
