### ISSUE TITLE
Remove Labelsync plugin

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#2497]
The Labelsync plugin in Optional Features has been really unreliable for years; it does not work for large wallets, it randomly gets in trouble even for small wallets, Cashfusion's barrage of labels is terrible for it, it fails awkwardly (generally by timing out), and the server at https://github.com/bauerj/electrum-sync-server and https://github.com/maran/electrum-sync-server has been rotting for years. 

Since the situation is unlikely to be improved anytime soon, creating the illusion of being able to sync then subjecting the user to subsequent troubles is likely worse than removing the ambiguity altogether. Let's remove the plugin from default list.

**Comment by georgengelmann** [comment]
As a LabelSync user, I agree. I can export my labels and push them on my own server if necessary.

#2281 should also be closed.
