### ISSUE TITLE
My daily bch

### ISSUE THREAD

**Issue by Mysticalgirl007** [Electron-Cash/Electron-Cash#2518]
How to use BCH using electroncash?

**Comment by Mysticalgirl007** [comment]
I tried to download and use electron cash, I even connect to wallet connect but after that I don't know what next and how to use it for payments

**Comment by mhsmith** [comment]
There are some tutorials [here](https://www.youtube.com/playlist?list=PL6P_87NPp72aMQeOiSO4Pq8u_yeOcY6K7).
