### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'save'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2521]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/home/nick/bitcoin/electron-cash/electroncash_gui/qt/main_window.py", line 4997, in closeEvent
    self.clean_up()
  File "/home/nick/bitcoin/electron-cash/electroncash_gui/qt/main_window.py", line 5113, in clean_up
    self.gui_object.daemon.stop_wallet(self.wallet.storage.path)
  File "/home/nick/bitcoin/electron-cash/electroncash/daemon.py", line 299, in stop_wallet
    wallet.stop_threads()
  File "/home/nick/bitcoin/electron-cash/electroncash/wallet.py", line 2174, in stop_threads
    self.synchronizer.save()

AttributeError: 'NoneType' object has no attribute 'save'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale | Stack |
|---|---|---|---|---|---|
| 4.2.11  | 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0] | Linux-6.0.12-arch1-1-x86_64-with-glibc2.36 | standard | en_US | [ℹ](https://crashhub.electroncash.org//crash/2094) | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by molecular** [comment]
This happened when I close a wallet (with others still open)

**Comment by cculianu** [comment]
Hmm. How to reproduce?

**Comment by molecular** [comment]
Yeah, this is not a good bug report. I tried to reproduce, but it doesn't happen any more.

Let's close this. I'll reopen when it happens again and I can reproduce.

**Comment by cculianu** [comment]
It makes me feel like maybe a plugin was not enabling the synchronizer.  Or.. maybe it happens only in `--offline` mode?

**Comment by cculianu** [comment]
Yeah I am auditing the codebase and it seems impossible to dereference that when `None`.. of course this happened to you so it must be possible.  Were you running some plugins? If so which?

**Comment by cculianu** [comment]
Ok, I pushed a commit to guard against this possibility. I can see how some invariants being violated by spaghetti code (maybe a plugin) can cause this crash. Fixed in latest master.

**Comment by molecular** [comment]
Yes, this is while having my own plugin "chaintipper" active.

What do you mean by "enabling synchronizer"? You might be onto something. I don't remember ever doing such a thing in my plugin, so that may be it.

**Comment by molecular** [comment]
What "app"? EC or chaintipper?

**Comment by cculianu** [comment]
EC :)

**Comment by molecular** [comment]
Not touching the wallet in a weird way ;-). But I did steal some network request code from synchronizer for this thing: https://github.com/molecular/chaintipper/blob/raintipper/follow_the_money.py#L101 . Maybe that counts as "doing some weird stuff"?

**Comment by molecular** [comment]
> No idea man.

Me neither. Well, it only happened on one day, so :shrug: 

Thanks for looking into it, though! :heart:
