### ISSUE TITLE
Upgrading from 4.2.12 to 4.2.13 gives "fatal error"

### ISSUE THREAD

**Issue by hkorth** [Electron-Cash/Electron-Cash#2542]
v4.2.12 was running flawlessly. Upgraded to 4.2.13 (running Electron-Cash-4.2.13.exe), and after password entry a box titled "Fatal error detected" pops up. The message in the window reads "Failed to execute script electron-cash". I verified the signature and SHA256, so it's not a download error.

**Comment by cculianu** [comment]
Yes there is a bug in the payment request stuff.  We fixed it in master. You can try this fresh build off master: https://c3-soft.com/downloads/BitcoinCash/Electron-Cash/testing/4.2.13-24-gafe5bb2cb/

The files there come from the gitlab builder and I just signed them now.  Let me know if this is now fixed for you off master!

**Comment by hkorth** [comment]
Yes, the linked version seems to fix the issue. Thank you.

**Comment by cculianu** [comment]
Ok cool. We're doing a release now -- 4.2.14 -- which will include this fix. It should be out maybe in the next day ...

**Comment by cculianu** [comment]
I am going to close this as fixed but will leave it "pinned" so others see it since I anticipate you are not the only person affected by this bug.
