### ISSUE TITLE
java.lang.RuntimeException: Unable to start service org.electroncash.electroncash3.CaptionService@47ec133 with Intent { cmp=org.electroncash.wallet/org.electroncash.electroncash3.CaptionService (has extras) }: java.lang.IllegalArgumentException: org.electroncash.wallet: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingInten...

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2566]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback

java.lang.RuntimeException: Unable to start service org.electroncash.electroncash3.CaptionService@47ec133 with Intent { cmp=org.electroncash.wallet/org.electroncash.electroncash3.CaptionService (has extras) }: java.lang.IllegalArgumentException: org.electroncash.wallet: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
```

Reporter
------------

This issue was reported by 41 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale | Stack |
|---|---|---|---|---|---|
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on motorola moto g 5G (2022) (austin) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2123) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on motorola moto g 5G (2022) (austin) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2124) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on motorola moto g 5G (2022) (austin) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2125) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:31:08)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on motorola moto g pure (ellis) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2126) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on samsung SM-M315F (m31) | unknown | en_PH | [ℹ](https://crashhub.electroncash.org//crash/2127) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:31:08)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on motorola moto g pure (ellis) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2128) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-N986U1 (c2q) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2129) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-N986U1 (c2q) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2130) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-N986U1 (c2q) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2132) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-G781W (r8q) | unknown | en_CA | [ℹ](https://crashhub.electroncash.org//crash/2133) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on samsung SM-S134DL (a03su) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2135) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on samsung SM-S134DL (a03su) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2136) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on samsung SM-M315F (m31) | unknown | en_PH | [ℹ](https://crashhub.electroncash.org//crash/2137) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2007J20CG (surya) | unknown | pl_PL | [ℹ](https://crashhub.electroncash.org//crash/2138) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on motorola moto g31 (coful) | unknown | es_AR | [ℹ](https://crashhub.electroncash.org//crash/2139) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-G780F (r8s) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2140) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-G780F (r8s) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2141) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on realme RMX3081 (RMX3081L1) | unknown | sk_SK | [ℹ](https://crashhub.electroncash.org//crash/2142) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on realme RMX3081 (RMX3081L1) | unknown | sk_SK | [ℹ](https://crashhub.electroncash.org//crash/2143) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on motorola moto g stylus 5G (2022) (milanf) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2144) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Xiaomi 22041216G (xaga) | unknown | ru_RU | [ℹ](https://crashhub.electroncash.org//crash/2145) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on Xiaomi 22041216G (xaga) | unknown | ru_RU | [ℹ](https://crashhub.electroncash.org//crash/2146) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-G780F (r8s) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2147) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-A515F (a51) | unknown | es_AR | [ℹ](https://crashhub.electroncash.org//crash/2148) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2007J20CG (surya) | unknown | pl_PL | [ℹ](https://crashhub.electroncash.org//crash/2149) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on realme RMX3081 (RMX3081L1) | unknown | sk_SK | [ℹ](https://crashhub.electroncash.org//crash/2150) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2007J20CG (surya) | unknown | pl_PL | [ℹ](https://crashhub.electroncash.org//crash/2151) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2007J20CG (surya) | unknown | pl_PL | [ℹ](https://crashhub.electroncash.org//crash/2152) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2007J20CG (surya) | unknown | pl_PL | [ℹ](https://crashhub.electroncash.org//crash/2153) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2007J20CG (surya) | unknown | pl_PL | [ℹ](https://crashhub.electroncash.org//crash/2154) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2007J20CG (surya) | unknown | pl_PL | [ℹ](https://crashhub.electroncash.org//crash/2155) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2007J20CG (surya) | unknown | pl_PL | [ℹ](https://crashhub.electroncash.org//crash/2156) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2007J20CG (surya) | unknown | pl_PL | [ℹ](https://crashhub.electroncash.org//crash/2157) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2007J20CG (surya) | unknown | pl_PL | [ℹ](https://crashhub.electroncash.org//crash/2158) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on Xiaomi M2007J20CG (surya) | unknown | pl_PL | [ℹ](https://crashhub.electroncash.org//crash/2159) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-G781W (r8q) | unknown | en_CA | [ℹ](https://crashhub.electroncash.org//crash/2163) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on HMD Global Nokia 5.4 (DRD_sprout) | unknown | de_DE | [ℹ](https://crashhub.electroncash.org//crash/2173) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 12 on HMD Global Nokia 5.4 (DRD_sprout) | unknown | de_DE | [ℹ](https://crashhub.electroncash.org//crash/2177) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-G781W (r8q) | unknown | en_CA | [ℹ](https://crashhub.electroncash.org//crash/2236) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-N986U1 (c2q) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2592) | 
| 4.2.14-5  | 3.8.13 (default, Sep 17 2022, 19:30:07)  [Clang 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315d | Android 13 on samsung SM-N986U1 (c2q) | unknown | en_US | [ℹ](https://crashhub.electroncash.org//crash/2593) | 

Additional Information
------------------------

> idk it just says error 

---

> bulshit

---

> just got my seed wrote down  and got an error

---

> updating app from version 4.2.5

---

> typing my password

---

> Hi what happened?  problem cause

---

> Ive updated the app and when trying to open a wallet it crashed

---

> bei einloggen 

---

> bei dem Einloggen 

---

**Comment by fyookball** [comment]
we will get a new release soon to patch this.
