### ISSUE TITLE
Task: Replace Python 3.12 beta with the release once it is done, also reenable Windows

### ISSUE THREAD

**Issue by EchterAgo** [Electron-Cash/Electron-Cash#2673]
We currently use a 3.12 beta build in our test matrix to test 3.12 compatibility. Once 3.12 is officially released we should switch this to the real release. We also need to reenable 3.12 for Windows, this was disabled in #2662 because Python crashes on startup.

**Comment by hegjon** [comment]
Would it be possible to bump it to Python 3.12rc2? https://www.python.org/downloads/release/python-3120rc2/

**Comment by EchterAgo** [comment]
See https://github.com/Electron-Cash/Electron-Cash/pull/2689

**Comment by hegjon** [comment]
Python 3.12 was released today https://www.python.org/downloads/release/python-3120/
