### ISSUE TITLE
Add Stack Wallet to list of wallets that support Cash Fusion

### ISSUE THREAD

**Issue by bigvtokyo** [Electron-Cash/Electron-Cash#2736]
Add Stack Wallet to list of wallets that support Cash Fusion, on the Cash Fusion website.

**Comment by The00Dustin** [comment]
I see Stack Wallet listed on https://cashfusion.org/wallets/

This repository likely isn't the correct place for this request, but even if it is, the request should probably be closed or updated to be more specific if the wallet should be listed elsewhere.

**Comment by bigvtokyo** [comment]
Thanks. As pointed out, it's been added.
