### ISSUE TITLE
Poor error checking of socks proxy server address.

### ISSUE THREAD

**Issue by tl121** [Electron-Cash/Electron-Cash#2743]
If the user configures EC network access via a Socks 5 server using a  numeric ip address that begins with a leading blank prior to the correct server ip address,, 
e.g " 192.168.8.229" instead of "192.168.8.229",
the user will not get any kind of error message, but no proxy connection will be made and the network status will remain disconnected, (red) if there is no server reachable except through a proxy. 

This bug is reproducible. Subsequent deletion of the leading blank character and closing the pop up window will allow the proxy to work.  Subsequent editing and adding the leading blank and closing the window will cause the proxy to fail, ...

This is a minor user experience problem.  This exists in EC 4.3.1,  and was also observed in Electrum 4.3.3.

**Comment by EchterAgo** [comment]
See #2744
