### ISSUE TITLE
Add support for Trezor Safe 3.

### ISSUE THREAD

**Issue by tl121** [Electron-Cash/Electron-Cash#2756]
This requires the support of Trezor 0.13.8.    The new Trezor Safe 3 has just arrived and works with  Trezor Suite.  It does not work with Electron-Casj 4.3.1  T

here are a few small tweaks required to get the Safe 3 working with Electron Cash..  See #2465  where I explain in somewhat more detail.  With the release of this new Trezor product #2465 no has benefit to users.

I have all three models of Trezors and will be happy to test software.

**Comment by imaginaryusername** [comment]
It sounds like you've got a PR all figured out. Can you submit one so people in #2465 can try it too?

**Comment by tl121** [comment]
Pull request done #2757.

**Comment by cculianu** [comment]
Can this be closed now that #2757 is merged?

**Comment by tl121** [comment]
Fine by be.  Please close it/
