### ISSUE TITLE
File identified that prevents current  EC Master from producing reproducible builds

### ISSUE THREAD

**Issue by tl121** [Electron-Cash/Electron-Cash#2768]
Following the recommended instructions on an Ubuntu 22.04 system an app image is built that is not reproducible.   Repeating this process produces appimages that have a different sha256sum.

git clone https://github.com/Electron-Cash/Electron-Cash
cd Electron-Cash
./contrib/build-linux/appimage/build.sh master

Using --appimage-extract and comparing files it was found a single file was located that varied with each appimage build:

< fc5b1c52cf60099502a6a8c7d101d80140522b08bdcc90f6de866ab9494b8f33  ./usr/lib/python3.8/site-packages/zxingcpp.cpython-38-x86_64-linux-gnu.so
---
> cb6be05c89731b49bfe439de5c971e6baa7f62105e564a21cb2748b2760436eb  ./usr/lib/python3.8/site-packages/zxingcpp.cpython-38-x86_64-linux-gnu.so

All other files had identical checksums.

**Comment by tl121** [comment]
That should have been --appimage-mount to expose the two different directories.  From other experiments, removing this one file from the build makes the build deterministic.

**Comment by cculianu** [comment]
@echterago Thoughts on this? It appears zxing-cpp has some non-reproducible stuff in it? Maybe they embed the build time in the file or somesuch? If so maybe we need to maintain our own patch that removes this.

**Comment by tl121** [comment]
if you go to the zxing-cpp github and build from source you can see that repeated builds differ.  It’s not just a few bytes here and there.  Lots of differences in hex dumps.  Perhaps we can just download one of the projects wheels.  There are several, built for various OS and hw arch.  I see that several hashes in the EC deterministic builds are for these files. This might be able to bypass the Make process.  Or perhaps changes in the Make tools will help.

I started messing around with the build process when I discovered that app images from my pull request failed to work with the new Trezor software, although running from source did.  Eventually, after many attempted builds, I got an appimage to work, but then I figured I’d better see if it was reproducible.  It wasn’t. Eventually after some sidetracking, I identified the errant file and it’s been in the EC master for some time.  So that ‘s why I put out the warning.  I will continue to work on figuring out the build process, with the goal of getting you a complete fix for the Trezor changes as promised.

**Comment by cculianu** [comment]
Nice detective work, man. My intuition tells me 70% chance there is some tag inside one of the .cpp files or something that causes it to embed build time. I would help you investigate this further but I am preparing for a long plane journey and have no extended "me" time necessarily today to help out.  But I suspect there is some git-build-commit or build-time tag in one of the .cpp files.. that would be a place to start. And then yeah we could download and re-patch a .whl or maintain our own branch of the repo for this (we have done that before).

**Comment by EchterAgo** [comment]
The difference is in the build path pip uses, which ends up in the executable. Somehow strip does not remove the paths and the executable is stripped already. We'd need to build from a fixed directory or find a way to override the directory pip uses to install.

Docker build:

```
$ strings squashfs-root/usr/lib/python3.8/site-packages/zxingcpp.cpython-38-x86_64-linux-gnu.so|grep PDFDecoder.cpp
/tmp/pip-install-v5ggto90/zxing-cpp_0b150bc8b3ce49749e069816ec8922ee/core/src/pdf417/PDFDecoder.cpp
```

Native build:

```
$ strings /home/ago/src/zxing-cpp/env/lib/python3.11/site-packages/zxingcpp.cpython-311-x86_64-linux-gnu.so|grep PDFDecoder.cpp
A/home/ago/src/zxing-cpp/wrappers/python/core/src/pdf417/PDFDecoder.cpp
```

The issue is that the `v5ggto90` and `0b150bc8b3ce49749e069816ec8922ee` part in `/tmp/pip-install-v5ggto90/zxing-cpp_0b150bc8b3ce49749e069816ec8922ee` are different each time.

**Comment by EchterAgo** [comment]
Ok, so the path is actually embedded because of the usage of `__FILE__` in the error macros of `zxing-cpp`:

https://github.com/zxing-cpp/zxing-cpp/blob/d1c34452b0a0a9a4936666e969c88f774f399c78/core/src/Error.h#L55

I'm not quite sure how we'd best sanitize this, I'll try to find out soon.

**Comment by cculianu** [comment]
Yep. That must be it. Probably one would have to write a 3-liner patch that just replaces `__FILE__` with either `__FUNCTION__` or a fixed string...

**Comment by tl121** [comment]
Pull request #2790 fixes this issue.
