### ISSUE TITLE
Code signature changed?

### ISSUE THREAD

**Issue by AmnaSN** [Electron-Cash/Electron-Cash#2803]
Hi , I just noticed that the version 4.4.0 is signed by "Calin Culianu (XB7TABN5UN)" instead of "Electron Cash LLC (3Q224F79FA)" and wanted to confirm about this change.

**Comment by cculianu** [comment]
Nice catch. Yes.. I couldn't figure out how to export the Electron Cash LLC private key from my 1 box to my signing box. I gave up and just signed with my own developer key rather than the project's developer key.

Yes, can confirm, this is legit.

**Comment by AmnaSN** [comment]
Thanks for the confirmation.
