### ISSUE TITLE
build-linux/appimage not reproducible

### ISSUE THREAD

**Issue by tl121** [Electron-Cash/Electron-Cash#2807]

**Comment by tl121** [comment]
Two builds of 4.4.0 produced different app images, neither of which matched the sha256sum in the release.  The problem was traced down to the following file, shown here from the two builds that I made a few minutes apart.
< a8c44d581dc8eb78e8d11df79d764f50cd1fc61b0e0cdc0872e2f62832f5c0f8  ./usr/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.cpython-311-x86_64-linux-gnu.so
---
> 74a753579b17f700812b9a3d3595dcf9dea512a3e86a97611558a8136a489d8f  ./usr/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.cpython-311-x86_64-linux-gnu.so

Does any one have suggestions on the easiest way to fix this?

**Comment by EchterAgo** [comment]
From Telegram:

```
ichundes#102; 🐪, [‎06‎/‎03‎/‎2024 ‎21‎:‎00]
appimage is not reproducible:
$ diff -urN squashfs-root.ago/ squashfs-root.ec/
Binary files squashfs-root.ago/usr/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.cpython-311-x86_64-linux-gnu.so and squashfs-root.ec/usr/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.cpython-311-x86_64-linux-gnu.so differ

ichundes#102; 🐪, [‎06‎/‎03‎/‎2024 ‎21‎:‎00]
the pip build isolation path leaks into the binary

ichundes#102; 🐪, [‎06‎/‎03‎/‎2024 ‎21‎:‎00]
but otherwise everything the same

ichundes#102; 🐪, [‎06‎/‎03‎/‎2024 ‎21‎:‎02]
seems cryptography also uses something like C __FILE__ in rust

ichundes#102; 🐪, [‎06‎/‎03‎/‎2024 ‎21‎:‎04]
@Oe4ef622 for the 4.4.0 package in AUR we should add a zxing-cpp dependency

ichundes#102; 🐪, [‎06‎/‎03‎/‎2024 ‎21‎:‎14]
[In reply to Calin Culianu (NilacTheGrim#2186; 🔑)]
i still haven't been able to figure out where that /tmp/pip-install path is actually built, grepping the pip sources didn't give me anything :\

ichundes#102; 🐪, [‎06‎/‎03‎/‎2024 ‎21‎:‎22]
https://github.com/pypa/pip/blob/ae5fff36b0aad6e5e0037884927eaa29163c0611/src/pip/_internal/utils/temp_dir.py#L177

ichundes#102; 🐪, [‎06‎/‎03‎/‎2024 ‎21‎:‎22]
ah

ichundes#102; 🐪, [‎06‎/‎03‎/‎2024 ‎21‎:‎50]
https://github.com/pypa/pip/issues/7808#issuecomment-770275723

ichundes#102; 🐪, [‎06‎/‎03‎/‎2024 ‎21‎:‎50]
apparently nix has a patch for this

ichundes#102; 🐪, [‎06‎/‎03‎/‎2024 ‎21‎:‎50]
otherwise it can't be disabled without also disabling build isolation, which we want

ichundes#102; 🐪, [‎06‎/‎03‎/‎2024 ‎21‎:‎51]
can't fix the seed for mkdtemp either
```

**Comment by tl121** [comment]
The non-determinism can be fixed easily by one change:  put back cryptography==3.3.2 in
contrib/deterministic-build/requirements-binaries.txt

This built deterministically and the linux appimage ran on Ubuntu 20.04 22.04 and 23.10.  I didn't test the other builds. Is there any reason not to stick with the older version of cryptography?

**Comment by tl121** [comment]
FWIW, I have an apparently working aarch64 appimage that runs on the Raspberry Pi 4 running Ubuntu 22.04 that also suffers from same non-determinism with cryptography.  (Running the build process on a PI4 is *very* slow  :-) )

**Comment by EchterAgo** [comment]
I fixed this by enabling rusts unstable `trim-path` feature and also a small patch for `cryptography` reproducibility: https://github.com/pyca/cryptography/commit/857d6b1d2fb1b93251a89ca3534e2a28b32c4950

**Comment by EchterAgo** [comment]
SHA256 of AppImage of latest master:

```
d561a19852b6b6f981c6d2a30c3643a5f885231b671cdeefd47771a4175c7d97  Electron-Cash-4.4.0-9-g8e966d3c5-x86_64.AppImage
```

**Comment by tl121** [comment]
Roger that,  ....7d97   ;-)
