### ISSUE TITLE
Paycodes require "paycode:" prefix

### ISSUE THREAD

**Issue by BeltranLeo** [Electron-Cash/Electron-Cash#2810]
When trying to copy an RPA address into the Send field, it is only detected as valid if it contains the `paycode:` prefix.

![image](https://github.com/Electron-Cash/Electron-Cash/assets/32263015/0dc94dc4-4052-4e93-8ebd-04cc68695ef1)

**Comment by fyookball** [comment]
Thanks for raising the issue but offhand it seems low priority not worth fixing right now.  The code to deal with parsing uri schemes was a bit tricky even though I understand the default BCH addresses allow this.  Not planning to fix this soon , so closing for now.
