### ISSUE TITLE
Support P2SH32

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#2831]
[P2SH32](https://gitlab.com/0353F40E/p2sh32/-/tree/main) has been activated on mainnet BCH since 2023, yet EC not only cannot make use of it nor send to it, the address format doesn't show in transaction detail window! Right P2SH32 simply shows as "unknown": 

![image](https://github.com/Electron-Cash/Electron-Cash/assets/34949601/74dbc93b-9643-4c20-a716-153c4d848797)

Applications such as Anyhedge/BCHBull V2 library that makes use of P2SH32 for its enhanced security are beginning to pop up, and it's probably time for EC to support it. If proper support all at once is difficult it can be broken down into chunks:

1. Support for address display in transaction detail window
2. Support for sending to P2SH32

--- low priority below this line ---

3. Use P2SH32 for multisig (perhaps along with proper Schnorr-multisig support)

**Comment by cculianu** [comment]
I think both (1) and (2) can be done together since they just depend on the `Address` class in `address.py` being updated to support this. I'm surprised I forgot to do this. Thanks for opening the issue this is relatively straightforward and should be done soon.

**Comment by cculianu** [comment]
Update: I just checked the code. `Address` class supports p2sh32 and it renders in the UI for me and also works in send tab.

Can you explain why you think it's not working? Any ways to reproduce it not working?

**Comment by cculianu** [comment]
Hypothesis: I believe user forgot to check the "Download Input Data" checkbox and thus assumed p2sh32 is not working....
