### ISSUE TITLE
Feature Request:  "Use Multiple Change Addresses" 

### ISSUE THREAD

**Issue by SZemanek** [Electron-Cash/Electron-Cash#2835]
One feature the BTC Electrum wallet has that Electron Cash surprisingly does not have is the "Use Multiple Change Addresses" feature.  

Quite simply, instead of having just one change address, BTC Electrum can send the change in randomized amounts to 3 different change addresses to further obfuscate the transaction.

**Comment by RowanSkie** [comment]
Uh... Electron Cash already has it? (I disabled mine because this wallet uses CashTokens.)

![image](https://github.com/Electron-Cash/Electron-Cash/assets/11764533/b8e038e3-7400-4f38-8354-484eb7636e7b)

**Comment by cculianu** [comment]
Yeah we have this. Closing...

**Comment by SZemanek** [comment]
I swear, I thought I looked everywhere.   I googled.   Found nothing.  It's not in the same place as on BTC-Electrum.   I feel like a dumbass now. 

For anyone looking for this setting:

Open your Electron Cash wallet.  > Tools > Preferences > Transactions > Use Multiple Change Addresses.
