### ISSUE TITLE
extremely slow to get to main screen after password, very sluggish app response

### ISSUE THREAD

**Issue by DaSpawn** [Electron-Cash/Electron-Cash#621]
I have latest version of electron cash via the ppa (3.1.5). running Ubuntu 17.10.  many "program not responding" windows, have to keep clicking wait

if I strace the program I seen endless stream of:
`futex(0xa89488, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1522338833, tv_nsec=339323000}, 0xffffffff) = 0
futex(0xa89420, FUTEX_WAKE_PRIVATE, 1)  = 0
futex(0xa8948c, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xa89420, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xa89488, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1522338833, tv_nsec=394224000}, 0xffffffff) = 0
futex(0xa89420, FUTEX_WAKE_PRIVATE, 1)  = 0
futex(0xa8948c, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xa89420, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xa89488, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1522338833, tv_nsec=406388000}, 0xffffffff) = 0
futex(0xa89420, FUTEX_WAKE_PRIVATE, 1)  = 0
futex(0xa8948c, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xa89420, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xa89488, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1522338833, tv_nsec=412040000}, 0xffffffff) = -1 EAGAIN (Resource temporarily unavailable)
futex(0xa89420, FUTEX_WAKE_PRIVATE, 1)  = 0
futex(0xa8948c, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xa89420, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xa89488, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1522338833, tv_nsec=445079000}, 0xffffffff) = 0
futex(0xa89420, FUTEX_WAKE_PRIVATE, 1)  = 0
futex(0xa8948c, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xa89420, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xa89488, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1522338833, tv_nsec=499953000}, 0xffffffff) = -1 EAGAIN (Resource temporarily unavailable)
futex(0xa89420, FUTEX_WAKE_PRIVATE, 1)  = 0
futex(0xa8948c, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xa89420, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xa89488, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1522338833, tv_nsec=512057000}, 0xffffffff) = 0
futex(0xa89420, FUTEX_WAKE_PRIVATE, 1)  = 0
futex(0xa8948c, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xa89420, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xa89488, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1522338833, tv_nsec=550946000}, 0xffffffff) = 0
futex(0xa89420, FUTEX_WAKE_PRIVATE, 1)  = 0
`

takes about 5 minutes to finally get to main window after entering password, all actions in the program are very very slow

**Comment by DaSpawn** [comment]
Interesting enough I tried the new version on a laptop I just clean installed with Ubuntu 17.10 and used my recovery seed to recreate the wallet and it opened right up without problem this time

However, when I got back to the office today and tried to open the existing wallet with the newest version the problem persists.  I deleted everything but the wallet files from the .electron-cash folder, and did not solve the issue.  

So eventually deleted the entire .electron-cash folder and started with fresh wallet files restored from seed and the problem is gone

**Comment by fyookball** [comment]
how many transactions and addresses?

**Comment by fyookball** [comment]
ok.  obviously its a performance issue somewhere but would be much easier to debug if i had access. Would it be possible to get a view only key (master public key) via private communication (dont post it publicly) for my personal use in debugging?

**Comment by DaSpawn** [comment]
can do, shall I message on reddit jonald_fyookball?.

**Comment by fyookball** [comment]
yes

**Comment by rt121212121** [comment]
@fyookball @DaSpawn Did you guys reach a resolution on this?

**Comment by DaSpawn** [comment]
Not yet unfortunately, but I can help with whatever is needed to solve this (I am a novice with Python but can help debug as I know numerous other languages/systems)

**Comment by rt121212121** [comment]
About the only thing you can do actively is run electron cash in verbose mode (--verbose command line argument) and send the log to one of us.  Leading someone through the processing of debugging sounds like a lot of work.

How about you start by emailing me the verbose log at roger.taylor.email@gmail.com? 

If that isn't enough, I might get you to email me the xpub you were going to send Jonald.

**Comment by DaSpawn** [comment]
I did message Jonald with the xpub on May 2nd.  I also suspect could be a bit of work to debug.  I tried to run with -verbose and there is nothing out of the ordinary from my other wallets and there is no output while the application is hanging.  I will still send the log

**Comment by fyookball** [comment]
you can send it to @rt121212121 if he has time, sorry i have been busy with some other responsibilities.

**Comment by DaSpawn** [comment]
will do!

**Comment by rt121212121** [comment]
Ping!  The ball is in your court when you get the time.  As discussing over email, this appears to be when your wallet gets written to disk.  The xpub did not reproduce the problem, and this needs to be profiled by someone who has a private key where it happens.

**Comment by marceloneil** [comment]
We could generate a private key with a bunch of dust transactions

**Comment by DaSpawn** [comment]
Life has been bit busy..  will get the details soon as I can per the email conversation (pasting details below to keep info on this ticket/issue also).  I will also double check/resend xpub

--------------------------
(I ran in verbose mode and sent log to @rt121212121)

[profiler] write 705.7047
[profiler] save_transactions 705.8049

What this says is that you have so much data, that Electrum Cash is struggling to write it. 

lib/wallet.py:save_transactions() is decorated with the profiler to give the line above
lb/storage.py:write() is also decorated with the profiler to give the other line above.

What you need to do is profile sub-sections of the lib/storage.py:_write() function and work out what parts of it are taking what time.  You'll probably have to put statments like this around various parts to narrow it down.  

        t0 = time.time()
        # Code of interest to "profile"
        t = time.time() - t0
        print_error("[profiler]", "SOME DESCRIPTIVE TEXT FOR THE TIMED CODE", "%.4f"%t)

**Comment by SomberNight** [comment]
Is the wallet encrypted? If so, do you have pycryptodome installed? pyaes (the fallback) is very slow.

**Comment by DaSpawn** [comment]
I just installed that module and updated to 3.3.1 and it is loading the problematic wallet much faster but still slower than a wallet with less activity.  I also tested a transaction that would error out before (but still actually send) and now the transaction goes through without error, but still sluggish (took about a minute for password dialog to appear)

I have not had time to do the debug tests unfortunately

**Comment by cculianu** [comment]
We've done some performance fixups since this issue was opened.  Reopen if you still are unsatisfied.
