### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'E:\\Electrum-Bitcoin\\electron_cash_data\\certs\\bitcoincash.quangld.com.temp'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#622]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\util.py", line 613, in run_with_except_hook
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\interface.py", line 233, in run
  File "site-packages\electron_cash-3.1.6-py3.5.egg\electroncash\interface.py", line 175, in get_socket

PermissionError: [Errno 13] Permission denied: 'E:\\Electrum-Bitcoin\\electron_cash_data\\certs\\bitcoincash.quangld.com.temp'
```

Reporter
------------

This issue was reported by 8 user(s):

| Electrum Version  | Operating System  | Wallet Type  | Locale |
|---|---|---|---|
| 3.1.6  | Windows-10-10.0.16299 | standard | en_US |
| 3.1.6  | Windows-7-6.1.7601-SP1 | standard | en_CA |
| 3.1.6  | Windows-7-6.1.7601-SP1 | standard | en_CA |
| 3.1.6  | Windows-7-6.1.7601-SP1 | standard | en_CA |
| 3.1.6  | Windows-7-6.1.7601-SP1 | standard | en_CA |
| 3.1.6  | Windows-7-6.1.7601-SP1 | standard | en_US |
| 3.1.6  | Windows-7-6.1.7601-SP1 | standard | en_US |
| 3.1.6  | Windows-7-6.1.7601-SP1 | standard | en_US |

Additional Information
------------------------

> I was doing nothing but would not connect to any server!

---

> viewing a transaction

---

> closing the app

---

**Comment by rt121212121** [comment]
Matched to:
https://github.com/spesmilo/electrum/issues/4097
Related to:
https://github.com/spesmilo/electrum/issues/4059
Unclear if this is fixed by the above commit, which came with a link:
https://stackoverflow.com/questions/7433057/is-rename-without-fsync-safe

**Comment by cculianu** [comment]
I think it's a race condition.  Closing this and leaving #631 open.
