### ISSUE TITLE
Electron Cash 2fa issue BCH - solved!

### ISSUE THREAD

**Issue by drumy1** [Electron-Cash/Electron-Cash#656]
Dear Electrum team,
I am in need of your help. At the time of the BTC/BCH Fork I had my funds on Airbitz wallet.

I retrieved the BCH from airbitz and followed the instructions on this article
https://medium.com/airbitz/how-do-i-get-my-bitcoin-cash-from-airbitz-e97982e3fc4c
(This article previously advised to setup a wallet using a trusted coin 2fa - it appears they have since edited this out)

After following those steps. I have created a wallet that shows the correct amount of BCH. 
The BCH is in this address
3Ek7VD1tjzgfKtNesv4QJSvSn4TiHWzHhD

And verified on the blockchain
https://bitinfocharts.com/bitcoin%20cash/address/3Ek7VD1tjzgfKtNesv4QJSvSn4TiHWzHhD

When trying to send the funds from electron cash I get an error message (the transaction was rejected due to network rules) - see attached picture

From reading online it seems the error message is associated with the initial 2fa setup, and some people are saying it can be solved by creating a new electron cash wallet using the same seed but disabling 2fa.. I am unfortunately getting nowhere with this.

I have used Electron Cash to show my private keys for this public address (using the export private keys function), then I have tried setting up another wallet with electron cash and doing a sweep into that wallet but when I try that I get an error message saying

'no inputs found (note that inputs need to be confirmed)' see attached picture.

I have also tried to sweep the funds into a wallet on my coinomi app but when I enter my private key the message comes up saying there are no funds in that address. (see attached picture)
This maybe a private key address format issue, as coinomi only accepts WIF format and I believe Electron exports only WIF compressed.
I have tried to convert WIF Compressed to WIF using Bitaddress.org however when I do this, it still doesnt work and also shows a different public key than my Electron Cash BCH address. 
So this leads me to believe that either im doing something wrong or in Electron Cash private key export the private key that appears next to the public address with the funds in it is wrong.  

I have also tried restoring an Electron wallet using the seed ive got, but that didnt work either.
Not sure if my seed is wrong (its the only one i have) or if im doing it wrong.

Now the wallet is setup with 2fa I am unable to send the funds out of Electron Cash

Basically just want the funds moved to a wallet/address that will allow me to send from it!
 
Let me know if this is something you can assist with and what I'll need to provide.

I've got a back up of the electron cash wallet file and an export of the public and private keys and my electron cash seed. But again im not sure if the seed is correct, or if the private key that electron cash is telling me is associated with my wallet is actually the one associated with that wallet !

![electron cash wallet screenshot showing balance](https://user-images.githubusercontent.com/38770610/39336590-add7bac2-49fb-11e8-9419-4bb38873eb9c.jpg)
![send error - this transaction was rejected by network rules](https://user-images.githubusercontent.com/38770610/39336592-ae09189c-49fb-11e8-9b8c-263a6d3293b8.jpg)
![no inputs found error](https://user-images.githubusercontent.com/38770610/39336593-ae387c18-49fb-11e8-9395-4b589d7f9f6d.jpg)
![coinomi error - this private key does not contain any funds](https://user-images.githubusercontent.com/38770610/39336594-ae69ae5a-49fb-11e8-8aff-b8fac92620c4.png)

**Comment by marceloneil** [comment]
Try this guide instead: https://github.com/fyookball/electrum/issues/41#issuecomment-357468208

**Comment by marceloneil** [comment]
For recovering funds from a 2fa wallet

**Comment by drumy1** [comment]
thanks for the reply. 
Trusted Coin were able to help me with this. 
I didnt have the back up seed for the 2fa as per the instrcutions you linked hence why iwas getting nowhere...
But i did have the actual 2fa working on my authenticator so trusted coin were able to help me.
They were actually really helpful and sorted it out all over email without any issue. 
 

Sent: Monday, April 30, 2018 at 12:35 PM

**Comment by marceloneil** [comment]
Awesome, glad you got it sorted out!
