### ISSUE TITLE
Debian 9 installation issue

### ISSUE THREAD

**Issue by davehorton** [Electron-Cash/Electron-Cash#791]
I followed the instructions to download and build on  fresh Debian 9 box.  The build went ok but when I try to run I get this:

```root@drachtio-nyc3-02:/usr/local/src/Electron Cash-3.3# ./electron-cash
Traceback (most recent call last):
  File "./electron-cash", line 392, in <module>
    d.init_gui(config, plugins)
  File "/usr/local/src/Electron Cash-3.3/lib/daemon.py", line 303, in init_gui
    gui = __import__('electroncash_gui.' + gui_name, fromlist=['electroncash_gui'])
  File "/usr/local/src/Electron Cash-3.3/gui/qt/__init__.py", line 36, in <module>
    from PyQt5.QtGui import *
ImportError: /usr/local/lib/python3.5/dist-packages/PyQt5/QtGui.so: undefined symbol: PySlice_AdjustIndices
```
any thoughts?

**Comment by davehorton** [comment]
Here are my commands and more info
```bash
cd /usr/local/src/
wget https://electroncash.org/downloads/3.3/win-linux/ElectronCash-3.3.tar.gz
tar xvfz ElectronCash-3.3.tar.gz 
apt-get install python3-setuptools
apt-get install python3-pip
pip3 install PyQt5
cd Electron\ Cash-3.3/
python3 setup.py install
./electron-cash
root@drachtio-nyc3-02:/usr/local/src/Electron Cash-3.3#  python3 --version
Python 3.5.3
```

**Comment by marceloneil** [comment]
PySlice_AdjustIndices seems to have been added in Python 3.6.1, and I think backported to Python 3.5.4. So either upgrade python, or try installing [`python3-pyqt5`](https://packages.debian.org/stretch/python3-pyqt5) from the apt repositories

**Comment by rt121212121** [comment]
Should we bump up the hard-coded constraints?
```python
if sys.version_info < (3, 5, 2):
    sys.exit("Error: Must be using Python 3.5.2 or higher")
```

**Comment by marceloneil** [comment]
I don't think so. Debian 9 currently ships 3.5.3 which still works fine. Its just the version of pyqt5 installed was built against 3.5.4

**Comment by davehorton** [comment]
Well, I'm confused about all of this because I installed a stock Debian 9 from digital ocean and followed these instructions: http://electroncash.readthedocs.io/en/latest/docs/install.html#installing-on-linux

so I installed pyqt5 via your instructions, but now you are saying it is the wrong version?

**Comment by marceloneil** [comment]
Debian is just providing an _older_ version of python - which is fine except for the edge case that you just experienced. My assumption would be that the Debian version of pyqt5 would be compatible. Is it working out for you?

**Comment by afduggirala** [comment]
Im getting this error trying to run 3.3.1 on Ubuntu 18.05
ModuleNotFoundError: No module named 'PyQt5.sip'
All I know is I have the python3-pyqt5 package installed, don't know how it got installed though.
Please help.

**Comment by cculianu** [comment]
I think someone else had this issue.  See #850. I think a combination of installing sip and also deleting old versions of installed Electron-Cash did the trick.

Read the issue linked above and hopefully it'll work for you.
