### ISSUE TITLE
Consider moving all code into a top-level package

### ISSUE THREAD

**Issue by mhsmith** [Electron-Cash/Electron-Cash#807]
[Electrum has now done this](https://github.com/spesmilo/electrum/commit/097ac144d976eb46dff809e1809783dc78ab6d8b). As per the current `setup.py`, I assume we'd want our package to be called `electroncash` rather than `electrum`, otherwise it would be impossible to install both programs in the same environment. This will unfortunately make merges from Electrum harder than they were before, but no harder than they are right now since Electrum made this change.

Advantages:
* Using the same directory names in the source code and at runtime is simpler, and is the normal Python practice.
* The workarounds for the mismatching names can be removed from each of the GUIs, and will be unnecessary in the new Android app.
* It would make it easier to run the unit tests, as discussed in #723. Tests which are easier to run are more likely to be kept up to date. (The [other test issue](https://github.com/fyookball/electrum/pull/723/commits/0b5d43f51e980a3a8eba53df30ad00f1ad1d33a4) in that PR had been broken for over a month, so evidently nobody had run the tests in that time.)

Disadvantages:
* All open branches and pull requests will have to be rebased.
* The workarounds for the mismatching names must be removed from each of the GUIs.

**Comment by cculianu** [comment]
I admit it's rather bizarre the way the dirs are mapped to module names right now.

I fear this may create a subtle source of bugs unless we are careful with text searches (I guess it shouldn't be too bad.. but still).

So no more "electroncash_gui" namespace?  Everything is filed under "electroncash" now? (Eg electroncash.gui)??

This external plugins will also be affected... :/

Are you sure you want to open this can of worms? :P  

(Clearly I'm of the pragmatic mindset: if it ain't broke, don't fix it.)

**Comment by fyookball** [comment]
i'd rather avoid this if not necessary

**Comment by kyuupichan** [comment]
I think this is a good idea.  Electron Cash now warns it's using obsolete features with Python3.7 because of the current hack

**Comment by rt121212121** [comment]
Some things we need to address:
* The smoothest workflow for replacing cherry-pick, as we can no longer use
it to cleanly map commits.
* How to retain git history, note that electrum did something wrong, and
the history of files was lost in github. It appears to have detected the
renames, but the history is cut off at the point of the move.

For example:
https://github.com/spesmilo/electrum/commits/master/electrum/network.py

**Comment by rt121212121** [comment]
Here's the electrum commit, which would be a good point of reference to ensure nothing is missed.

https://github.com/spesmilo/electrum/commit/097ac144d976eb46dff809e1809783dc78ab6d8b#diff-554a6e574ded9f74c5821ea55e34d488

**Comment by cculianu** [comment]
Ok, this wasn't quote handled fully by #2020 but partially.  The reason why it wasn't done completely is that it's a lot smaller a diff to do it the way it was done in #2020.  Ideally we'd have `electroncas/gui` and `electroncash/plugins` but that would break existing external plugins -- and maybe that would be a major revision thing.

**Comment by mhsmith** [comment]
Yeah, I don't think that would be worth the trouble.
