### ISSUE TITLE
BitPay invoice unsupported on iOS

### ISSUE THREAD

**Issue by alexwagg** [Electron-Cash/Electron-Cash#808]
When I copy a BitPay invoice URL from a BitPay invoice screen into Electrum-iOS send screen->pay_to input field, I get incorrect address type. Are BitPay invoice urls supported?

**Comment by cculianu** [comment]
They weren't initially implemented for iOS, but I do think they work on the desktop version (not much of a consolation to you if you want to use it only on iOS).

I'm getting ready to take a small 2-week vacation so I may not get to implement this until I get back.

But it's on my to-do list!

**Comment by cculianu** [comment]
This has now been implemented in latest github.  I will push out an update to the store this week.

Fixed by #908
