### ISSUE TITLE
fee issues 

### ISSUE THREAD

**Issue by fyookball** [Electron-Cash/Electron-Cash#827]
I'm not sure what you are aware but you've changed the fee calculator and it is not working efectivly.

If I click send "MAX" and adjust the fee to 0 the max balance should display the max balance it does not. If I set the fee to 0 the click max again shows less than the max balance and then editing the fee does not change the max balance. Prior versions of Electrum and Electron used to adjust the transaction balance when you changed the fee.

It is nice if you keep the historic behavior so people can add the extra satoshis to the fee and send a round number.

also since V3.1 you've changed the fee policy, after the 32MB hard fork I was able to send free transactions using electron, now that I've upgraded to 3.2 I am not able to send a low fee or free transaction as Electron won't broadcast it.

the historic behavior is preferred, (FYI I have my preference set to edit fee manually)

**Comment by jchavannes** [comment]
Not sure if this is related, but when editing a fee it always rounds to 100 sats.

For example, if I put in a fee of 226 satoshis, it will round to 300 satoshis.

**Comment by cculianu** [comment]
I don't think this is relevant anymore. It appears to me that the behavior/bugs described in this issue are no longer the case. If that's not the case, please do let me know and I will re-open.
