### ISSUE TITLE
Error build apk for android

### ISSUE THREAD

**Issue by johnlarfour** [Electron-Cash/Electron-Cash#831]
I follow the guide in readme step by step but I can not build the apk. I use ubuntu 16.04
This is the output: https://hastebin.com/erojivipur.md

**Comment by marceloneil** [comment]
You need to download the [CrystaX NDK](https://www.crystax.net), and set the NDK value in `buildozer.spec` to point towards it

**Comment by johnlarfour** [comment]
I do. I have crystax-ndk-10.3.2 in /home/ubuntu/Downloads 
And in the buildozer.spec is set android.ndk_path = /home/ubuntu/Downloads/crystax-ndk-10.3.2

**Comment by marceloneil** [comment]
Hmmm, buildozer automatically downloads the google NDK to the folder if it can't find a valid NDK. I suspect something weird like that happened. Maybe try re-extracting the CrystaX NDK and clearing `.buildozer/`

**Comment by marceloneil** [comment]
I had the same error as you before:
```
[ERROR]:   The python3crystax recipe can only be built when using the CrystaX NDK. Exiting.
```
The issue for me was that the NDK dir didn't contain CrystaX for whatever reason, and buildozer installed the google NDK overtop of it. What are the outputs of these commands? (replace `.android/crystax` with your path
```
$ ls .android/crystax
BACKERS.md     find-win-host.cmd  ndk-gdb-py	  prebuilt		     sources
build	       GNUmakefile	  ndk-gdb.py	  README.md		     tests
checkbuild.py  ndk-build	  ndk-gdb-py.cmd  realpath		     toolchains
crew	       ndk-build.cmd	  ndk-stack	  RELEASE.TXT		     tools
crew.cmd       ndk-depends	  ndk-which	  remove-windows-symlink.sh
docs	       ndk-gdb		  platforms	  samples
$ du -sh .android/crystax
7.7G	.android/crystax
```

**Comment by johnlarfour** [comment]
`$ ls .android/crystax`
`ls: cannot access '.android/crystax': No such file or directory`

`$ ls .android`
`adbkey      androidwin.cfg  cache             sites-settings.cfg
adbkey.pub  avd             repositories.cfg`

**Comment by marceloneil** [comment]
> (replace .android/crystax with your path)

**Comment by marceloneil** [comment]
As in the path to _your_ installation of crystax

**Comment by johnlarfour** [comment]
my bad, sorry.
`~/Downloads/crystax-ndk-10.3.2$ ls`
`build          ndk-build.cmd   ndk-stack    remove-windows-symlink.sh
docs                ndk-depends     ndk-which    samples
documentation.html  ndk-gdb         platforms    sources
find-win-host.cmd   ndk-gdb-py      prebuilt     tests
GNUmakefile         ndk-gdb.py      README.TXT   toolchains
ndk-build           ndk-gdb-py.cmd  RELEASE.TXT`

`~/Downloads$ du -sh crystax-ndk-10.3.2`
`1,3G	 crystax-ndk-10.3.2`

**Comment by marceloneil** [comment]
1,3G is too small. Something is wrong in that folder, it should be ~7,7G
```
$ du -sh .android/crystax-ndk-10.3.2-linux-x86_64.tar.xz 
707M	.android/crystax-ndk-10.3.2-linux-x86_64.tar.xz
$ mkdir .android/test
$ tar xf .android/crystax-ndk-10.3.2-linux-x86_64.tar.xz -C .android/test 
$ du -sh .android/test 
7.7G	.android/test
```

**Comment by johnlarfour** [comment]
oh yes, the problem was just that, I had not used it `tar xf` but I simply used it `Extract here`
Thank you for your help.

**Comment by marceloneil** [comment]
Great :+1:, if there are any other errors let me know

**Comment by johnlarfour** [comment]
Now the apk is builded, but, when I open it crash.
When I build I receive this error:
`error: kivy/core/window/window_info.c: No such file or directory`
`fatal error: no input files`
`error: command '/usr/bin/ccache' failed with exit status 1`

**Comment by marceloneil** [comment]
Can you provide a full log?

**Comment by marceloneil** [comment]
And if the app crashes when you open it on android, can you see what `adb logcat` outputs?

**Comment by johnlarfour** [comment]
I leave here the log file (in the shell I can not see the full log) 
at this moment I do not have the possibility to use adb, maybe if it will serve I will post it tomorrow

[log.txt](https://github.com/fyookball/electrum/files/2308251/log.txt)

**Comment by marceloneil** [comment]
Thanks. Make sure you ran `make theming`

**Comment by johnlarfour** [comment]
yes i do make theming.
This is the log of adb https://pastebin.com/Z9D8jNtY

**Comment by fyookball** [comment]
hmm...wrong python version.  i know we saw that somewhere before. do you recall @marceloneil @rt121212121

**Comment by johnlarfour** [comment]
yes the error is this: 

>      I  Error: Must be using Python 3.5.2 or higher

**Comment by mhsmith** [comment]
The old Android app is no longer supported. Please close this issue.
