### ISSUE TITLE
BitPay testnet is using incorrect CASHADDR_PREFIX

### ISSUE THREAD

**Issue by jonas-lundqvist** [Electron-Cash/Electron-Cash#867]
This might not be an issue in Electron-Cash but rather BitPay.
I submitted this to BitPay also (ticket 246889) but I think it would be good to at least inform people here and track it.

When using the BitPay testnet service the invoice will be of the form:
bitcoincash:?r=https://test.bitpay.com/i/RdabihnTM4VR1bkEGaCxTB

Normally testnet addresses will have the prefix "bchtest", not "bitcoincash".
If anyone needs to run Electron-Cash in testnet mode and test BitPay invoices the following line needs to be changed from:
cls.CASHADDR_PREFIX = "bchtest"
to:
cls.CASHADDR_PREFIX = "bitcoincash"
in lib/networks.py line 79.

**Comment by jonas-lundqvist** [comment]
Update from BitPay:
<redacted>, Oct 3, 11:44 AM EDT

Jonas, thank you for the feedback. You are correct and we are working on this change.
I will leave this ticket on hold and update you when we have made the update to test and production. Let me know if you have any other questions. Thank you.

**Comment by cculianu** [comment]
They have yet to fix this.  Weird.

I have to spend $1 each time I really want to test this.  Annoying.

**Comment by cculianu** [comment]
Welp, closing to keep issue count down.
