### ISSUE TITLE
Help With Install

### ISSUE THREAD

**Issue by oopsiedaisy726** [Electron-Cash/Electron-Cash#869]
Hey everyone! 
I have looked everywhere on the www.electroncash.org for an answer, but I simply don't understand how to install it on my computer. I've downloaded the exe and it opens up fine and I can connect to my wallet, but it's no where to be found on my computer. Is there a comprehensive guide to accomplish this somewhere?

Ultimately I am trying to install the tumbler plugin and the instructions to do that are super confusing. In the githup FAQ it talks about file structure and command line commands which are just not very well written.

Can anyone help me with understanding this?

**Comment by EchterAgo** [comment]
If you mean the CashShuffle plugin, be careful with those instructions as they result in a vulnerable installation of Electron Cash:

cashshuffle/cashshuffle-electron-cash-plugin/issues/36

There seems to be a general lack of installation instructions for Linux.

For installing the plugin, download the latest release ("shuffle_050.zip") from here:

https://github.com/cashshuffle/cashshuffle-electron-cash-plugin/releases

Open Electron Cash, go to "Tools" | "Installed Plugins" and click the "Add Plugin" button. Select the plugin release you just downloaded. Confirm that you understand the risks and dangers (do read the dialog, don't just blindly click through) and click "Install". Restart Electron Cash and you now should see the "Shuffle" tab in the main window.
