### ISSUE TITLE
need to unify QR codes

### ISSUE THREAD

**Issue by markblundeberg** [Electron-Cash/Electron-Cash#871]
The receive tab and address dialog make quite different QR codes for the same address.

* Receive tab QR encodes: `BITCOINCASH:QR8ZT8NCV94RSNC0LFKUJ3QVDZU2JTY2ASQ44CJHKU`
* Address tab QR encodes: `qr8zt8ncv94rsnc0lfkuj3qvdzu2jty2asq44cjhku`

Both QR codes end up as the same size because, even though the first one is longer, it uses all-uppercase which lets it use the compact QR alphanumeric encoding. I believe the prefix is a good idea in general, so I am leaning towards the prefixed, all-caps option.

(the reason for the difference: address_detail.py uses to_ui_string(), and main_window.py receive tab uses the update_receive_qr() function which does more things)

![screenshot from 2018-09-28 10-07-50](https://user-images.githubusercontent.com/36528214/46222967-daa0ee00-c306-11e8-815b-f3bde133d1ed.png)

![screenshot from 2018-09-28 10-08-09](https://user-images.githubusercontent.com/36528214/46222974-de347500-c306-11e8-9dac-20b27e08ceb3.png)

**Comment by jhoenicke** [comment]
Definitely always add the prefix to the qr-code as it is part of the address.  It would be very cumbersome if every multi-crypto wallet would need to add all known prefixes (bchtest:, bitcoincash:, bc1, ltc1, ...) and check for which the checksum matches just to determine what kind of address was provided :)

Also some qr-code scanner can use this prefix to find the application that should handle the address.

**Comment by cculianu** [comment]
I'm all for going over to the bitcoincash: - style...

Just curious -- why does it matter if it's a more compact encoding, really?

**Comment by imaginaryusername** [comment]
More compact QRs are "easier" to scan in my experience (they do better if resized, have wider tolerance at being scanned from distance or out of focus, etc). Don't know if there are robust research backing it.

**Comment by cculianu** [comment]
Ah, makes sense.  I imagine they would be.  

Although honestly I'm amazed at how good QR already is and how well it works even when it's dense and packed with info and the squares are small. (like has a huge long URL or something).  I have never been unable to scan a QR code ever.  But maybe i'm just lucky...

**Comment by markblundeberg** [comment]
@cculianu I have only failed scanning QR codes when I am [trying to take Roger Ver's money](https://youtu.be/dHiz5dSpZAY?t=3m36s). Probably has to do with the fuzziness and angle, but I can't get a scan.

Speaking of which, the bitcoin.com wallet's QR codes for addresses are a third type: prefixed and lowercased. They are significantly larger not just because of this but also they use the second-highest error correction level possible (then slap their logo in the middle)

![screenshot from 2018-09-29 09-28-43](https://user-images.githubusercontent.com/36528214/46248152-7e9f9d80-c3ca-11e8-9c3e-5d87b61e89bf.png)

![screenshot from 2018-09-29 09-30-32](https://user-images.githubusercontent.com/36528214/46248153-819a8e00-c3ca-11e8-813d-d4f5dd7b1282.png)

For example this last one has the same size and format as:
![rory donations](https://i.redd.it/m2b6t7tzjyo11.jpg)

**Comment by cculianu** [comment]
@markblundeberg  Hahahaha.  Did you actually stand a chance of getting that money? Hilarious.


Didn't realize there are various ECC options for QR.  Maybe we can see if the lib we use can do better?


Well -- i can easily change the Qt code to generate whatever.  So I guess the consensus is all screens do BITCOINCASH:QQBLABLA (all uppercase)??
