### ISSUE TITLE
Electron-cash has no fiat display by default 

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#878]
At fresh install Electron-Cash has no fiat display and only starts displaying fiat when a user goes to settings and choose an exchange. This is pretty confusing for new users who would assume electron-cash just doesn't support fiat display at all.

If there's a conscious decision to pick one exchange as default, there should probably at least be a popup notice at fresh install prompting users to choose it in settings.

**Comment by rt121212121** [comment]
I always assumed that this was general policy because of the concern against an auto-update check on application start.  In much the same way that it is undesirable for the application to notify EC server that they are looking for latest version, making it an option to enable fiat causes notify to exchange API.

**Comment by imaginaryusername** [comment]
Right, hence my suggestion that EC can probably just notify that you _can_ enable fiat, but "we're not gonna do it for you, you gotta check the box yourself".

**Comment by cculianu** [comment]
I am not sure I understand the equivalency being drawn between querying an exchange API and some other more draconian things like what Microsoft and Apple have been known to do to their users (such as gathering usage data or worse).  

An exchange API just returns 1 value -- rate, which is a floating point number.  The more advanced exchanges return multiple values (such as historical rate).  At no time is the exchange told anything about you or how much money you have.

it's probably the least "evil" thing happening network-wise with Electron Cash, really.

Consider that the ElectrumX servers are given much more identifying information (than what exchanges receive) -- they know the set of addresses belonging to you.

I personally thing @imaginaryusername's suggestion is a good one -- new users may benefit from seeing both FIAT and BCH amounts in their wallet.  A helpful dialog box or perhaps even (gasp!) turning the option on by default has my vote.

**Comment by rt121212121** [comment]
Any time you make an outward connection you are telling people something by your pattern of usage and any other factors, not just if you choose to tell them who you are and what you are using it for explicitly.  For the two situations to not be the same, you need to prove that that inference cannot be made by them.  Personally I think we should be checking for latest version on startup and comparing to current version, and telling user to update if applicable, and don't care about the subjective privacy concerns.

**Comment by cculianu** [comment]
> Any time you make an outward connection you are telling people something by your pattern of usage and any other factors, not just if you choose to tell them who you are and what you are using it for explicitly. 

Yes, this is true.  That is correct.  And in the crypto space we have a tradition of more privacy rather than less -- and traditionally this was at the expense of ease-of-use  for newbies and/or convenience.

Ha! I'm glad you're all for an update check too, though. 👍 

So we had our little discussion and we elucidated the issues.  Really I think this is probably up to Jonald since he's the Electron Cash PR community diviner. :P

**Comment by rt121212121** [comment]
To be fair, I suspect only the vocal minority would complain about an update check, and they'd probably still use it if we added it.  We could also add a command line argument or something to bypass it and if they really cared they could do that, and the bulk of users could just get pushed to more stable updated versions.

Also, I have concerns about the popup.  EC is an arcane tool not for beginners IMO, and adding more UI to push stuff at users seems to me like part of the larger problem of making EC more approachable.  That said, I don't see that happening anytime soon, so we maybe should just double down and do the popup 😛
