### ISSUE TITLE
Build environment for Android sucks

### ISSUE THREAD

**Issue by jonas-lundqvist** [Electron-Cash/Electron-Cash#879]
Yesterday I had some time over and tried to build the Android (kivy) version. I did not manage during the hour I tried and I assume that many new developers might run into these environment issues. It seems like it is problematic if you are not explicitly using Ubuntu (16.04).

Has anyone thought of putting it all inside a Docker container? That way a user would be able to download the EC source code and just run Docker and get an APK built.

Of course this might be a moot point if the native Android version is imminent.

**Comment by fyookball** [comment]
The new native android version already is functional.  Mostly needs features added.

**Comment by jonas-lundqvist** [comment]
@fyookball
Is there any code repository available so I can have a look (and possibly help out)?

**Comment by fyookball** [comment]
Malcom is working on it.  We should have it checked in , in about 1-2 days. i'll let you know :)

**Comment by jonas-lundqvist** [comment]
Since the new Android app has been merged to master I think it's reasonable to close the issue.
