### ISSUE TITLE
change to util based on android need close examination

### ISSUE THREAD

**Issue by fyookball** [Electron-Cash/Electron-Cash#884]
![image](https://user-images.githubusercontent.com/7663756/46574861-57bc0b00-c978-11e8-96b8-1fa101e4f8a5.png)

**Comment by mhsmith** [comment]
It used to format zero satoshis as "0.". This changes that to "0.0". Since there wasn't a unit test covering this case, I assumed it wasn't intentional. I've added a unit test for zero satoshis, and verified that all the other tests of this function still pass.

**Comment by cculianu** [comment]
Right, the tests will pass but I have to now go in and verify all the code that calls it isn't actually expecting the "0." behavior.  I doubt it's a huge deal but I was curious why change it? I have to do extra work now... to make sure it doesn't change the display unintentionally anywhere... :)

**Comment by mhsmith** [comment]
Understood, I'll change it back then.

**Comment by cculianu** [comment]
Awesome.. thanks man! :)
