### ISSUE TITLE
Windows error occurred during installation.

### ISSUE THREAD

**Issue by wef2f** [Electron-Cash/Electron-Cash#893]
![default](https://user-images.githubusercontent.com/36073274/46806504-53d62180-cd9a-11e8-8c19-58c1a4b1be2a.PNG)

**Comment by wef2f** [comment]
Does anyone know how to deal with the problems during installation?

**Comment by cculianu** [comment]
@wef2f Please try the latest Electron Cash SLP here and get back to me that this fixed: https://electroncash.org/downloads/3.4.3/win-linux/Electron-Cash-SLP-3.4.3.exe

Let me know so I can close this issue!

**Comment by jcramer** [comment]
It seems like this should be closed
