### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'Testing crash reports'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#900]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.3.1-py3.5.egg\electroncash\util.py", line 645, in run_with_except_hook
  File "threading.py", line 862, in run
  File "<string>", line 1, in <lambda>

ValueError: invalid literal for int() with base 10: 'Testing crash reports'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.1  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-7-6.1.7601-SP1 | standard | en_GB | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by mhsmith** [comment]
Testing complete, please close this issue.

**Comment by mhsmith** [comment]
Please close this issue: it was just a test of the crash report system.

**Comment by cculianu** [comment]
You got it boss.
