### ISSUE TITLE
Browser bitcoincash: links do not work on macOS

### ISSUE THREAD

**Issue by imaginaryusername** [Electron-Cash/Electron-Cash#901]
When clicking on bitcoincash:xxxx links in browsers, if EC is not running, it opens EC and fills in the send tab. However, if EC is already running, it does nothing.

**Comment by cculianu** [comment]
I created an issue with the Electrum devs since there are more of them and perhaps their insights/discussion would be helpful.

https://github.com/spesmilo/electrum/issues/4796

**Comment by cculianu** [comment]
This is now fixed for windows & linux with the latest commit.  Still an issue on Mac that needs fixing in pyinstaller (not pyqt as I initially thought).

I'm working on a pyinstaller patch.  If I figure it out I can submit the patch to the pyinstaller devs.

**Comment by cculianu** [comment]
I submitted a patch to fix this to the pyinstaller project.  PR is here:

https://github.com/pyinstaller/pyinstaller/pull/3832

**Comment by cculianu** [comment]
Update: This works now on Windows & Linux with git latest.  For macOS, my pyinstaller patch needs to be accepted then it will work once we build & release with the new pyinstaller sometime in the future.

**Comment by cculianu** [comment]
This is fixed on macOS release.  The pyinstaller guys are slow in merging PRs.  So I went ahead and built Electron Cash for macOS using my fork that handles URLs properly.

Closing as it's fixed in 3.3.2 release (to be out shortly).
