### ISSUE TITLE
chain split detection failure

### ISSUE THREAD

**Issue by markblundeberg** [Electron-Cash/Electron-Cash#912]
@mengerian got hit by a strange bug when trying to join the currently running BCH fork testnet. Instead of detecting the chain split, the wallet decided that the server is lagging and got permanently stuck that way. This is worrying in the context of the upcoming mainnet forks on November 15 that some wallet users may get stuck in a bad state.

![screenshot from 2018-11-01 16-18-41](https://user-images.githubusercontent.com/36528214/47885348-d4180180-ddf1-11e8-8e66-3902d9b5291a.png)

Due to the way EC behaves on lagging servers, this led to a further problem in that the wallet started generating txes with a future nLocktime, that could not be broadcasted on the fork testnet.

~~This was running on a codebase (my fork's csplit branch) that branched off from October 28's master, commit f598bd0cf54a37bcba8259380f43c4c7b7c19ba0. The altered code does not touch any network/blockchain stuff so the bug should be present on main.~~ The bug affects at least commit f598bd0cf54a37bcba8259380f43c4c7b7c19ba0 (October 28's master).

I have gotten a copy of his `~/.electron-cash/testnet` directory and I am able to reproduce the bug. Restarting EC does not resolve the problem. Removing `blockchain_headers` *does* resolve the problem. Initial technical symptoms:

* the `forks/` subdirectory is completely empty, when it should have files describing the different chain splits.
* with --verbose on, the terminal is spammed with an error message `[SPV] v.no blockchain blackie.c3-soft.com:60002:s`.

Will continue to investigate and hopefully make a PR to fix this.

**Comment by fyookball** [comment]
im confused how if the server was lagging would cause nLocktime to get pushed to the future.  If this is for the coinsplitting tool , could you use locktime 0 as a workaround?

**Comment by markblundeberg** [comment]
It's possible to workaround on the coinsplit tool, but it's a major problem for the entire wallet which relies on `make_unsigned_transaction`, which is where nLocktime gets set:

https://github.com/Electron-Cash/Electron-Cash/blob/master/lib/wallet.py#L1034

**Comment by markblundeberg** [comment]
@rt121212121 awesome! Works for me. :-D
