### ISSUE TITLE
Review signing 

### ISSUE THREAD

**Issue by hanshaueter** [Electron-Cash/Electron-Cash#914]
Dear Developers, 
I'm not sure if this is an issue, rather it's a question. I have a multi-sig set-up which electron-cash wallet (BCH) with 3 out of 6 keys. How can I look-up which of the 6 keys have signed a transaction?
I didn't find anything on the support docs for electrum http://docs.electrum.org/en/latest/ . It would be great if someone could help me.  
Thank you for your support.

**Comment by markblundeberg** [comment]
Hi @hanshaueter, this is in principle possible but a bit tricky, as we would have to carefully verify signatures in the right order (see [OP_CHECKMULTISIG](https://en.bitcoin.it/wiki/Script#Crypto)), see which ones match which pubkeys, and moreover correctly handle all 'sighash' types. If there is demand for this feature it could be added but it's definitely not a priority right now.
