### ISSUE TITLE
Nano S not recognised 

### ISSUE THREAD

**Issue by ekseesse** [Electron-Cash/Electron-Cash#925]
Hi, 
Electron Cash doesn not recognise my Nano S:
![screenshot from 2018-11-09 14-50-18](https://user-images.githubusercontent.com/44899698/48266224-0c8d9000-e42f-11e8-8c20-2c4cd8c34c89.png)
Ledger Live connects to the Nano S without any problem. Any ideas?

Environment:
Electron Cash 3.3.1 on Ubuntu 18.04
Ledger Nano S Firmware 1.4.2

**Comment by marceloneil** [comment]
Make sure that no other process on your computer is connected to the ledger (ie. close ledger live). This document also may help: https://github.com/Electron-Cash/Electron-Cash/blob/master/plugins/ledger/README.md

**Comment by ekseesse** [comment]
Ledger Live is closed, Electron Cash still does not connect.
From your link: "Browser Support" is disabled in the Bitcoin Cash Ledger app (only required for Nano S and/or Blue)"
--> didn't find this option in Ledger Live. Any idea?
Ledger manager extension does not seem to exist anymore in the google store.

**Comment by ekseesse** [comment]
Any other ideas?

**Comment by marceloneil** [comment]
Do you have any output from running EC in verbose mode (`electron-cash -v`)?

**Comment by ekseesse** [comment]
Here is the output:
[profiler] on_update 0.0201
[profiler] on_update 0.0233
[BitcoinAverage] getting fx quotes for EUR
[BitcoinAverage] received fx quotes
[BitcoinAverage] getting fx quotes for EUR
[BitcoinAverage] received fx quotes
[WalletStorage] wallet path /home/ekhard/.electron-cash/wallets/wallet_1
[WalletStorage] wallet path /home/ekhard/.electron-cash/wallets/wallet_1
[WalletStorage] wallet path /home/ekhard/.electron-cash/wallets/wallet_1
[WalletStorage] wallet path /home/ekhard/.electron-cash/wallets/t
[WalletStorage] wallet path /home/ekhard/.electron-cash/wallets/te
[WalletStorage] wallet path /home/ekhard/.electron-cash/wallets/tes
[WalletStorage] wallet path /home/ekhard/.electron-cash/wallets/test
[Plugins] loaded internal plugin digitalbitbox
[Plugins] loaded internal plugin keepkey
[Plugins] loaded internal plugin ledger
[Plugins] loaded internal plugin trezor
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[BitcoinAverage] getting fx quotes for EUR
[BitcoinAverage] received fx quotes


nothing suspicious, afaik.

**Comment by ekseesse** [comment]
Hi any other ideas?

**Comment by cculianu** [comment]
This is off latest source?

**Comment by dh35** [comment]
Yes sir, very latest. I am relatively new to linux mint, though. It very well could be operator error--just not sure how/what.

**Comment by jasonbcox** [comment]
Have you tried adding udev rules? https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues (Linux -> step 2)

**Comment by cculianu** [comment]
Hi @ekseesse -- sorry for the delayed action.  There is a latest PR that was merged that purports to fix issues with the Nano: #959 .  Can you try latest github head code and let us know? Thanks.

**Comment by cculianu** [comment]
Also @dh35  ^^

**Comment by EchterAgo** [comment]
@cculianu I don't think #959 will fix the issue, but I also had some issues getting my Ledger detected. I will try to figure out what my problems with detection are.

**Comment by cculianu** [comment]
Sorry I can't be more helpful here.  I don't have one of these devices -- I only have a Trezor.  I contacted Ledger but they are too stingy to supply one for free so.. it is what it is.  I do appreciate your help with the other PR and whatever else you can pitch in!

**Comment by EchterAgo** [comment]
I think my first issue with detection was udev rules, but that has already been mentioned. My second problem was that if `btchip-python` is not installed, there is no error or warning at all. @ekseesse @dh35 please try running the following:

`pip3 install btchip-python`

We should make sure there is at least a warning in verbose mode.

**Comment by cculianu** [comment]
I think ideally even the plugin should try and pop up a window but that may
not fit easily with how EC does plugins.

If that's the issue maybe i can at least add a warning in verbose mode..

**Comment by EchterAgo** [comment]
I will add the warning. I also have some other things I want to improve.

**Comment by cculianu** [comment]
Thank you so much.

**Comment by cculianu** [comment]
I am closing this issue as I believe our new release 4.0.3 should handle the issues here more gracefully and/or be more compatible.

To all in this thread: Let me know if this issue needs to be re-opened.
