### ISSUE TITLE
Import labels -- always fails?

### ISSUE THREAD

**Issue by markblundeberg** [Electron-Cash/Electron-Cash#929]
Steps: 1) Wallet | Labels | Export. 2) Wallet | Labels | Import. Result:

![screenshot from 2018-11-11 03-48-46](https://user-images.githubusercontent.com/36528214/48312542-0994bb80-e565-11e8-81f6-d1856bfc7e49.png)

**Comment by cculianu** [comment]
I didn’t even know this was a thing. Lol.

I’ll look at it..

**Comment by cculianu** [comment]
I finally fixed this!
