### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'inputs'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#930]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.3.1-py3.5.egg\electroncash_gui\qt\history_list.py", line 158, in create_menu
  File "site-packages\electron_cash-3.3.1-py3.5.egg\electroncash\wallet.py", line 502, in get_wallet_delta

AttributeError: 'NoneType' object has no attribute 'inputs'
```

Reporter
------------

This issue was reported by 2 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.1  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-7-6.1.7601-SP1 | standard | en_US | 
| 3.2  |  | Windows-7-6.1.7601-SP1 | standard | en_MY | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
This has been fixed long ago.
