### ISSUE TITLE
Extracting BCH from Nano

### ISSUE THREAD

**Issue by Tharrso** [Electron-Cash/Electron-Cash#931]
I have an old Ledger Nano that had pre-fork BTC on it. I have sent the BTC to another wallet, but I would like to extract the BCH if possible.
I was under the impression that I could create an electron-cash BCH wallet by using the recovery phrase (24 words) from my Nano wallet.
I've downloaded the electron-cash wallet, but not installed it. How exactly do I go about creating a wallet with the same passphrase as my Nano so that it will incorporate my BCH?

Thanks,
Ted

**Comment by mrbianchi** [comment]
create new wallet -> standard wallet -> i already have a seed 
paste your seed
click on options and enable bip39 , if you have a password (not the PIN!) enable custom word too
next, paste your password
should be done

**Comment by Tharrso** [comment]
I don't have a previous password, so I left the derivation path at the default. The wallet setup completed, but the balance shows as zero. Should I have done something differently?

**Comment by mrbianchi** [comment]
On electron cash default path isn't correct for your case
You need to use m/44'/0'/0'

**Comment by cculianu** [comment]
Ok well this issue seems solved. Thanks @mrbianchi for helping the user.
