### ISSUE TITLE
Release notes for 3.3.2 is missing in RELEASE-NOTES

### ISSUE THREAD

**Issue by hegjon** [Electron-Cash/Electron-Cash#935]
Include the update of the RELEASE-NOTES as part of the workflow.

**Comment by cculianu** [comment]
You're right.  Good catch.  Pinging @fyookball .. I'll try and remember to do this too next time but up until now poor only Jonald was the one that was doing it.

**Comment by cculianu** [comment]
Ok well we fixed this in subsequent releases.  Thanks for pointing this out!
