### ISSUE TITLE
How to select bch server with electron-cash after hard fork?

### ISSUE THREAD

**Issue by egonson** [Electron-Cash/Electron-Cash#936]
I modified and tested the servers.json file with an electron-cash to be attached to a server on the bitcoin ABC side or to the bitcoin SV.

for ABC side
{
    "bch.imaginary.cash": {
        "pruning": "-",
        "s": "50002",
        "t": "50001",
        "version": "1.4"
    },
    "bch0.kister.net": {
        "pruning": "-",
        "s": "50002",
        "t": "50001",
        "version": "1.4"
    },
    "blackie.c3-soft.com": {
        "pruning": "-",
        "s": "50002",
        "t": "50001",
        "version": "1.4"
    },
    "crypto.mldlabs.com": {
        "pruning": "-",
        "s": "50002",
        "t": "50001",
        "version": "1.4"
    },
    "electron-cash.dragon.zone": {
        "pruning": "-",
        "s": "50002",
        "t": "50001",
        "version": "1.4"
    },
    "electron.coinucopia.io": {
        "pruning": "-",
        "s": "50002",
        "t": "50001",
        "version": "1.4"
    },
    "electron.jochen-hoenicke.de": {
        "pruning": "-",
        "s": "51002",
        "t": "51001",
        "version": "1.4"
    },
    "electroncash.cascharia.com": {
        "pruning": "-",
        "s": "50002",
        "t": "50001",
        "version": "1.4"
    },
    "electrum.leblancnet.us": {
        "pruning": "-",
        "s": "50012",
        "t": "50011",
        "version": "1.4"
    },
    "wallet.satoshiscoffeehouse.com": {
        "pruning": "-",
        "s": "50002",
        "t": "50001",
        "version": "1.4"
    }
}

=============================================================
for SV side
{
    "94.1.159.183": {
        "pruning": "-",
        "s": "50002",
        "t": "50001",
        "version": "1.4"
    },
    "abc1.hsmiths.com": {
        "pruning": "-",
        "s": "60002",
        "t": "60001",
        "version": "1.4"
    },
    "bch.electrumx.cash": {
        "pruning": "-",
        "s": "50002",
        "t": "50001",
        "version": "1.4"
    }
}

I confirmed that the client was connected to another servers that are not configured regardless of whether it is set up to connect to ABC side or SV side.

[bch.curalle.ovh] connected
[bitcoincash.quangld.com] connected
[electrum.imaginary.cash] connected

How can I connect to only ABC servers or SV servers with the client?

I could select servers with Electron-Cash UI tool. But how to with command tool?

**Comment by gogetteryoungun** [comment]
I have the same problem too.. does anyone have the answer? Please advise..!

**Comment by rt121212121** [comment]
Set a default server in the config, and start it up with --oneserver would be one way IIRC.  Can't look ATM thought.

**Comment by egonson** [comment]
Does the "in the config" mean servers.json file?

**Comment by rt121212121** [comment]
parser.add_argument("-1", "--oneserver", action="store_true", dest="oneserver", default=False, help="connect to one server only")
    parser.add_argument("-s", "--server", dest="server", default=None, help="set server host:port:protocol, where protocol is either t (tcp) or s (ssl)")

**Comment by rt121212121** [comment]
Note that your default server binds you to the blockchain which it is serving. You want your Electron Cash to connect to as many different servers as possible, the only problem is if it unbinds from the default server.  So it should connect to SV servers and it should connect to ABC servers, and it should collect blockchain data even in the chains that are not the same as your default server.

**Comment by rt121212121** [comment]
Note the Electron Cash fork handling may collapse completely, even if you only follow ABC or only SV, so oneserver is probably the way to go - if you trust that server.  But if the fork handling were fixed, then it'd be better to not use oneserver.

**Comment by egonson** [comment]
I did set electron-cash.conf file and used --oneserver option.
But the client still connected to several servers that was not configured.

**Comment by markblundeberg** [comment]
I agree with RT, it is good to be connected to many servers and then manually (through Network dialog) choose the chain you want to follow. Yes, you will see a somewhat annoying 'chain split' icon in the bottom right but that will help remind you that you are living in chaotic times. :-)

**Comment by gogetteryoungun** [comment]
I am aware that we can manually connect to servers through the UI but I was wondering how to manually set servers in a program using Electron-Cash.

**Comment by rt121212121** [comment]
The only solution is `oneserver` with `server`, if you can get it to work.  Connecting to any server will add to your servers list, even if you curate it, as I understand it.  So to ensure just SV or just ABC, you can only have one server, and you need to make sure it's of the chain you want.
