### ISSUE TITLE
(prefix, kind, hash) - how i can get legacy address from this parametres?

### ISSUE THREAD

**Issue by mousemove** [Electron-Cash/Electron-Cash#938]
Hello!
I try to convert addresses with https://github.com/Electron-Cash/Electron-Cash/blob/master/lib/cashaddr.py
Used function decode, and get a tuple with three parameters - (prefix, kind, hash)
(prefix, kind, hash) - how i can get STRING legacy address from this parametres?
tnx, sorry for my english

**Comment by cculianu** [comment]
Use address.py class Address instead.  It has a method to_storage_string() that gives you the legacy format.
