### ISSUE TITLE
bch fork 15 november 2018

### ISSUE THREAD

**Issue by azarharus** [Electron-Cash/Electron-Cash#947]
Hi i have some bitcoin cash in electron cash since early 2018 what do i do now after the fork to access them and change them to bitcoin Thanks

**Comment by cculianu** [comment]
Check out my reddit post that goes over how to separate out the coins.  It's a bit terse.  Write me on that reddit thread if you want to find out more: https://www.reddit.com/r/btc/comments/9xmh2n/psa_how_to_split_your_coins_with_electron_cash/
