### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Pete\\Desktop\\electron_cash_data\\certs\\207.180.195.239.temp' -> 'C:\\Users\\Pete\\Desktop\\electron_cash_data\\certs\\207.180.195.239'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#948]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.3.2-py3.5.egg\electroncash\util.py", line 609, in run_with_except_hook
  File "site-packages\electron_cash-3.3.2-py3.5.egg\electroncash\interface.py", line 240, in run
  File "site-packages\electron_cash-3.3.2-py3.5.egg\electroncash\interface.py", line 235, in get_socket

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Pete\\Desktop\\electron_cash_data\\certs\\207.180.195.239.temp' -> 'C:\\Users\\Pete\\Desktop\\electron_cash_data\\certs\\207.180.195.239'
```

Reporter
------------

This issue was reported by 51 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.2  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-7-6.1.7601-SP1 | standard | en_CA | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPhone9,3-64bit iOS 12.1 iPhone (D2A8804C-71A2-4E33-8AC9-D69951EF7BFF) | standard | en_UK | 
| 3.3.2  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-7-6.1.7601-SP1 | standard | zh_CN | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.0.0-iPhone8,2-64bit iOS 12.0.1 iPhone (ABFB12BE-12AF-47E7-AFA5-955733261496) | standard | zh_CN | 
| 3.3.1CS  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-7-6.1.7601-SP1 | standard | de_DE | 
| 3.3.1CS  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17134 | standard | en_US | 
| 3.3.1CS  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17134 | standard | en_US | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPhone8,4-64bit iOS 12.1 iPhone (CC2E0C8B-1B88-4491-84F3-30A86DC35428) | imported_addr | cs_CZ | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPhone11,6-64bit iOS 12.1 iPhone (B43540CD-4A27-4A26-BB90-7BAB7524AE15) | standard | en_UK | 
| 3.3.2  | 3.5.3 (default, Sep 27 2018, 17:25:39)  [GCC 6.3.0 20170516] | Linux-4.18.0-2-amd64-x86_64-with-debian-9.5 | standard | en_US | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPhone10,4-64bit iOS 12.1 iPhone (3E204B65-8A92-4587-ACF2-5A8FBAF6DFD8) | standard | es_ES | 
| 3.3.1CS  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17134 | standard | en_US | 
| 3.3.1CS  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17134 | standard | de_DE | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPhone9,4-64bit iOS 12.1.1 iPhone (1D286E0D-A2A2-4F5F-9F1C-6A1659F72CEC) | standard | en_UK | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPhone8,2-64bit iOS 12.1 iPhone (A6027A50-0C6F-45EE-A2BF-5CD9FB24281F) | standard | en_UK | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPhone8,2-64bit iOS 12.1 iPhone (B60F1773-99B0-48EE-BB42-C5A768A2BFA6) | standard | en_UK | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPhone8,2-64bit iOS 12.1 iPhone (A6598528-7429-498B-A1BC-F5617DC4ED71) | standard | en_UK | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPhone8,2-64bit iOS 12.1 iPhone (A6598528-7429-498B-A1BC-F5617DC4ED71) | standard | en_UK | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.0.0-iPhone10,6-64bit iOS 12.0 iPhone (5959CA2C-09CD-4523-B8E1-3D5CEB4172DE) | imported_addr | en_UK | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPhone6,2-64bit iOS 12.1 iPhone (115EF0D5-0E75-4D34-A4B2-9D26524412BF) | standard | en_UK | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-16.6.0-iPhone7,1-64bit iOS 10.3.2 iPhone (6AE82166-BF88-46DC-8846-589D52BB99D6) | standard | en_UK | 
| 3.3.1 (iOS Build: 315)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPhone8,1-64bit iOS 12.1 iPhone (ECC9DAAE-1621-4FE7-94DF-D6075051EC4E) | standard | en_UK | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-17.6.0-iPhone10,4-64bit iOS 11.4 iPhone (43C88CA5-4C7F-407D-B04D-DB67CDFA70CB) | standard | en_UK | 
| 3.3.1CS  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17134 | standard | fr_FR | 
| 3.3.1CS  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17134 | standard | en_CA | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-16.7.0-iPhone7,2-64bit iOS 10.3.3 iPhone (5F69D872-B3B5-4EB2-83BA-02CBABBF982F) | standard | zh_CN | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPhone9,4-64bit iOS 12.1 iPhone (7E53D806-E903-4F7D-AA2B-294777EF0EB4) | standard | ru_RU | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPhone9,2-64bit iOS 12.1 iPhone (8D40FAB8-DAF5-499D-B6DA-B235BAC77E17) | standard | zh_CN | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPhone9,2-64bit iOS 12.1 iPhone (8D40FAB8-DAF5-499D-B6DA-B235BAC77E17) | standard | zh_CN | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.0.0-iPhone10,2-64bit iOS 12.0.1 iPhone (4E4CE91F-CFCC-4460-A4E4-237AB4DC72DE) | imported_privkey | zh_CN | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPhone10,3-64bit iOS 12.1 iPhone (A2AD95A0-B547-4988-A780-1F31E5F59D6C) | standard | zh_CN | 
| 3.3.2  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-7-6.1.7601-SP1 | standard | he_IL | 
| 3.3.2  | 3.6.6 (default, Sep 12 2018, 18:26:19)  [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] | Linux-4.15.0-42-generic-x86_64-with-Ubuntu-18.04-bionic | standard | en_US | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-16.7.0-iPhone8,1-64bit iOS 10.3.3 iPhone (81972DF0-8090-47A4-85D1-516ACE6F6E21) | standard | zh_CN | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-17.6.0-iPhone8,4-64bit iOS 11.4 iPhone (0FFD3D98-C697-44AC-8FEC-623070267A51) | standard | tr_TR | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.0.0-iPhone8,1-64bit iOS 12.0.1 iPhone (6F2F38A4-6949-41CB-8829-937FEFD3044E) | standard | zh_CN | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPhone9,1-64bit iOS 12.1.1 iPhone (A4844252-D92E-48FC-B5E4-B3E9986ED1F9) | standard | en_UK | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPad7,6-64bit iOS 12.1.1 iPad (FD1EFAD0-A05E-4035-A6AE-33E208B316A4) | standard | en_UK | 
| 3.3.2  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17134 | imported_privkey | en_US | 
| 3.3.3  | 3.7.1 (default, Oct 22 2018, 10:41:28)  [GCC 8.2.1 20180831] | Linux-4.19.9-arch1-1-ARCH-x86_64-with-arch | standard | en_US | 
| 3.3.3  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17134 | standard | en_US | 
| 3.3.3 (iOS Build: 03030300)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPhone9,1-64bit iOS 12.1.2 iPhone (A4844252-D92E-48FC-B5E4-B3E9986ED1F9) | standard | en_UK | 
| 3.3.1 (iOS Build: 320)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPad4,1-64bit iOS 12.1.1 iPad (E9408BF2-26F7-4A0A-8763-AFF78EC0DEDD) | standard | ru_RU | 
| 3.3.3 (iOS Build: 03030300)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-18.2.0-iPhone10,6-64bit iOS 12.1 iPhone (AD9AF328-DBE0-4B33-A0F4-A2F568D89730) | standard | es_ES | 
| 3.3.4  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17763 | standard | en_US | 
| 3.3.4  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.15063 | standard | de_AT | 
| 3.3.4  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-7-6.1.7601-SP1 | imported_privkey,standard | es_AR | 
| 3.3.4_iOS (iOS Build: 03030401)  | 3.5.5+ (default, Jul  5 2018, 10:38:23)  [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] | Darwin-17.5.0-iPhone7,2-64bit iOS 11.3.1 iPhone (2CC6B616-E7B5-4608-BA08-BF32FAAD13C7) | imported_privkey | en_UK | 
| 3.3.1CS  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17134 | standard | en_US | 
| 3.3.1CS  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17134 | standard | en_US | 
| 3.3.2  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-7-6.1.7601-SP1 | imported_privkey | ru_RU | 

Additional Information
------------------------

> Entered sv server and then got an error

---

> I entered sv.electrumx.cash:50002

---

> I just changed the server.  Sv

---

> Test wallet. Attempting to switch to a different server or node. 

---

> just trying to get one of these damn sv servers to work. idk what the error ever is about. 

---

**Comment by cculianu** [comment]
Jesus christ this is a common error.  NEEDS FIXING.
