### ISSUE TITLE
exception: invalid status 6b00

### ISSUE THREAD

**Issue by ytrottier** [Electron-Cash/Electron-Cash#949]
I just upgraded to 3.3.2 on OSX. I'm using a Ledger Nano S, plugged in, unlocked, with the BCH app. When I start up Electron Cash, it pops up a window that says "Exception: Invalid status 6b00".

**Comment by cculianu** [comment]
Uh oh. Paging Johen.  He knows Nanos like I know Grimness. :)

**Comment by jhoenicke** [comment]
One user reported that a firmware update helped with this bug.

Also, does the patch #749 help here?

I think it is related to cashaddr support and happens, if the os doesn't support cashaddr, but electron cash uses the cashaddr.

**Comment by ytrottier** [comment]
Thanks. Updating firmware from 1.4.1 to 1.4.2 fixed it.

**Comment by cculianu** [comment]
Thanks @jhoenicke ! 👍

**Comment by emergent-reasons** [comment]
The firmware update fixed this for another user's configuration:

OS: Windows 10
Old Firmware: 1.3.1
