### ISSUE TITLE
AttributeError: 'TrezorKeyStore' object has no attribute 'thread'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#951]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "C:\Users\devon\AppData\Local\Temp\_MEI84442\electroncash_plugins\trezor\qt_generic.py", line 196, in show_address
    keystore.thread.add(partial(self.show_address, wallet, addrs[0]))

AttributeError: 'TrezorKeyStore' object has no attribute 'thread'
```

Reporter
------------

This issue was reported by 1 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17134 | standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
Looks like the plugin wasn't properly initialized or something.  Very weird. From my reading of the trezor plugin code this shouldn't be a likely scenario. Leaving it open though.

**Comment by cculianu** [comment]
Closing. Only happened once and since then Trezor has been revamped.
