### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'to_full_ui_string'

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#960]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "/home/anders/Hentet/Electron Cash-3.3.2CS/gui/qt/main_window.py", line 1424, in request_password
    return func(self, *args, **kwargs)
  File "/home/anders/Hentet/Electron Cash-3.3.2CS/gui/qt/main_window.py", line 2192, in start_coinsplit_mul
    coinsplitmul.show_dialog(self, address, password)
  File "/home/anders/Hentet/Electron Cash-3.3.2CS/gui/qt/coinsplitmul.py", line 26, in show_dialog
    d = SplitDialog(*args, **kwargs)
  File "/home/anders/Hentet/Electron Cash-3.3.2CS/gui/qt/coinsplitmul.py", line 177, in __init__
    self.redeem_address_e.setText(self.default_redeem_address.to_full_ui_string())

AttributeError: 'NoneType' object has no attribute 'to_full_ui_string'
```

Reporter
------------

This issue was reported by 3 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 3.3.2CS  | 3.6.7 (default, Oct 22 2018, 11:32:17)  [GCC 8.2.0] | Linux-4.18.0-11-generic-x86_64-with-Ubuntu-18.10-cosmic | 2of2 | da_DK | 
| 3.3.2CS  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-7-6.1.7601-SP1 | imported_privkey | en_US | 
| 3.3.2CS  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17134 | imported_privkey | en_ZA | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by cculianu** [comment]
Paging @markblundeberg  :)

**Comment by markblundeberg** [comment]
this one I do know and I think it was fixed :-D

**Comment by cculianu** [comment]
🤔
Hmm. I hope so!
