### ISSUE TITLE
Electron Cash reuses already used address

### ISSUE THREAD

**Issue by dskloet** [Electron-Cash/Electron-Cash#968]
I created a wallet with my Ledger Nano S. When I went to get a receiving address, it showed me the very first BIP44 address for my seed, but that was already used years ago. Shouldn't it give me a new address?

**Comment by jhoenicke** [comment]
Did you wait until the transactions were fully synchronized?  For me Electron Cash uses the first unused address (even if later addresses were already used).  Maybe it didn't see the old transaction, yet.

**Comment by dskloet** [comment]
Yes, I could see my transaction history and the correct balance so it must have been synchronized.

**Comment by dskloet** [comment]
After having used that address, it now gives a fresh address. My guess is some kind of race condition on a new wallet.

**Comment by markblundeberg** [comment]
I've noticed the Receive tab doesn't update automatically, so you have to click 'New'.

**Comment by cculianu** [comment]
This has finally been addressed in latest git head.  Better late than never.  Note the enforcement of "always a fresh address in receive tab" only happens if the user has "use change address" set in preferences (the assumption is the user cares about privacy and not re-using addresses).
