### ISSUE TITLE
Confirmed transaction but bitcoins not received

### ISSUE THREAD

**Issue by tesniawel** [Electron-Cash/Electron-Cash#978]

**Comment by tesniawel** [comment]
Hi can you assist new user of electrumcas. I bought some bitcoin yesterday and can see confirmed at:https://www.blockchain.com/btc/tx/64850983c592f4ca644e4ce27226d5203560c9a34a3900db4ece94961bebc918 But nothing has appeared in my wallet

**Comment by tesniawel** [comment]
I meant Electron Cash

**Comment by SomberNight** [comment]
Electrum [[1]](https://github.com/spesmilo/electrum) [[2]](https://electrum.org/) is for Bitcoin.
This repo (Electron Cash) is for Bitcoin Cash.

**Comment by tesniawel** [comment]
Thanks...what does that mean?

**Comment by SomberNight** [comment]
You will not see Bitcoin transactions when using Electron Cash.
You should try to restore from seed words using Electrum.

**Comment by tesniawel** [comment]
Do you mean download electrum wallet then restore using the seed words that electron cash generated?

**Comment by SomberNight** [comment]
Yes.

**Comment by tesniawel** [comment]
I'll try that - thanks for you help. Any pointers on restoring?

**Comment by SomberNight** [comment]
Follow the instructions in the built-in wizard.

**Comment by tesniawel** [comment]
I can't see how to open the wizard?

**Comment by SomberNight** [comment]
https://bitcoinelectrum.com/restoring-your-standard-wallet-from-seed/

**Comment by tesniawel** [comment]
Thanks...that's fixed it.
