### ISSUE TITLE
ImportError: Loader FrozenImporter cannot handle module electroncash.qrscanner

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#988]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "site-packages\electron_cash-3.3.2-py3.5.egg\electroncash_gui\qt\main_window.py", line 83, in onPress
  File "site-packages\electron_cash-3.3.2-py3.5.egg\electroncash_gui\qt\main_window.py", line 2923, in settings_dialog
  File "c:\python3.5.4\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 611, in exec_module
  File "c:\python3.5.4\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 444, in get_code

ImportError: Loader FrozenImporter cannot handle module electroncash.qrscanner
```

Reporter
------------

This issue was reported by 7 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale | Stack |
|---|---|---|---|---|---|
| 3.3.2  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-8.1-6.3.9600 | standard | sk_SK | [ℹ](https://crashhub.electroncash.org//crash/100) | 
| 3.3.4  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17134 | standard | nl_BE | [ℹ](https://crashhub.electroncash.org//crash/324) | 
| 3.3.1CS  | 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] | Windows-10-10.0.17134 | standard | en_US | [ℹ](https://crashhub.electroncash.org//crash/399) | 
| 4.0.2  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-8.1-6.3.9600-SP0 | standard | en_US | [ℹ](https://crashhub.electroncash.org//crash/607) | 
| 3.6.6  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | slp_standard | fr_FR | [ℹ](https://crashhub.electroncash.org//crash/1516) | 
| 4.2.11  | 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | standard | en_GB | [ℹ](https://crashhub.electroncash.org//crash/1982) | 
| 4.2.14  | 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)] | Windows-10-10.0.19041-SP0 | standard | zh_CN | [ℹ](https://crashhub.electroncash.org//crash/2320) | 

Additional Information
------------------------

> Typing to enter a seed prhase give this error

---

**Comment by cculianu** [comment]
Odd. If this is the released version then electroncash.qrscanner is nearly a no-op.

Odd.

Mark was this you in testing your new zbar?

**Comment by cculianu** [comment]
Wow.  So it has a storied history.  When testing on the command-line using Python 3.5 I got an error using qrscanner.py -- but it wasn't exactly the same stack trace.  On 3.6 I never got that error (this is on MacOS).

I suspect it's related to the prefs pane need to query the video devices using that `_find_video_devices` call in qrscanner.py... but WHY?!

Yeah.  Bizarre. Really bizarre.

**Comment by cculianu** [comment]
More info: It's failing in PyInstaller's loader here: https://github.com/pyinstaller/pyinstaller/blob/0f31b35fe96de59e1a6faf692340a9ef93492472/PyInstaller/loader/pyimod03_importers.py#L428

Probably the way to really troubleshoot this is to:

1. figure out how to reproduce this (seems to only happen on windows)
2. Once it happens consistently, print a better traceback to see what exactly it doesn't like.
