### ISSUE TITLE
Transacción BCH retorno (Hardfork BCH)

### ISSUE THREAD

**Issue by electronr** [Electron-Cash/Electron-Cash#989]
Realice una transacción BCH  hacia una wallet uphold en los días del hardfork (Exactamente el día 16-11-2018) pero la misma no ha llegado a la wallet uphold.
Me puse en contacto con uphold los cuales me dijeron que me pusiera en contacto con los de electron para el retorno de la transacción.

Gracias de antemano por su ayuda.

**Comment by electronr** [comment]
Esta es la tx de la transacción:

https://blockchair.com/bitcoin-cash/transaction/0cfa003da29f557b0605d4f2becd621f5bf57388fa5b8584ed2a657ed46824b5

Tiene 1502 COnfirmaciones y no ha llegado al destino.
La wallet de destino es: 1L1EE7Mmy8D1oR8gGsPQSsQ8YdmAuy8y5M

**Comment by electronr** [comment]
And by your knowledge do you believe that if you reach your destination the money?

**Comment by markblundeberg** [comment]
Lo siento, mi español no es tan bueno así que responderé en inglés.

It looks like your transaction was confirmed so the problem is with Uphold exchange... are you 100% sure that 1L1EE7Mmy8D1oR8gGsPQSsQ8YdmAuy8y5M was the bitcoin cash deposit address they gave you?

**Comment by electronr** [comment]
Yes, I'm totally sure, I've already made several transfers to that address
