### ISSUE TITLE
Electron Cash won't connect to any servers. Version 3.3.2

### ISSUE THREAD

**Issue by mforno1** [Electron-Cash/Electron-Cash#991]
I have tried connecting manually as well as connect automatically but Electron Cash still says "Not connected". I am not running any VPN. I do have Norton Security running but I dont believe it is the problem. Any help appreciated.

**Comment by rt121212121** [comment]
This is something on your end.  EC comes with multiple servers, and if you can connect to one, it will feed you addresses for more.

I assume you are using the the non-mobile desktop version.  If you can run it from the command-line, run it with --verbose argument and see what it prints.

**Comment by mforno1** [comment]
Yes, I am using the Windows version on a desktop PC. Where do I begin to
start using the command-line? do I need linux?

**Comment by markblundeberg** [comment]
@mforno1 go into Tools | Network and make sure you've disabled Proxy.

**Comment by mforno1** [comment]
use proxy is unticked and servers are set to choose automatically... still
not working.

**Comment by mforno1** [comment]
It turned out to be Norton Firewall. As soon as I turned it off it worked.
Thanks

**Comment by rt121212121** [comment]
Yes, you should be able to add EC as an exception to it, and leave the firewall on.  Good luck.
