### ISSUE TITLE
Network error causes network thread to get stuck in infinite loop

### ISSUE THREAD

**Issue by mhsmith** [Electron-Cash/Electron-Cash#994]
On Android, I often see the network thread getting stuck in an infinite loop in the code below.

https://github.com/Electron-Cash/Electron-Cash/blob/f94409eb99bf58db0e65fe53da79cae17049e01f/lib/util.py#L577-L589

The exception is an OSError with errno either "Broken pipe" or "Bad file descriptor". I can reproduce this by leaving my phone asleep and not charging for a few minutes. I can't reproduce it using airplane mode, though that has its own problems (#971).

This code was introduced without a proper explanation in Electrum commit 89240571d49e8374cb99bad34a2e7cc1bededcc9, but no longer exists in Electrum because they've made some major changes to their network system.

I don't think we can release the Android app until this is fixed. Can anyone who understands this area suggest a solution?

**Comment by cculianu** [comment]
Jesus.  This .. doesn't look right. 

😱
