### ISSUE TITLE
Stolen my BCH

### ISSUE THREAD

**Issue by muckiknack** [Electron-Cash/Electron-Cash#997]
Hello,

I have done the settings as shown here

https://bitcointalk.org/index.php?topic=5070999.60

But now my coins are gone and never come back.

Whats that?

I am very angry

**Comment by markblundeberg** [comment]
@muckiknack can you provide more details?

One unfortunate aspect of the fork is that there was no replay protection. So if you moved SV coins then it's possible your BCH got moved the same way.

**Comment by muckiknack** [comment]
Hello,
i follows the description on the Link. 
But also the Link to the Software.
Maybe it is a hacked  Version?
I Import my private Key to claim BCHSV.
One Minute After i Import my Key there was a Transfer from my Exodus wallet to a Unknown Adress.
The TX ID can i send you later.
this there a Chance to get the Coins back?
Gesendet von Yahoo Mail auf Android 
 
  Am Fr., Nov. 30, 2018 at 4:12 schrieb Mark B Lundeberg<notifications@github.com>:   
@muckiknack can you provide more details?

One unfortunate aspect of the fork is that there was no replay protection. So if you moved SV coins then it's possible your BCH got moved the same way.

**Comment by cculianu** [comment]
That link is a scam wallet. I just checked it.  Yes -- your coins were stolen by scammers.

I'm sorry this happened to you.  Our official version is https://www.electroncash.org.

You probably have no way of getting your coins back.  Scammers stole them. :(

Anyone got a bitcointalk account?  The guy that pasted that link is a scammer and at the very least that post should be deleted.

@fyookball @markblundeberg -- you guys got a bitcointalk account?

**Comment by cculianu** [comment]
Nevermind.  I created an account on bitcointalk.org and posted a scam warning there in that thread.

Anyway -- @muckiknack  there is nothing you can do.  A scammer got you.  I'm really sorry.  In the future be really careful with the bitcoin / bitcoin cash software you download.  Only install software from reputable sources.
